import type { StoryTemplate } from "@/lib/pets/lore-types";

/** Egg-origin templates. Bred sources must use BREEDING-compatible entries only. */
export const ORIGIN_TEMPLATES: StoryTemplate[] = [
  {
    id: "ember-glass-nest",
    compatibleRegions: ["Ember Crater"],
    compatibleAffinities: ["EMBER"],
    incompatibleSources: ["BREEDING", "SHOP"],
    text: "Its egg rested in a ring of cooled volcanic glass beneath {region}, warmed by residual heat long after the ash had settled.",
  },
  {
    id: "ember-cooling-station",
    compatibleRegions: ["Ember Crater"],
    compatibleAffinities: ["EMBER", "STONE", "ALLOY"],
    incompatibleSources: ["BREEDING"],
    text: "Recovered from a cracked stone chamber beneath an abandoned cooling station on the rim of {region}.",
  },
  {
    id: "tide-shipwreck",
    compatibleRegions: ["Moonwater Coast"],
    compatibleAffinities: ["TIDE", "STORM", "SPIRIT"],
    incompatibleSources: ["BREEDING", "SHOP"],
    minimumRarity: "UNCOMMON",
    text: "Washed ashore after a Rift storm tore open a sandbar vault along {region}, its shell still glistening with tideglass.",
  },
  {
    id: "tide-pool-shrine",
    compatibleRegions: ["Moonwater Coast"],
    compatibleAffinities: ["TIDE"],
    incompatibleSources: ["BREEDING"],
    text: "Found nestled in a tide-pool shrine where moonlit foam gathers each dusk along {region}.",
  },
  {
    id: "grove-ancient-roots",
    compatibleRegions: ["Elderwood Forest"],
    compatibleAffinities: ["GROVE", "SPIRIT"],
    incompatibleSources: ["BREEDING"],
    text: "Discovered beneath ancient roots in {region}, protected by a living lattice of moss and thorn.",
  },
  {
    id: "grove-fern-hollow",
    compatibleRegions: ["Elderwood Forest"],
    compatibleAffinities: ["GROVE"],
    incompatibleSources: ["BREEDING", "SHOP"],
    text: "Sheltered inside a fern hollow of {region} where seed-light never fully fades.",
  },
  {
    id: "storm-spire-ledge",
    compatibleRegions: ["Stormspire Peaks"],
    compatibleAffinities: ["STORM"],
    incompatibleSources: ["BREEDING"],
    text: "Cradled on a crystal ledge high in {region}, humming faintly whenever thunder rolled past.",
  },
  {
    id: "storm-kite-nest",
    compatibleRegions: ["Stormspire Peaks"],
    compatibleAffinities: ["STORM", "RADIANT"],
    incompatibleSources: ["BREEDING"],
    text: "Found in a wind-scooped nest of scrap kite silk along the upper ridges of {region}.",
  },
  {
    id: "stone-collapsed-mine",
    compatibleRegions: ["Stoneheart Canyon"],
    compatibleAffinities: ["STONE", "ALLOY", "EMBER"],
    incompatibleSources: ["BREEDING"],
    text: "Recovered from a collapsed mine gallery in {region}, still dusted with fossil grit.",
  },
  {
    id: "stone-fossil-shelf",
    compatibleRegions: ["Stoneheart Canyon"],
    compatibleAffinities: ["STONE"],
    incompatibleSources: ["BREEDING"],
    text: "Unearthed beside a fossil shelf in {region}, where canyon winds polish stone into soft curves.",
  },
  {
    id: "frost-frozen-cavern",
    compatibleRegions: ["Frostveil Basin"],
    compatibleAffinities: ["FROST", "SPIRIT"],
    incompatibleSources: ["BREEDING"],
    text: "Discovered inside a frozen cavern of {region}, sealed behind a thin pane of aurora ice.",
  },
  {
    id: "frost-snowdrift",
    compatibleRegions: ["Frostveil Basin"],
    compatibleAffinities: ["FROST"],
    incompatibleSources: ["BREEDING", "SHOP"],
    text: "Found half-buried in a quiet snowdrift of {region}, leaving a faint crystal print when lifted.",
  },
  {
    id: "radiant-citadel-alcove",
    compatibleRegions: ["Radiant Citadel"],
    compatibleAffinities: ["RADIANT"],
    incompatibleSources: ["BREEDING"],
    text: "Protected inside a ruined shrine alcove of {region}, catching dawn light through a cracked prism.",
  },
  {
    id: "radiant-sunshaft",
    compatibleRegions: ["Radiant Citadel", "Riftwild Commons"],
    compatibleAffinities: ["RADIANT", "SPIRIT"],
    incompatibleSources: ["BREEDING"],
    text: "Found where a sunshaft struck the floor of {region} and refused to move with the hour.",
  },
  {
    id: "void-unstable-portal",
    compatibleRegions: ["Void Hollow"],
    compatibleAffinities: ["VOID"],
    incompatibleSources: ["BREEDING", "SHOP"],
    minimumRarity: "RARE",
    text: "Discovered near an unstable portal mouth in {region}, pulsing between silence and echo.",
  },
  {
    id: "void-hollow-corridor",
    compatibleRegions: ["Void Hollow"],
    compatibleAffinities: ["VOID", "SPIRIT"],
    incompatibleSources: ["BREEDING"],
    text: "Recovered from a misted corridor of {region} where footsteps arrive before their owners.",
  },
  {
    id: "alloy-inactive-machine",
    compatibleRegions: ["Alloy Ruins"],
    compatibleAffinities: ["ALLOY", "STONE"],
    incompatibleSources: ["BREEDING"],
    text: "Found beside an inactive machine in {region}, ticking once as if acknowledging a visitor.",
  },
  {
    id: "alloy-scrap-garden",
    compatibleRegions: ["Alloy Ruins"],
    compatibleAffinities: ["ALLOY"],
    incompatibleSources: ["BREEDING"],
    text: "Nestled among copper wires and bloom-moss in a scrap garden of {region}.",
  },
  {
    id: "spirit-marsh-lantern",
    compatibleRegions: ["Spirit Marsh"],
    compatibleAffinities: ["SPIRIT", "GROVE", "TIDE"],
    incompatibleSources: ["BREEDING"],
    text: "Left beneath a lantern reed in {region}, glowing only when someone whispered nearby.",
  },
  {
    id: "commons-recovery-center",
    compatibleRegions: ["Riftwild Commons"],
    incompatibleSources: ["BREEDING"],
    text: "Left at a recovery center in {region} with no note—only a soft shell-mark matching a local crest.",
  },
  {
    id: "commons-traveling-npc",
    compatibleRegions: ["Riftwild Commons"],
    incompatibleSources: ["BREEDING"],
    text: "Gifted by a traveling Riftkeeper who stopped overnight in {region} and refused payment beyond a promise of care.",
  },
  {
    id: "celestial-gateway",
    compatibleRegions: ["Celestial Rift"],
    compatibleAffinities: ["RADIANT", "VOID", "SPIRIT"],
    incompatibleSources: ["BREEDING", "SHOP"],
    minimumRarity: "EPIC",
    text: "Drawn from a starlit gateway memory along the {region}, where time thinned into silk.",
  },
  {
    id: "vault-forgotten",
    incompatibleSources: ["BREEDING"],
    minimumRarity: "RARE",
    text: "Found inside a forgotten vault whose door seals only answered to {affinity} resonance.",
  },
  {
    id: "boss-aftermath",
    incompatibleSources: ["BREEDING", "SHOP", "STARTER_CLAIM"],
    tags: ["boss"],
    text: "Recovered after a dangerous confrontation near {region}, still warm from residual Rift charge.",
  },
  {
    id: "event-community",
    incompatibleSources: ["BREEDING", "SHOP", "STARTER_CLAIM", "WILD_FIND"],
    tags: ["event"],
    text: "Earned during a community gathering, its shell stamped with the event’s soft Rift sigil.",
  },
  {
    id: "seasonal-release",
    incompatibleSources: ["BREEDING", "WILD_FIND", "BOSS"],
    tags: ["seasonal"],
    text: "Claimed during an official seasonal egg release, wrapped in ceremonial ribbon of {region}.",
  },
  {
    id: "shop-official",
    incompatibleSources: ["BREEDING", "WILD_FIND", "BOSS", "EVENT", "STARTER_CLAIM"],
    tags: ["shop"],
    text: "Purchased during an official egg release and carefully transported to the Hatchery from {region}.",
  },
  {
    id: "starter-hatchery",
    incompatibleSources: ["BREEDING", "SHOP", "EVENT", "BOSS", "WILD_FIND"],
    tags: ["starter"],
    text: "Assigned as a starter companion egg in the Hatchery, chosen for a new Riftkeeper’s first bond.",
  },
  {
    id: "bred-hatchery-nest",
    incompatibleSources: [
      "STARTER_CLAIM",
      "EVENT",
      "SHOP",
      "WILD_FIND",
      "BOSS",
      "SEASONAL",
    ],
    tags: ["bred"],
    text: "Created through careful breeding in the Hatchery. Its parents’ affinities braided into a single shell before incubation began.",
  },
  {
    id: "bred-homestead",
    incompatibleSources: [
      "STARTER_CLAIM",
      "EVENT",
      "SHOP",
      "WILD_FIND",
      "BOSS",
      "SEASONAL",
    ],
    tags: ["bred"],
    text: "Hatched from a bred egg tended at a quiet homestead nest, watched over by both parent lines.",
  },
];
