import { choice, defineNpc, node } from "@/game/npcs/factory";
import type { NpcDef } from "@/game/npcs/types";

const T = 32;

type Compact = {
  id: string;
  slug: string;
  displayName: string;
  shortName: string;
  title: string;
  regionId: string;
  locationId: string;
  col: number;
  row: number;
  occupation: string;
  ageRange: string;
  pronouns: string;
  species?: string;
  traits: string[];
  bio: string;
  look: string;
  clothing: string;
  accessories: string;
  palette: string[];
  style: string;
  history: string;
  riftling: string;
  questFn: string;
  shopOrService: string;
  greet: string[];
  repeat: string[];
  shopId?: string;
  behavior?: Parameters<typeof defineNpc>[0]["ambientBehavior"];
  merchantLine?: string;
};

function regional(c: Compact): NpcDef {
  return defineNpc({
    id: c.id,
    slug: c.slug,
    displayName: c.displayName,
    shortName: c.shortName,
    title: c.title,
    regionId: c.regionId,
    locationId: c.locationId,
    x: c.col * T,
    y: c.row * T,
    occupation: c.occupation,
    ageRange: c.ageRange,
    pronouns: c.pronouns,
    species: c.species,
    personalityTraits: c.traits,
    biography: c.bio,
    visualDescription: c.look,
    clothing: c.clothing,
    accessories: c.accessories,
    colorPalette: c.palette,
    dialogueStyle: c.style,
    personalHistory: c.history,
    riftlingRelationship: c.riftling,
    questFunction: c.questFn,
    shopOrService: c.shopOrService,
    greetingDialogue: c.greet,
    repeatDialogue: c.repeat,
    shopDialogue: c.merchantLine ? [c.merchantLine] : [],
    shopId: c.shopId,
    ambientBehavior: c.behavior ?? "idle",
    dialogueNodes: [
      node("greeting", c.greet, [
        ...(c.shopId
          ? [
              choice("shop", "Browse goods", undefined, {
                action: "open_shop" as const,
                shopId: c.shopId,
              }),
            ]
          : []),
        choice("lore", "Tell me about this place", "lore"),
        choice("bye", "Safe roads", undefined, { action: "close" }),
      ]),
      node(
        "lore",
        [
          `${c.displayName} watches over ${c.regionId.replace(/-/g, " ")}.`,
          c.bio,
        ],
        [choice("back", "Back", "greeting")],
      ),
    ],
  });
}

const RAW: Compact[] = [
  // Ember Crater 11-14
  {
    id: "kael-ashwalker",
    slug: "kael-ashwalker",
    displayName: "Kael Ashwalker",
    shortName: "Kael",
    title: "Crater Scout",
    regionId: "ember-crater",
    locationId: "entrance-camp",
    col: 6,
    row: 8,
    occupation: "Volcano scout",
    ageRange: "30s",
    pronouns: "he/him",
    traits: ["alert", "dry", "loyal"],
    bio: "Kael maps cooled stone paths and warns Keepers when the caldera breathes wrong.",
    look: "Ash-dusted ranger with sharp cheekbones and heat-scarred forearms.",
    clothing: "Heat-resistant cloak, charcoal wrap, crater boots",
    accessories: "Obsidian path-finder, ash goggles",
    palette: ["#1a0e0a", "#ff5a1f", "#ffb84d", "#3de7ff"],
    style: "Terse trail talk",
    history: "Lost a bridge to a surge once — never trusts a 'safe' lava lane again.",
    riftling: "Walks with an Emberkit that senses heat blooms",
    questFn: "Crater guidance and safe-route tips",
    shopOrService: "none",
    greet: ["Stay on cooled stone. I'm Kael Ashwalker.", "Crystal fields glow — mine carefully."],
    repeat: ["Ash storms lie about distance. Count your turns."],
    behavior: "scout",
  },
  {
    id: "forgekeeper-vessa",
    slug: "forgekeeper-vessa",
    displayName: "Forgekeeper Vessa",
    shortName: "Vessa",
    title: "Ember Weaponsmith",
    regionId: "ember-crater",
    locationId: "molten-forge",
    col: 26,
    row: 28,
    occupation: "Weapon specialist",
    ageRange: "40s",
    pronouns: "she/her",
    traits: ["intense", "exacting", "proud"],
    bio: "Vessa forges ember-tempered tools and judges Keepers by how they treat heat.",
    look: "Muscular smith with braided copper hair and forge-glow eyes.",
    clothing: "Molten-forge apron, scaled shoulder guard",
    accessories: "Ember tongs, tempering crystal",
    palette: ["#ff5a1f", "#2a1010", "#ffb84d", "#8a9aaa"],
    style: "Commanding forge voice",
    history: "Inherited the Molten Forge after the Fracture cracked the old guild hall.",
    riftling: "A Magmawhelp curls near her quench trough",
    questFn: "Ember weapon quests",
    shopOrService: "Ember tools",
    shopId: "shop-vessa-ember",
    merchantLine: "Heat-kissed tools — priced in demo credits.",
    greet: ["Forgekeeper Vessa. If it can't take heat, it doesn't leave my bench."],
    repeat: ["Quench twice. Brag once."],
    behavior: "forge",
  },
  {
    id: "cinder-sage-malrec",
    slug: "cinder-sage-malrec",
    displayName: "Cinder Sage Malrec",
    shortName: "Malrec",
    title: "Volcanic Scholar",
    regionId: "ember-crater",
    locationId: "caldera-temple",
    col: 22,
    row: 40,
    occupation: "Scholar",
    ageRange: "60s",
    pronouns: "he/him",
    traits: ["patient", "curious", "soot-stained"],
    bio: "Malrec studies volcanic Riftlings and the memory held in cooled magma glass.",
    look: "Stooped scholar with ember-glass spectacles and ash-white beard.",
    clothing: "Layered sage robes with cinder embroidery",
    accessories: "Lava-glass tablet, soot quill",
    palette: ["#a03020", "#e8d080", "#1a0e0a", "#3de7ff"],
    style: "Lecture-soft, precise",
    history: "Mapped eruption cycles for decades and still calls each one a teacher.",
    riftling: "Consults a thoughtful Ashquill for field notes",
    questFn: "Volcanic lore quests",
    shopOrService: "none",
    greet: ["Ash remembers. Listen before you dig. I am Malrec."],
    repeat: ["Glass tells older stories than smoke."],
    behavior: "read",
  },
  {
    id: "warden-pyra",
    slug: "warden-pyra",
    displayName: "Warden Pyra",
    shortName: "Pyra",
    title: "Lava Warden",
    regionId: "ember-crater",
    locationId: "burned-grove",
    col: 42,
    row: 26,
    occupation: "Settlement protector",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["fierce", "loyal", "watchful"],
    bio: "Pyra keeps lava creatures from pressing the camp perimeter.",
    look: "Tall warden with flame-marked pauldrons and unwavering stare.",
    clothing: "Crimson warden plate over heat weave",
    accessories: "Signal flare rod, ward crest",
    palette: ["#ff5a1f", "#1a2438", "#ffb84d", "#ffffff"],
    style: "Sharp warnings",
    history: "Earned her crest stopping a crawler wave with three Keepers and one stubborn Riftling.",
    riftling: "Commands a disciplined Cinderhound",
    questFn: "Defense patrols",
    shopOrService: "none",
    greet: ["Warden Pyra. Perimeter holds — if you listen."],
    repeat: ["If the ground sings, step back."],
    behavior: "patrol",
  },

  // Moonwater Coast 15-18
  {
    id: "luma-tidecrest",
    slug: "luma-tidecrest",
    displayName: "Captain Luma Tidecrest",
    shortName: "Luma",
    title: "Harbor Captain",
    regionId: "moonwater-coast",
    locationId: "coastal-village",
    col: 8,
    row: 10,
    occupation: "Harbor captain",
    ageRange: "40s",
    pronouns: "she/her",
    traits: ["steady", "salty", "kind"],
    bio: "Luma charts sea routes and tide gates for Keepers arriving by portal or boat.",
    look: "Sun-lined captain with seafoam braids and a navigator's calm.",
    clothing: "Navy captain coat, tide-silk sash",
    accessories: "Brass spyglass, tide whistle",
    palette: ["#1e5a8a", "#c4b896", "#3de7ff", "#e8f7ff"],
    style: "Harbor-command warmth",
    history: "Grew up reading moon tables before she could write her name.",
    riftling: "A Tidefin scout rides her bowsprit when seas allow",
    questFn: "Sea-route guidance",
    shopOrService: "none",
    greet: ["Captain Luma Tidecrest. Tide gates open on the cycle — watch the pools."],
    repeat: ["Fog lies. Charts don't — if you update them."],
    behavior: "look_around",
  },
  {
    id: "finn-coralhand",
    slug: "finn-coralhand",
    displayName: "Finn Coralhand",
    shortName: "Finn",
    title: "Fisher & Gatherer",
    regionId: "moonwater-coast",
    locationId: "moonlit-beach",
    col: 22,
    row: 32,
    occupation: "Fisher",
    ageRange: "20s",
    pronouns: "he/him",
    traits: ["easygoing", "observant", "playful"],
    bio: "Finn teaches coastal gathering and the patience of tide pools.",
    look: "Sun-bleached hair, coral-scarred hands, perpetual grin.",
    clothing: "Rolled sleeves, waterproof wrap pants, open vest",
    accessories: "Bone fishhook, net pouch",
    palette: ["#3a8fd4", "#4adf7a", "#c4b896", "#1a2430"],
    style: "Laid-back coach",
    history: "Learned fishing from Marina Drift and never stopped skipping chores for the tide.",
    riftling: "Buddies with a splashy Puddlefin",
    questFn: "Gathering trainer",
    shopOrService: "Bait & shells",
    shopId: "shop-finn-tide",
    merchantLine: "Bait, shells, and beginner nets.",
    greet: ["Finn Coralhand. Cast near quiet pools — fish prefer calm company."],
    repeat: ["If the pool swirls odd, don't scoop first."],
    behavior: "fish",
  },
  {
    id: "oracle-selene",
    slug: "oracle-selene",
    displayName: "Oracle Selene",
    shortName: "Selene",
    title: "Tide Oracle",
    regionId: "moonwater-coast",
    locationId: "underwater-ruins",
    col: 40,
    row: 10,
    occupation: "Memory oracle",
    ageRange: "ageless",
    pronouns: "she/her",
    traits: ["mysterious", "gentle", "distant"],
    bio: "Selene studies ocean memories and Tide Riftlings that dream in salt.",
    look: "Pale luminous skin, moon-white hair, eyes like deep water.",
    clothing: "Translucent tide veils over silver-blue wraps",
    accessories: "Pearl memory-orb, shell circlet",
    palette: ["#e8f7ff", "#3de7ff", "#1e5a8a", "#9b7bff"],
    style: "Soft prophecy fragments",
    history: "Appeared after a Gateway surge and stayed where the moon hits the water longest.",
    riftling: "Accompanied by a silent Moonray",
    questFn: "Ocean memory quests",
    shopOrService: "none",
    greet: ["The tide keeps what the Gateways forgot. I am Selene."],
    repeat: ["Listen under the foam."],
    behavior: "idle",
  },
  {
    id: "marina-drift",
    slug: "marina-drift",
    displayName: "Marina Drift",
    shortName: "Marina",
    title: "Boat-Builder",
    regionId: "moonwater-coast",
    locationId: "coastal-village",
    col: 6,
    row: 14,
    occupation: "Boat-builder & merchant",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["practical", "funny", "sturdy"],
    bio: "Marina builds coastal craft and sells dockside supplies.",
    look: "Strong arms, salt-stiff curls, paint-flecked cheeks.",
    clothing: "Work tunic, tool belt, waterproof apron",
    accessories: "Keel chalk, copper nails",
    palette: ["#4adf7a", "#3a8fd4", "#c4b896", "#2a2a30"],
    style: "Dockyard banter",
    history: "Repaired every skiff in the village after a storm year — still undercharges friends.",
    riftling: "A wood-chewing Driftling 'helps' sand hulls",
    questFn: "Coastal merchant & boat tips",
    shopOrService: "Dock supplies",
    shopId: "shop-marina-dock",
    merchantLine: "Rope, resin, and honest oars.",
    greet: ["Marina Drift — if it floats, I probably rebuilt it once."],
    repeat: ["Paint after caulk. Always."],
    behavior: "organize_goods",
  },

  // Elderwood 19-22
  {
    id: "warden-sylvi",
    slug: "warden-sylvi",
    displayName: "Warden Sylvi",
    shortName: "Sylvi",
    title: "Forest Guardian",
    regionId: "elderwood-forest",
    locationId: "grove-camp",
    col: 8,
    row: 8,
    occupation: "Forest warden",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["vigilant", "green-hearted", "firm"],
    bio: "Sylvi guards Elderwood paths and keeps Keepers from trampling spirit moss.",
    look: "Lithe guardian with leaf-flecked braid and keen green eyes.",
    clothing: "Moss-cloak, bark-leather bracers",
    accessories: "Living-wood bowpin, path whistle",
    palette: ["#143020", "#4adf7a", "#3de7ff", "#ffb84d"],
    style: "Quiet authority",
    history: "Raised on ranger trails; promoted after guiding lost Keepers through a mist week.",
    riftling: "Bonds with a Mossrunner scout",
    questFn: "Forest path quests",
    shopOrService: "none",
    greet: ["Warden Sylvi. Follow glowing moss if you get lost."],
    repeat: ["Paths twist. Don't chase every light."],
    behavior: "patrol",
  },
  {
    id: "mosskeeper-elden",
    slug: "mosskeeper-elden",
    displayName: "Mosskeeper Elden",
    shortName: "Elden",
    title: "Herbalist",
    regionId: "elderwood-forest",
    locationId: "herb-trails",
    col: 20,
    row: 10,
    occupation: "Herbalist",
    ageRange: "50s",
    pronouns: "he/him",
    traits: ["gentle", "earthy", "wise"],
    bio: "Elden teaches herb gathering and respects every root he harvests.",
    look: "Soft-bellied naturalist with mossy beard beads and dirt under nails.",
    clothing: "Herb-stained robes, woven sash",
    accessories: "Drying rack charm, clay mortar",
    palette: ["#6a9040", "#143020", "#e8f7ff", "#ffb84d"],
    style: "Garden-soft lessons",
    history: "Cataloged grove herbs since before the Commons plaza was paved.",
    riftling: "A Bloomling nestles in his satchel",
    questFn: "Herb quests",
    shopOrService: "Herbs",
    shopId: "shop-elden-herbs",
    merchantLine: "Fresh mossmeal and grove herbs.",
    greet: ["Mosskeeper Elden. Take only what the trail offers twice."],
    repeat: ["Smell before you pick."],
    behavior: "mix_remedies",
  },
  {
    id: "fenn-quickbranch",
    slug: "fenn-quickbranch",
    displayName: "Fenn Quickbranch",
    shortName: "Fenn",
    title: "Hidden-Path Scout",
    regionId: "elderwood-forest",
    locationId: "ancient-grove",
    col: 16,
    row: 24,
    occupation: "Scout",
    ageRange: "teens-20s",
    pronouns: "they/them",
    traits: ["quick", "mischievous", "brave"],
    bio: "Fenn knows shortcuts that maps refuse to print.",
    look: "Wiry scout with leaf-cap and restless feet.",
    clothing: "Camouflage wrap, light boots",
    accessories: "Twig semaphore, seed pouch",
    palette: ["#3a6040", "#4adf7a", "#ffb84d", "#1a2438"],
    style: "Fast whispers",
    history: "Beat Sylvi's trial course twice — then got stuck in a root tunnel once.",
    riftling: "Races a Zipwing through canopy gaps",
    questFn: "Hidden path guidance",
    shopOrService: "none",
    greet: ["Fenn Quickbranch. Want a path the trees pretend isn't there?"],
    repeat: ["If I run, keep up — or mark your own way back."],
    behavior: "scout",
  },
  {
    id: "grandmother-willowmere",
    slug: "grandmother-willowmere",
    displayName: "Grandmother Willowmere",
    shortName: "Willowmere",
    title: "Spiritual Elder",
    regionId: "elderwood-forest",
    locationId: "spirit-glade",
    col: 8,
    row: 36,
    occupation: "Lore elder",
    ageRange: "elder",
    pronouns: "she/her",
    traits: ["serene", "story-rich", "kind"],
    bio: "Willowmere keeps Elderwood spirit stories and blesses careful Keepers.",
    look: "Silver-green hair in willow braids, eyes like deep forest pools.",
    clothing: "Layered leaf-silk robes",
    accessories: "Memory lantern, root cane",
    palette: ["#e8f7ff", "#4adf7a", "#9b7bff", "#143020"],
    style: "Storyteller cadence",
    history: "Outlived three Gateway generations and still plants saplings every spring.",
    riftling: "An ancient Willowisp rests in her lantern",
    questFn: "Spirit lore",
    shopOrService: "none",
    greet: ["Sit, child of the Rift. I am Grandmother Willowmere."],
    repeat: ["Stories grow where feet tread lightly."],
    behavior: "read",
  },
];

// Remaining regions 23-54 in second array for file size clarity
const RAW2: Compact[] = [
  // Stormspire 23-26
  {
    id: "aeron-cloudstep",
    slug: "aeron-cloudstep",
    displayName: "Aeron Cloudstep",
    shortName: "Aeron",
    title: "Mountain Pathfinder",
    regionId: "stormspire-peaks",
    locationId: "trailhead",
    col: 8,
    row: 10,
    occupation: "Pathfinder",
    ageRange: "30s",
    pronouns: "he/him",
    traits: ["bold", "windswept", "reliable"],
    bio: "Aeron marks wind-safe ledges across Stormspire.",
    look: "Lean climber with windburn and sky-blue wrap.",
    clothing: "Stormcloak, harness straps",
    accessories: "Pitons, wind vane pin",
    palette: ["#243848", "#3de7ff", "#e8f7ff", "#ffb84d"],
    style: "Altitude-short sentences",
    history: "Guided a stranded caravan through a lightning week.",
    riftling: "A Stormkite shares thermal reads",
    questFn: "Peak path quests",
    shopOrService: "none",
    greet: ["Aeron Cloudstep. Rope first. Brag later."],
    repeat: ["If the wind turns mean, hug stone."],
    behavior: "scout",
  },
  {
    id: "engineer-volt",
    slug: "engineer-volt",
    displayName: "Engineer Volt",
    shortName: "Volt",
    title: "Storm Researcher",
    regionId: "stormspire-peaks",
    locationId: "spark-lab",
    col: 20,
    row: 16,
    occupation: "Storm-energy engineer",
    ageRange: "20s",
    pronouns: "they/them",
    traits: ["buzzing", "clever", "caffeinated"],
    bio: "Volt measures storm crystals without frying Keepers — usually.",
    look: "Static-frizz hair, goggles, nervous energy.",
    clothing: "Insulated coat, rubberized gloves",
    accessories: "Spark meter, coil notebook",
    palette: ["#ffb84d", "#3de7ff", "#1a2438", "#9b7bff"],
    style: "Tech rambles that land on good advice",
    history: "Once powered a whole camp with a miswired crystal — still banned from that fuse box.",
    riftling: "A Sparkling nests in their instrument case",
    questFn: "Storm research",
    shopOrService: "Spark tools",
    shopId: "shop-volt-spark",
    merchantLine: "Insulators and spark taps.",
    greet: ["Engineer Volt! Don't lick the crystals. Seriously."],
    repeat: ["Ground yourself. Then ground your tools."],
    behavior: "repair",
  },
  {
    id: "skywarden-ilya",
    slug: "skywarden-ilya",
    displayName: "Skywarden Ilya",
    shortName: "Ilya",
    title: "Air-Route Warden",
    regionId: "stormspire-peaks",
    locationId: "skybridge",
    col: 30,
    row: 12,
    occupation: "Sky warden",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["composed", "aerial", "strict"],
    bio: "Ilya protects air routes and skybridge crossings.",
    look: "Feather-trimmed armor, sharp profile, calm eyes.",
    clothing: "Skywarden mantle, light plate",
    accessories: "Signal flags, glide charm",
    palette: ["#e8f7ff", "#3de7ff", "#243848", "#ffb84d"],
    style: "Clear flight instructions",
    history: "Caught a falling Keeper mid-gust and never let anyone skip harness checks again.",
    riftling: "Partners with a Windtalon",
    questFn: "Air safety",
    shopOrService: "none",
    greet: ["Skywarden Ilya. Harness on before the view."],
    repeat: ["Air routes close when pride opens."],
    behavior: "patrol",
  },
  {
    id: "hermit-thane",
    slug: "hermit-thane",
    displayName: "Hermit Thane",
    shortName: "Thane",
    title: "Weather Scholar",
    regionId: "stormspire-peaks",
    locationId: "hermit-cave",
    col: 40,
    row: 28,
    occupation: "Weather hermit",
    ageRange: "70s",
    pronouns: "he/him",
    traits: ["reclusive", "ancient", "accurate"],
    bio: "Thane reads storms older than most maps.",
    look: "Bearded hermit wrapped in cloud-wool, eyes bright as lightning.",
    clothing: "Patchwork storm robes",
    accessories: "Bone weather stick, cloud jar",
    palette: ["#8b93a7", "#e8f7ff", "#1a2438", "#3de7ff"],
    style: "Cryptic then suddenly exact",
    history: "Left the Citadel archives to live where weather tells the truth.",
    riftling: "A sleepy Thunderpuff shares his cave",
    questFn: "Ancient weather lore",
    shopOrService: "none",
    greet: ["Hermit Thane. The sky already answered. Want the translation?"],
    repeat: ["Storms keep diaries. I just read aloud."],
    behavior: "read",
  },

  // Stoneheart 27-30
  {
    id: "doran-flint",
    slug: "doran-flint",
    displayName: "Doran Flint",
    shortName: "Doran",
    title: "Mine Guide",
    regionId: "stoneheart-canyon",
    locationId: "mine-mouth",
    col: 10,
    row: 14,
    occupation: "Miner",
    ageRange: "40s",
    pronouns: "he/him",
    traits: ["sturdy", "blunt", "safe"],
    bio: "Doran leads Keepers through canyon caves without collapsing ceilings.",
    look: "Stocky miner with stone-dust beard and lamp-bright eyes.",
    clothing: "Hard hat wrap, canvas overalls",
    accessories: "Pick, safety chalk",
    palette: ["#6a5a4a", "#ffb84d", "#3de7ff", "#1a2438"],
    style: "Mine-safety bluntness",
    history: "Pulled three crews from a slide and still taps every support beam.",
    riftling: "A Rockbite sniffs unstable seams",
    questFn: "Cave guidance",
    shopOrService: "none",
    greet: ["Doran Flint. Tap the beam. Then dig."],
    repeat: ["If dust falls up, leave."],
    behavior: "pace",
  },
  {
    id: "petra-stoneveil",
    slug: "petra-stoneveil",
    displayName: "Petra Stoneveil",
    shortName: "Petra",
    title: "Relic Archaeologist",
    regionId: "stoneheart-canyon",
    locationId: "dig-site",
    col: 24,
    row: 20,
    occupation: "Archaeologist",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["meticulous", "excited", "dusty"],
    bio: "Petra uncovers pre-Fracture relics sealed in canyon stone.",
    look: "Spectacled digger with scarf over dust and ink on wrists.",
    clothing: "Field coat, knee pads, relic gloves",
    accessories: "Brush set, site tags",
    palette: ["#c4b896", "#1a2438", "#9b7bff", "#ffb84d"],
    style: "Museum enthusiasm outdoors",
    history: "Found a Gateway seal that still hummed — and politely put it back until Solen arrived.",
    riftling: "A Relicurl carries sample trays",
    questFn: "Relic quests",
    shopOrService: "none",
    greet: ["Petra Stoneveil. Don't pocket unmarked shards."],
    repeat: ["Context first. Shine second."],
    behavior: "organize_goods",
  },
  {
    id: "marshal-korr",
    slug: "marshal-korr",
    displayName: "Marshal Korr",
    shortName: "Korr",
    title: "Canyon Security",
    regionId: "stoneheart-canyon",
    locationId: "checkpoint",
    col: 16,
    row: 10,
    occupation: "Marshal",
    ageRange: "40s",
    pronouns: "he/him",
    traits: ["stern", "just", "immovable"],
    bio: "Korr keeps canyon trails secure from raiders and reckless digs.",
    look: "Broad marshal with stone-gray coat and iron stare.",
    clothing: "Canyon badge coat, reinforced boots",
    accessories: "Badge, restraint cord",
    palette: ["#4a4038", "#ffb84d", "#8b93a7", "#3de7ff"],
    style: "Lawful brevity",
    history: "Negotiated a diggers' truce that still holds on paper and mostly in practice.",
    riftling: "A Bastionhound guards his post",
    questFn: "Security quests",
    shopOrService: "none",
    greet: ["Marshal Korr. Papers optional. Common sense mandatory."],
    repeat: ["Checkpoint closes for fools and floods."],
    behavior: "patrol",
  },
  {
    id: "gemwright-opal",
    slug: "gemwright-opal",
    displayName: "Gemwright Opal",
    shortName: "Opal",
    title: "Jeweler",
    regionId: "stoneheart-canyon",
    locationId: "gem-stall",
    col: 28,
    row: 12,
    occupation: "Jeweler & upgrader",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["sparkling", "fair", "precise"],
    bio: "Opal cuts gems and explains upgrade sockets without hype.",
    look: "Bright eyes, gem-dust freckles, meticulous hands.",
    clothing: "Velvet work vest, crystal loupe chain",
    accessories: "Facet tools, sample tray",
    palette: ["#9b7bff", "#3de7ff", "#ffb84d", "#1a2438"],
    style: "Boutique clarity",
    history: "Left Citadel courts to cut stones where miners still know their names.",
    riftling: "A Glintling sorts chips by color",
    questFn: "Upgrade intro",
    shopOrService: "Gems & polish",
    shopId: "shop-opal-gems",
    merchantLine: "Polish kits and starter sockets.",
    greet: ["Gemwright Opal — beauty with receipts."],
    repeat: ["Clarity beats carat for Keepers on day one."],
    behavior: "organize_goods",
  },

  // Frostveil 31-34
  {
    id: "freya-snowmark",
    slug: "freya-snowmark",
    displayName: "Freya Snowmark",
    shortName: "Freya",
    title: "Survival Guide",
    regionId: "frostveil-basin",
    locationId: "snow-camp",
    col: 10,
    row: 12,
    occupation: "Cold-region guide",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["tough", "warm-hearted", "prepared"],
    bio: "Freya teaches cold survival without romanticizing frostbite.",
    look: "Fur-lined hood, wind-red cheeks, steady gaze.",
    clothing: "Insulated explorer coat, snow gaiters",
    accessories: "Flare stick, heat stone",
    palette: ["#e8f7ff", "#3de7ff", "#1a2438", "#ffb84d"],
    style: "Survival checklist talk",
    history: "Wintered alone after a portal misfire and wrote the basin's first safety pamphlet.",
    riftling: "A Frostfox warms her pack",
    questFn: "Survival quests",
    shopOrService: "Cold kits",
    shopId: "shop-freya-cold",
    merchantLine: "Warmth packs and ice picks.",
    greet: ["Freya Snowmark. Layers beat bravado."],
    repeat: ["If your fingers go quiet, turn back."],
    behavior: "scout",
  },
  {
    id: "jori-icebloom",
    slug: "jori-icebloom",
    displayName: "Jori Icebloom",
    shortName: "Jori",
    title: "Frost Alchemist",
    regionId: "frostveil-basin",
    locationId: "alchemy-tent",
    col: 18,
    row: 14,
    occupation: "Alchemist",
    ageRange: "20s",
    pronouns: "they/them",
    traits: ["curious", "chilly-humored", "careful"],
    bio: "Jori brews frost-herb remedies that shouldn't explode — and mostly don't.",
    look: "Pale chemist with ice-crystal earrings and blue-stained fingertips.",
    clothing: "White lab wrap over winter layers",
    accessories: "Frost vial rack, thermometer pin",
    palette: ["#a0e0ff", "#9b7bff", "#e8f7ff", "#1a2438"],
    style: "Lab notes spoken aloud",
    history: "Apprenticed under Nyla's marsh mentors, then followed cold herbs north.",
    riftling: "An Icebloom sprite stirs gentle chill",
    questFn: "Frost herb quests",
    shopOrService: "Frost potions",
    shopId: "shop-jori-frost",
    merchantLine: "Chill salves and focus draughts.",
    greet: ["Jori Icebloom. Don't lick the blue ones."],
    repeat: ["Cold preserves. Heat finishes."],
    behavior: "mix_remedies",
  },
  {
    id: "hunter-varek",
    slug: "hunter-varek",
    displayName: "Hunter Varek",
    shortName: "Varek",
    title: "Frost Tracker",
    regionId: "frostveil-basin",
    locationId: "track-line",
    col: 28,
    row: 20,
    occupation: "Hunter",
    ageRange: "40s",
    pronouns: "he/him",
    traits: ["quiet", "lethal", "ethical"],
    bio: "Varek tracks dangerous frozen creatures and teaches restraint.",
    look: "Scarred tracker with white-blond beard ice and pale eyes.",
    clothing: "Camo winter cloak, silent boots",
    accessories: "Bone charms, tracking lens",
    palette: ["#8b93a7", "#e8f7ff", "#1a2438", "#ff5a5a"],
    style: "Whispered field craft",
    history: "Quit trophy culture after a void-touched hunt went wrong.",
    riftling: "A Snowstalker shares his silence",
    questFn: "Hunt warnings",
    shopOrService: "none",
    greet: ["Hunter Varek. Track to understand — strike only to survive."],
    repeat: ["Prints lie in wind. Wait for the second set."],
    behavior: "scout",
  },
  {
    id: "aurora-linn",
    slug: "aurora-linn",
    displayName: "Aurora Linn",
    shortName: "Aurora",
    title: "Northern Lights Scholar",
    regionId: "frostveil-basin",
    locationId: "aurora-ridge",
    col: 36,
    row: 10,
    occupation: "Celestial energy scholar",
    ageRange: "20s",
    pronouns: "she/her",
    traits: ["wonderstruck", "bright", "night-owl"],
    bio: "Aurora studies northern lights for Celestial energy echoes.",
    look: "Glow-kissed skin, aurora-dyed tips in dark hair.",
    clothing: "Star-thread coat, soft mittens",
    accessories: "Sky prism, night journal",
    palette: ["#9b7bff", "#3de7ff", "#ff9ad5", "#0a101c"],
    style: "Poetic science",
    history: "Followed a light ribbon from Coast to Basin and never stopped looking up.",
    riftling: "A Lumenkit pulses with her readings",
    questFn: "Aurora lore",
    shopOrService: "none",
    greet: ["Aurora Linn. When the sky paints, the Rift is speaking softly."],
    repeat: ["Don't chase every color. Some are echos."],
    behavior: "look_around",
  },

  // Radiant Citadel 35-38
  {
    id: "chancellor-aurex",
    slug: "chancellor-aurex",
    displayName: "Chancellor Aurex",
    shortName: "Aurex",
    title: "Citadel Chancellor",
    regionId: "radiant-citadel",
    locationId: "hall",
    col: 16,
    row: 12,
    occupation: "Political leader",
    ageRange: "50s",
    pronouns: "he/him",
    traits: ["diplomatic", "burdened", "radiant"],
    bio: "Aurex balances Citadel politics with Keeper needs after the Fracture.",
    look: "Silver-gold robes, composed face, tired kindness in the eyes.",
    clothing: "Chancellor mantle with sunthread",
    accessories: "Seal ring, light staff",
    palette: ["#e8d080", "#ffffff", "#3de7ff", "#1a2438"],
    style: "Formal but human",
    history: "Helped open Commons portals when factions wanted them sealed.",
    riftling: "A Luminguard stands at his side in ceremonies",
    questFn: "Political / history quests",
    shopOrService: "none",
    greet: ["Chancellor Aurex. The Citadel remembers — and still argues."],
    repeat: ["Policy is slow. Kindness can be quick."],
    behavior: "idle",
  },
  {
    id: "scholar-lyra",
    slug: "scholar-lyra",
    displayName: "Scholar Lyra",
    shortName: "Lyra",
    title: "Gateway Heart Researcher",
    regionId: "radiant-citadel",
    locationId: "research-wing",
    col: 24,
    row: 14,
    occupation: "Researcher",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["brilliant", "intense", "hopeful"],
    bio: "Lyra studies the Gateway Heart and how Keepers stabilize it.",
    look: "Ink-smudged genius with luminous irises and messy bun.",
    clothing: "Research coat over citadel silk",
    accessories: "Heart schematic slate",
    palette: ["#3de7ff", "#e8d080", "#9b7bff", "#1a2438"],
    style: "Fast science, slower feelings",
    history: "Published the first post-Fracture Heart model Solen still cites.",
    riftling: "A Prismling projects her diagrams",
    questFn: "Gateway research",
    shopOrService: "none",
    greet: ["Scholar Lyra. The Heart isn't a battery — it's a promise."],
    repeat: ["Measure twice. Portal once."],
    behavior: "read",
  },
  {
    id: "sentinel-cassian",
    slug: "sentinel-cassian",
    displayName: "Sentinel Cassian",
    shortName: "Cassian",
    title: "Citadel Defender",
    regionId: "radiant-citadel",
    locationId: "gate",
    col: 10,
    row: 20,
    occupation: "Sentinel",
    ageRange: "30s",
    pronouns: "he/him",
    traits: ["honorable", "bright", "dutiful"],
    bio: "Cassian defends Citadel gates and trains ceremonial guards.",
    look: "Polished armor, open face, disciplined stance.",
    clothing: "Radiant sentinel plate",
    accessories: "Sunspear pin, oath band",
    palette: ["#ffffff", "#e8d080", "#3de7ff", "#1a2438"],
    style: "Oath-clear speech",
    history: "Stood the night a void echo tested the southern gate.",
    riftling: "A Brightpaw shares watch rotations",
    questFn: "Defense drills",
    shopOrService: "none",
    greet: ["Sentinel Cassian. State your purpose — then welcome."],
    repeat: ["Light holds better with friends at the wall."],
    behavior: "patrol",
  },
  {
    id: "curator-verin",
    slug: "curator-verin",
    displayName: "Curator Verin",
    shortName: "Verin",
    title: "Artifact Curator",
    regionId: "radiant-citadel",
    locationId: "museum",
    col: 30,
    row: 16,
    occupation: "Curator",
    ageRange: "40s",
    pronouns: "they/them",
    traits: ["precise", "protective", "witty"],
    bio: "Verin manages recovered artifacts and hates sticky fingers.",
    look: "Elegant curator gloves, sharp bob, evaluating gaze.",
    clothing: "Museum coat with gold trim",
    accessories: "Catalog monocle, white gloves",
    palette: ["#e8d080", "#1a2438", "#3de7ff", "#c8b090"],
    style: "Museum dry humor",
    history: "Caught a forged relic ring that nearly rewrote Fracture timelines.",
    riftling: "A Archivewisp floats label tags",
    questFn: "Artifact quests",
    shopOrService: "Replica seals",
    shopId: "shop-verin-relics",
    merchantLine: "Replica seals — not forgeries.",
    greet: ["Curator Verin. Look. Don't lick. Don't loot."],
    repeat: ["Provenance or it doesn't enter the hall."],
    behavior: "organize_goods",
  },

  // Void Hollow 39-42
  {
    id: "shadecaller-neris",
    slug: "shadecaller-neris",
    displayName: "Shadecaller Neris",
    shortName: "Neris",
    title: "Void Guide",
    regionId: "void-hollow",
    locationId: "threshold",
    col: 12,
    row: 14,
    occupation: "Void guide",
    ageRange: "ageless",
    pronouns: "she/her",
    traits: ["unnerving", "helpful", "honest"],
    bio: "Neris guides Keepers through unstable Void pockets without sugarcoating danger.",
    look: "Shadow-edged cloak, fan of dark hair, eyes like eclipses.",
    clothing: "Voidweave wraps",
    accessories: "Anchor charm, shade lantern",
    palette: ["#1a1020", "#9b7bff", "#3de7ff", "#ff5a5a"],
    style: "Calm dread clarity",
    history: "Walked out of a hollow that shouldn't have exits — and kept the map.",
    riftling: "A Shadekit dissolves when nervous",
    questFn: "Void navigation",
    shopOrService: "none",
    greet: ["Shadecaller Neris. Hold my lantern. Don't chase whispers."],
    repeat: ["If a path offers everything, it wants something."],
    behavior: "scout",
  },
  {
    id: "watcher-omen",
    slug: "watcher-omen",
    displayName: "Watcher Omen",
    shortName: "Omen",
    title: "Corruption Monitor",
    regionId: "void-hollow",
    locationId: "watch-spire",
    col: 22,
    row: 10,
    occupation: "Watcher",
    ageRange: "unknown",
    pronouns: "they/them",
    traits: ["still", "prophetic", "tired"],
    bio: "Omen monitors corruption blooms and sounds quiet alarms.",
    look: "Hooded sentinel with constellation freckles across gray skin.",
    clothing: "Watch-order robes",
    accessories: "Corruption gauge, sealed eye-charm",
    palette: ["#2a2030", "#ff5a5a", "#3de7ff", "#e8f7ff"],
    style: "Sparse omens",
    history: "Predicted three hollow surges — two were believed in time.",
    riftling: "An Omencurl coils around their gauge",
    questFn: "Corruption alerts",
    shopOrService: "none",
    greet: ["Watcher Omen. The bloom is quieter today. Stay loud anyway."],
    repeat: ["Silence is data."],
    behavior: "look_around",
  },
  {
    id: "veya-dusk",
    slug: "veya-dusk",
    displayName: "Veya Dusk",
    shortName: "Veya",
    title: "Void Researcher",
    regionId: "void-hollow",
    locationId: "lab-ruin",
    col: 30,
    row: 18,
    occupation: "Researcher",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["brave", "scientific", "haunted"],
    bio: "Veya researches Void physics while refusing to become it.",
    look: "Dark circles, bright mind, violet-streaked black hair.",
    clothing: "Layered research armor",
    accessories: "Sample vials, null gloves",
    palette: ["#9b7bff", "#1a1020", "#3de7ff", "#ffffff"],
    style: "Field-lab urgency",
    history: "Lost a mentor to a hollow echo and stayed to finish the paper.",
    riftling: "A Nullpup stays at heel",
    questFn: "Void research",
    shopOrService: "none",
    greet: ["Veya Dusk. Samples only from marked zones."],
    repeat: ["Curiosity without anchors is how hollows grow."],
    behavior: "read",
  },
  {
    id: "keeper-null",
    slug: "keeper-null",
    displayName: "Keeper Null",
    shortName: "Null",
    title: "Sealed Ruins Custodian",
    regionId: "void-hollow",
    locationId: "sealed-gate",
    col: 36,
    row: 24,
    occupation: "Custodian",
    ageRange: "unknown",
    pronouns: "it/its",
    traits: ["enigmatic", "absolute", "patient"],
    bio: "Null watches sealed ruins and opens them only for the ready.",
    look: "Feature-soft silhouette in matte void plate, voice like distant glass.",
    clothing: "Sealed custodian shell",
    accessories: "Key-of-absence, silent bell",
    palette: ["#0a0a0f", "#3de7ff", "#9b7bff", "#8b93a7"],
    style: "Ritual minimalism",
    history: "No living Keeper remembers appointing Null — yet the seals obey.",
    riftling: "None visible — perhaps it is the companion",
    questFn: "Sealed ruin story gates",
    shopOrService: "none",
    greet: ["Keeper Null. Readiness is quieter than desire."],
    repeat: ["Not yet."],
    behavior: "idle",
  },

  // Alloy Ruins 43-46
  {
    id: "tinker-pax",
    slug: "tinker-pax",
    displayName: "Tinker Pax",
    shortName: "Pax",
    title: "Machine Expert",
    regionId: "alloy-ruins",
    locationId: "workshop",
    col: 12,
    row: 14,
    occupation: "Ancient-machine expert",
    ageRange: "40s",
    pronouns: "he/him",
    traits: ["grease-smart", "optimistic", "loud"],
    bio: "Pax reverse-engineers Alloy machines with Pip-level enthusiasm.",
    look: "Oil-streaked inventor with wild mustache and bright eyes.",
    clothing: "Machinist coveralls, magnetic tool sash",
    accessories: "Ratchet crown, blueprint roll",
    palette: ["#c07040", "#3de7ff", "#8b93a7", "#1a2438"],
    style: "Workshop bellows",
    history: "Restarted a Gateway gear that hadn't turned since the Fracture — then politely turned it off.",
    riftling: "A Cogling fetches bolts",
    questFn: "Machine repair quests",
    shopOrService: "Parts",
    shopId: "shop-pax-parts",
    merchantLine: "Gears, grease, and hope.",
    greet: ["Tinker Pax! If it ticks, we can teach it manners."],
    repeat: ["Lefty loosey — unless it's Alloy, then read the rune."],
    behavior: "repair",
  },
  {
    id: "unit-ari-7",
    slug: "unit-ari-7",
    displayName: "Unit ARI-7",
    shortName: "ARI-7",
    title: "Mechanical Custodian",
    regionId: "alloy-ruins",
    locationId: "core-hall",
    col: 22,
    row: 16,
    occupation: "Mechanical NPC",
    species: "alloy construct",
    ageRange: "pre-Fracture+",
    pronouns: "it/its",
    traits: ["logical", "loyal", "learning"],
    bio: "ARI-7 is an original Riftwilds mechanical caretaker still running on residual Gateway charge.",
    look: "Polished alloy chassis with cyan optic band and soft joint lights.",
    clothing: "Integral plating with keeper-era insignia",
    accessories: "Status antenna, tool digits",
    palette: ["#8b93a7", "#3de7ff", "#ffb84d", "#1a2438"],
    style: "Polite machine cadence",
    history: "Rebooted after centuries and chose to help Keepers rather than seal halls forever.",
    riftling: "Treats Gearlings as junior units",
    questFn: "Alloy lore & access",
    shopOrService: "none",
    greet: ["Unit ARI-7 online. Welcome, Keeper. Directives: assist, protect, catalog."],
    repeat: ["Battery stable. Curiosity: elevated."],
    behavior: "pace",
  },
  {
    id: "salvager-knox",
    slug: "salvager-knox",
    displayName: "Salvager Knox",
    shortName: "Knox",
    title: "Ruins Merchant",
    regionId: "alloy-ruins",
    locationId: "scrap-yard",
    col: 30,
    row: 20,
    occupation: "Salvager merchant",
    ageRange: "30s",
    pronouns: "he/him",
    traits: ["shrewd", "friendly", "resourceful"],
    bio: "Knox sells salvage and buys scrap without cheating newcomers too hard.",
    look: "Scrap-armor jacket, crooked smile, magnetic fingers.",
    clothing: "Patchwork salvage coat",
    accessories: "Price magnet, scrap scales",
    palette: ["#8b93a7", "#ffb84d", "#c07040", "#1a2438"],
    style: "Scrap-yard charm",
    history: "Turned a junk field into a Keepers' supply line.",
    riftling: "A Scrapling sorts shiny from useful",
    questFn: "Salvage trade",
    shopOrService: "Salvage goods",
    shopId: "shop-knox-salvage",
    merchantLine: "Bolts, plates, and almost-working gadgets.",
    greet: ["Salvager Knox. One Keeper's scrap is another's upgrade."],
    repeat: ["I buy honest scrap. I sell labeled scrap."],
    behavior: "organize_goods",
  },
  {
    id: "professor-ferrum",
    slug: "professor-ferrum",
    displayName: "Professor Ferrum",
    shortName: "Ferrum",
    title: "Alloy Scholar",
    regionId: "alloy-ruins",
    locationId: "lecture-deck",
    col: 18,
    row: 24,
    occupation: "Professor",
    ageRange: "60s",
    pronouns: "he/him",
    traits: ["lecturing", "kind", "metal-minded"],
    bio: "Ferrum researches technology preserved by Alloy Riftlings.",
    look: "Spectacles on alloy chain, iron-gray hair, chalky fingers.",
    clothing: "Academic coat with metal thread",
    accessories: "Lecture slate, sample magnet",
    palette: ["#8b93a7", "#3de7ff", "#e8d080", "#1a2438"],
    style: "Professorial warmth",
    history: "Debated Solen for a decade and still sends friendly footnotes.",
    riftling: "An Alloyquill takes dictation",
    questFn: "Tech lore",
    shopOrService: "none",
    greet: ["Professor Ferrum. Alloy Riftlings are archivists with teeth."],
    repeat: ["Technology is a fossil until a Keeper asks why."],
    behavior: "read",
  },

  // Spirit Marsh 47-50
  {
    id: "medium-amara",
    slug: "medium-amara",
    displayName: "Medium Amara",
    shortName: "Amara",
    title: "Memory Medium",
    regionId: "spirit-marsh",
    locationId: "lantern-dock",
    col: 12,
    row: 14,
    occupation: "Medium",
    ageRange: "30s",
    pronouns: "she/her",
    traits: ["empathic", "serene", "brave"],
    bio: "Amara communicates with marsh memories without trapping them.",
    look: "Lantern-lit face, reed-woven hair charms, soft glow at fingertips.",
    clothing: "Marsh veils, waterproof wraps",
    accessories: "Memory bell, reed staff",
    palette: ["#1a4050", "#9b7bff", "#e8f7ff", "#4adf7a"],
    style: "Soft ritual speech",
    history: "Learned from Willowmere and brought lantern rites to the marsh docks.",
    riftling: "A Mistwisp orbits her bell",
    questFn: "Memory quests",
    shopOrService: "none",
    greet: ["Medium Amara. Speak kindly — the marsh echoes tone."],
    repeat: ["Memories visit. They do not owe us stays."],
    behavior: "idle",
  },
  {
    id: "ferryman-grey",
    slug: "ferryman-grey",
    displayName: "Ferryman Grey",
    shortName: "Grey",
    title: "Marsh Ferryman",
    regionId: "spirit-marsh",
    locationId: "ferry",
    col: 20,
    row: 22,
    occupation: "Ferryman",
    ageRange: "50s",
    pronouns: "he/him",
    traits: ["quiet", "reliable", "fog-wise"],
    bio: "Grey ferries Keepers through mist channels others can't read.",
    look: "Gray coat, lantern pole, face half in fog shadow.",
    clothing: "Long ferryman coat, waterproof boots",
    accessories: "Pole, ferry token",
    palette: ["#8b93a7", "#1a4050", "#ffb84d", "#e8f7ff"],
    style: "Few words, exact directions",
    history: "Never lost a passenger who stayed seated — lost many who stood for photos.",
    riftling: "A Fogfin guides the prow",
    questFn: "Transport guidance",
    shopOrService: "Ferry tokens",
    shopId: "shop-grey-ferry",
    merchantLine: "Tokens for marked crossings.",
    greet: ["Ferryman Grey. Sit. Hold the rail. Trust the fog."],
    repeat: ["Standing invites spirits to ask questions."],
    behavior: "pace",
  },
  {
    id: "lantern-keeper-sio",
    slug: "lantern-keeper-sio",
    displayName: "Lantern Keeper Sio",
    shortName: "Sio",
    title: "Lantern Keeper",
    regionId: "spirit-marsh",
    locationId: "lantern-row",
    col: 28,
    row: 16,
    occupation: "Lantern keeper",
    ageRange: "20s",
    pronouns: "they/them",
    traits: ["bright", "protective", "nervous-brave"],
    bio: "Sio lights paths that keep lost spirits from confusing travelers.",
    look: "Youthful keeper with many small lanterns clipped to a harness.",
    clothing: "Glow-thread vest, marsh boots",
    accessories: "Primary lantern, wick tin",
    palette: ["#ffb84d", "#1a4050", "#3de7ff", "#e8f7ff"],
    style: "Earnest caution",
    history: "Took the lantern oath after Amara saved them from a memory loop.",
    riftling: "A Lanternkit carries a spare glow",
    questFn: "Safe path lights",
    shopOrService: "Lantern oil",
    shopId: "shop-sio-lanterns",
    merchantLine: "Oil and wick kits.",
    greet: ["Lantern Keeper Sio. Stay in the light cones."],
    repeat: ["If a lantern blinks twice, wait — don't chase."],
    behavior: "look_around",
  },
  {
    id: "echo-child-nimi",
    slug: "echo-child-nimi",
    displayName: "Echo Child Nimi",
    shortName: "Nimi",
    title: "Memory Echo",
    regionId: "spirit-marsh",
    locationId: "echo-pool",
    col: 34,
    row: 26,
    occupation: "Story NPC",
    ageRange: "appears child",
    pronouns: "they/them",
    species: "memory echo",
    traits: ["mysterious", "playful", "sad-bright"],
    bio: "Nimi is a mysterious story presence tied to forgotten marsh memories.",
    look: "Childlike silhouette with soft afterimage edges and starry eyes.",
    clothing: "Simple reed tunic that flickers like mist",
    accessories: "Broken toy compass",
    palette: ["#e8f7ff", "#9b7bff", "#3de7ff", "#1a4050"],
    style: "Fragmented childlike riddles",
    history: "Appears when Keepers carry unfinished stories — leaves when listened to well.",
    riftling: "Sometimes becomes the companion-shaped memory",
    questFn: "Major memory story beats",
    shopOrService: "none",
    greet: ["I'm Nimi… or I was. Will you remember with me?"],
    repeat: ["The pool keeps secrets that want soft hands."],
    behavior: "look_around",
  },

  // Celestial Rift 51-54
  {
    id: "astronomer-caelis",
    slug: "astronomer-caelis",
    displayName: "Astronomer Caelis",
    shortName: "Caelis",
    title: "Cosmic Astronomer",
    regionId: "celestial-rift",
    locationId: "observatory",
    col: 14,
    row: 12,
    occupation: "Astronomer",
    ageRange: "40s",
    pronouns: "they/them",
    traits: ["awed", "exact", "night-long"],
    bio: "Caelis studies cosmic Rift activity from the Celestial observatory.",
    look: "Star-chart tattoos, silver hair in a scholar's knot, cosmic freckles.",
    clothing: "Observatory cloak with constellation lining",
    accessories: "Astrolabe, night lens",
    palette: ["#0a101c", "#3de7ff", "#9b7bff", "#e8d080"],
    style: "Starlit precision",
    history: "Charted the Fracture flare that woke Celestial Gateways.",
    riftling: "A Starling orbits their astrolabe",
    questFn: "Cosmic observation",
    shopOrService: "none",
    greet: ["Astronomer Caelis. The sky is a ledger if you can stand the cold."],
    repeat: ["Count flares, not wishes."],
    behavior: "look_around",
  },
  {
    id: "guardian-seraphine",
    slug: "guardian-seraphine",
    displayName: "Guardian Seraphine",
    shortName: "Seraphine",
    title: "Celestial Gateway Guardian",
    regionId: "celestial-rift",
    locationId: "gateway",
    col: 24,
    row: 16,
    occupation: "Guardian",
    ageRange: "ageless",
    pronouns: "she/her",
    traits: ["radiant", "solemn", "kind"],
    bio: "Seraphine protects the Celestial Gateway from the unready and the unkind.",
    look: "Tall guardian with soft luminous wings of light-thread, calm gold eyes.",
    clothing: "Celestial plate-silk hybrid armor",
    accessories: "Gateway key-spear, halo band",
    palette: ["#e8d080", "#ffffff", "#3de7ff", "#9b7bff"],
    style: "Sacred clarity",
    history: "Stood the Gateway when lesser seals failed — still greets Keepers by name when earned.",
    riftling: "A Celestpaw rests at her feet between trials",
    questFn: "Gateway trials",
    shopOrService: "none",
    greet: ["Guardian Seraphine. Worthiness is patience with power."],
    repeat: ["The Gateway opens for those who carry others, not trophies."],
    behavior: "idle",
  },
  {
    id: "starforger-orion",
    slug: "starforger-orion",
    displayName: "Starforger Orion",
    shortName: "Orion",
    title: "Celestial Smith",
    regionId: "celestial-rift",
    locationId: "starforge",
    col: 32,
    row: 14,
    occupation: "Celestial craftsman",
    ageRange: "30s",
    pronouns: "he/him",
    traits: ["proud", "creative", "hot-starred"],
    bio: "Orion crafts advanced Celestial equipment from riftlight alloys.",
    look: "Muscular forger with star-burn scars that glow faintly.",
    clothing: "Starforge apron, meteor bracers",
    accessories: "Constellation hammer, cooling comet-stone",
    palette: ["#ffb84d", "#3de7ff", "#0a101c", "#e8d080"],
    style: "Forge poetry",
    history: "Apprenticed under Vessa's legends then found Celestial heat differently honest.",
    riftling: "A Starember coils near the anvil",
    questFn: "Advanced craft gates",
    shopOrService: "Celestial kits",
    shopId: "shop-orion-star",
    merchantLine: "Starter star-temper kits — advanced gear later.",
    greet: ["Starforger Orion. Heat from above, patience from below."],
    repeat: ["Don't quench starlight in pride."],
    behavior: "forge",
  },
  {
    id: "nameless-witness",
    slug: "nameless-witness",
    displayName: "The Nameless Witness",
    shortName: "Witness",
    title: "Veiled Story Presence",
    regionId: "celestial-rift",
    locationId: "veil-altar",
    col: 20,
    row: 28,
    occupation: "Major story NPC",
    ageRange: "unknown",
    pronouns: "they/them",
    species: "unknown",
    traits: ["enigmatic", "ancient", "watching"],
    bio: "The Nameless Witness observes Keeper choices; identity reveals later in the story.",
    look: "Veiled figure with constellation voids for eyes and a silhouette that shifts slightly.",
    clothing: "Layered void-star veils",
    accessories: "Sealed name-locket",
    palette: ["#0a0a0f", "#e8f7ff", "#9b7bff", "#3de7ff"],
    style: "Riddles that become plot",
    history: "Present at the Fracture — or so every record almost says.",
    riftling: "Unclear whether they bond or become",
    questFn: "Late story revelations",
    shopOrService: "none",
    greet: ["…You may call me Witness. Names are doors. Not all should open yet."],
    repeat: ["Return when your companion's story has weight."],
    behavior: "idle",
  },
];

export const REGIONS_NAMED: NpcDef[] = [...RAW, ...RAW2].map(regional);
