import type { NpcShopDef } from "@/game/npcs/types";

export const NPC_SHOPS: NpcShopDef[] = [
  {
    id: "shop-mira-hatchery",
    title: "Mira's Hatchery Supplies",
    sellHint: "Sell surplus care materials here (demo).",
    buy: [
      {
        itemId: "mossmeal",
        name: "Mossmeal",
        price: 5,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/mossmeal.png",
        stock: 20,
      },
      {
        itemId: "basic-pet-meal",
        name: "Basic Pet Meal",
        price: 8,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/basic-pet-meal.png",
        stock: 15,
      },
      {
        itemId: "starter-egg-voucher",
        name: "Starter Egg Voucher",
        price: 0,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "COMMON",
        iconPath: "/assets/ui/map/quest-available.png",
        stock: 1,
      },
    ],
  },
  {
    id: "shop-bram-forge",
    title: "Bram's Forge Counter",
    buy: [
      {
        itemId: "training-claw-blank",
        name: "Training Claw Blank",
        price: 12,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/charstone.png",
        stock: 10,
      },
      {
        itemId: "repair-kit-basic",
        name: "Basic Repair Kit",
        price: 15,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/alloy-scrap.png",
        stock: 8,
      },
    ],
  },
  {
    id: "shop-tessa-exchange",
    title: "Tessa's Beginner Stalls",
    buy: [
      {
        itemId: "travel-snack",
        name: "Travel Snack",
        price: 4,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/emberberry.png",
        stock: 30,
      },
      {
        itemId: "rope-coil",
        name: "Rope Coil",
        price: 6,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/driftwood.png",
        stock: 12,
      },
    ],
  },
  {
    id: "shop-solen-codex",
    title: "Codex Desk",
    buy: [
      {
        itemId: "field-journal",
        name: "Field Journal",
        price: 10,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "COMMON",
        iconPath: "/assets/ui/map/quest-active.png",
        stock: 5,
      },
      {
        itemId: "index-seal",
        name: "Index Seal",
        price: 7,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "COMMON",
        iconPath: "/assets/ui/map/quest-complete.png",
        stock: 5,
      },
    ],
  },
  {
    id: "shop-nyla-recovery",
    title: "Nyla's Recovery Shelf",
    buy: [
      {
        itemId: "herb-salve",
        name: "Herb Salve",
        price: 9,
        currency: "demo_credits",
        family: "POTION",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/potions/herb-salve.png",
        stock: 20,
      },
      {
        itemId: "restore-draught",
        name: "Restore Draught",
        price: 14,
        currency: "demo_credits",
        family: "POTION",
        rarity: "UNCOMMON",
        iconPath: "/assets/items/icons/potions/restore-draught.png",
        stock: 10,
      },
    ],
  },
  {
    id: "shop-pip-gadgets",
    title: "Pip's Gadget Bin",
    buy: [
      {
        itemId: "map-marker-pin",
        name: "Map Marker Pin",
        price: 5,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "COMMON",
        iconPath: "/assets/ui/map/marker.png",
        stock: 10,
      },
      {
        itemId: "resonator-dial",
        name: "Resonator Dial",
        price: 11,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/alloy-scrap.png",
        stock: 6,
      },
    ],
  },
  {
    id: "shop-rook-arena",
    title: "Rook's Training Supplies",
    buy: [
      {
        itemId: "spar-bandage",
        name: "Spar Bandage",
        price: 6,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/potions/herb-salve.png",
        stock: 20,
      },
      {
        itemId: "spar-snack",
        name: "Spar Snack",
        price: 5,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/emberberry.png",
        stock: 20,
      },
    ],
  },
  {
    id: "shop-vessa-ember",
    title: "Vessa's Ember Bench",
    buy: [
      {
        itemId: "charstone",
        name: "Charstone",
        price: 8,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/charstone.png",
        stock: 12,
      },
    ],
  },
  {
    id: "shop-finn-tide",
    title: "Finn's Tide Basket",
    buy: [
      {
        itemId: "bait-bundle",
        name: "Bait Bundle",
        price: 4,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/seaweed-bundle.png",
        stock: 20,
      },
    ],
  },
  {
    id: "shop-marina-dock",
    title: "Marina's Dock Store",
    buy: [
      {
        itemId: "rope-coil",
        name: "Rope Coil",
        price: 6,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/driftwood.png",
        stock: 15,
      },
    ],
  },
  {
    id: "shop-elden-herbs",
    title: "Elden's Herb Satchel",
    buy: [
      {
        itemId: "mossmeal",
        name: "Mossmeal",
        price: 5,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/mossmeal.png",
        stock: 25,
      },
    ],
  },
  {
    id: "shop-volt-spark",
    title: "Volt's Spark Kit",
    buy: [
      {
        itemId: "insulator-tape",
        name: "Insulator Tape",
        price: 7,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/alloy-scrap.png",
        stock: 10,
      },
    ],
  },
  {
    id: "shop-opal-gems",
    title: "Opal's Gem Tray",
    buy: [
      {
        itemId: "polish-kit",
        name: "Polish Kit",
        price: 12,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/moon-pearl.png",
        stock: 8,
      },
    ],
  },
  {
    id: "shop-freya-cold",
    title: "Freya's Cold Kit",
    buy: [
      {
        itemId: "warmth-pack",
        name: "Warmth Pack",
        price: 9,
        currency: "demo_credits",
        family: "CARE",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/emberberry.png",
        stock: 12,
      },
    ],
  },
  {
    id: "shop-jori-frost",
    title: "Jori's Frost Shelf",
    buy: [
      {
        itemId: "chill-salve",
        name: "Chill Salve",
        price: 10,
        currency: "demo_credits",
        family: "POTION",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/potions/herb-salve.png",
        stock: 10,
      },
    ],
  },
  {
    id: "shop-verin-relics",
    title: "Verin's Replica Desk",
    buy: [
      {
        itemId: "replica-seal",
        name: "Replica Seal",
        price: 15,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "UNCOMMON",
        iconPath: "/assets/ui/map/quest-complete.png",
        stock: 5,
      },
    ],
  },
  {
    id: "shop-pax-parts",
    title: "Pax Parts",
    buy: [
      {
        itemId: "alloy-scrap",
        name: "Alloy Scrap",
        price: 6,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/alloy-scrap.png",
        stock: 20,
      },
    ],
  },
  {
    id: "shop-knox-salvage",
    title: "Knox Salvage",
    buy: [
      {
        itemId: "scrap-plate",
        name: "Scrap Plate",
        price: 5,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/alloy-scrap.png",
        stock: 25,
      },
    ],
  },
  {
    id: "shop-grey-ferry",
    title: "Grey's Ferry Tokens",
    buy: [
      {
        itemId: "ferry-token",
        name: "Ferry Token",
        price: 3,
        currency: "demo_credits",
        family: "QUEST",
        rarity: "COMMON",
        iconPath: "/assets/ui/map/waypoint.png",
        stock: 30,
      },
    ],
  },
  {
    id: "shop-sio-lanterns",
    title: "Sio's Lantern Oil",
    buy: [
      {
        itemId: "lantern-oil",
        name: "Lantern Oil",
        price: 4,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "COMMON",
        iconPath: "/assets/items/icons/materials/glowcap.png",
        stock: 20,
      },
    ],
  },
  {
    id: "shop-orion-star",
    title: "Orion's Starforge Kits",
    buy: [
      {
        itemId: "star-temper-kit",
        name: "Star-Temper Kit",
        price: 25,
        currency: "demo_credits",
        family: "MATERIAL",
        rarity: "RARE",
        iconPath: "/assets/items/icons/materials/ember-crystal.png",
        stock: 4,
      },
    ],
  },
];

export const NPC_SHOP_BY_ID = Object.fromEntries(
  NPC_SHOPS.map((s) => [s.id, s]),
) as Record<string, NpcShopDef>;
