import { GENERATOR_VERSION } from "@/lib/world-expansion/config";
import type { MapTemplate, TemplateKey } from "@/lib/world-expansion/types";

const budget = (
  maxProps: number,
  maxNpcs: number,
  maxPlots: number,
  maxDistricts: number,
): MapTemplate["performanceBudget"] => ({
  maxProps,
  maxNpcs,
  maxPlots,
  maxDistricts,
  targetTickMs: 16,
});

/**
 * Data-driven map templates — Living Towns: districts, roads, hubs, no empty scatter.
 */
export const MAP_TEMPLATES: Record<TemplateKey, MapTemplate> = {
  forest_hamlet: {
    key: "forest_hamlet",
    name: "Forest Hamlet",
    biome: "forest",
    mapKind: "permanent",
    blurb: "Lantern paths under canopy — Keeper Row cottages and a well plaza.",
    housingStyles: ["timber_cottage", "grove_cabin", "moss_porch"],
    districtKinds: ["residential", "temple", "farming", "entertainment"],
    hubs: ["well_plaza", "grove_shrine", "woodcutters_yard"],
    roadStyle: "worn_dirt",
    performanceBudget: budget(420, 48, 40, 6),
    softPlayerLimit: 80,
    hardPlayerLimit: 120,
    targetPlotCount: { min: 24, max: 40 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  coastal_village: {
    key: "coastal_village",
    name: "Coastal Village",
    biome: "coastal",
    mapKind: "permanent",
    blurb: "Boardwalk pier, salt cottages, and a tide market square.",
    housingStyles: ["salt_cottage", "pier_loft", "dune_bungalow"],
    districtKinds: ["residential", "fishing", "merchant", "entertainment"],
    hubs: ["tide_square", "pier_hub", "lighthouse_stub"],
    roadStyle: "boardwalk",
    performanceBudget: budget(480, 52, 42, 6),
    softPlayerLimit: 90,
    hardPlayerLimit: 130,
    targetPlotCount: { min: 28, max: 42 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  mountain_hold: {
    key: "mountain_hold",
    name: "Mountain Hold",
    biome: "mountain",
    mapKind: "permanent",
    blurb: "Switchback roads, terrace homes, and a stone gate yard.",
    housingStyles: ["stone_terrace", "cliff_villa", "hold_cabin"],
    districtKinds: ["residential", "military", "crafting", "temple"],
    hubs: ["gate_yard", "forge_terrace", "overlook_shrine"],
    roadStyle: "stone_switchback",
    performanceBudget: budget(400, 44, 36, 5),
    softPlayerLimit: 70,
    hardPlayerLimit: 110,
    targetPlotCount: { min: 22, max: 36 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  farming_croft: {
    key: "farming_croft",
    name: "Farming Croft",
    biome: "farmland",
    mapKind: "permanent",
    blurb: "Crop rows, scarecrow lanes, and a barn commons.",
    housingStyles: ["farmstead", "croft_cabin", "orchard_porch"],
    districtKinds: ["farming", "residential", "merchant", "entertainment"],
    hubs: ["barn_commons", "mill_stub", "greenfold_well"],
    roadStyle: "worn_dirt",
    performanceBudget: budget(380, 40, 44, 5),
    softPlayerLimit: 75,
    hardPlayerLimit: 115,
    targetPlotCount: { min: 28, max: 44 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  merchant_crossroads: {
    key: "merchant_crossroads",
    name: "Merchant Crossroads",
    biome: "merchant",
    mapKind: "permanent",
    blurb: "Stall rows, trade square, and warehouse alleys with purpose.",
    housingStyles: ["shopfront_flat", "warehouse_loft", "trader_townhouse"],
    districtKinds: ["merchant", "residential", "crafting", "entertainment"],
    hubs: ["trade_square", "exchange_hall", "caravan_yard"],
    roadStyle: "curved_cobble",
    performanceBudget: budget(520, 60, 38, 7),
    softPlayerLimit: 110,
    hardPlayerLimit: 160,
    targetPlotCount: { min: 26, max: 38 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  harbor_port: {
    key: "harbor_port",
    name: "Harbor Port",
    biome: "harbor",
    mapKind: "permanent",
    blurb: "Docks cover shoreline, skiff slips, and a customs plaza.",
    housingStyles: ["dockside_flat", "captain_cottage", "net_loft"],
    districtKinds: ["fishing", "merchant", "residential", "guild"],
    hubs: ["customs_plaza", "skiff_slip", "net_market"],
    roadStyle: "boardwalk",
    performanceBudget: budget(500, 56, 40, 6),
    softPlayerLimit: 100,
    hardPlayerLimit: 150,
    targetPlotCount: { min: 26, max: 40 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  beginner_meadow: {
    key: "beginner_meadow",
    name: "Beginner Meadow",
    biome: "meadow",
    mapKind: "beginner_seed",
    blurb: "Soft paths, academy stub, and quiet starter plots — never empty ghost towns.",
    housingStyles: ["starter_cabin", "meadow_cottage"],
    districtKinds: ["residential", "temple", "entertainment", "farming"],
    hubs: ["welcome_hearth", "academy_stub", "helper_bench"],
    roadStyle: "worn_dirt",
    performanceBudget: budget(320, 36, 32, 4),
    softPlayerLimit: 60,
    hardPlayerLimit: 90,
    targetPlotCount: { min: 20, max: 32 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  guild_banner_court: {
    key: "guild_banner_court",
    name: "Guild Banner Court",
    biome: "guild",
    mapKind: "permanent",
    blurb: "Muster yard, banner poles, and hall approaches — cosmetic drill only.",
    housingStyles: ["banner_townhouse", "muster_flat", "hall_annex"],
    districtKinds: ["guild", "residential", "military", "merchant"],
    hubs: ["muster_yard", "banner_hall", "council_steps"],
    roadStyle: "curved_cobble",
    performanceBudget: budget(440, 50, 34, 5),
    softPlayerLimit: 85,
    hardPlayerLimit: 125,
    targetPlotCount: { min: 22, max: 34 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  island_archipelago: {
    key: "island_archipelago",
    name: "Island Archipelago",
    biome: "island",
    mapKind: "permanent",
    blurb: "Bridges between coves, cliff gardens, and a ferry hub.",
    housingStyles: ["cove_cabin", "cliff_garden_villa", "ferry_loft"],
    districtKinds: ["residential", "fishing", "luxury", "temple"],
    hubs: ["ferry_hub", "cove_shrine", "bridge_plaza"],
    roadStyle: "boardwalk",
    performanceBudget: budget(360, 38, 30, 5),
    softPlayerLimit: 55,
    hardPlayerLimit: 85,
    targetPlotCount: { min: 18, max: 30 },
    allowsPermanentHousing: true,
    generatorVersion: GENERATOR_VERSION,
  },
  rift_edge_outpost: {
    key: "rift_edge_outpost",
    name: "Rift-Edge Outpost",
    biome: "rift_edge",
    mapKind: "overflow",
    blurb: "Temporary festival / boss staging — NPCs and events only, no deeds.",
    housingStyles: [],
    districtKinds: ["entertainment", "military", "temple"],
    hubs: ["staging_ring", "event_stage", "safe_logout_tent"],
    roadStyle: "curved_cobble",
    performanceBudget: budget(280, 80, 0, 3),
    softPlayerLimit: 200,
    hardPlayerLimit: 400,
    targetPlotCount: { min: 0, max: 0 },
    allowsPermanentHousing: false,
    generatorVersion: GENERATOR_VERSION,
  },
};

export function getTemplate(key: TemplateKey): MapTemplate {
  return MAP_TEMPLATES[key];
}

export function listTemplates(): MapTemplate[] {
  return Object.values(MAP_TEMPLATES);
}

export function templatesForPermanentHousing(): MapTemplate[] {
  return listTemplates().filter((t) => t.allowsPermanentHousing);
}
