/* AUTO-GENERATED by scripts/comics/emit-issue-009-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_009_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: LEGENDS OF THE RIFT",
    "CAPTION: ISSUE #9 — VOLUME ONE FINALE",
    "CAPTION: THE RIFTWRIGHT"
  ],
  "2": [
    "NARRATION: Legends of the Rift · Volume One · Issue Nine",
    "CAPTION: Previously: Arkan sacrificed. Axiom awoke. Second Forge activated.",
    "CAPTION: “Someone finally reached my Forge.”",
    "CAPTION: VOLUME ONE FINALE"
  ],
  "3": [
    "NARRATION: Riftwilds · Legends of the Rift",
    "CAPTION: Story · Art Direction · Lettering · Continuity",
    "CAPTION: Keeper: Mira Eggwarden  ·  Cal Reed is not canon",
    "CAPTION: Volume One Finale"
  ],
  "4": [
    "CAPTION: CHAPTER NINE",
    "CAPTION: THE RIFTWRIGHT",
    "NARRATION: Volume One Finale — history meets its maker."
  ],
  "5": [
    "NARRATION: After Arkan's sacrifice… the second Forge answered the Gate's last whisper.",
    "WHISPER: Begin the second creation…",
    "CAPTION: SECOND FORGE — ACTIVE",
    "SFX: engine-HUMMMM"
  ],
  "6": [
    "SPEECH (Nira Quill): They're still manufacturing tears.",
    "CREATURE (Axiom): Protocol… rewritten.",
    "SPEECH (Mira Eggwarden): Arkan said they were grown to protect — not obey.",
    "CREATURE (Spark): …yip.",
    "SPEECH (Unknown): So… after all this time… someone finally reached my Forge."
  ],
  "7": [
    "CAPTION: OFFICIAL RECORD — FIRST RIFT",
    "SPEECH (Mira Eggwarden): This record was rewritten.",
    "SPEECH (Cael Vesper): Meridian stamps. Older than Meridian ink underneath.",
    "CREATURE (Axiom): Protocol mismatch.",
    "NARRATION: Someone older than Meridian held the quill."
  ],
  "8": [
    "SPEECH (Elyan Voss): I am Professor Elyan Voss. They named me Riftwright so the world would have a monster.",
    "SPEECH (Mira Eggwarden): If you're the monster… why does the egg answer you like kin?",
    "SPEECH (Elyan Voss): I disappeared before activation. Someone else pushed the final command. I built cradles."
  ],
  "9": [
    "NARRATION: Riftborn were grown to protect — not obey. Then someone rewrote the protocols.",
    "SPEECH (Elyan Voss): Arkan stayed at Engine Alpha. He sacrificed himself so Spark's line could choose.",
    "MAGIC (Arkan (echo)): Finish the cradle, Elyan… not the war.",
    "CREATURE (Axiom): System Restore… incomplete.",
    "WHISPER (Arkan (echo)): The rewrite… was never Meridian's first hand.",
    "SPEECH (Mira Eggwarden): Then help us keep what's left. No more manufactured tears."
  ],
  "10": [
    "SPEECH (Elyan Voss): They needed a name. Mine was already on the blueprints.",
    "SPEECH (Aurelia Voss): Voss… I bargained under a name I never fully owned.",
    "SPEECH (Elyan Voss): Kin is not guilt. Choose what the name means now.",
    "SPEECH (Cael Vesper): I opened one gate under coercion. I won't open another for them.",
    "NARRATION: One hand remains unwritten. Older. Patient."
  ],
  "11": [
    "NARRATION: The Nova bloodline — Prime Companion. Twin-key to the Last Light.",
    "SPEECH (Elyan Voss): Spark was never meant to stand alone.",
    "CREATURE (Spark): …!",
    "SFX: pulse-SYNC"
  ],
  "12": [
    "SPEECH (Mira Eggwarden): No force. No Meridian override. You come if you choose.",
    "CREATURE (Spark): …come.",
    "SFX: CRACK-kk",
    "NARRATION: A second heart answers the first."
  ],
  "13": [
    "NARRATION: Her name is Nova — Prime Companion. Twin-key to Spark.",
    "SPEECH (Mira Eggwarden): Welcome home.",
    "CREATURE (Nova): …mrr.",
    "CREATURE (Spark): …yip!",
    "SFX: STARBURST"
  ],
  "14": [
    "MAGIC: TWIN-KEY LOCK",
    "SPEECH (Elyan Voss): That's the cradle protocol. Not the weapon.",
    "SPEECH (Seris Vale): Subject One… and a Prime. Perfect. Begin Ascendant Protocol.",
    "SFX: ALARM-ooo"
  ],
  "15": [
    "SHOUT (Ascendant Commander): The Forges answer me now!",
    "CAPTION: ASCENDANT COMMANDER — SERIS VALE",
    "SFX: ASCEND-KRRAK"
  ],
  "16": [
    "SFX: CLANG",
    "SPEECH (Nira Quill): Left flank — move!",
    "CREATURE (Mossprig): …hold.",
    "SPEECH (Cael Vesper): Lantern line — stay behind the light!",
    "CREATURE (Axiom): Pulse Repair engaged."
  ],
  "17": [
    "NARRATION: Not an army. A Compact.",
    "CREATURE (Cindermink): Break!",
    "SFX: CHAIN-SNAP",
    "SPEECH (Mira Eggwarden): We keep each other. That's the whole doctrine."
  ],
  "18": [
    "SPEECH (Elyan Voss): If we stabilize both Engines in cradle mode, the artificial tears collapse.",
    "MAGIC (Arkan (echo)): Remember the lattice, not the blade.",
    "SHOUT (Ascendant Commander): Cradle mode dies with you, Professor!",
    "SPEECH (Nira Quill): Not today."
  ],
  "19": [
    "SPEECH (Aurelia Voss): Closed Contract — no more doors for conquerors.",
    "SPEECH (Cael Vesper): I don't ask forgiveness. I ask for useful light.",
    "SPEECH (Mira Eggwarden): Useful light is a start."
  ],
  "20": [
    "NARRATION: Volume One ends where manufactured skies learn to break.",
    "SFX: WAR-ROAR",
    "CAPTION: BATTLE OF THE TWIN FORGES"
  ],
  "21": [
    "SPEECH (Mira Eggwarden): Only if you both choose.",
    "CREATURE (Spark): …choose.",
    "CREATURE (Nova): …choose.",
    "SFX: TWIN-KEY SURGE",
    "SPEECH (Elyan Voss): Now — cradle lattice!"
  ],
  "22": [
    "SFX: KRRAAASH",
    "SFX: VVVOOM",
    "SPEECH (Elyan Voss): Heal the tear — don't widen it!",
    "CREATURE (Axiom): System Restore — 62%.",
    "SPEECH (Nira Quill): Keep the Keepers standing!"
  ],
  "23": [
    "SHOUT (Ascendant Commander): Subjects belong to the sky I make!",
    "SPEECH (Mira Eggwarden): They belong to themselves!",
    "SFX: SHATTER-RING",
    "MAGIC: CRADLE LATTICE LOCK",
    "SPEECH (Seris Vale): …you… rewrote my victory…",
    "SPEECH (Elyan Voss): No. We restored a purpose."
  ],
  "24": [
    "NARRATION: The Engines remember they were built to mend.",
    "MAGIC (Arkan (echo)): Good night, spare heart.",
    "SFX: hummm… steady",
    "CAPTION: ENGINES: CRADLE MODE"
  ],
  "25": [
    "CAPTION: FORGE RECORD — RESTORED",
    "SPEECH (Mira Eggwarden): The world outside will take longer. Truth isn't a switch.",
    "SPEECH (Elyan Voss): Then I will teach. Not hide.",
    "NARRATION: One signature still refuses the light."
  ],
  "26": [
    "SPEECH (Nira Quill): She'll try again.",
    "SPEECH (Mira Eggwarden): Then we keep better doors. We don't become Meridian.",
    "SPEECH (Cael Vesper): Supervised travel. I'll earn the unmasked road.",
    "NARRATION: Found family is a kind of Engine."
  ],
  "27": [
    "SPEECH (Elyan Voss): Professor. Keeper. Merchant. Lantern. Hunter. Companions. That's a faculty.",
    "SPEECH (Mira Eggwarden): That's a home.",
    "WHISPER (Elara Venn (vision)): Keep choosing keeping.",
    "NARRATION: A First Keeper's blessing — echo, not body."
  ],
  "28": [
    "NARRATION: Far above healed Engines… a star forgets how to shine whole.",
    "SPEECH (Mira Eggwarden): What is that?",
    "SPEECH (Elyan Voss): Not Meridian work. Older… or farther.",
    "SFX: distant-chime"
  ],
  "29": [
    "NARRATION: Volume One ends. Something older than Meridian still dreams in pieces.",
    "CAPTION: NEXT — VOLUME TWO",
    "CAPTION: THE SHATTERED STAR"
  ],
  "30": [
    "CAPTION: MIRA EGGWARDEN — Keeper",
    "CAPTION: ELYAN VOSS — Riftwright",
    "CAPTION: SERIS VALE — Ascendant",
    "CAPTION: CAEL · NIRA · AURELIA",
    "NARRATION: Tragedy is not the same as villainy."
  ],
  "31": [
    "CAPTION: NOVA — Prime Companion",
    "CAPTION: SPARK — Last Light / Twin-Key",
    "CAPTION: AXIOM — Adaptive Matrix",
    "NARRATION: Twin-Key Resonance · Pulse Repair · System Restore"
  ],
  "32": [
    "CAPTION: TWIN ENGINES — CRADLE MODE",
    "NARRATION: Artificial Rift production collapses when healing lattice locks.",
    "CAPTION: See technology.json"
  ],
  "33": [
    "CAPTION: VOLUME ONE — FRACTURE DAWN",
    "NARRATION: Nine issues. One Compact. One unfinished signature.",
    "CAPTION: See timeline.json"
  ],
  "34": [
    "NARRATION: We restore what we can prove. We leave unmarked what still hunts in older ink.",
    "CAPTION: MYSTERY RETAINED",
    "CAPTION: Who rewrote history after the First Rift?"
  ],
  "35": [
    "CAPTION: ABILITY — TWIN-KEY RESONANCE",
    "NARRATION: When Spark and Nova act together, cradle protocols override weapon protocols.",
    "CAPTION: Card tease · Codex link"
  ],
  "36": [
    "CAPTION: NEXT VOLUME",
    "CAPTION: THE SHATTERED STAR",
    "NARRATION: Sleeping companions in a broken star. An enemy older than Meridian. Volume Two begins when the sky cracks."
  ],
  "37": [
    "NARRATION: Thank you for reading Volume One of Legends of the Rift.",
    "CAPTION: Keepers · Companions · Compact",
    "CAPTION: Local Archive copy · Volume One Finale"
  ],
  "38": [
    "CAPTION: VOLUME ONE — COMPLETE",
    "NARRATION: The Riftwright was never the only hand on history.",
    "CAPTION: Volume Two: The Shattered Star — Coming Next"
  ]
};

export const ISSUE_009_COMIC: ComicIssue = {
  slug: "the-riftwright",
  issueNumber: 9,
  title: "The Riftwright",
  subtitle: "Chapter Nine — Volume One Finale",
  synopsis: "At the Second Forge, Mira Eggwarden meets Professor Elyan Voss — the Riftwright history blamed. The dormant egg hatches into Nova, Prime Companion and twin-key to Spark. Ascendant Commander Seris Vale wages war for the Engines; cradle lattice wins. History is restored in the Forge records, one older-than-Meridian signature left unmarked. Volume One ends on a shattered star — next: The Shattered Star.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: [
    "the-riftwright",
    "volume-one-finale",
    "elyan-voss",
    "nova",
    "second-forge",
    "issue-009",
    "mira-eggwarden",
    "twin-key",
  ],
  covers: expandCoverVariants("The Riftwright", "/assets/comics/covers/09-the-riftwright.png"),
  pages: [
  {
    id: "the-riftwright-issue-009-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The Riftwright — Cover",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-001.webp",
    artAlt: "The Riftwright — Cover — The Riftwright page 1",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p001-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 8 }, { kind: "caption", text: "ISSUE #9 — VOLUME ONE FINALE", x: 50, y: 16 }, { kind: "caption", text: "THE RIFTWRIGHT", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-002.webp",
    artAlt: "Inside Front Cover — The Riftwright page 2",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p002-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-002.webp",
      
      bubbles: [{ kind: "narration", text: "Legends of the Rift · Volume One · Issue Nine", x: 50, y: 18 }, { kind: "caption", text: "Previously: Arkan sacrificed. Axiom awoke. Second Forge activated.", x: 50, y: 48 }, { kind: "caption", text: "“Someone finally reached my Forge.”", x: 50, y: 72 }, { kind: "caption", text: "VOLUME ONE FINALE", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-003.webp",
    artAlt: "Credits — The Riftwright page 3",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p003-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-003.webp",
      
      bubbles: [{ kind: "narration", text: "Riftwilds · Legends of the Rift", x: 50, y: 20 }, { kind: "caption", text: "Story · Art Direction · Lettering · Continuity", x: 50, y: 45 }, { kind: "caption", text: "Keeper: Mira Eggwarden  ·  Cal Reed is not canon", x: 50, y: 70 }, { kind: "caption", text: "Volume One Finale", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Nine — The Riftwright",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-004.webp",
    artAlt: "Chapter Nine — The Riftwright — The Riftwright page 4",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p004-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER NINE", x: 50, y: 20 }, { kind: "caption", text: "THE RIFTWRIGHT", x: 50, y: 40 }, { kind: "narration", text: "Volume One Finale — history meets its maker.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Second Forge Threshold",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-005.webp",
    artAlt: "Second Forge Threshold — The Riftwright page 5",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p005-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "After Arkan's sacrifice… the second Forge answered the Gate's last whisper.", x: 50, y: 8 }, { kind: "whisper", text: "Begin the second creation…", x: 28, y: 38 }, { kind: "caption", text: "SECOND FORGE — ACTIVE", x: 50, y: 88 }, { kind: "sfx", text: "engine-HUMMMM", x: 78, y: 42 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Machine That Makes Tears",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-006.webp",
    artAlt: "Machine That Makes Tears — The Riftwright page 6",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p006-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "They're still manufacturing tears.", speaker: "Nira Quill", x: 30, y: 22, tail: "down" }, { kind: "creature", text: "Protocol… rewritten.", speaker: "Axiom", x: 70, y: 28, tail: "down-left" }],
    },
    {
      id: "the-riftwright-issue-009-p006-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "Arkan said they were grown to protect — not obey.", speaker: "Mira Eggwarden", x: 40, y: 50, tail: "down" }, { kind: "creature", text: "…yip.", speaker: "Spark", x: 72, y: 70, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p006-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "So… after all this time… someone finally reached my Forge.", speaker: "Unknown", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p007",
    pageNumber: 7,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Archives of Blame",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-007.webp",
    artAlt: "Archives of Blame — The Riftwright page 7",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p007-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-007.webp",
      
      bubbles: [{ kind: "caption", text: "OFFICIAL RECORD — FIRST RIFT", x: 50, y: 20 }],
    },
    {
      id: "the-riftwright-issue-009-p007-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-007.webp",
      
      bubbles: [{ kind: "speech", text: "This record was rewritten.", speaker: "Mira Eggwarden", x: 40, y: 55, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p007-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-007.webp",
      
      bubbles: [{ kind: "speech", text: "Meridian stamps. Older than Meridian ink underneath.", speaker: "Cael Vesper", x: 60, y: 40, tail: "down-left" }, { kind: "creature", text: "Protocol mismatch.", speaker: "Axiom", x: 75, y: 70, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p007-panel-3",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-007.webp",
      
      bubbles: [{ kind: "narration", text: "Someone older than Meridian held the quill.", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p008",
    pageNumber: 8,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Riftwright Speaks",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-008.webp",
    artAlt: "The Riftwright Speaks — The Riftwright page 8",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p008-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "I am Professor Elyan Voss. They named me Riftwright so the world would have a monster.", speaker: "Elyan Voss", x: 35, y: 18, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p008-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "If you're the monster… why does the egg answer you like kin?", speaker: "Mira Eggwarden", x: 65, y: 55, tail: "down-left" }, { kind: "speech", text: "I disappeared before activation. Someone else pushed the final command. I built cradles.", speaker: "Elyan Voss", x: 70, y: 80, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p009",
    pageNumber: 9,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Professor Elyan Voss",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-009.webp",
    artAlt: "Professor Elyan Voss — The Riftwright page 9",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p009-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-009.webp",
      
      bubbles: [{ kind: "narration", text: "Riftborn were grown to protect — not obey. Then someone rewrote the protocols.", x: 50, y: 12 }, { kind: "speech", text: "Arkan stayed at Engine Alpha. He sacrificed himself so Spark's line could choose.", speaker: "Elyan Voss", x: 40, y: 35, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p009-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-009.webp",
      
      bubbles: [{ kind: "magic", text: "Finish the cradle, Elyan… not the war.", speaker: "Arkan (echo)", x: 55, y: 50 }, { kind: "creature", text: "System Restore… incomplete.", speaker: "Axiom", x: 78, y: 70, tail: "up" }, { kind: "whisper", text: "The rewrite… was never Meridian's first hand.", speaker: "Arkan (echo)", x: 35, y: 78, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p009-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "Then help us keep what's left. No more manufactured tears.", speaker: "Mira Eggwarden", x: 45, y: 88, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p010",
    pageNumber: 10,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "History Was a Weapon",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-010.webp",
    artAlt: "History Was a Weapon — The Riftwright page 10",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p010-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "They needed a name. Mine was already on the blueprints.", speaker: "Elyan Voss", x: 40, y: 20, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p010-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "Voss… I bargained under a name I never fully owned.", speaker: "Aurelia Voss", x: 60, y: 45, tail: "down-left" }, { kind: "speech", text: "Kin is not guilt. Choose what the name means now.", speaker: "Elyan Voss", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p010-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "I opened one gate under coercion. I won't open another for them.", speaker: "Cael Vesper", x: 35, y: 50, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p010-panel-3",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-010.webp",
      
      bubbles: [{ kind: "narration", text: "One hand remains unwritten. Older. Patient.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p011",
    pageNumber: 11,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Prime Companion",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-011.webp",
    artAlt: "Prime Companion — The Riftwright page 11",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p011-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "The Nova bloodline — Prime Companion. Twin-key to the Last Light.", x: 50, y: 8 }, { kind: "speech", text: "Spark was never meant to stand alone.", speaker: "Elyan Voss", x: 30, y: 78, tail: "up-right" }, { kind: "creature", text: "…!", speaker: "Spark", x: 68, y: 72, tail: "down" }, { kind: "sfx", text: "pulse-SYNC", x: 80, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p012",
    pageNumber: 12,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Egg of Twin Keys",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-012.webp",
    artAlt: "Egg of Twin Keys — The Riftwright page 12",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p012-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "No force. No Meridian override. You come if you choose.", speaker: "Mira Eggwarden", x: 40, y: 20, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p012-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-012.webp",
      
      bubbles: [{ kind: "creature", text: "…come.", speaker: "Spark", x: 55, y: 50, tail: "down" }, { kind: "sfx", text: "CRACK-kk", x: 70, y: 60 }],
    },
    {
      id: "the-riftwright-issue-009-p012-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-012.webp",
      
      bubbles: [{ kind: "narration", text: "A second heart answers the first.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p013",
    pageNumber: 13,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Nova Hatches",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-013.webp",
    artAlt: "Nova Hatches — The Riftwright page 13",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p013-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-013.webp",
      
      bubbles: [{ kind: "narration", text: "Her name is Nova — Prime Companion. Twin-key to Spark.", x: 50, y: 8 }, { kind: "speech", text: "Welcome home.", speaker: "Mira Eggwarden", x: 28, y: 70, tail: "down-right" }, { kind: "creature", text: "…mrr.", speaker: "Nova", x: 62, y: 62, tail: "down" }, { kind: "creature", text: "…yip!", speaker: "Spark", x: 74, y: 78, tail: "up" }, { kind: "sfx", text: "STARBURST", x: 80, y: 35 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p014",
    pageNumber: 14,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Twin-Key Resonance",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-014.webp",
    artAlt: "Twin-Key Resonance — The Riftwright page 14",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p014-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-014.webp",
      
      bubbles: [{ kind: "magic", text: "TWIN-KEY LOCK", x: 50, y: 18 }, { kind: "speech", text: "That's the cradle protocol. Not the weapon.", speaker: "Elyan Voss", x: 40, y: 80, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p014-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-014.webp",
      
      bubbles: [{ kind: "speech", text: "Subject One… and a Prime. Perfect. Begin Ascendant Protocol.", speaker: "Seris Vale", x: 60, y: 40, tail: "down" }, { kind: "sfx", text: "ALARM-ooo", x: 75, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p015",
    pageNumber: 15,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Ascendant Protocol",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-015.webp",
    artAlt: "Ascendant Protocol — The Riftwright page 15",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p015-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-015.webp",
      
      bubbles: [{ kind: "shout", text: "The Forges answer me now!", speaker: "Ascendant Commander", x: 50, y: 12 }, { kind: "caption", text: "ASCENDANT COMMANDER — SERIS VALE", x: 50, y: 90 }, { kind: "sfx", text: "ASCEND-KRRAK", x: 78, y: 45 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p016",
    pageNumber: 16,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Siege of the Cradle",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-016.webp",
    artAlt: "Siege of the Cradle — The Riftwright page 16",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p016-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-016.webp",
      
      bubbles: [{ kind: "sfx", text: "CLANG", x: 30, y: 20 }, { kind: "speech", text: "Left flank — move!", speaker: "Nira Quill", x: 55, y: 30, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p016-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-016.webp",
      
      bubbles: [{ kind: "creature", text: "…hold.", speaker: "Mossprig", x: 40, y: 55, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p016-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "Lantern line — stay behind the light!", speaker: "Cael Vesper", x: 60, y: 50, tail: "down-left" }],
    },
    {
      id: "the-riftwright-issue-009-p016-panel-3",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-016.webp",
      
      bubbles: [{ kind: "creature", text: "Pulse Repair engaged.", speaker: "Axiom", x: 50, y: 85, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p017",
    pageNumber: 17,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Companions Rally",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-017.webp",
    artAlt: "Companions Rally — The Riftwright page 17",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p017-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-017.webp",
      
      bubbles: [{ kind: "narration", text: "Not an army. A Compact.", x: 50, y: 12 }],
    },
    {
      id: "the-riftwright-issue-009-p017-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-017.webp",
      
      bubbles: [{ kind: "creature", text: "Break!", speaker: "Cindermink", x: 40, y: 50, tail: "down" }, { kind: "sfx", text: "CHAIN-SNAP", x: 70, y: 55 }],
    },
    {
      id: "the-riftwright-issue-009-p017-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "We keep each other. That's the whole doctrine.", speaker: "Mira Eggwarden", x: 50, y: 85, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p018",
    pageNumber: 18,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Engine Control",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-018.webp",
    artAlt: "Engine Control — The Riftwright page 18",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p018-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "If we stabilize both Engines in cradle mode, the artificial tears collapse.", speaker: "Elyan Voss", x: 35, y: 20, tail: "down" }, { kind: "magic", text: "Remember the lattice, not the blade.", speaker: "Arkan (echo)", x: 55, y: 70 }],
    },
    {
      id: "the-riftwright-issue-009-p018-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-018.webp",
      
      bubbles: [{ kind: "shout", text: "Cradle mode dies with you, Professor!", speaker: "Ascendant Commander", x: 65, y: 30, tail: "down-left" }, { kind: "speech", text: "Not today.", speaker: "Nira Quill", x: 40, y: 80, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p019",
    pageNumber: 19,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Roads and Lanterns",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-019.webp",
    artAlt: "Roads and Lanterns — The Riftwright page 19",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p019-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "Closed Contract — no more doors for conquerors.", speaker: "Aurelia Voss", x: 45, y: 22, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p019-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "I don't ask forgiveness. I ask for useful light.", speaker: "Cael Vesper", x: 50, y: 50, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p019-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "Useful light is a start.", speaker: "Mira Eggwarden", x: 50, y: 82, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p020",
    pageNumber: 20,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Twin Forge War",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-020.webp",
    artAlt: "Twin Forge War — The Riftwright page 20",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p020-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-020.webp",
      
      bubbles: [{ kind: "narration", text: "Volume One ends where manufactured skies learn to break.", x: 50, y: 8 }, { kind: "sfx", text: "WAR-ROAR", x: 78, y: 40 }, { kind: "caption", text: "BATTLE OF THE TWIN FORGES", x: 50, y: 90 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p021",
    pageNumber: 21,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Last Light, First Star",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-021.webp",
    artAlt: "Last Light, First Star — The Riftwright page 21",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p021-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "Only if you both choose.", speaker: "Mira Eggwarden", x: 40, y: 20, tail: "down" }, { kind: "creature", text: "…choose.", speaker: "Spark", x: 55, y: 55, tail: "up" }, { kind: "creature", text: "…choose.", speaker: "Nova", x: 70, y: 60, tail: "up-left" }],
    },
    {
      id: "the-riftwright-issue-009-p021-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-021.webp",
      
      bubbles: [{ kind: "sfx", text: "TWIN-KEY SURGE", x: 50, y: 40 }, { kind: "speech", text: "Now — cradle lattice!", speaker: "Elyan Voss", x: 60, y: 80, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p022",
    pageNumber: 22,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Clash — Part One",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-022.webp",
    artAlt: "Clash — Part One — The Riftwright page 22",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p022-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "KRRAAASH", x: 40, y: 25 }],
    },
    {
      id: "the-riftwright-issue-009-p022-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "VVVOOM", x: 55, y: 45 }],
    },
    {
      id: "the-riftwright-issue-009-p022-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-022.webp",
      
      bubbles: [{ kind: "speech", text: "Heal the tear — don't widen it!", speaker: "Elyan Voss", x: 40, y: 60, tail: "down" }, { kind: "creature", text: "System Restore — 62%.", speaker: "Axiom", x: 70, y: 70, tail: "up" }],
    },
    {
      id: "the-riftwright-issue-009-p022-panel-3",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-022.webp",
      
      bubbles: [{ kind: "speech", text: "Keep the Keepers standing!", speaker: "Nira Quill", x: 50, y: 85, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p023",
    pageNumber: 23,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Clash — Part Two",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-023.webp",
    artAlt: "Clash — Part Two — The Riftwright page 23",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p023-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-023.webp",
      
      bubbles: [{ kind: "shout", text: "Subjects belong to the sky I make!", speaker: "Ascendant Commander", x: 55, y: 15, tail: "down" }, { kind: "speech", text: "They belong to themselves!", speaker: "Mira Eggwarden", x: 35, y: 35, tail: "up-right" }],
    },
    {
      id: "the-riftwright-issue-009-p023-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-023.webp",
      
      bubbles: [{ kind: "sfx", text: "SHATTER-RING", x: 50, y: 50 }, { kind: "magic", text: "CRADLE LATTICE LOCK", x: 50, y: 65 }],
    },
    {
      id: "the-riftwright-issue-009-p023-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "…you… rewrote my victory…", speaker: "Seris Vale", x: 45, y: 85, tail: "up" }, { kind: "speech", text: "No. We restored a purpose.", speaker: "Elyan Voss", x: 70, y: 88, tail: "up-left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p024",
    pageNumber: 24,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Engines Stabilize",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-024.webp",
    artAlt: "Engines Stabilize — The Riftwright page 24",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p024-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-024.webp",
      
      bubbles: [{ kind: "narration", text: "The Engines remember they were built to mend.", x: 50, y: 8 }, { kind: "magic", text: "Good night, spare heart.", speaker: "Arkan (echo)", x: 30, y: 70 }, { kind: "sfx", text: "hummm… steady", x: 75, y: 40 }, { kind: "caption", text: "ENGINES: CRADLE MODE", x: 50, y: 90 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p025",
    pageNumber: 25,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "History Restored",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-025.webp",
    artAlt: "History Restored — The Riftwright page 25",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p025-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-025.webp",
      
      bubbles: [{ kind: "caption", text: "FORGE RECORD — RESTORED", x: 50, y: 18 }],
    },
    {
      id: "the-riftwright-issue-009-p025-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-025.webp",
      
      bubbles: [{ kind: "speech", text: "The world outside will take longer. Truth isn't a switch.", speaker: "Mira Eggwarden", x: 45, y: 45, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p025-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-025.webp",
      
      bubbles: [{ kind: "speech", text: "Then I will teach. Not hide.", speaker: "Elyan Voss", x: 55, y: 55, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p025-panel-3",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-025.webp",
      
      bubbles: [{ kind: "narration", text: "One signature still refuses the light.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p026",
    pageNumber: 26,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "What We Keep",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-026.webp",
    artAlt: "What We Keep — The Riftwright page 26",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p026-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "She'll try again.", speaker: "Nira Quill", x: 30, y: 20, tail: "down" }, { kind: "speech", text: "Then we keep better doors. We don't become Meridian.", speaker: "Mira Eggwarden", x: 55, y: 30, tail: "down-left" }],
    },
    {
      id: "the-riftwright-issue-009-p026-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "Supervised travel. I'll earn the unmasked road.", speaker: "Cael Vesper", x: 50, y: 55, tail: "down" }],
    },
    {
      id: "the-riftwright-issue-009-p026-panel-2",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-026.webp",
      
      bubbles: [{ kind: "narration", text: "Found family is a kind of Engine.", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p027",
    pageNumber: 27,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Found Family",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-027.webp",
    artAlt: "Found Family — The Riftwright page 27",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p027-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-027.webp",
      
      bubbles: [{ kind: "speech", text: "Professor. Keeper. Merchant. Lantern. Hunter. Companions. That's a faculty.", speaker: "Elyan Voss", x: 40, y: 18, tail: "down" }, { kind: "speech", text: "That's a home.", speaker: "Mira Eggwarden", x: 60, y: 40, tail: "down-left" }],
    },
    {
      id: "the-riftwright-issue-009-p027-panel-1",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-027.webp",
      
      bubbles: [{ kind: "whisper", text: "Keep choosing keeping.", speaker: "Elara Venn (vision)", x: 50, y: 70, tail: "up" }, { kind: "narration", text: "A First Keeper's blessing — echo, not body.", x: 50, y: 90 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p028",
    pageNumber: 28,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "A Crack in the Sky",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-028.webp",
    artAlt: "A Crack in the Sky — The Riftwright page 28",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p028-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-028.webp",
      
      bubbles: [{ kind: "narration", text: "Far above healed Engines… a star forgets how to shine whole.", x: 50, y: 10 }, { kind: "speech", text: "What is that?", speaker: "Mira Eggwarden", x: 30, y: 70, tail: "up-right" }, { kind: "speech", text: "Not Meridian work. Older… or farther.", speaker: "Elyan Voss", x: 65, y: 78, tail: "up-left" }, { kind: "sfx", text: "distant-chime", x: 80, y: 35 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Shattered Star",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-029.webp",
    artAlt: "The Shattered Star — The Riftwright page 29",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p029-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-029.webp",
      
      bubbles: [{ kind: "narration", text: "Volume One ends. Something older than Meridian still dreams in pieces.", x: 50, y: 8 }, { kind: "caption", text: "NEXT — VOLUME TWO", x: 50, y: 78 }, { kind: "caption", text: "THE SHATTERED STAR", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p030",
    pageNumber: 30,
    layout: "lore" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Character Profiles",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-030.webp",
    artAlt: "Character Profiles — The Riftwright page 30",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p030-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "MIRA EGGWARDEN — Keeper", x: 25, y: 20 }, { kind: "caption", text: "ELYAN VOSS — Riftwright", x: 75, y: 20 }, { kind: "caption", text: "SERIS VALE — Ascendant", x: 25, y: 55 }, { kind: "caption", text: "CAEL · NIRA · AURELIA", x: 75, y: 55 }, { kind: "narration", text: "Tragedy is not the same as villainy.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p031",
    pageNumber: 31,
    layout: "lore" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profiles",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-031.webp",
    artAlt: "Companion Profiles — The Riftwright page 31",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p031-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "NOVA — Prime Companion", x: 50, y: 12 }, { kind: "caption", text: "SPARK — Last Light / Twin-Key", x: 25, y: 40 }, { kind: "caption", text: "AXIOM — Adaptive Matrix", x: 75, y: 40 }, { kind: "narration", text: "Twin-Key Resonance · Pulse Repair · System Restore", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p032",
    pageNumber: 32,
    layout: "lore" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Technology of the Forges",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-032.webp",
    artAlt: "Technology of the Forges — The Riftwright page 32",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p032-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "TWIN ENGINES — CRADLE MODE", x: 50, y: 12 }, { kind: "narration", text: "Artificial Rift production collapses when healing lattice locks.", x: 50, y: 50 }, { kind: "caption", text: "See technology.json", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p033",
    pageNumber: 33,
    layout: "lore" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "Volume One Timeline",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-033.webp",
    artAlt: "Volume One Timeline — The Riftwright page 33",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p033-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-033.webp",
      
      bubbles: [{ kind: "caption", text: "VOLUME ONE — FRACTURE DAWN", x: 50, y: 10 }, { kind: "narration", text: "Nine issues. One Compact. One unfinished signature.", x: 50, y: 50 }, { kind: "caption", text: "See timeline.json", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p034",
    pageNumber: 34,
    layout: "lore" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Behind the Lore",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-034.webp",
    artAlt: "Behind the Lore — The Riftwright page 34",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p034-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-034.webp",
      
      bubbles: [{ kind: "narration", text: "We restore what we can prove. We leave unmarked what still hunts in older ink.", x: 50, y: 30 }, { kind: "caption", text: "MYSTERY RETAINED", x: 50, y: 70 }, { kind: "caption", text: "Who rewrote history after the First Rift?", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p035",
    pageNumber: 35,
    layout: "lore" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Twin-Key Resonance",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-035.webp",
    artAlt: "Ability Spotlight — Twin-Key Resonance — The Riftwright page 35",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p035-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "ABILITY — TWIN-KEY RESONANCE", x: 50, y: 12 }, { kind: "narration", text: "When Spark and Nova act together, cradle protocols override weapon protocols.", x: 50, y: 55 }, { kind: "caption", text: "Card tease · Codex link", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next — Volume Two: The Shattered Star",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-036.webp",
    artAlt: "Next — Volume Two: The Shattered Star — The Riftwright page 36",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p036-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-036.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT VOLUME", x: 50, y: 15 }, { kind: "caption", text: "THE SHATTERED STAR", x: 50, y: 40 }, { kind: "narration", text: "Sleeping companions in a broken star. An enemy older than Meridian. Volume Two begins when the sky cracks.", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-037.webp",
    artAlt: "Inside Back Cover — The Riftwright page 37",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p037-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-037.webp",
      
      bubbles: [{ kind: "narration", text: "Thank you for reading Volume One of Legends of the Rift.", x: 50, y: 30 }, { kind: "caption", text: "Keepers · Companions · Compact", x: 50, y: 60 }, { kind: "caption", text: "Local Archive copy · Volume One Finale", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-riftwright-issue-009-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover",
    artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-038.webp",
    artAlt: "Back Cover — The Riftwright page 38",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-riftwright-issue-009-p038-panel-0",
      artSrc: "/assets/comics/the-riftwright/issue-009/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "VOLUME ONE — COMPLETE", x: 50, y: 15 }, { kind: "narration", text: "The Riftwright was never the only hand on history.", x: 50, y: 45 }, { kind: "caption", text: "Volume Two: The Shattered Star — Coming Next", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Volume One finale POV — protects Spark and Nova." },
    { name: "Professor Elyan Voss", role: "The Riftwright", blurb: "Tragic architect — blamed wrongly for the First Rift." },
    { name: "Nova", role: "Prime Companion", blurb: "Hatched from the dormant egg; twin-key with Spark.", speciesSlug: "nova" },
    { name: "Spark", role: "Last Light / Twin-Key", blurb: "Resonance Keeper — voluntary Compact with Nova.", speciesSlug: "spark" },
    { name: "Seris Vale", role: "Ascendant Commander", blurb: "Defeated and contained — not executed." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Supervised ally — redemption unfinished." },
    { name: "Axiom", role: "Prototype companion", blurb: "Adaptive Matrix · Pulse Repair · System Restore.", speciesSlug: "axiom" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Blessing on the quiet terrace — not present-day POV." },
  ],
  locations: [
    { name: "Second Forge", blurb: "Spare heart under another continent." },
    { name: "Companion Incubator Beta", blurb: "Nova hatch site." },
    { name: "Twin Engine Control", blurb: "Cradle lattice victory." },
    { name: "Shattered Star", blurb: "Volume Two tease only — sleeping companions in a broken star." },
  ],
  timelineNote: "Volume One Finale — after The Forge of Rifts. NEXT: The Shattered Star.",
  playChapterHref: "/comics",
  playChapterLabel: "Archive Shelves",
  unlockGates: [
    { kind: "prior-issue", slug: "the-forge-of-rifts", label: "Complete Issue #8: The Forge of Rifts" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-shattered-star",
    hook: "A broken star sleeps with companions inside. Volume Two begins.",
  },
  readingTimeMinutes: 24,
  factions: [
    { name: "Hatchery Compact", blurb: "Consent over force — twin-key cradle." },
    { name: "Veiled Meridian", blurb: "Ascendant Protocol broken." },
    { name: "Forge Architects", blurb: "Elyan + Arkan echo — healing intent restored." },
  ],
  collectibles: [],
  rewards: [
    {
      id: "rw-volume-one-finale-badge",
      label: "Volume One Finale Badge",
      description: "Archive Shelves badge for completing Legends of the Rift Volume One.",
      kind: "badge",
      creditsStub: 20,
    },
  ],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
  volumeFinale: true,
  shelfBadge: "Volume One Finale",
  commentary: [
    "Volume One Finale. Mystery retained: who manipulated history after the First Rift (older than Meridian).",
    "Do not start Volume Two issues beyond the teaser page.",
  ],
};

export function getIssue009Transcript(pageNumber: number): string[] {
  return ISSUE_009_TRANSCRIPTS[pageNumber] ?? [];
}
