/**
 * Emit client-safe generated catalog module for Issue #010 (Volume Two opener).
 *   npx tsx scripts/comics/emit-issue-010-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-shattered-star/issue-010");
const OUT = path.join(ROOT, "src/content/comics/the-shattered-star/issue-010.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-shattered-star-issue-010-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "celestial")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/10-the-shattered-star.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-010-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_010_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

/** Volume Two opener — unlock after Issue #9 (or admin/dev). */
export const ISSUE_010_COMIC: ComicIssue = {
  slug: "the-shattered-star",
  issueNumber: 10,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: [
    "shattered-star",
    "volume-two",
    "volume-two-opener",
    "celestial-keepers",
    "astra",
    "nova",
    "hollow-ones",
    "issue-010",
    "mira-eggwarden",
  ],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Leads the ascent; learns the sky has a door." },
    { name: "Spark", role: "Resonance Key", blurb: "Designed to reconnect Forge world and Star.", speciesSlug: "spark" },
    { name: "Nova", role: "Hatched Prime Companion", blurb: "Issue #9 hatchling; twin-key with Spark.", speciesSlug: "nova" },
    { name: "High Keeper Lyra", role: "Celestial Keepers", blurb: "Stern guardian who learns to trust anew." },
    { name: "Astra", role: "Prime Celestial Companion", blurb: "Starlight Bond · Celestial Step · Sky of a Thousand Lights.", speciesSlug: "astra" },
    { name: "Professor Elyan Voss", role: "Riftwright", blurb: "Names the Star; guides the twin keys." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Supervised redemption — holds the lantern line." },
    { name: "Aurelia Voss", role: "Gilded Merchant", blurb: "Bargains with the sky without selling consent." },
    { name: "Axiom", role: "Prototype companion", blurb: "Repairs what the Hollow cracks.", speciesSlug: "axiom" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — founding counsel only if invoked." },
  ],
  locations: [
    { name: "The Shattered Star", blurb: "Drifting celestial sanctuary — paradise megastructure." },
    { name: "Prime Sanctuaries", blurb: "Thousands of sleeping Prime companions." },
    { name: "Star Engine", blurb: "Twin Resonance Key core." },
    { name: "Celestial Archives", blurb: "Galaxy maps beyond the Compact." },
    { name: "Guardian Cities", blurb: "Beacon grid supporting from below." },
  ],
  factions: [
    { name: "Celestial Keepers", blurb: "Original guardians of the Primes." },
    { name: "Hollow Ones", blurb: "Consume Rift energy — cannot create." },
    { name: "Keeper Compact", blurb: "Protect, don't obey — now among the stars." },
  ],
  timelineNote: "Volume Two opens — months after Forge Network restoration.",
  playChapterHref: "/live-world",
  playChapterLabel: "Return to Live World",
  unlockGates: [
    { kind: "prior-issue", slug: "the-riftwright", label: "Complete Issue #9: The Riftwright" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-hollow-king",
    hook: "The lights have returned… then so have they.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 20},
  collectibles: [],
  rewards: [],
  arcId: "arc-shattered-sky",
  volumeId: "vol-2-shattered-sky",
  volumeOpener: true,
  shelfBadge: "Volume Two · Issue #1",
  commentary: [
    "Volume Two Issue #1 / Issue #10 — Archive Shelf banner: Volume Two.",
    "Hatched companion continuity: Nova (Issue #9).",
  ],
};

export function getIssue010Transcript(pageNumber: number): string[] {
  return ISSUE_010_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
