/**
 * Emit client-safe generated catalog module for Issue #008.
 *   npx tsx scripts/comics/emit-issue-008-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-forge-of-rifts/issue-008");
const OUT = path.join(ROOT, "src/content/comics/the-forge-of-rifts/issue-008.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-forge-of-rifts-issue-008-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "rift")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/08-the-forge-of-rifts.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-008-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_008_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_008_COMIC: ComicIssue = {
  slug: "the-forge-of-rifts",
  issueNumber: 8,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: ["forge-of-rifts", "arkan", "axiom", "riftborn", "issue-008", "veiled-meridian", "mira-eggwarden", "riftwright"],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Discovers how the First Rift was engineered — protects Spark and the egg." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Missing Forge component who chooses to stabilize — protect, not obey." },
    { name: "Chief Engineer Arkan", role: "Forge architect", blurb: "Last surviving engineer — sacrifices his preserved body." },
    { name: "Axiom", role: "Prototype companion", blurb: "Adaptive Matrix · Pulse Repair · System Restore.", speciesSlug: "axiom" },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Restarts the Forge; steals the Second Forge blueprint." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Supervised redemption from Issue #7 — not instantly trusted." },
    { name: "Nira Quill", role: "Allied hunter", blurb: "Field support after Gate judgment." },
    { name: "The Riftwright", role: "Cliffhanger", blurb: "Alive — silhouette only; identity withheld." },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "The Forge of Rifts", blurb: "Underground civilization that manufactures artificial Rift energy." },
    { name: "Companion Incubator Alpha", blurb: "Origin line of Resonance Keepers." },
    { name: "Rift Engine Alpha", blurb: "Primary reactor — Spark-stabilized." },
    { name: "Second Forge", blurb: "Hidden under another continent — cliffhanger." },
  ],
  timelineNote: "After The Traitor's Gate — Meridian Road into the Forge.",
  playChapterHref: "/live-world",
  playChapterLabel: "Travel the Meridian Road",
  unlockGates: ${JSON.stringify(meta.unlockGates || [
    { kind: "prior-issue", slug: "the-traitors-gate", label: "Complete Issue #7: The Traitor's Gate" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ])},
  nextIssueTeaser: {
    slug: "the-riftwright",
    hook: "So… after all this time… someone finally reached my Forge.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 20},
  factions: [
    { name: "Veiled Meridian", blurb: "Restart Forge; mass-produce artificial Riftborn." },
    { name: "Forge Architects", blurb: "Defunct — Arkan last survivor." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Protect — don't own." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies — wards off-page." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "keepers-road",
  volumeId: "volume-2",
};

export function getIssue008Transcript(pageNumber: number): string[] {
  return ISSUE_008_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
