/**
 * Emit client-safe generated catalog module for Issue #007.
 *   npx tsx scripts/comics/emit-issue-007-catalog.mts
 *
 * Spoiler-safe: public synopsis + characters omit traitor identity.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-traitors-gate/issue-007");
const OUT = path.join(ROOT, "src/content/comics/the-traitors-gate/issue-007.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
  spoilerLevel?: string;
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-traitors-gate-issue-007-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "rift")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/07-the-traitors-gate.png";
  const publicSynopsis = meta.synopsis;

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-007-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_007_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

/** Spoiler-safe Archive Shelf entry — traitor name withheld from public metadata. */
export const ISSUE_007_COMIC: ComicIssue = {
  slug: "the-traitors-gate",
  issueNumber: 7,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(publicSynopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: ["traitors-gate", "oathwarden", "riftborn", "issue-007", "veiled-meridian", "mira-eggwarden", "suspicion"],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Suspicion, judgment, and rescue at the Gate." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Senses incomplete accusations; opens Resonance locks." },
    { name: "Nira Quill", role: "Hunter under suspicion", blurb: "Obvious suspect — not the whole truth." },
    { name: "Aurelia Voss", role: "Gilded Merchant", blurb: "Selective evidence; refuses to name without proof." },
    { name: "Oathwarden Seraph", role: "Gate guardian", blurb: "Judges identity, bond, and intent." },
    { name: "Truthwing", role: "Gate companion", blurb: "Clear Reflection · Oathlight · Unmasked Sky.", speciesSlug: "truthwing" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Gilded Crossroads", blurb: "Aftermath of the portal collapse." },
    { name: "Traitor's Gate", blurb: "Ancient Rift transit fortress of judgment." },
    { name: "Verification Chamber", blurb: "Name, bond, purpose, oath, keys." },
    { name: "Forge of Rifts", blurb: "Issue #8 teaser beyond the lower route." },
  ],
  timelineNote: "After The Merchant's Secret — the transmission named a gate.",
  playChapterHref: "/live-world",
  playChapterLabel: "Travel the Fracture roads",
  unlockGates: [
    { kind: "prior-issue", slug: "the-merchants-secret", label: "Complete Issue #6: The Merchant's Secret" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-forge-of-rifts",
    hook: "Begin the second creation.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 24},
  factions: [
    { name: "Veiled Meridian", blurb: "Siege the Gate; dual keys; erase witnesses." },
    { name: "Gilded Merchant Circle", blurb: "Aurelia — evidence without premature verdict." },
    { name: "Lanternveil Circus", blurb: "Ally under strain after Crossroads." },
    { name: "Hatchery Compact", blurb: "Voluntary bonds over stolen keys." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "arc-keepers-compact",
  volumeId: "vol-2-keepers-road",
  spoilerPolicy: {
    hideTraitorNameUntilComplete: true,
    hideEvidenceFileUntilReveal: true,
    hideTraitorProfileUntilComplete: true,
    publicCharactersOmitTraitorRole: true,
  },
};

export function getIssue007Transcript(pageNumber: number): string[] {
  return ISSUE_007_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
