/**
 * Emit client-safe generated catalog module for Issue #004.
 *   npx tsx scripts/comics/emit-issue-004-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-lost-city/issue-004");
const OUT = path.join(ROOT, "src/content/comics/the-lost-city/issue-004.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-lost-city-issue-004-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "ruin")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/04-the-lost-city.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-004-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_004_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_004_COMIC: ComicIssue = {
  slug: "the-lost-city",
  issueNumber: 4,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: ["lost-city", "aureth-vale", "guardian", "riftborn", "issue-004", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Leads the expedition — invite, wait, refuse ownership of Spark." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Last Light — chooses empathy over tool-status." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Admits circus moved Resonance Keepers for generations." },
    { name: "The Last Guardian", role: "City defense", blurb: "Stuck in evacuation law until Spark shares the truth." },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Partial codes; believes control prevents catastrophe." },
    { name: "Nira Quill", role: "Uncertain hunter", blurb: "Disables the override; refuses full trust." },
    { name: "Echoquill", role: "Memory scout", blurb: "Memory Trace · Echo Step · Living Archive.", speciesSlug: "echoquill" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Aureth Vale", blurb: "Lost City — Fracture-layered Riftkeeper capital." },
    { name: "Companion Sanctuary", blurb: "Empty Resonance cradles; Echoquill's nest." },
    { name: "City Core", blurb: "Engine chamber Meridian tries to claim." },
    { name: "Storm Kingdom", blurb: "Issue #5 signal — teaser only." },
  ],
  timelineNote: "After The Traveling Circus — map warning: The Guardian remembers.",
  playChapterHref: "/world",
  playChapterLabel: "Open World Map",
  unlockGates: [
    { kind: "prior-issue", slug: "the-traveling-circus", label: "Complete Issue #3: The Traveling Circus" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-storm-king",
    hook: "Above the clouds, a king who never surrendered hears the call.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 22},
  factions: [
    { name: "Veiled Meridian", blurb: "Core infiltration — Seris Vale's city cell." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies; crystal remains warded off-page." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue004Transcript(pageNumber: number): string[] {
  return ISSUE_004_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
