/**
 * Emit client-safe generated catalog module for Issue #002.
 *   npx tsx scripts/comics/emit-issue-002-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/sparks-journey/issue-002");
const OUT = path.join(ROOT, "src/content/comics/sparks-journey/issue-002.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `sparks-journey-issue-002-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "dawn")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/02-sparks-journey.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-002-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_002_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_002_COMIC: ComicIssue = {
  slug: "sparks-journey",
  issueNumber: 2,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: ["spark", "riftborn", "hatchery", "issue-002", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Hatchery mentor — invites, waits, refuses the cage." },
    { name: "Spark", role: "Riftborn Glowpup", blurb: "Unknown resonance; chooses trust." },
    { name: "Vex Halden", role: "Meridian hunter", blurb: "Capture Subject One alive." },
    { name: "Nira Quill", role: "Meridian hunter", blurb: "Questions the mission." },
    { name: "Elara Venn", role: "Vision echo", blurb: "First Keeper — Soft Exodus memory only." },
  ],
  locations: [
    { name: "Riftwild Commons", blurb: "Hatch dawn and Compact hearth." },
    { name: "First-Rift scar wilds", blurb: "Warped roads after the First Tear." },
    { name: "Shellward Sanctum", blurb: "Ancient sanctuary of Riftborn kin." },
  ],
  timelineNote: "Immediately after The First Rift — Mira's pulse-egg hatches.",
  playChapterHref: "/hatchery",
  playChapterLabel: "Visit the Hatchery",
  unlockGates: [
    { kind: "prior-issue", slug: "the-first-rift", label: "Complete Issue #1: The First Rift" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-traveling-circus",
    hook: "Subject One has awakened. Begin the collection.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 20},
  factions: [
    { name: "Veiled Meridian", blurb: "Field hunters for Subject One — org still veiled." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue002Transcript(pageNumber: number): string[] {
  return ISSUE_002_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
