/**
 * Emit client-safe generated catalog module for Issue #001 (no fs at runtime).
 *   npx tsx scripts/comics/emit-issue-001-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-first-rift/issue-001");
const OUT = path.join(ROOT, "src/content/comics/the-first-rift/issue-001.generated.ts");

type RawLine = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id: string;
  role: string;
  title?: string | null;
  layout: string;
  atmosphere?: string;
  panels: { caption?: string; lines: RawLine[] }[];
  publicArtRel: string;
  letteringStatus?: string;
};

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] = raw.panels.flatMap((p) =>
      (p.lines || []).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
    );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const panels = (raw.panels.length ? raw.panels : [{ lines: [] }]).map((panel, i) => {
      const bubbles = (panel.lines || []).map((l) => {
        const parts = [
          `kind: ${JSON.stringify(l.kind)}`,
          `text: ${JSON.stringify(l.text)}`,
        ];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${raw.id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(raw.id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(raw.layout || "narrative")} as ComicPanelLayout,
    role: ${JSON.stringify(raw.role || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(`${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "dusk")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const src = `/**
 * AUTO-GENERATED by scripts/comics/emit-issue-001-catalog.mts — do not hand-edit.
 * Source of truth: src/content/comics/the-first-rift/issue-001/
 */
import { COVER } from "@/content/comics/art";
import { expandCoverVariants } from "@/content/comics/publishing-engine";
import type {
  ComicIssue,
  ComicPage,
  ComicPageRole,
  ComicPanelLayout,
} from "@/content/comics/types";

const coverSrc = COVER["the-first-rift"];

export const ISSUE_001_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_001_COMIC: ComicIssue = {
  slug: "the-first-rift",
  issueNumber: 1,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.storyTitle || meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: "2026-07-20",
  readingTimeMinutes: 18,
  status: "published",
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, coverSrc),
  tags: ["first-rift", "elara", "mira", "compact", "issue-001", "pulse-below"],
  playChapterHref: "/live-world",
  playChapterLabel: "Enter Live World",
  collectibles: [
    {
      id: "col-first-rift-cover",
      kind: "cover",
      label: "The First Rift — Standard",
      description: "Issue #001 cover collectible",
      coverKind: "standard",
    },
  ],
  rewards: [
    {
      id: "rw-first-rift-complete",
      label: "Pulse Witness",
      description: "Finished The Pulse Below",
      kind: "badge",
    },
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Present POV", blurb: "Hatchery mentor who finds the pulse." },
    { name: "Elara Venn", role: "First Keeper", blurb: "Courier who chose to keep.", speciesSlug: undefined },
    { name: "First Riftling", role: "Soft archive", blurb: "Becoming, not inventory." },
    { name: "Bramblefox", role: "Companion", blurb: "Forest Bond.", speciesSlug: "bramblefox" },
    { name: "Mossprig", role: "Companion", blurb: "Living Bulwark.", speciesSlug: "mossprig" },
    { name: "Thornling", role: "Companion", blurb: "Sprouting Energy.", speciesSlug: "thornling" },
  ],
  locations: [
    { name: "Riftwild Commons", blurb: "Present-day hearth of the Compact." },
    { name: "Commons fringe Rift", blurb: "Unstable ancient tear." },
  ],
  timelineNote: "Present Compact era + Age of First Eggs vision.",
  unlockGates: [{ kind: "free" }],
  nextIssueTeaser: {
    slug: "sparks-journey",
    hook: "A Glowpup learns the road between hatchery and heart.",
  },
  arcId: "fracture-dawn",
  volumeId: "volume-1",
  pages: [
    ${pagesLiteral.join(",\n    ")}
  ],
};

export function getIssue001Transcript(pageNumber: number): string[] {
  return ISSUE_001_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.writeFileSync(OUT, src, "utf8");
  console.log(`Wrote ${rawPages.length} pages → ${path.relative(ROOT, OUT)}`);
}

main();
