/**
 * Emit client-safe generated catalog module for Issue #009 — The Riftwright (Volume One Finale).
 *   npx tsx scripts/comics/emit-issue-009-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-riftwright/issue-009");
const OUT = path.join(ROOT, "src/content/comics/the-riftwright/issue-009.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-riftwright-issue-009-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "rift")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/09-the-riftwright.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-009-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_009_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_009_COMIC: ComicIssue = {
  slug: "the-riftwright",
  issueNumber: 9,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: [
    "the-riftwright",
    "volume-one-finale",
    "elyan-voss",
    "nova",
    "second-forge",
    "issue-009",
    "mira-eggwarden",
    "twin-key",
  ],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Volume One finale POV — protects Spark and Nova." },
    { name: "Professor Elyan Voss", role: "The Riftwright", blurb: "Tragic architect — blamed wrongly for the First Rift." },
    { name: "Nova", role: "Prime Companion", blurb: "Hatched from the dormant egg; twin-key with Spark.", speciesSlug: "nova" },
    { name: "Spark", role: "Last Light / Twin-Key", blurb: "Resonance Keeper — voluntary Compact with Nova.", speciesSlug: "spark" },
    { name: "Seris Vale", role: "Ascendant Commander", blurb: "Defeated and contained — not executed." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Supervised ally — redemption unfinished." },
    { name: "Axiom", role: "Prototype companion", blurb: "Adaptive Matrix · Pulse Repair · System Restore.", speciesSlug: "axiom" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Blessing on the quiet terrace — not present-day POV." },
  ],
  locations: [
    { name: "Second Forge", blurb: "Spare heart under another continent." },
    { name: "Companion Incubator Beta", blurb: "Nova hatch site." },
    { name: "Twin Engine Control", blurb: "Cradle lattice victory." },
    { name: "Shattered Star", blurb: "Volume Two tease only — sleeping companions in a broken star." },
  ],
  timelineNote: "Volume One Finale — after The Forge of Rifts. NEXT: The Shattered Star.",
  playChapterHref: "/comics",
  playChapterLabel: "Archive Shelves",
  unlockGates: [
    { kind: "prior-issue", slug: "the-forge-of-rifts", label: "Complete Issue #8: The Forge of Rifts" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-shattered-star",
    hook: "A broken star sleeps with companions inside. Volume Two begins.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 24},
  factions: [
    { name: "Hatchery Compact", blurb: "Consent over force — twin-key cradle." },
    { name: "Veiled Meridian", blurb: "Ascendant Protocol broken." },
    { name: "Forge Architects", blurb: "Elyan + Arkan echo — healing intent restored." },
  ],
  collectibles: [],
  rewards: [
    {
      id: "rw-volume-one-finale-badge",
      label: "Volume One Finale Badge",
      description: "Archive Shelves badge for completing Legends of the Rift Volume One.",
      kind: "badge",
      creditsStub: 20,
    },
  ],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
  volumeFinale: true,
  shelfBadge: "Volume One Finale",
  commentary: [
    "Volume One Finale. Mystery retained: who manipulated history after the First Rift (older than Meridian).",
    "Do not start Volume Two issues beyond the teaser page.",
  ],
};

export function getIssue009Transcript(pageNumber: number): string[] {
  return ISSUE_009_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
