/**
 * Emit client-safe generated catalog module for Issue #005.
 *   npx tsx scripts/comics/emit-issue-005-catalog.mts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const ISSUE = path.join(ROOT, "content/comics/the-storm-king/issue-005");
const OUT = path.join(ROOT, "src/content/comics/the-storm-king/issue-005.generated.ts");

type Bubble = {
  kind: string;
  speaker?: string;
  text: string;
  x?: number;
  y?: number;
  tail?: string;
};

type RawPage = {
  pageNumber: number;
  id?: string;
  bookRole?: string;
  title?: string | null;
  layout?: { type?: string } | string;
  atmosphere?: string;
  panels: { bubbles?: Bubble[]; lines?: Bubble[]; caption?: string; description?: string }[];
  publicArtRel: string;
  artAlt?: string;
  transcript?: string[];
};

function layoutOf(raw: RawPage): string {
  if (typeof raw.layout === "string") return raw.layout;
  return raw.layout?.type || "narrative";
}

function bubblesOf(panel: RawPage["panels"][0]): Bubble[] {
  return panel.bubbles || panel.lines || [];
}

function main() {
  const meta = JSON.parse(fs.readFileSync(path.join(ISSUE, "issue.json"), "utf8"));
  const pagesDir = path.join(ISSUE, "pages");
  const rawPages: RawPage[] = fs
    .readdirSync(pagesDir)
    .filter((f) => f.startsWith("page-") && f.endsWith(".json"))
    .sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(pagesDir, f), "utf8")));

  const transcripts: Record<number, string[]> = {};
  for (const raw of rawPages) {
    transcripts[raw.pageNumber] =
      raw.transcript ||
      raw.panels.flatMap((p) =>
        bubblesOf(p).map((l) => (l.speaker ? `${l.speaker}: ${l.text}` : l.text)),
      );
  }

  const pagesLiteral = rawPages.map((raw) => {
    const artSrc = `/${raw.publicArtRel.replace(/^\//, "")}`;
    const id = raw.id || `the-storm-king-issue-005-p${String(raw.pageNumber).padStart(3, "0")}`;
    const panels = (raw.panels.length ? raw.panels : [{ bubbles: [] }]).map((panel, i) => {
      const bubbles = bubblesOf(panel).map((l) => {
        const parts = [`kind: ${JSON.stringify(l.kind)}`, `text: ${JSON.stringify(l.text)}`];
        if (l.speaker) parts.push(`speaker: ${JSON.stringify(l.speaker)}`);
        if (l.x != null) parts.push(`x: ${l.x}`);
        if (l.y != null) parts.push(`y: ${l.y}`);
        if (l.tail) parts.push(`tail: ${JSON.stringify(l.tail)}`);
        return `{ ${parts.join(", ")} }`;
      });
      return `{
      id: ${JSON.stringify(`${id}-panel-${i}`)},
      artSrc: ${JSON.stringify(artSrc)},
      ${panel.caption ? `caption: ${JSON.stringify(panel.caption)},` : ""}
      bubbles: [${bubbles.join(", ")}],
    }`;
    });

    return `{
    id: ${JSON.stringify(id)},
    pageNumber: ${raw.pageNumber},
    layout: ${JSON.stringify(layoutOf(raw))} as ComicPanelLayout,
    role: ${JSON.stringify(raw.bookRole || "story")} as ComicPageRole,
    ${raw.title ? `title: ${JSON.stringify(raw.title)},` : ""}
    artSrc: ${JSON.stringify(artSrc)},
    artAlt: ${JSON.stringify(raw.artAlt || `${meta.title} p${raw.pageNumber}`)},
    atmosphere: ${JSON.stringify(raw.atmosphere || "storm")} as ComicPage["atmosphere"],
    panels: [${panels.join(",\n    ")}],
    composedPlate: true,
    bakedLettering: true,
  }`;
  });

  const coverSrc = "/assets/comics/covers/05-the-storm-king.png";

  const body = `/* AUTO-GENERATED by scripts/comics/emit-issue-005-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_005_TRANSCRIPTS: Record<number, string[]> = ${JSON.stringify(transcripts, null, 2)};

export const ISSUE_005_COMIC: ComicIssue = {
  slug: "the-storm-king",
  issueNumber: 5,
  title: ${JSON.stringify(meta.title)},
  subtitle: ${JSON.stringify(meta.subtitle)},
  synopsis: ${JSON.stringify(meta.synopsis)},
  publishedAt: ${JSON.stringify(meta.publishedAt || "2026-07-20")},
  status: "published",
  tags: ["storm-king", "tempestria", "thundervane", "riftborn", "issue-005", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants(${JSON.stringify(meta.title)}, ${JSON.stringify(coverSrc)}),
  pages: [
  ${pagesLiteral.join(",\n  ")}
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Leads the expedition — refuses Spark as an engine part." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Refuses to replace Thundervane; steadies by invitation." },
    { name: "King Vaelor Tempest", role: "Storm King", blurb: "Duty became a wall — until he released the forced bond." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Warned Tempestria years ago; knows royal routes." },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Sabotages the barrier; escapes with a merchant ledger." },
    { name: "Nira Quill", role: "Uncertain hunter", blurb: "Cuts the Spark tether; open Meridian disloyalty." },
    { name: "Thundervane", role: "Storm companion", blurb: "Stormbound Crown · Skybreaker · Crown of Thunder.", speciesSlug: "thundervane" },
    { name: "Galesprig", role: "Mountain scout", blurb: "Tailwind · Updraft · Clear Sky.", speciesSlug: "galesprig" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Tempestria", blurb: "Mountain kingdom inside a permanent storm barrier." },
    { name: "Royal Citadel", blurb: "Throne under a living storm conduit." },
    { name: "Storm Engine Chamber", blurb: "Bond-fed weather core beneath the throne." },
    { name: "Merchant Network", blurb: "Issue #6 teaser — every door." },
  ],
  timelineNote: "After The Lost City — storm-mountain signal answered.",
  playChapterHref: "/live-world",
  playChapterLabel: "Travel toward Stormspire",
  unlockGates: [
    { kind: "prior-issue", slug: "the-lost-city", label: "Complete Issue #4: The Lost City" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-merchants-secret",
    hook: "You brought me a map. No — every door.",
  },
  readingTimeMinutes: ${meta.estimatedReadMinutes || 22},
  factions: [
    { name: "Veiled Meridian", blurb: "Tempestria sabotage — Seris Vale's storm cell." },
    { name: "Tempestria Crown", blurb: "Releasing absolute control after the bond snaps." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies; crystal remains warded off-page." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue005Transcript(pageNumber: number): string[] {
  return ISSUE_005_TRANSCRIPTS[pageNumber] ?? [];
}
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log("Wrote", OUT, "pages=", rawPages.length);
}

main();
