import type { DeedSize, LandDeedDef } from "@/lib/neighborhoods/types";

export const LAND_DEEDS: LandDeedDef[] = [
  {
    size: "tiny",
    name: "Tiny Lot",
    creditsCost: 100,
    buildLimit: 40,
    decorLimit: 30,
    terrain: "packed_earth",
    elevation: "low",
    roadAccess: true,
    waterAccess: false,
    blurb: "Starter footprint beside the lane.",
  },
  {
    size: "small",
    name: "Small Plot",
    creditsCost: 120,
    buildLimit: 80,
    decorLimit: 60,
    terrain: "meadow",
    elevation: "low",
    roadAccess: true,
    waterAccess: false,
    blurb: "Room for a cottage and mailbox.",
  },
  {
    size: "medium",
    name: "Medium Holding",
    creditsCost: 220,
    buildLimit: 140,
    decorLimit: 110,
    terrain: "grove_edge",
    elevation: "mid",
    roadAccess: true,
    waterAccess: false,
    blurb: "Balanced residential parcel.",
  },
  {
    size: "large",
    name: "Large Acre",
    creditsCost: 380,
    buildLimit: 220,
    decorLimit: 180,
    terrain: "orchard",
    elevation: "mid",
    roadAccess: true,
    waterAccess: false,
    blurb: "Farm-friendly acreage.",
  },
  {
    size: "estate",
    name: "Estate Grounds",
    creditsCost: 650,
    buildLimit: 320,
    decorLimit: 280,
    terrain: "terraced",
    elevation: "mid",
    roadAccess: true,
    waterAccess: false,
    blurb: "Manor-scale grounds.",
  },
  {
    size: "castle",
    name: "Castle Spur",
    creditsCost: 1200,
    buildLimit: 480,
    decorLimit: 400,
    terrain: "stone_ridge",
    elevation: "high",
    roadAccess: true,
    waterAccess: false,
    blurb: "Rare fortified footprint — cosmetic prestige.",
  },
  {
    size: "island",
    name: "Islet Claim",
    creditsCost: 900,
    buildLimit: 200,
    decorLimit: 220,
    terrain: "isle_sand",
    elevation: "low",
    roadAccess: false,
    waterAccess: true,
    blurb: "Water-locked plot with ferry stub.",
  },
  {
    size: "lakefront",
    name: "Lakefront Parcel",
    creditsCost: 520,
    buildLimit: 180,
    decorLimit: 160,
    terrain: "shore",
    elevation: "low",
    roadAccess: true,
    waterAccess: true,
    blurb: "Dock-ready water access.",
  },
  {
    size: "cliffside",
    name: "Cliff Terrace",
    creditsCost: 700,
    buildLimit: 160,
    decorLimit: 200,
    terrain: "cliff",
    elevation: "high",
    roadAccess: true,
    waterAccess: false,
    blurb: "Overlook elevation bonus for exteriors.",
  },
  {
    size: "grove",
    name: "Deep Grove Lot",
    creditsCost: 280,
    buildLimit: 150,
    decorLimit: 170,
    terrain: "canopy",
    elevation: "mid",
    roadAccess: true,
    waterAccess: false,
    blurb: "Treehouse-friendly canopy plot.",
  },
];

export function getDeed(size: DeedSize): LandDeedDef | undefined {
  return LAND_DEEDS.find((d) => d.size === size);
}
