/* AUTO-GENERATED by scripts/comics/emit-issue-002-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_002_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: RIFTWILDS",
    "CAPTION: SPARK'S JOURNEY",
    "CAPTION: ISSUE #2"
  ],
  "2": [
    "NARRATION: Legends of the Rift · Volume One · Issue Two",
    "CAPTION: Previously: The First Rift"
  ],
  "3": [
    "CAPTION: SPARK'S JOURNEY",
    "NARRATION: Story & Continuity · Riftwilds Lore Desk  ·  Art Pipeline · Grok + programmatic lettering  ·  Original Riftwilds IP"
  ],
  "4": [
    "CAPTION: CHAPTER TWO",
    "CAPTION: HATCHLING OF THE PULSE",
    "NARRATION: Trust is not a collar. It is a step taken twice."
  ],
  "5": [
    "NARRATION: The storm ended before sunrise. The pulse did not.",
    "SFX: shell-song…",
    "WHISPER (Mira Eggwarden): Stay with me. Quiet now."
  ],
  "6": [
    "SFX: KRK-KRACK",
    "CREATURE (Thornling): *eep!*",
    "CREATURE (Mossprig): *steady…*",
    "NARRATION: Something chooses the world — and flinches."
  ],
  "7": [
    "CREATURE (Spark): *chirp—!*",
    "SFX: PULSE-THUM",
    "CREATURE (Bramblefox): *soft rrk*",
    "SPEECH (Mira Eggwarden): I'm not going to grab you. Invite only.",
    "NARRATION: Compact starts at the first breath."
  ],
  "8": [
    "SPEECH (Mira Eggwarden): Easy. Just reading the shell-song you kept.",
    "SFX: scan-hummm",
    "CAPTION: UNKNOWN RESONANCE",
    "CAPTION: NO MATCH FOUND",
    "THOUGHT (Mira Eggwarden): Not Nature. Not Storm. Not anything we catalogued."
  ],
  "9": [
    "SPEECH (Keeper Scholar Len): That mark… Shellward. Pre-Commons nesting law.",
    "NARRATION: A door older than the plaza. A promise older than fear.",
    "SPEECH (Mira Eggwarden): If the Compact still means anything, we take it there — not to a cage."
  ],
  "10": [
    "SPEECH (Mira Eggwarden): Take Spark to Shellward Sanctum before the pulse frays.",
    "SPEECH (Mira Eggwarden): We walk. We invite. We don't make it a weapon.",
    "WHISPER (Hunter Spotter): Subject One lives. Mark the trail.",
    "NARRATION: Some invitations arrive with knives."
  ],
  "11": [
    "NARRATION: The road teaches tempo before it teaches danger.",
    "CREATURE (Spark): *…chir?*",
    "SPEECH (Mira Eggwarden): That's Bramblefox. Scout. That's Mossprig. Wall. Thornling… chaos with thorns."
  ],
  "12": [
    "CREATURE (Thornling): *hee!*",
    "CREATURE (Spark): *chir-chir!*",
    "SPEECH (Mira Eggwarden): Curiosity that can play is Keeper-shaped.",
    "SFX: FLARE-CRACKLE",
    "SPEECH (Mira Eggwarden): Hey— hey. Breathe with me."
  ],
  "13": [
    "NARRATION: Where the First Tear taught stone to forget gravity.",
    "WHISPER (Mira Eggwarden): Stay close. This ground remembers wrong.",
    "SFX: rift-hummm"
  ],
  "14": [
    "SPEECH (Travel Kid): It shines like a Gateway…",
    "CREATURE (Spark): *chir?*",
    "SHOUT (Frightened Traveler): That thing woke the tear! Look at our road!",
    "SPEECH (Merchant): Keep it away from the wagons!"
  ],
  "15": [
    "SPEECH (Mira Eggwarden): It hatched after we sealed a wound. Blame the hand that opened it — not the pulse that survived.",
    "CREATURE (Spark): *…*",
    "THOUGHT (Mira Eggwarden): They heard a monster. It heard a verdict.",
    "WHISPER (Mira Eggwarden): You're not a weapon. I won't let them write you as one."
  ],
  "16": [
    "SFX: pad-pad-pad",
    "SHOUT (Mira Eggwarden): Spark—!",
    "SPEECH (Vex Halden): Trail lock. Alive capture only.",
    "WHISPER (Nira Quill): If it's only a hatchling…",
    "SPEECH (Vex Halden): Subject One is inventory. Move."
  ],
  "17": [
    "CREATURE (Bramblefox): *hunt-rrk*",
    "CREATURE (Wisplet): *chime…*",
    "SPEECH (Mira Eggwarden): I'm not reclaiming property. I'm answering a runaway invitation."
  ],
  "18": [
    "CREATURE (Spark): *…chir*",
    "SFX: stone-awaken",
    "NARRATION: Some doors do not open for keys. They open for kinship.",
    "CAPTION: SHELLWARD ROAD"
  ],
  "19": [
    "WHISPER (Mira Eggwarden): You found a door. You still get to choose the room.",
    "SFX: SIGIL-LOCK",
    "SPEECH (Vex Halden): Subject One. Step away from the Keepers.",
    "THOUGHT (Nira Quill): It looks like a child of light — not a weapon crate."
  ],
  "20": [
    "SPEECH (Vex Halden): It belongs to the Meridian. Hand it over — alive.",
    "SPEECH (Mira Eggwarden): It belongs to its own becoming. Compact law. Back away.",
    "SPEECH (Nira Quill): Vex— if the scan was wrong—",
    "SFX: WHUMP",
    "SFX: SHIIING",
    "CREATURE (Bramblefox): *snarl*"
  ],
  "21": [
    "SFX: BIND-LANCE",
    "CREATURE (Mossprig): *BULWARK!*",
    "SFX: KRRRAAAK",
    "CREATURE (Spark): *chir—!!*",
    "SPEECH (Mira Eggwarden): Mossprig!"
  ],
  "22": [
    "SFX: LEAF-SNAP",
    "CREATURE (Thornling): *sprout-GO!*",
    "SFX: phase-chime",
    "NARRATION: Power without choice is just another cage.",
    "CREATURE (Spark): *tremble-hum*"
  ],
  "23": [
    "SPEECH (Vex Halden): End this. Collar the anomaly.",
    "SFX: RESONANCE+++",
    "SPEECH (Mira Eggwarden): You don't have to fight for us. You don't have to be useful to be kept.",
    "WHISPER (Mira Eggwarden): If you run through that door, I'll still call you Spark."
  ],
  "24": [
    "CAPTION: You were never made to obey.",
    "TELEPATHY (Ancient Keeper Echo): Become. Then choose."
  ],
  "25": [
    "CREATURE (Spark): *chir…* (bond-warmth)",
    "SPEECH (Mira Eggwarden): Okay. Together — if you want.",
    "NARRATION: Resonance held — not spilled.",
    "CAPTION: RIFT RESONANCE"
  ],
  "26": [
    "SFX: PRISM—BURST",
    "SFX: field-SHATTER",
    "SHOUT (Vex Halden): Dampening— hold the line!"
  ],
  "27": [
    "SPEECH (Nira Quill): Alive capture — not a corpse for the ledger.",
    "SPEECH (Vex Halden): You'll answer for this.",
    "NARRATION: The Meridian withdraws — not defeated forever.",
    "SPEECH (Mira Eggwarden): It opens for you. We'll wait our turn.",
    "CREATURE (Spark): *invite-chirp*"
  ],
  "28": [
    "NARRATION: Not a mistake. A lineage of thresholds.",
    "SPEECH (Mira Eggwarden): You're one of several… Riftborn.",
    "CAPTION: CODEX CLASS: RIFTBORN (PROVISIONAL)",
    "CREATURE (Spark): *soft wonder-hum*"
  ],
  "29": [
    "NARRATION: Someone reached the heart first.",
    "TELEPATHY (Veiled Meridian Channel): Subject One has awakened. Begin the collection.",
    "CAPTION: TO BE CONTINUED IN ISSUE #3",
    "CAPTION: THE TRAVELING CIRCUS"
  ],
  "30": [
    "CAPTION: NEXT ISSUE",
    "CAPTION: THE TRAVELING CIRCUS",
    "NARRATION: Lantern wagons. Honest applause. A collection already in motion."
  ],
  "31": [
    "NARRATION: MIRA EGGWARDEN — Hatchery mentor. Bond philosophy: keep, don't own. Compact first. Refuses to treat companions as weapons even when the Meridian calls them inventory."
  ],
  "32": [
    "NARRATION: SPARK — Glowpup-line Riftborn hatchling. Codex: UNKNOWN RESONANCE → provisional Riftborn. Communicates in chirps and bond-warmth. Passive: Rift Resonance. Ultimate: Prismatic Burst."
  ],
  "33": [
    "NARRATION: CODEX ENTRY (DRAFT): Riftborn — rare companions whose affinity does not lock to a single element. Linked to threshold Rifts across Aeryndra. Shellward Sanctum catalogs them as kin, not inventory. Status: provisional · Subject One awakened."
  ],
  "34": [
    "NARRATION: RIFT RESONANCE — When another companion uses an elemental ability, Spark gains 1 Resonance (max 3). Prismatic Burst consumes Resonance to strike and briefly boost allies. Not domination — shared pulse."
  ],
  "35": [
    "CAPTION: RIFTWILD COMMONS → SHELLWARD SANCTUM"
  ],
  "36": [
    "NARRATION: EDITOR'S NOTE: Spark's Journey is about trust under fear — the difference between protection and control. A companion who can run away and still be invited back is the Compact made flesh. Write the Lore Desk. Keep invitations honest."
  ],
  "37": [
    "NARRATION: Continue in Live World · Study Riftborn in the Codex · Visit the Hatchery under Compact law"
  ],
  "38": [
    "CAPTION: THE TRAVELING LANTERN CARAVAN",
    "NARRATION: Lanterns. Companion acts. Honest cheers — never SOL in the hat. Masked Host invites Keepers who listen. (In-world advertisement · not a real-money offer.)"
  ]
};

export const ISSUE_002_COMIC: ComicIssue = {
  slug: "sparks-journey",
  issueNumber: 2,
  title: "Spark's Journey",
  subtitle: "Chapter Two — Hatchling of the Pulse",
  synopsis: "The pulse-egg under Mira Eggwarden's Compact care hatches into Spark, an unstable Glowpup-line Riftborn. Mira escorts Spark toward Shellward Sanctum while Veiled Meridian hunters try to capture Subject One. Spark flees fear, returns by choice, unlocks Prismatic Burst, and discovers it is one of several Riftborn — as the Meridian begins the collection at the Traveling Circus.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: ["spark", "riftborn", "hatchery", "issue-002", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants("Spark's Journey", "/assets/comics/covers/02-sparks-journey.png"),
  pages: [
  {
    id: "sparks-journey-issue-002-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "Spark's Journey — Cover",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-001.webp",
    artAlt: "Spark's Journey — Cover",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p001-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "RIFTWILDS", x: 50, y: 8 }, { kind: "caption", text: "SPARK'S JOURNEY", x: 50, y: 18 }, { kind: "caption", text: "ISSUE #2", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-002.webp",
    artAlt: "Inside Front Cover",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p002-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-002.webp",
      
      bubbles: [{ kind: "narration", text: "Legends of the Rift · Volume One · Issue Two", x: 50, y: 40 }, { kind: "caption", text: "Previously: The First Rift", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-003.webp",
    artAlt: "Credits",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p003-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "SPARK'S JOURNEY", x: 50, y: 20 }, { kind: "narration", text: "Story & Continuity · Riftwilds Lore Desk  ·  Art Pipeline · Grok + programmatic lettering  ·  Original Riftwilds IP", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Two — Hatchling of the Pulse",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-004.webp",
    artAlt: "Chapter Two — Hatchling of the Pulse",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p004-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER TWO", x: 50, y: 30 }, { kind: "caption", text: "HATCHLING OF THE PULSE", x: 50, y: 45 }, { kind: "narration", text: "Trust is not a collar. It is a step taken twice.", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Pulse Did Not End",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-005.webp",
    artAlt: "The Pulse Did Not End — Spark's Journey page 1",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p005-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "The storm ended before sunrise. The pulse did not.", x: 50, y: 12 }, { kind: "sfx", text: "shell-song…", x: 58, y: 48 }, { kind: "whisper", text: "Stay with me. Quiet now.", speaker: "Mira Eggwarden", x: 35, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "First Eye",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-006.webp",
    artAlt: "First Eye — Spark's Journey page 2",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p006-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-006.webp",
      
      bubbles: [{ kind: "sfx", text: "KRK-KRACK", x: 50, y: 40 }],
    },
    {
      id: "sparks-journey-issue-002-p006-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-006.webp",
      
      bubbles: [{ kind: "creature", text: "*eep!*", speaker: "Thornling", x: 70, y: 55, tail: "up" }, { kind: "creature", text: "*steady…*", speaker: "Mossprig", x: 30, y: 60, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p006-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-006.webp",
      
      bubbles: [{ kind: "narration", text: "Something chooses the world — and flinches.", x: 50, y: 18 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p007",
    pageNumber: 7,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Hatchling",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-007.webp",
    artAlt: "Hatchling — Spark's Journey page 3",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p007-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-007.webp",
      
      bubbles: [{ kind: "creature", text: "*chirp—!*", speaker: "Spark", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p007-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-007.webp",
      
      bubbles: [{ kind: "sfx", text: "PULSE-THUM", x: 55, y: 45 }],
    },
    {
      id: "sparks-journey-issue-002-p007-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-007.webp",
      
      bubbles: [{ kind: "creature", text: "*soft rrk*", speaker: "Bramblefox", x: 40, y: 70, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p007-panel-3",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-007.webp",
      
      bubbles: [{ kind: "speech", text: "I'm not going to grab you. Invite only.", speaker: "Mira Eggwarden", x: 50, y: 25, tail: "down" }, { kind: "narration", text: "Compact starts at the first breath.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p008",
    pageNumber: 8,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Unknown Resonance",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-008.webp",
    artAlt: "Unknown Resonance — Spark's Journey page 4",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p008-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "Easy. Just reading the shell-song you kept.", speaker: "Mira Eggwarden", x: 40, y: 20, tail: "down" }, { kind: "sfx", text: "scan-hummm", x: 60, y: 50 }],
    },
    {
      id: "sparks-journey-issue-002-p008-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-008.webp",
      
      bubbles: [{ kind: "caption", text: "UNKNOWN RESONANCE", x: 50, y: 30 }, { kind: "caption", text: "NO MATCH FOUND", x: 50, y: 48 }, { kind: "thought", text: "Not Nature. Not Storm. Not anything we catalogued.", speaker: "Mira Eggwarden", x: 50, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p009",
    pageNumber: 9,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Shellward Mark",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-009.webp",
    artAlt: "Shellward Mark — Spark's Journey page 5",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p009-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "That mark… Shellward. Pre-Commons nesting law.", speaker: "Keeper Scholar Len", x: 50, y: 20, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p009-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-009.webp",
      
      bubbles: [{ kind: "narration", text: "A door older than the plaza. A promise older than fear.", x: 50, y: 70 }],
    },
    {
      id: "sparks-journey-issue-002-p009-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "If the Compact still means anything, we take it there — not to a cage.", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p010",
    pageNumber: 10,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Before Destabilization",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-010.webp",
    artAlt: "Before Destabilization — Spark's Journey page 6",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p010-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "Take Spark to Shellward Sanctum before the pulse frays.", speaker: "Mira Eggwarden", x: 45, y: 22, tail: "down" }, { kind: "speech", text: "We walk. We invite. We don't make it a weapon.", speaker: "Mira Eggwarden", x: 50, y: 70, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p010-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-010.webp",
      
      bubbles: [{ kind: "whisper", text: "Subject One lives. Mark the trail.", speaker: "Hunter Spotter", x: 55, y: 28, tail: "down" }, { kind: "narration", text: "Some invitations arrive with knives.", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p011",
    pageNumber: 11,
    layout: "wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Leaving the Hearth",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-011.webp",
    artAlt: "Leaving the Hearth — Spark's Journey page 7",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p011-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "The road teaches tempo before it teaches danger.", x: 50, y: 10 }, { kind: "creature", text: "*…chir?*", speaker: "Spark", x: 48, y: 45, tail: "up" }, { kind: "speech", text: "That's Bramblefox. Scout. That's Mossprig. Wall. Thornling… chaos with thorns.", speaker: "Mira Eggwarden", x: 55, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p012",
    pageNumber: 12,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Motes and Marks",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-012.webp",
    artAlt: "Motes and Marks — Spark's Journey page 8",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p012-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-012.webp",
      
      bubbles: [{ kind: "creature", text: "*hee!*", speaker: "Thornling", x: 30, y: 40, tail: "up" }, { kind: "creature", text: "*chir-chir!*", speaker: "Spark", x: 65, y: 50, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p012-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "Curiosity that can play is Keeper-shaped.", speaker: "Mira Eggwarden", x: 50, y: 20, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p012-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-012.webp",
      
      bubbles: [{ kind: "sfx", text: "FLARE-CRACKLE", x: 55, y: 40 }, { kind: "speech", text: "Hey— hey. Breathe with me.", speaker: "Mira Eggwarden", x: 40, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p013",
    pageNumber: 13,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Scar of the First Tear",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-013.webp",
    artAlt: "Scar of the First Tear — Spark's Journey page 9",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p013-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-013.webp",
      
      bubbles: [{ kind: "narration", text: "Where the First Tear taught stone to forget gravity.", x: 50, y: 12 }, { kind: "whisper", text: "Stay close. This ground remembers wrong.", speaker: "Mira Eggwarden", x: 35, y: 80, tail: "up" }, { kind: "sfx", text: "rift-hummm", x: 70, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p014",
    pageNumber: 14,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Fear Has a Finger",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-014.webp",
    artAlt: "Fear Has a Finger — Spark's Journey page 10",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p014-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-014.webp",
      
      bubbles: [{ kind: "speech", text: "It shines like a Gateway…", speaker: "Travel Kid", x: 40, y: 25, tail: "down" }, { kind: "creature", text: "*chir?*", speaker: "Spark", x: 60, y: 60, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p014-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-014.webp",
      
      bubbles: [{ kind: "shout", text: "That thing woke the tear! Look at our road!", speaker: "Frightened Traveler", x: 50, y: 28, tail: "down" }, { kind: "speech", text: "Keep it away from the wagons!", speaker: "Merchant", x: 55, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p015",
    pageNumber: 15,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Not a Weapon",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-015.webp",
    artAlt: "Not a Weapon — Spark's Journey page 11",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p015-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "It hatched after we sealed a wound. Blame the hand that opened it — not the pulse that survived.", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p015-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-015.webp",
      
      bubbles: [{ kind: "creature", text: "*…*", speaker: "Spark", x: 50, y: 55 }],
    },
    {
      id: "sparks-journey-issue-002-p015-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-015.webp",
      
      bubbles: [{ kind: "thought", text: "They heard a monster. It heard a verdict.", speaker: "Mira Eggwarden", x: 50, y: 40, tail: "up" }, { kind: "whisper", text: "You're not a weapon. I won't let them write you as one.", speaker: "Mira Eggwarden", x: 50, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p016",
    pageNumber: 16,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Glow Into Dark",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-016.webp",
    artAlt: "Glow Into Dark — Spark's Journey page 12",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p016-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-016.webp",
      
      bubbles: [{ kind: "sfx", text: "pad-pad-pad", x: 60, y: 40 }, { kind: "shout", text: "Spark—!", speaker: "Mira Eggwarden", x: 35, y: 70, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p016-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "Trail lock. Alive capture only.", speaker: "Vex Halden", x: 50, y: 25, tail: "down" }, { kind: "whisper", text: "If it's only a hatchling…", speaker: "Nira Quill", x: 45, y: 70, tail: "up" }, { kind: "speech", text: "Subject One is inventory. Move.", speaker: "Vex Halden", x: 55, y: 85, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p017",
    pageNumber: 17,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Scent and Spirit",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-017.webp",
    artAlt: "Scent and Spirit — Spark's Journey page 13",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p017-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-017.webp",
      
      bubbles: [{ kind: "creature", text: "*hunt-rrk*", speaker: "Bramblefox", x: 40, y: 55, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p017-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-017.webp",
      
      bubbles: [{ kind: "creature", text: "*chime…*", speaker: "Wisplet", x: 55, y: 40, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p017-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "I'm not reclaiming property. I'm answering a runaway invitation.", speaker: "Mira Eggwarden", x: 50, y: 25, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p018",
    pageNumber: 18,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Arch That Waits",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-018.webp",
    artAlt: "The Arch That Waits — Spark's Journey page 14",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p018-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-018.webp",
      
      bubbles: [{ kind: "creature", text: "*…chir*", speaker: "Spark", x: 45, y: 70, tail: "up" }, { kind: "sfx", text: "stone-awaken", x: 60, y: 40 }],
    },
    {
      id: "sparks-journey-issue-002-p018-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-018.webp",
      
      bubbles: [{ kind: "narration", text: "Some doors do not open for keys. They open for kinship.", x: 50, y: 15 }, { kind: "caption", text: "SHELLWARD ROAD", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p019",
    pageNumber: 19,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Sigils Ignite",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-019.webp",
    artAlt: "Sigils Ignite — Spark's Journey page 15",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p019-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-019.webp",
      
      bubbles: [{ kind: "whisper", text: "You found a door. You still get to choose the room.", speaker: "Mira Eggwarden", x: 50, y: 20, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p019-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-019.webp",
      
      bubbles: [{ kind: "sfx", text: "SIGIL-LOCK", x: 50, y: 50 }],
    },
    {
      id: "sparks-journey-issue-002-p019-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "Subject One. Step away from the Keepers.", speaker: "Vex Halden", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p019-panel-3",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-019.webp",
      
      bubbles: [{ kind: "thought", text: "It looks like a child of light — not a weapon crate.", speaker: "Nira Quill", x: 50, y: 60, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p020",
    pageNumber: 20,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Refuse the Cage",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-020.webp",
    artAlt: "Refuse the Cage — Spark's Journey page 16",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p020-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "It belongs to the Meridian. Hand it over — alive.", speaker: "Vex Halden", x: 50, y: 25, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p020-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "It belongs to its own becoming. Compact law. Back away.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "speech", text: "Vex— if the scan was wrong—", speaker: "Nira Quill", x: 40, y: 75, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p020-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-020.webp",
      
      bubbles: [{ kind: "sfx", text: "WHUMP", x: 30, y: 40 }, { kind: "sfx", text: "SHIIING", x: 70, y: 50 }, { kind: "creature", text: "*snarl*", speaker: "Bramblefox", x: 45, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p021",
    pageNumber: 21,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Living Bulwark",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-021.webp",
    artAlt: "Living Bulwark — Spark's Journey page 17",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p021-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-021.webp",
      
      bubbles: [{ kind: "sfx", text: "BIND-LANCE", x: 60, y: 35 }, { kind: "creature", text: "*BULWARK!*", speaker: "Mossprig", x: 40, y: 55, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p021-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-021.webp",
      
      bubbles: [{ kind: "sfx", text: "KRRRAAAK", x: 50, y: 30 }, { kind: "creature", text: "*chir—!!*", speaker: "Spark", x: 65, y: 60, tail: "up" }, { kind: "speech", text: "Mossprig!", speaker: "Mira Eggwarden", x: 30, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p022",
    pageNumber: 22,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Grove Against Veil",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-022.webp",
    artAlt: "Grove Against Veil — Spark's Journey page 18",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p022-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "LEAF-SNAP", x: 50, y: 40 }],
    },
    {
      id: "sparks-journey-issue-002-p022-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-022.webp",
      
      bubbles: [{ kind: "creature", text: "*sprout-GO!*", speaker: "Thornling", x: 50, y: 50, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p022-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "phase-chime", x: 55, y: 45 }],
    },
    {
      id: "sparks-journey-issue-002-p022-panel-3",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-022.webp",
      
      bubbles: [{ kind: "narration", text: "Power without choice is just another cage.", x: 50, y: 15 }, { kind: "creature", text: "*tremble-hum*", speaker: "Spark", x: 50, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p023",
    pageNumber: 23,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "You Do Not Have To",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-023.webp",
    artAlt: "You Do Not Have To — Spark's Journey page 19",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p023-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "End this. Collar the anomaly.", speaker: "Vex Halden", x: 55, y: 30, tail: "down" }],
    },
    {
      id: "sparks-journey-issue-002-p023-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-023.webp",
      
      bubbles: [{ kind: "sfx", text: "RESONANCE+++", x: 50, y: 45 }],
    },
    {
      id: "sparks-journey-issue-002-p023-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "You don't have to fight for us. You don't have to be useful to be kept.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "whisper", text: "If you run through that door, I'll still call you Spark.", speaker: "Mira Eggwarden", x: 50, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p024",
    pageNumber: 24,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "You Were Never Made to Obey",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-024.webp",
    artAlt: "You Were Never Made to Obey — Spark's Journey page 20",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p024-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-024.webp",
      
      bubbles: [{ kind: "caption", text: "You were never made to obey.", x: 50, y: 18 }, { kind: "telepathy", text: "Become. Then choose.", speaker: "Ancient Keeper Echo", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p025",
    pageNumber: 25,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Chosen Step",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-025.webp",
    artAlt: "Chosen Step — Spark's Journey page 21",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p025-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-025.webp",
      
      bubbles: [{ kind: "creature", text: "*chir…* (bond-warmth)", speaker: "Spark", x: 45, y: 40, tail: "up" }, { kind: "speech", text: "Okay. Together — if you want.", speaker: "Mira Eggwarden", x: 55, y: 70, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p025-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-025.webp",
      
      bubbles: [{ kind: "narration", text: "Resonance held — not spilled.", x: 50, y: 15 }, { kind: "caption", text: "RIFT RESONANCE", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p026",
    pageNumber: 26,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Prismatic Burst",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-026.webp",
    artAlt: "Prismatic Burst — Spark's Journey page 22",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p026-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-026.webp",
      
      bubbles: [{ kind: "sfx", text: "PRISM—BURST", x: 50, y: 22 }, { kind: "sfx", text: "field-SHATTER", x: 70, y: 55 }, { kind: "shout", text: "Dampening— hold the line!", speaker: "Vex Halden", x: 30, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p027",
    pageNumber: 27,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Door for One",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-027.webp",
    artAlt: "Door for One — Spark's Journey page 23",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p027-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-027.webp",
      
      bubbles: [{ kind: "speech", text: "Alive capture — not a corpse for the ledger.", speaker: "Nira Quill", x: 50, y: 25, tail: "down" }, { kind: "speech", text: "You'll answer for this.", speaker: "Vex Halden", x: 55, y: 70, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p027-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-027.webp",
      
      bubbles: [{ kind: "narration", text: "The Meridian withdraws — not defeated forever.", x: 50, y: 50 }],
    },
    {
      id: "sparks-journey-issue-002-p027-panel-2",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-027.webp",
      
      bubbles: [{ kind: "speech", text: "It opens for you. We'll wait our turn.", speaker: "Mira Eggwarden", x: 40, y: 75, tail: "up" }, { kind: "creature", text: "*invite-chirp*", speaker: "Spark", x: 60, y: 55, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p028",
    pageNumber: 28,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Riftborn",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-028.webp",
    artAlt: "Riftborn — Spark's Journey page 24",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p028-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-028.webp",
      
      bubbles: [{ kind: "narration", text: "Not a mistake. A lineage of thresholds.", x: 50, y: 12 }, { kind: "speech", text: "You're one of several… Riftborn.", speaker: "Mira Eggwarden", x: 40, y: 75, tail: "up" }],
    },
    {
      id: "sparks-journey-issue-002-p028-panel-1",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-028.webp",
      
      bubbles: [{ kind: "caption", text: "CODEX CLASS: RIFTBORN (PROVISIONAL)", x: 50, y: 20 }, { kind: "creature", text: "*soft wonder-hum*", speaker: "Spark", x: 50, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Begin the Collection",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-029.webp",
    artAlt: "Begin the Collection — Spark's Journey page 25",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p029-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-029.webp",
      
      bubbles: [{ kind: "narration", text: "Someone reached the heart first.", x: 50, y: 10 }, { kind: "telepathy", text: "Subject One has awakened. Begin the collection.", speaker: "Veiled Meridian Channel", x: 50, y: 48 }, { kind: "caption", text: "TO BE CONTINUED IN ISSUE #3", x: 50, y: 72 }, { kind: "caption", text: "THE TRAVELING CIRCUS", x: 50, y: 84 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p030",
    pageNumber: 30,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next Issue — The Traveling Circus",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-030.webp",
    artAlt: "Next Issue — The Traveling Circus",
    atmosphere: "festival" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p030-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 15 }, { kind: "caption", text: "THE TRAVELING CIRCUS", x: 50, y: 28 }, { kind: "narration", text: "Lantern wagons. Honest applause. A collection already in motion.", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p031",
    pageNumber: 31,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Keeper Profile — Mira Eggwarden",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-031.webp",
    artAlt: "Keeper Profile — Mira Eggwarden",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p031-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-031.webp",
      
      bubbles: [{ kind: "narration", text: "MIRA EGGWARDEN — Hatchery mentor. Bond philosophy: keep, don't own. Compact first. Refuses to treat companions as weapons even when the Meridian calls them inventory.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profile — Spark",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-032.webp",
    artAlt: "Companion Profile — Spark",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p032-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-032.webp",
      
      bubbles: [{ kind: "narration", text: "SPARK — Glowpup-line Riftborn hatchling. Codex: UNKNOWN RESONANCE → provisional Riftborn. Communicates in chirps and bond-warmth. Passive: Rift Resonance. Ultimate: Prismatic Burst.", x: 50, y: 60 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p033",
    pageNumber: 33,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Codex — Riftborn",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-033.webp",
    artAlt: "Codex — Riftborn",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p033-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-033.webp",
      
      bubbles: [{ kind: "narration", text: "CODEX ENTRY (DRAFT): Riftborn — rare companions whose affinity does not lock to a single element. Linked to threshold Rifts across Aeryndra. Shellward Sanctum catalogs them as kin, not inventory. Status: provisional · Subject One awakened.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p034",
    pageNumber: 34,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Rift Resonance",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-034.webp",
    artAlt: "Ability Spotlight — Rift Resonance",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p034-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-034.webp",
      
      bubbles: [{ kind: "narration", text: "RIFT RESONANCE — When another companion uses an elemental ability, Spark gains 1 Resonance (max 3). Prismatic Burst consumes Resonance to strike and briefly boost allies. Not domination — shared pulse.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p035",
    pageNumber: 35,
    layout: "splash" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "World Map — Commons to Shellward",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-035.webp",
    artAlt: "World Map — Commons to Shellward",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p035-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "RIFTWILD COMMONS → SHELLWARD SANCTUM", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Editor's Note — Trust & Choice",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-036.webp",
    artAlt: "Editor's Note — Trust & Choice",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p036-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-036.webp",
      
      bubbles: [{ kind: "narration", text: "EDITOR'S NOTE: Spark's Journey is about trust under fear — the difference between protection and control. A companion who can run away and still be invited back is the Compact made flesh. Write the Lore Desk. Keep invitations honest.", x: 50, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-037.webp",
    artAlt: "Inside Back Cover",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p037-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-037.webp",
      
      bubbles: [{ kind: "narration", text: "Continue in Live World · Study Riftborn in the Codex · Visit the Hatchery under Compact law", x: 50, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "sparks-journey-issue-002-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover — Traveling Lantern Caravan",
    artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-038.webp",
    artAlt: "Back Cover — Traveling Lantern Caravan",
    atmosphere: "festival" as ComicPage["atmosphere"],
    panels: [{
      id: "sparks-journey-issue-002-p038-panel-0",
      artSrc: "/assets/comics/sparks-journey/issue-002/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "THE TRAVELING LANTERN CARAVAN", x: 50, y: 18 }, { kind: "narration", text: "Lanterns. Companion acts. Honest cheers — never SOL in the hat. Masked Host invites Keepers who listen. (In-world advertisement · not a real-money offer.)", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Hatchery mentor — invites, waits, refuses the cage." },
    { name: "Spark", role: "Riftborn Glowpup", blurb: "Unknown resonance; chooses trust." },
    { name: "Vex Halden", role: "Meridian hunter", blurb: "Capture Subject One alive." },
    { name: "Nira Quill", role: "Meridian hunter", blurb: "Questions the mission." },
    { name: "Elara Venn", role: "Vision echo", blurb: "First Keeper — Soft Exodus memory only." },
  ],
  locations: [
    { name: "Riftwild Commons", blurb: "Hatch dawn and Compact hearth." },
    { name: "First-Rift scar wilds", blurb: "Warped roads after the First Tear." },
    { name: "Shellward Sanctum", blurb: "Ancient sanctuary of Riftborn kin." },
  ],
  timelineNote: "Immediately after The First Rift — Mira's pulse-egg hatches.",
  playChapterHref: "/hatchery",
  playChapterLabel: "Visit the Hatchery",
  unlockGates: [
    { kind: "prior-issue", slug: "the-first-rift", label: "Complete Issue #1: The First Rift" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-traveling-circus",
    hook: "Subject One has awakened. Begin the collection.",
  },
  readingTimeMinutes: 20,
  factions: [
    { name: "Veiled Meridian", blurb: "Field hunters for Subject One — org still veiled." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue002Transcript(pageNumber: number): string[] {
  return ISSUE_002_TRANSCRIPTS[pageNumber] ?? [];
}
