import type { CivilizationMilestoneDef } from "@/game/civilization/types";

export const CIVILIZATION_MILESTONES: CivilizationMilestoneDef[] = [
  {
    key: "commons_lanterns",
    name: "Lanterns Relit",
    description: "Keepers restore the Commons plaza lanterns — night travel feels safer.",
    category: "commons",
    threshold: 500,
    era: 1,
    imageSrc: "/assets/restoration/commons-lanterns.png",
    worldEffects: [
      { kind: "visual_overlay", regionSlug: "riftwild-commons", overlayKey: "lanterns_restored" },
      { kind: "npc_schedule_add", npcKey: "night-market-vendor" },
    ],
    keeperRewardHint: "Night plaza cosmetics unlock for homestead guest areas.",
  },
  {
    key: "ember_forge_reignited",
    name: "Crater Forge Reignited",
    description: "Collective ash clearing reopens the crater forge vents.",
    category: "ember",
    threshold: 1200,
    era: 1,
    imageSrc: "/assets/restoration/ember-forge-reignited.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "ember-crater", feature: "forge_vents" },
      { kind: "resource_multiplier", resourceKey: "ember_shard", multiplier: 1.1 },
    ],
    keeperRewardHint: "Ember crafting recipes preview in the forge room.",
  },
  {
    key: "tide_piers_rebuilt",
    name: "Moonwater Piers Rebuilt",
    description: "Coastal piers return — fishing nodes expand.",
    category: "tide",
    threshold: 1200,
    era: 1,
    imageSrc: "/assets/restoration/tide-piers-rebuilt.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "moonwater-coast", feature: "deep_piers" },
      { kind: "resource_multiplier", resourceKey: "tide_pearl", multiplier: 1.1 },
    ],
    keeperRewardHint: "Homestead fishing pond yield flavor bonus.",
  },
  {
    key: "grove_shrine_restored",
    name: "Elderwood Shrine Restored",
    description: "The Bloomtide shrine stands again — seasonal stories deepen.",
    category: "grove",
    threshold: 1500,
    era: 1,
    imageSrc: "/assets/restoration/grove-shrine-restored.png",
    worldEffects: [
      { kind: "story_flag", flag: "grove_shrine_restored" },
      { kind: "festival_unlock", festivalKey: "bloomtide_festival" },
    ],
    keeperRewardHint: "Seasonal festival board unlocks.",
  },
  {
    key: "storm_beacons",
    name: "Stormspire Beacons",
    description: "Lightning beacons guide aerial routes through peaks.",
    category: "storm",
    threshold: 2000,
    era: 2,
    imageSrc: "/assets/restoration/storm-beacons.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "stormspire-peaks", feature: "sky_beacons" },
    ],
    keeperRewardHint: "Expedition aerial routes become available.",
  },
  {
    key: "stone_bridges",
    name: "Canyon Bridges",
    description: "Stoneheart crossings reconnect canyon trade.",
    category: "stone",
    threshold: 2000,
    era: 2,
    imageSrc: "/assets/restoration/stone-bridges.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "stoneheart-canyon", feature: "trade_bridges" },
    ],
    keeperRewardHint: "Marketplace travel time flavor reduction.",
  },
  {
    key: "frost_observatory",
    name: "Frostveil Observatory",
    description: "Keepers raise a crystal observatory for aurora research.",
    category: "frost",
    threshold: 2500,
    era: 2,
    imageSrc: "/assets/restoration/frost-observatory.png",
    worldEffects: [
      { kind: "weather_bias", regionSlug: "frostveil-basin", weatherKey: "rift_aurora", weightBonus: 2 },
      { kind: "homestead_room", roomKey: "observatory-nook" },
    ],
    keeperRewardHint: "Homestead observatory nook blueprint.",
  },
  {
    key: "radiant_archives",
    name: "Radiant Archives Wing",
    description: "Citadel archives reopen — Archivist capacity expands.",
    category: "radiant",
    threshold: 3000,
    era: 2,
    imageSrc: "/assets/restoration/radiant-archives.png",
    worldEffects: [
      { kind: "story_flag", flag: "radiant_archives_open" },
      { kind: "npc_schedule_add", npcKey: "citadel-librarian" },
    ],
    keeperRewardHint: "Codex deep-lore pages unlock.",
  },
  {
    key: "void_seals",
    name: "Hollow Seals Stabilized",
    description: "Void blooms are cataloged and sealed — safer hollow expeditions.",
    category: "void",
    threshold: 3500,
    era: 3,
    imageSrc: "/assets/restoration/void-seals.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "void-hollow", feature: "stable_seals" },
    ],
    keeperRewardHint: "Endless Rift entry prep (endgame stub).",
  },
  {
    key: "alloy_foundry",
    name: "Alloy Foundry Chorus",
    description: "Ruins forges sing again in coordinated rhythm.",
    category: "alloy",
    threshold: 3500,
    era: 3,
    imageSrc: "/assets/restoration/alloy-foundry.png",
    worldEffects: [
      { kind: "resource_multiplier", resourceKey: "alloy_cog", multiplier: 1.15 },
    ],
    keeperRewardHint: "Gear upgrade preview recipes.",
  },
  {
    key: "spirit_ways",
    name: "Spirit Marsh Ways",
    description: "Lantern paths through the marsh guide lost pets home.",
    category: "spirit",
    threshold: 4000,
    era: 3,
    imageSrc: "/assets/restoration/spirit-ways.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "spirit-marsh", feature: "lantern_ways" },
    ],
    keeperRewardHint: "Pet memory reunion encounters.",
  },
  {
    key: "celestial_gate",
    name: "Celestial Gate Primed",
    description: "The high rift gate hums — raid and endless content scaffolds unlock.",
    category: "celestial",
    threshold: 10000,
    era: 4,
    imageSrc: "/assets/restoration/celestial-gate.png",
    worldEffects: [
      { kind: "unlock_region_feature", regionSlug: "celestial-rift", feature: "gate_primed" },
      { kind: "story_flag", flag: "endgame_gate_open" },
    ],
    keeperRewardHint: "Endgame raid briefing access.",
  },
  {
    key: "global_era_two",
    name: "Second Restoration Era",
    description: "World-wide milestone — regions evolve visual layers permanently.",
    category: "global",
    threshold: 25000,
    era: 2,
    imageSrc: "/assets/restoration/global-era-two.png",
    worldEffects: [
      { kind: "story_flag", flag: "civilization_era_2" },
      { kind: "visual_overlay", regionSlug: "riftwild-commons", overlayKey: "era2_plaza" },
    ],
    keeperRewardHint: "Era title cosmetic for keepers who contributed.",
  },
];

export function milestoneByKey(key: string): CivilizationMilestoneDef | undefined {
  return CIVILIZATION_MILESTONES.find((m) => m.key === key);
}
