/**
 * Published clean art under /assets/cards/{expansion}/{slug}/.
 * Index generated by scripts/tcg/publish-card-assets.mjs — never bakes stats.
 */

import assetPathsV1 from "@/content/tcg/data/migrations/card-asset-paths-v1.json";

export type CardAssetPathEntry = {
  expansion: string;
  slug: string;
  art: string | null;
  thumb: string | null;
  source?: string;
  missing?: boolean;
};

export type CardAssetPathBundle = {
  version: number;
  schema: string;
  generatedAt: string;
  paths: Record<string, CardAssetPathEntry>;
};

const bundle = assetPathsV1 as CardAssetPathBundle;

export function resolvePublishedCleanArt(cardId: string): string | null {
  const entry = bundle.paths?.[cardId];
  if (!entry || entry.missing) return null;
  return entry.art ?? entry.thumb ?? null;
}

export function resolvePublishedThumb(cardId: string): string | null {
  const entry = bundle.paths?.[cardId];
  if (!entry || entry.missing) return null;
  return entry.thumb ?? entry.art ?? null;
}

export function getCardAssetPathBundle(): CardAssetPathBundle {
  return bundle;
}
