/**
 * Published clean art under /assets/cards/{expansion}/{slug}/.
 * Index generated by scripts/tcg/publish-card-assets.mjs — never bakes stats.
 */

import assetPathsV1 from "@/content/tcg/data/migrations/card-asset-paths-v1.json";

export type CardAssetPathEntry = {
  expansion: string;
  slug: string;
  art: string | null;
  thumb: string | null;
  source?: string;
  missing?: boolean;
};

export type CardAssetPathBundle = {
  version: number;
  schema: string;
  generatedAt: string;
  paths: Record<string, CardAssetPathEntry>;
};

const bundle = assetPathsV1 as CardAssetPathBundle;

/** Bump when habitat-composited clean art is regenerated. */
export const CARD_CLEAN_ART_V = "habcard1";

function withArtCacheBust(src: string | null): string | null {
  if (!src) return null;
  const join = src.includes("?") ? "&" : "?";
  return `${src}${join}v=${CARD_CLEAN_ART_V}`;
}

export function resolvePublishedCleanArt(cardId: string): string | null {
  const entry = bundle.paths?.[cardId];
  if (!entry || entry.missing) return null;
  return withArtCacheBust(entry.art ?? entry.thumb ?? null);
}

export function resolvePublishedThumb(cardId: string): string | null {
  const entry = bundle.paths?.[cardId];
  if (!entry || entry.missing) return null;
  return withArtCacheBust(entry.thumb ?? entry.art ?? null);
}

export function getCardAssetPathBundle(): CardAssetPathBundle {
  return bundle;
}
