import type {
  FarmPlotDef,
  FurnitureDef,
  HomesteadExpansionModel,
} from "@/game/housing/types";

/** Extends the 12 shell rooms on the Homestead page with gameplay data. */
export const HOMESTEAD_ROOMS = [
  {
    roomKey: "pet-house",
    name: "Pet house",
    unlockHint: "Starter unlock with first hatch",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "garden",
    name: "Garden",
    unlockHint: "Civilization grove milestone or care streak",
    supportsFarming: true,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "training-yard",
    name: "Training yard",
    unlockHint: "Complete Arena training bouts",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: true,
  },
  {
    roomKey: "forge",
    name: "Forge",
    unlockHint: "Ember forge civilization milestone",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "potion-laboratory",
    name: "Potion laboratory",
    unlockHint: "Craft or brew preview unlock",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "fishing-pond",
    name: "Fishing pond",
    unlockHint: "Tide piers civilization milestone",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: true,
  },
  {
    roomKey: "egg-incubator",
    name: "Egg incubator",
    unlockHint: "Hatch 3 eggs",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "trophy-room",
    name: "Trophy room",
    unlockHint: "Unlock 10 achievements",
    supportsFarming: false,
    supportsTrophies: true,
    supportsGuest: true,
  },
  {
    roomKey: "marketplace-stall",
    name: "Marketplace stall",
    unlockHint: "Marketplace browse + listing preview",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: true,
  },
  {
    roomKey: "healing-room",
    name: "Healing room",
    unlockHint: "Care recovery mastery",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "storage",
    name: "Storage",
    unlockHint: "Inventory capacity milestone",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: false,
  },
  {
    roomKey: "guest-area",
    name: "Guest area",
    unlockHint: "Host first friend visit",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: true,
  },
  {
    roomKey: "observatory-nook",
    name: "Observatory nook",
    unlockHint: "Frostveil observatory civilization milestone",
    supportsFarming: false,
    supportsTrophies: false,
    supportsGuest: true,
  },
] as const;

export const FURNITURE_CATALOG: FurnitureDef[] = [
  {
    key: "moss_bed",
    name: "Moss Nest Bed",
    category: "care",
    roomKeys: ["pet-house", "healing-room"],
    rarity: "common",
    description: "Soft nest that hints at sleep recovery bonuses.",
    footprint: { w: 2, h: 2 },
  },
  {
    key: "rift_lantern",
    name: "Rift Lantern",
    category: "lighting",
    roomKeys: ["pet-house", "guest-area", "observatory-nook"],
    rarity: "uncommon",
    description: "Glows with seasonal weather tint.",
    footprint: { w: 1, h: 1 },
  },
  {
    key: "herb_planter",
    name: "Herb Planter",
    category: "farming",
    roomKeys: ["garden"],
    rarity: "common",
    description: "Hosts grove herb crops.",
    footprint: { w: 2, h: 1 },
  },
  {
    key: "trophy_plinth",
    name: "Trophy Plinth",
    category: "trophy",
    roomKeys: ["trophy-room"],
    rarity: "rare",
    description: "Displays achievement and boss relics.",
    footprint: { w: 1, h: 1 },
  },
  {
    key: "forge_anvil",
    name: "Crater Anvil",
    category: "workshop",
    roomKeys: ["forge"],
    rarity: "rare",
    description: "Workshop prop for future crafting jobs.",
    footprint: { w: 2, h: 2 },
  },
  {
    key: "guest_bench",
    name: "Visitor Bench",
    category: "guest",
    roomKeys: ["guest-area", "training-yard"],
    rarity: "common",
    description: "Friends can emote while visiting.",
    footprint: { w: 2, h: 1 },
  },
  {
    key: "egg_cradle",
    name: "Incubator Cradle",
    category: "care",
    roomKeys: ["egg-incubator"],
    rarity: "uncommon",
    description: "Visual home for incubating eggs.",
    footprint: { w: 2, h: 2 },
  },
  {
    key: "stall_awning",
    name: "Stall Awning",
    category: "decor",
    roomKeys: ["marketplace-stall"],
    rarity: "uncommon",
    description: "Cosmetic front for homestead trading flavor.",
    footprint: { w: 3, h: 1 },
  },
  {
    key: "crystal_scope",
    name: "Crystal Scope",
    category: "decor",
    roomKeys: ["observatory-nook"],
    rarity: "epic",
    description: "Watches aurora weather for living timeline notes.",
    footprint: { w: 1, h: 2 },
  },
  {
    key: "storage_crate",
    name: "Keeper Crate",
    category: "storage",
    roomKeys: ["storage"],
    rarity: "common",
    description: "Inventory overflow flavor prop.",
    footprint: { w: 1, h: 1 },
  },
];

export const FARM_PLOTS: FarmPlotDef[] = [
  {
    key: "grove_herb_row",
    name: "Grove Herb Row",
    cropKeys: ["grove_herb", "moon_mint"],
    growWorldDays: 2,
    roomKey: "garden",
  },
  {
    key: "ember_pepper_box",
    name: "Ember Pepper Box",
    cropKeys: ["ember_pepper"],
    growWorldDays: 3,
    roomKey: "garden",
  },
  {
    key: "frost_berry_patch",
    name: "Frost Berry Patch",
    cropKeys: ["frost_berry"],
    growWorldDays: 3,
    roomKey: "garden",
  },
];

export function getHomesteadExpansionModel(): HomesteadExpansionModel {
  return {
    rooms: HOMESTEAD_ROOMS.map((r) => ({ ...r })),
    furniture: FURNITURE_CATALOG,
    farmPlots: FARM_PLOTS,
    visitPolicies: ["PRIVATE", "FRIENDS", "GUILD", "PUBLIC"],
  };
}
