import type { QuestDef } from "@/game/quests/quest-types";

/**
 * Beginner chain Quests 1–8 — keys match play-state + generated NPC dialogue.
 */
export const STARTER_QUEST_CHAIN: QuestDef[] = [
  {
    key: "starter-q1-awakening",
    name: "Awakening in the Commons",
    description: "Learn the basics from Keeper Rowan Vale, then visit Elara Venn.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    objectives: [
      { key: "move", description: "Move around the Commons", metric: "player_move", target: 1 },
      { key: "talk-rowan", description: "Speak with Rowan Vale", metric: "npc_talk", target: 1 },
      { key: "find-elara", description: "Find Elara Venn", metric: "npc_talk", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 50 },
      { kind: "soft_currency", amount: 25, label: "Demo Credits" },
    ],
    sortOrder: 1,
  },
  {
    key: "starter-q2-fragments",
    name: "Fragments of the Past",
    description: "Hear the Fracture story and visit Archivist Solen at the Codex.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q1-awakening"],
    objectives: [
      { key: "hear-fracture", description: "Hear Elara's Fracture story", metric: "story_flag", target: 1 },
      { key: "visit-codex", description: "Speak with Archivist Solen", metric: "npc_talk", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 75 },
      { kind: "soft_currency", amount: 30, label: "Demo Credits" },
    ],
    sortOrder: 2,
  },
  {
    key: "starter-q3-waiting-heart",
    name: "A Waiting Heart",
    description: "Visit the Hatchery with Mira and hatch your first Riftling.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q2-fragments"],
    objectives: [
      { key: "visit-hatchery", description: "Visit the Hatchery", metric: "building_visit", target: 1 },
      { key: "inspect-egg", description: "Inspect a starter egg", metric: "egg_inspect", target: 1 },
      { key: "gather-mossmeal", description: "Gather mossmeal", metric: "item_owned", target: 1 },
      { key: "hatch", description: "Hatch your first Riftling", metric: "hatch_count", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 120 },
      { kind: "soft_currency", amount: 50, label: "Demo Credits" },
    ],
    sortOrder: 3,
  },
  {
    key: "starter-q4-new-bond",
    name: "A New Bond",
    description: "Name, care for, and equip your Riftling as active companion.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q3-waiting-heart"],
    objectives: [
      { key: "name", description: "Name your Riftling", metric: "pet_name", target: 1 },
      { key: "profile", description: "Open the Riftling profile", metric: "pet_profile", target: 1 },
      { key: "care", description: "Feed or care for your Riftling", metric: "care_feed", target: 1 },
      { key: "equip", description: "Equip as active companion", metric: "pet_equip", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 100 },
      { kind: "soft_currency", amount: 40, label: "Demo Credits" },
    ],
    sortOrder: 4,
  },
  {
    key: "starter-q5-first-steps",
    name: "First Steps Together",
    description: "Captain Orren sends you to defeat a beginner enemy and return.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q4-new-bond"],
    objectives: [
      { key: "leave-safe", description: "Travel to the outer woods", metric: "region_zone", target: 1 },
      { key: "defeat", description: "Defeat a beginner rift-slime", metric: "enemy_defeat", target: 1 },
      { key: "loot", description: "Collect a dropped resource", metric: "loot_collect", target: 1 },
      { key: "return", description: "Return to Captain Orren", metric: "npc_talk", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 150 },
      { kind: "soft_currency", amount: 60, label: "Demo Credits" },
      { kind: "care_item", itemKey: "slime-gel", label: "Slime Gel", quantity: 1 },
    ],
    sortOrder: 5,
  },
  {
    key: "starter-q6-tools",
    name: "Tools of the Keeper",
    description: "Gather materials with Bram and craft a beginner tool.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q5-first-steps"],
    objectives: [
      { key: "gather", description: "Gather ore or wood", metric: "gather_count", target: 1 },
      { key: "craft", description: "Craft a beginner tool", metric: "craft_item", target: 1 },
      { key: "equip-tool", description: "Equip the tool", metric: "equip_tool", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 100 },
      { kind: "soft_currency", amount: 40, label: "Demo Credits" },
      { kind: "care_item", itemKey: "starter-pick", label: "Starter Pick", quantity: 1 },
    ],
    sortOrder: 6,
  },
  {
    key: "starter-q7-broken-marker",
    name: "Map and Marker",
    description: "Pip teaches map markers before your first portal authorization.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q6-tools"],
    objectives: [
      { key: "components", description: "Gather marker components", metric: "gather_count", target: 1 },
      { key: "place-marker", description: "Place a practice map marker", metric: "map_marker", target: 1 },
      { key: "confirm-portal", description: "Confirm portal circle readout", metric: "portal_readout", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 80 },
      { kind: "soft_currency", amount: 35, label: "Demo Credits" },
    ],
    sortOrder: 7,
  },
  {
    key: "starter-q8-world-beyond",
    name: "The First Portal",
    description: "Elara authorizes your first region portal — travel beyond Commons.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q7-broken-marker"],
    objectives: [
      { key: "choose", description: "Speak with Elara about portals", metric: "npc_talk", target: 1 },
      { key: "portal", description: "Use a region portal", metric: "portal_use", target: 1 },
      { key: "travel", description: "Enter Ember, Coast, or Elderwood", metric: "region_travel", target: 1 },
      { key: "meet-guide", description: "Meet a regional guide", metric: "npc_talk", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 200 },
      { kind: "soft_currency", amount: 100, label: "Demo Credits" },
    ],
    sortOrder: 8,
  },
];

export const STARTER_QUEST_BY_KEY = Object.fromEntries(
  STARTER_QUEST_CHAIN.map((q) => [q.key, q]),
) as Record<string, QuestDef>;

export const STARTER_QUEST_KEYS = STARTER_QUEST_CHAIN.map((q) => q.key);
