import type { QuestDef } from "@/game/quests/quest-types";

/**
 * Quest-board starter chain for launch (TCG-first).
 * Live World Phaser still uses `starter-quests.ts` — do not delete that chain.
 */
export const STARTER_QUEST_CHAIN_TCG: QuestDef[] = [
  {
    key: "starter-q1-awakening",
    name: "Awakening as a Duelist",
    description: "Open your Card Binder and step onto a practice Rift Battle board.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    objectives: [
      { key: "open-binder", description: "Open the Card Binder", metric: "binder_open", target: 1 },
      { key: "start-practice", description: "Start a practice Rift Battle", metric: "tcg_match_play", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 50 },
      { kind: "soft_currency", amount: 25, label: "Credits" },
    ],
    sortOrder: 1,
  },
  {
    key: "starter-q2-fragments",
    name: "Fragments of the Rift",
    description: "Learn why Rift Energy powers every duel — then return ready to hatch.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q1-awakening"],
    objectives: [
      { key: "academy-tip", description: "Read a Rift Battle Academy tip", metric: "academy_visit", target: 1 },
      { key: "play-cards", description: "Play 3 cards in battle", metric: "tcg_card_play", target: 3 },
    ],
    rewards: [
      { kind: "xp", amount: 75 },
      { kind: "soft_currency", amount: 30, label: "Credits" },
    ],
    sortOrder: 2,
  },
  {
    key: "starter-q3-waiting-heart",
    name: "A Waiting Heart",
    description: "Visit the Hatchery and hatch your first Riftling companion.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q2-fragments"],
    objectives: [
      { key: "visit-hatchery", description: "Visit the Hatchery", metric: "hatchery_visit", target: 1 },
      { key: "inspect-egg", description: "Inspect a starter egg", metric: "egg_inspect", target: 1 },
      { key: "hatch", description: "Hatch your first Riftling", metric: "hatch_count", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 120 },
      { kind: "soft_currency", amount: 50, label: "Credits" },
    ],
    sortOrder: 3,
  },
  {
    key: "starter-q4-new-bond",
    name: "Bond & Binder",
    description: "Care for your Riftling, then claim their starter card into your binder.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q3-waiting-heart"],
    objectives: [
      { key: "care", description: "Feed or care for your Riftling", metric: "care_feed", target: 1 },
      { key: "binder-claim", description: "Collect a starter species card", metric: "tcg_card_collect", target: 1 },
      { key: "set-deck", description: "Set an active deck", metric: "tcg_deck_set", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 100 },
      { kind: "soft_currency", amount: 40, label: "Credits" },
    ],
    sortOrder: 4,
  },
  {
    key: "starter-q5-first-steps",
    name: "First Victory",
    description: "Win a practice Rift Battle — your first rung on the duel ladder.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q4-new-bond"],
    objectives: [
      { key: "play-match", description: "Complete a Rift Battle", metric: "tcg_match_play", target: 1 },
      { key: "win", description: "Win a practice Rift Battle", metric: "tcg_match_win", target: 1 },
      { key: "spend-energy", description: "Spend 6 Rift Energy in battle", metric: "tcg_energy_spend", target: 6 },
    ],
    rewards: [
      { kind: "xp", amount: 150 },
      { kind: "soft_currency", amount: 60, label: "Credits" },
      { kind: "arena_points", amount: 40 },
      {
        kind: "egg",
        label: "Ember Egg",
        eggType: "EMBER",
        earnPath: "QUEST",
      },
    ],
    sortOrder: 5,
  },
  {
    key: "starter-q6-tools",
    name: "Tools of the Duelist",
    description: "Grow your binder and lock a practice deck for the board.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q5-first-steps"],
    objectives: [
      { key: "collect-three", description: "Own 3 unique cards", metric: "tcg_card_collect", target: 3 },
      { key: "set-deck", description: "Confirm your active deck", metric: "tcg_deck_set", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 100 },
      { kind: "soft_currency", amount: 40, label: "Credits" },
    ],
    sortOrder: 6,
  },
  {
    key: "starter-q7-broken-marker",
    name: "Energy Discipline",
    description: "Play clean turns — spend energy, play units, and finish a match.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q6-tools"],
    objectives: [
      { key: "play-eight", description: "Play 8 cards across battles", metric: "tcg_card_play", target: 8 },
      { key: "finish", description: "Complete 2 Rift Battles", metric: "tcg_match_play", target: 2 },
    ],
    rewards: [
      { kind: "xp", amount: 80 },
      { kind: "soft_currency", amount: 35, label: "Credits" },
    ],
    sortOrder: 7,
  },
  {
    key: "starter-q8-world-beyond",
    name: "Beyond Practice",
    description: "Win three Rift Battles and prove you are ready for the seasonal ladder.",
    category: "STORY",
    boardTab: "story",
    difficulty: "easy",
    regionKey: "riftwild-commons",
    regionName: "Riftwild Commons",
    chainKey: "starter",
    repeatable: false,
    requires: ["starter-q7-broken-marker"],
    objectives: [
      { key: "win-three", description: "Win 3 practice Rift Battles", metric: "tcg_match_win", target: 3 },
      { key: "open-ladder", description: "Visit the Rift Battles leaderboard", metric: "leaderboard_visit", target: 1 },
    ],
    rewards: [
      { kind: "xp", amount: 200 },
      { kind: "soft_currency", amount: 100, label: "Credits" },
      { kind: "arena_points", amount: 75 },
    ],
    sortOrder: 8,
  },
];
