/* AUTO-GENERATED by scripts/comics/emit-issue-005-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_005_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: LEGENDS OF THE RIFT",
    "CAPTION: THE STORM KING",
    "CAPTION: ISSUE #5"
  ],
  "2": [
    "NARRATION: Previously: Aureth Vale woke. The Guardian remembered. A signal answered from the peaks.",
    "CAPTION: CONTINUE THE FRACTURE DAWN"
  ],
  "3": [
    "CAPTION: THE STORM KING",
    "NARRATION: Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden.",
    "CAPTION: ORIGINAL RIFTWILDS IP"
  ],
  "4": [
    "CAPTION: CHAPTER FIVE",
    "CAPTION: THE STORM KING",
    "NARRATION: Duty built a wall of weather. The wall began to eat its makers."
  ],
  "5": [
    "NARRATION: Some kingdoms built walls. Tempestria built weather.",
    "CAPTION: TEMPESTRIA",
    "SFX: KRACK-BOOM"
  ],
  "6": [
    "SPEECH (Tavi Brightline): Hold the little green!",
    "SFX: WHOOOOM",
    "CREATURE (Mossprig): *root-brace*",
    "SPEECH (Mira Eggwarden): Thank you. Stay low.",
    "CREATURE (Spark): *pain-chirp*",
    "THOUGHT (Mira Eggwarden): The lightning hurts him. The engine is already speaking."
  ],
  "7": [
    "CREATURE (Galesprig): *chirp-updraft*",
    "SPEECH (Cael Vesper): A local scout. Follow the wind — carefully.",
    "NARRATION: Some doors are made of weather.",
    "SFX: wind-tunnel-WHOOSH"
  ],
  "8": [
    "NARRATION: They built homes under a sky that never forgives.",
    "WHISPER (Villager): That light… Resonance?",
    "CREATURE (Spark): *shy-glow*"
  ],
  "9": [
    "SPEECH (Mira Eggwarden): Does the king keep you safe — or keep you in?",
    "SPEECH (Villager A): Without Vaelor, the Rift would have eaten us generations ago.",
    "SPEECH (Villager B): Safe is a word for people who can leave. We can't.",
    "CREATURE (Echoquill): *archive-trill*",
    "THOUGHT (Mira Eggwarden): Protection that forbids exit is still a cage."
  ],
  "10": [
    "SPEECH (Royal Captain): Outsiders. The King requires your presence.",
    "SFX: armor-CLACK",
    "SPEECH (Cael Vesper): That crest… I negotiated under it once. Years ago.",
    "WHISPER (Cael Vesper): He does not forget visitors.",
    "SPEECH (Mira Eggwarden): We'll come. Spark stays with me."
  ],
  "11": [
    "NARRATION: Duty sat the throne so long it forgot how to stand.",
    "SPEECH (King Vaelor Tempest): Approach. The storm has already named you.",
    "SFX: conduit-HUMMMM"
  ],
  "12": [
    "SPEECH (King Vaelor Tempest): Resonance Keeper. Last Light of a broken line.",
    "CREATURE (Spark): *alert-chirp*",
    "SPEECH (King Vaelor Tempest): You may stabilize what my bond can no longer hold alone.",
    "SPEECH (Mira Eggwarden): Stabilize how? What does that cost him?",
    "THOUGHT (Mira Eggwarden): Invite. Wait. Never own."
  ],
  "13": [
    "SPEECH (King Vaelor Tempest): Bring the Resonance to the chamber. The kingdom endures.",
    "SPEECH (Mira Eggwarden): No. Not until I understand the risk — and he chooses.",
    "SHOUT (Royal Captain): Insolence—",
    "SPEECH (King Vaelor Tempest): Choice is a luxury walls cannot afford.",
    "WHISPER (Cael Vesper): Mira… careful."
  ],
  "14": [
    "SFX: THOOM-KRACK",
    "CREATURE (Spark): *shared-pain!*",
    "CREATURE (Thundervane): *agonized-roar*",
    "SPEECH (King Vaelor Tempest): Hold— hold the crown—"
  ],
  "15": [
    "NARRATION: The engine did not love them. It used their love as fuel.",
    "SFX: engine-PULSE",
    "SPEECH (Cael Vesper): It draws through the bond. Both of them.",
    "SPEECH (King Vaelor Tempest): Without it, Tempestria dies. With it… we dwindle."
  ],
  "16": [
    "SPEECH (Cael Vesper): I stood here years ago. I warned you the bond could not hold forever.",
    "SPEECH (King Vaelor Tempest): And I refused to abandon my duty. I refuse still.",
    "CREATURE (Thundervane): *weak-rumble*",
    "SPEECH (Mira Eggwarden): Duty that empties the one you love is not protection."
  ],
  "17": [
    "SFX: BOOOOM",
    "SHOUT (Villager): The tower—!",
    "SPEECH (Seris Vale): Component online. Tear the wall.",
    "SFX: seal-CLICK",
    "SPEECH (King Vaelor Tempest): Outsiders bring rot—",
    "SPEECH (Mira Eggwarden): That seal is Meridian — Lost City work."
  ],
  "18": [
    "SPEECH (Seris Vale): Tempestria — your king has lost control. Meridian offers orderly protection.",
    "SFX: crowd-panic",
    "SPEECH (Villager B): Protection or a new cage?",
    "SHOUT (King Vaelor Tempest): You came with them!",
    "SPEECH (Mira Eggwarden): We came for a signal — not a seizure."
  ],
  "19": [
    "NARRATION: When a wall built of weather fails, the sky itself becomes an invasion.",
    "SFX: TEEEAR-KRACK",
    "CAPTION: CORRUPTED SKY HOST"
  ],
  "20": [
    "SPEECH (King Vaelor Tempest): Rise, old friend. One more wall.",
    "CREATURE (Thundervane): *pained-roar*",
    "SPEECH (Mira Eggwarden): He cannot survive another battle like this!",
    "SPEECH (King Vaelor Tempest): Neither can the kingdom.",
    "SFX: wing-BEAT"
  ],
  "21": [
    "CREATURE (Bramblefox): *track-snap*",
    "SFX: vine-WHIP",
    "CREATURE (Mossprig): *bulwark!*",
    "CREATURE (Thornling): *zzzt-power*",
    "SFX: conductor-ZAP",
    "CREATURE (Galesprig): *updraft!*",
    "CREATURE (Wisplet): *phase-hum*",
    "SPEECH (Mira Eggwarden): Companions — hold the people first!"
  ],
  "22": [
    "SFX: SKYBREAKER",
    "SFX: KRACK-BOOM",
    "SHOUT (Mira Eggwarden): Spark — left!",
    "SPEECH (Seris Vale): Secure the Resonance. Ignore the king.",
    "CREATURE (Thundervane): *battle-roar*"
  ],
  "23": [
    "SPEECH (Seris Vale): Replacement stabilizer online — Subject One, yield.",
    "SFX: tether-HUM",
    "SPEECH (Nira Quill): Not like that. Not him.",
    "CREATURE (Spark): *free-chirp!*",
    "SPEECH (Seris Vale): Quill—? You cut your own leash.",
    "WHISPER (Nira Quill): I cut theirs.",
    "SPEECH (Mira Eggwarden): Nira—!"
  ],
  "24": [
    "NARRATION: Once, the wall was a promise — not a prison.",
    "CREATURE (Young Thundervane): *joy-rumble*",
    "NARRATION: Years became walls. Walls became hunger.",
    "SFX: time-HUM",
    "TELEPATHY (Thundervane): Do not become the next wall.",
    "CREATURE (Spark): *understand-glow*"
  ],
  "25": [
    "CREATURE (Spark): *refuse-replace*",
    "SPEECH (Mira Eggwarden): He won't take Thundervane's place. He won't be owned by an engine.",
    "TELEPATHY (Thundervane): I stayed for love. You kept me for fear.",
    "SPEECH (King Vaelor Tempest): I confused loyalty… with obligation.",
    "WHISPER (Cael Vesper): Then choose which one remains."
  ],
  "26": [
    "SPEECH (King Vaelor Tempest): I release you. Live — even if I fall.",
    "SFX: bond-SNAP",
    "NARRATION: For one breath, Tempestria had a sky.",
    "SFX: silence…",
    "SPEECH (Mira Eggwarden): Together — invite, don't own.",
    "CREATURE (Spark): *steady-hum*",
    "CREATURE (Thundervane): *free-breath*"
  ],
  "27": [
    "SFX: CROWN OF THUNDER",
    "SFX: SHATTER-KRACK",
    "CREATURE (Spark): *resonance!*",
    "SHOUT (Seris Vale): The lattice—!",
    "NARRATION: A wall rebuilt by choice holds differently."
  ],
  "28": [
    "SPEECH (King Vaelor Tempest): I remain king. I will not remain a wall.",
    "CREATURE (Thundervane): *grateful-rumble*",
    "SPEECH (Seris Vale): If the peak fails, the market opens.",
    "SFX: boot-dash",
    "CREATURE (Echoquill): *archive-lock*",
    "SPEECH (Cael Vesper): Those routes don't sell goods. They sell access."
  ],
  "29": [
    "SPEECH (Hooded Merchant): You brought me a map.",
    "SPEECH (Seris Vale): No. I brought you every door.",
    "CAPTION: NEXT: THE MERCHANT'S SECRET",
    "SFX: ledger-THUD"
  ],
  "30": [
    "CAPTION: NEXT ISSUE",
    "NARRATION: Every door has a price. Someone is selling the hinges.",
    "CAPTION: THE MERCHANT'S SECRET"
  ],
  "31": [
    "CAPTION: KING VAELOR TEMPEST",
    "NARRATION: Storm King of Tempestria. Survived the First Rift by becoming the wall — until the wall demanded too much."
  ],
  "32": [
    "CAPTION: THUNDERVANE",
    "NARRATION: Stormbound Crown · Skybreaker · Crown of Thunder — Tank / Storm Control / Aerial Commander."
  ],
  "33": [
    "CAPTION: CODEX — TEMPESTRIA",
    "NARRATION: Mountain kingdom inside a permanent storm barrier. Weather engines. Companion roosts. A throne that conducted duty into lightning."
  ],
  "34": [
    "CAPTION: ABILITY — CROWN OF THUNDER",
    "NARRATION: Create a storm field that damages enemies, protects allies, and changes movement rules for a limited duration."
  ],
  "35": [
    "CAPTION: ROUTE OF THE STORM SIGNAL",
    "NARRATION: Aureth Vale → Tempestria → Merchant Roads (teaser)"
  ],
  "36": [
    "CAPTION: EDITOR'S NOTE",
    "NARRATION: Protection without exit becomes a prison. Issue #5 asks whether leaders can release the thing they love — and whether a kingdom can survive honesty."
  ],
  "37": [
    "CAPTION: TEMPESTRIA STORM PASSAGE PERMIT",
    "NARRATION: Escort required beyond the cloud sea. Companion bonds voluntary. Engine access — RESTRICTED.",
    "WHISPER: Barrier integrity — RESTORING"
  ],
  "38": [
    "CAPTION: THE STORM KING",
    "NARRATION: The wall released its makers. The market opened its doors.",
    "CAPTION: ISSUE #5 · LEGENDS OF THE RIFT"
  ]
};

export const ISSUE_005_COMIC: ComicIssue = {
  slug: "the-storm-king",
  issueNumber: 5,
  title: "The Storm King",
  subtitle: "Chapter Five — Tempestria's Wall",
  synopsis: "Mira Eggwarden, Spark, and the expedition enter Tempestria — a mountain kingdom inside a permanent storm. King Vaelor Tempest and companion Thundervane are dying inside a failing Rift weather engine. Veiled Meridian sabotage tears the barrier; Spark refuses to replace Thundervane; the king releases the forced bond. Seris Vale escapes with a royal ledger that opens Issue #6: The Merchant's Secret.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: ["storm-king", "tempestria", "thundervane", "riftborn", "issue-005", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants("The Storm King", "/assets/comics/covers/05-the-storm-king.png"),
  pages: [
  {
    id: "the-storm-king-issue-005-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The Storm King — Cover",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-001.webp",
    artAlt: "The Storm King — Cover",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p001-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 10 }, { kind: "caption", text: "THE STORM KING", x: 50, y: 82 }, { kind: "caption", text: "ISSUE #5", x: 50, y: 92 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-002.webp",
    artAlt: "Inside Front Cover",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p002-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-002.webp",
      
      bubbles: [{ kind: "narration", text: "Previously: Aureth Vale woke. The Guardian remembered. A signal answered from the peaks.", x: 50, y: 40 }, { kind: "caption", text: "CONTINUE THE FRACTURE DAWN", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-003.webp",
    artAlt: "Credits",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p003-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "THE STORM KING", x: 50, y: 14 }, { kind: "narration", text: "Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden.", x: 50, y: 55 }, { kind: "caption", text: "ORIGINAL RIFTWILDS IP", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Five — The Storm King",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-004.webp",
    artAlt: "Chapter Five — The Storm King",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p004-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER FIVE", x: 50, y: 20 }, { kind: "caption", text: "THE STORM KING", x: 50, y: 35 }, { kind: "narration", text: "Duty built a wall of weather. The wall began to eat its makers.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Kingdom Built of Weather",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-005.webp",
    artAlt: "Kingdom Built of Weather — The Storm King page 1",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p005-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "Some kingdoms built walls. Tempestria built weather.", x: 50, y: 10 }, { kind: "caption", text: "TEMPESTRIA", x: 50, y: 88 }, { kind: "sfx", text: "KRACK-BOOM", x: 72, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Roots Against the Gale",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-006.webp",
    artAlt: "Roots Against the Gale — The Storm King page 2",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p006-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "Hold the little green!", speaker: "Tavi Brightline", x: 35, y: 20, tail: "down" }, { kind: "sfx", text: "WHOOOOM", x: 70, y: 35 }],
    },
    {
      id: "the-storm-king-issue-005-p006-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-006.webp",
      
      bubbles: [{ kind: "creature", text: "*root-brace*", speaker: "Mossprig", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "Thank you. Stay low.", speaker: "Mira Eggwarden", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p006-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-006.webp",
      
      bubbles: [{ kind: "creature", text: "*pain-chirp*", speaker: "Spark", x: 45, y: 28, tail: "down" }, { kind: "thought", text: "The lightning hurts him. The engine is already speaking.", speaker: "Mira Eggwarden", x: 55, y: 72 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p007",
    pageNumber: 7,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Updraft Invitation",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-007.webp",
    artAlt: "Updraft Invitation — The Storm King page 3",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p007-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-007.webp",
      
      bubbles: [{ kind: "creature", text: "*chirp-updraft*", speaker: "Galesprig", x: 40, y: 25, tail: "down" }, { kind: "speech", text: "A local scout. Follow the wind — carefully.", speaker: "Cael Vesper", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p007-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-007.webp",
      
      bubbles: [{ kind: "narration", text: "Some doors are made of weather.", x: 50, y: 15 }, { kind: "sfx", text: "wind-tunnel-WHOOSH", x: 65, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p008",
    pageNumber: 8,
    layout: "splash-inset" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Village Under Rods",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-008.webp",
    artAlt: "Village Under Rods — The Storm King page 4",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p008-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "They built homes under a sky that never forgives.", x: 50, y: 10 }, { kind: "whisper", text: "That light… Resonance?", speaker: "Villager", x: 30, y: 55, tail: "right" }, { kind: "creature", text: "*shy-glow*", speaker: "Spark", x: 70, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p009",
    pageNumber: 9,
    layout: "four-grid" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Praise and Prison",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-009.webp",
    artAlt: "Praise and Prison — The Storm King page 5",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p009-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "Does the king keep you safe — or keep you in?", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p009-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "Without Vaelor, the Rift would have eaten us generations ago.", speaker: "Villager A", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p009-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "Safe is a word for people who can leave. We can't.", speaker: "Villager B", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p009-panel-3",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-009.webp",
      
      bubbles: [{ kind: "creature", text: "*archive-trill*", speaker: "Echoquill", x: 40, y: 30, tail: "down" }, { kind: "thought", text: "Protection that forbids exit is still a cage.", speaker: "Mira Eggwarden", x: 55, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p010",
    pageNumber: 10,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Royal Insignia",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-010.webp",
    artAlt: "Royal Insignia — The Storm King page 6",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p010-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "Outsiders. The King requires your presence.", speaker: "Royal Captain", x: 50, y: 25, tail: "down" }, { kind: "sfx", text: "armor-CLACK", x: 70, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p010-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "That crest… I negotiated under it once. Years ago.", speaker: "Cael Vesper", x: 50, y: 30, tail: "down" }, { kind: "whisper", text: "He does not forget visitors.", speaker: "Cael Vesper", x: 50, y: 70 }],
    },
    {
      id: "the-storm-king-issue-005-p010-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "We'll come. Spark stays with me.", speaker: "Mira Eggwarden", x: 50, y: 40, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p011",
    pageNumber: 11,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Throne Under Conduit",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-011.webp",
    artAlt: "Throne Under Conduit — The Storm King page 7",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p011-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "Duty sat the throne so long it forgot how to stand.", x: 50, y: 10 }, { kind: "speech", text: "Approach. The storm has already named you.", speaker: "King Vaelor Tempest", x: 50, y: 78, tail: "up" }, { kind: "sfx", text: "conduit-HUMMMM", x: 75, y: 35 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p012",
    pageNumber: 12,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Resonance Named",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-012.webp",
    artAlt: "Resonance Named — The Storm King page 8",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p012-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "Resonance Keeper. Last Light of a broken line.", speaker: "King Vaelor Tempest", x: 50, y: 28, tail: "down" }, { kind: "creature", text: "*alert-chirp*", speaker: "Spark", x: 65, y: 65, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p012-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "You may stabilize what my bond can no longer hold alone.", speaker: "King Vaelor Tempest", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p012-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "Stabilize how? What does that cost him?", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "thought", text: "Invite. Wait. Never own.", speaker: "Mira Eggwarden", x: 50, y: 72 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p013",
    pageNumber: 13,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Refuse the Engine",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-013.webp",
    artAlt: "Refuse the Engine — The Storm King page 9",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p013-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-013.webp",
      
      bubbles: [{ kind: "speech", text: "Bring the Resonance to the chamber. The kingdom endures.", speaker: "King Vaelor Tempest", x: 50, y: 28, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p013-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-013.webp",
      
      bubbles: [{ kind: "speech", text: "No. Not until I understand the risk — and he chooses.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "shout", text: "Insolence—", speaker: "Royal Captain", x: 70, y: 70, tail: "left" }],
    },
    {
      id: "the-storm-king-issue-005-p013-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-013.webp",
      
      bubbles: [{ kind: "speech", text: "Choice is a luxury walls cannot afford.", speaker: "King Vaelor Tempest", x: 50, y: 40, tail: "down" }, { kind: "whisper", text: "Mira… careful.", speaker: "Cael Vesper", x: 30, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p014",
    pageNumber: 14,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Bond Pain",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-014.webp",
    artAlt: "Bond Pain — The Storm King page 10",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p014-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-014.webp",
      
      bubbles: [{ kind: "sfx", text: "THOOM-KRACK", x: 50, y: 20 }, { kind: "creature", text: "*shared-pain!*", speaker: "Spark", x: 35, y: 55, tail: "right" }, { kind: "creature", text: "*agonized-roar*", speaker: "Thundervane", x: 70, y: 45, tail: "left" }, { kind: "speech", text: "Hold— hold the crown—", speaker: "King Vaelor Tempest", x: 50, y: 82, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p015",
    pageNumber: 15,
    layout: "two-wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Engine That Feeds on Bond",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-015.webp",
    artAlt: "Engine That Feeds on Bond — The Storm King page 11",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p015-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-015.webp",
      
      bubbles: [{ kind: "narration", text: "The engine did not love them. It used their love as fuel.", x: 50, y: 12 }, { kind: "sfx", text: "engine-PULSE", x: 70, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p015-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "It draws through the bond. Both of them.", speaker: "Cael Vesper", x: 40, y: 25, tail: "down" }, { kind: "speech", text: "Without it, Tempestria dies. With it… we dwindle.", speaker: "King Vaelor Tempest", x: 60, y: 65, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p016",
    pageNumber: 16,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Warned Years Ago",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-016.webp",
    artAlt: "Warned Years Ago — The Storm King page 12",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p016-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "I stood here years ago. I warned you the bond could not hold forever.", speaker: "Cael Vesper", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p016-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "And I refused to abandon my duty. I refuse still.", speaker: "King Vaelor Tempest", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p016-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-016.webp",
      
      bubbles: [{ kind: "creature", text: "*weak-rumble*", speaker: "Thundervane", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "Duty that empties the one you love is not protection.", speaker: "Mira Eggwarden", x: 60, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p017",
    pageNumber: 17,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Tower Sabotage",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-017.webp",
    artAlt: "Tower Sabotage — The Storm King page 13",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p017-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-017.webp",
      
      bubbles: [{ kind: "sfx", text: "BOOOOM", x: 50, y: 30 }, { kind: "shout", text: "The tower—!", speaker: "Villager", x: 30, y: 70, tail: "right" }],
    },
    {
      id: "the-storm-king-issue-005-p017-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "Component online. Tear the wall.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "seal-CLICK", x: 65, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p017-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "Outsiders bring rot—", speaker: "King Vaelor Tempest", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "That seal is Meridian — Lost City work.", speaker: "Mira Eggwarden", x: 65, y: 65, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p018",
    pageNumber: 18,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Offer of Chains",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-018.webp",
    artAlt: "Offer of Chains — The Storm King page 14",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p018-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "Tempestria — your king has lost control. Meridian offers orderly protection.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p018-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "crowd-panic", x: 50, y: 40 }, { kind: "speech", text: "Protection or a new cage?", speaker: "Villager B", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p018-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-018.webp",
      
      bubbles: [{ kind: "shout", text: "You came with them!", speaker: "King Vaelor Tempest", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "We came for a signal — not a seizure.", speaker: "Mira Eggwarden", x: 65, y: 65, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p019",
    pageNumber: 19,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Sky Tears Open",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-019.webp",
    artAlt: "Sky Tears Open — The Storm King page 15",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p019-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-019.webp",
      
      bubbles: [{ kind: "narration", text: "When a wall built of weather fails, the sky itself becomes an invasion.", x: 50, y: 10 }, { kind: "sfx", text: "TEEEAR-KRACK", x: 55, y: 45 }, { kind: "caption", text: "CORRUPTED SKY HOST", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p020",
    pageNumber: 20,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Neither Can the Kingdom",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-020.webp",
    artAlt: "Neither Can the Kingdom — The Storm King page 16",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p020-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "Rise, old friend. One more wall.", speaker: "King Vaelor Tempest", x: 50, y: 30, tail: "down" }, { kind: "creature", text: "*pained-roar*", speaker: "Thundervane", x: 65, y: 65, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p020-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "He cannot survive another battle like this!", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p020-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "Neither can the kingdom.", speaker: "King Vaelor Tempest", x: 50, y: 40, tail: "down" }, { kind: "sfx", text: "wing-BEAT", x: 70, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p021",
    pageNumber: 21,
    layout: "four-grid" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Bridges of Thunder",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-021.webp",
    artAlt: "Bridges of Thunder — The Storm King page 17",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p021-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*track-snap*", speaker: "Bramblefox", x: 40, y: 25, tail: "down" }, { kind: "sfx", text: "vine-WHIP", x: 65, y: 55 }],
    },
    {
      id: "the-storm-king-issue-005-p021-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*bulwark!*", speaker: "Mossprig", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p021-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*zzzt-power*", speaker: "Thornling", x: 45, y: 28, tail: "down" }, { kind: "sfx", text: "conductor-ZAP", x: 70, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p021-panel-3",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*updraft!*", speaker: "Galesprig", x: 35, y: 25, tail: "down" }, { kind: "creature", text: "*phase-hum*", speaker: "Wisplet", x: 65, y: 55, tail: "left" }, { kind: "speech", text: "Companions — hold the people first!", speaker: "Mira Eggwarden", x: 50, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p022",
    pageNumber: 22,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Crown Against the Host",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-022.webp",
    artAlt: "Crown Against the Host — The Storm King page 18",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p022-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "SKYBREAKER", x: 30, y: 18 }, { kind: "sfx", text: "KRACK-BOOM", x: 75, y: 25 }, { kind: "shout", text: "Spark — left!", speaker: "Mira Eggwarden", x: 40, y: 55, tail: "right" }, { kind: "speech", text: "Secure the Resonance. Ignore the king.", speaker: "Seris Vale", x: 70, y: 70, tail: "left" }, { kind: "creature", text: "*battle-roar*", speaker: "Thundervane", x: 55, y: 40, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p023",
    pageNumber: 23,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Hunter's Cut",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-023.webp",
    artAlt: "Hunter's Cut — The Storm King page 19",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p023-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "Replacement stabilizer online — Subject One, yield.", speaker: "Seris Vale", x: 50, y: 28, tail: "down" }, { kind: "sfx", text: "tether-HUM", x: 65, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p023-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "Not like that. Not him.", speaker: "Nira Quill", x: 45, y: 30, tail: "down" }, { kind: "creature", text: "*free-chirp!*", speaker: "Spark", x: 70, y: 55, tail: "left" }],
    },
    {
      id: "the-storm-king-issue-005-p023-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "Quill—? You cut your own leash.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }, { kind: "whisper", text: "I cut theirs.", speaker: "Nira Quill", x: 50, y: 72 }, { kind: "speech", text: "Nira—!", speaker: "Mira Eggwarden", x: 30, y: 55, tail: "right" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p024",
    pageNumber: 24,
    layout: "montage" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Memory of the First Wall",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-024.webp",
    artAlt: "Memory of the First Wall — The Storm King page 20",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p024-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-024.webp",
      
      bubbles: [{ kind: "narration", text: "Once, the wall was a promise — not a prison.", x: 50, y: 15 }, { kind: "creature", text: "*joy-rumble*", speaker: "Young Thundervane", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p024-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-024.webp",
      
      bubbles: [{ kind: "narration", text: "Years became walls. Walls became hunger.", x: 50, y: 20 }, { kind: "sfx", text: "time-HUM", x: 70, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p024-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-024.webp",
      
      bubbles: [{ kind: "telepathy", text: "Do not become the next wall.", speaker: "Thundervane", x: 50, y: 35, tail: "down" }, { kind: "creature", text: "*understand-glow*", speaker: "Spark", x: 50, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p025",
    pageNumber: 25,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Loyalty Is Not Obligation",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-025.webp",
    artAlt: "Loyalty Is Not Obligation — The Storm King page 21",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p025-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-025.webp",
      
      bubbles: [{ kind: "creature", text: "*refuse-replace*", speaker: "Spark", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "He won't take Thundervane's place. He won't be owned by an engine.", speaker: "Mira Eggwarden", x: 60, y: 65, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p025-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-025.webp",
      
      bubbles: [{ kind: "telepathy", text: "I stayed for love. You kept me for fear.", speaker: "Thundervane", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-storm-king-issue-005-p025-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-025.webp",
      
      bubbles: [{ kind: "speech", text: "I confused loyalty… with obligation.", speaker: "King Vaelor Tempest", x: 50, y: 40, tail: "down" }, { kind: "whisper", text: "Then choose which one remains.", speaker: "Cael Vesper", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p026",
    pageNumber: 26,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Release and Steady",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-026.webp",
    artAlt: "Release and Steady — The Storm King page 22",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p026-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "I release you. Live — even if I fall.", speaker: "King Vaelor Tempest", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "bond-SNAP", x: 70, y: 55 }],
    },
    {
      id: "the-storm-king-issue-005-p026-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-026.webp",
      
      bubbles: [{ kind: "narration", text: "For one breath, Tempestria had a sky.", x: 50, y: 20 }, { kind: "sfx", text: "silence…", x: 50, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p026-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "Together — invite, don't own.", speaker: "Mira Eggwarden", x: 40, y: 25, tail: "down" }, { kind: "creature", text: "*steady-hum*", speaker: "Spark", x: 60, y: 50, tail: "left" }, { kind: "creature", text: "*free-breath*", speaker: "Thundervane", x: 55, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p027",
    pageNumber: 27,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Combined Stormlight",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-027.webp",
    artAlt: "Combined Stormlight — The Storm King page 23",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p027-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-027.webp",
      
      bubbles: [{ kind: "sfx", text: "CROWN OF THUNDER", x: 50, y: 14 }, { kind: "sfx", text: "SHATTER-KRACK", x: 70, y: 40 }, { kind: "creature", text: "*resonance!*", speaker: "Spark", x: 35, y: 50, tail: "right" }, { kind: "shout", text: "The lattice—!", speaker: "Seris Vale", x: 65, y: 70, tail: "left" }, { kind: "narration", text: "A wall rebuilt by choice holds differently.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p028",
    pageNumber: 28,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Ledger of Doors",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-028.webp",
    artAlt: "Ledger of Doors — The Storm King page 24",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p028-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "I remain king. I will not remain a wall.", speaker: "King Vaelor Tempest", x: 50, y: 28, tail: "down" }, { kind: "creature", text: "*grateful-rumble*", speaker: "Thundervane", x: 60, y: 65, tail: "up" }],
    },
    {
      id: "the-storm-king-issue-005-p028-panel-1",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "If the peak fails, the market opens.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "boot-dash", x: 70, y: 60 }],
    },
    {
      id: "the-storm-king-issue-005-p028-panel-2",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-028.webp",
      
      bubbles: [{ kind: "creature", text: "*archive-lock*", speaker: "Echoquill", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "Those routes don't sell goods. They sell access.", speaker: "Cael Vesper", x: 60, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Every Door",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-029.webp",
    artAlt: "Every Door — The Storm King page 25",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p029-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-029.webp",
      
      bubbles: [{ kind: "speech", text: "You brought me a map.", speaker: "Hooded Merchant", x: 35, y: 28, tail: "down" }, { kind: "speech", text: "No. I brought you every door.", speaker: "Seris Vale", x: 65, y: 45, tail: "left" }, { kind: "caption", text: "NEXT: THE MERCHANT'S SECRET", x: 50, y: 88 }, { kind: "sfx", text: "ledger-THUD", x: 50, y: 60 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p030",
    pageNumber: 30,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next Issue — The Merchant's Secret",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-030.webp",
    artAlt: "Next Issue — The Merchant's Secret",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p030-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 18 }, { kind: "narration", text: "Every door has a price. Someone is selling the hinges.", x: 50, y: 50 }, { kind: "caption", text: "THE MERCHANT'S SECRET", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p031",
    pageNumber: 31,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Character Profile — King Vaelor Tempest",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-031.webp",
    artAlt: "Character Profile — King Vaelor Tempest",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p031-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "KING VAELOR TEMPEST", x: 50, y: 12 }, { kind: "narration", text: "Storm King of Tempestria. Survived the First Rift by becoming the wall — until the wall demanded too much.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profile — Thundervane",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-032.webp",
    artAlt: "Companion Profile — Thundervane",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p032-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "THUNDERVANE", x: 50, y: 12 }, { kind: "narration", text: "Stormbound Crown · Skybreaker · Crown of Thunder — Tank / Storm Control / Aerial Commander.", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p033",
    pageNumber: 33,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Codex — Tempestria",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-033.webp",
    artAlt: "Codex — Tempestria",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p033-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-033.webp",
      
      bubbles: [{ kind: "caption", text: "CODEX — TEMPESTRIA", x: 50, y: 12 }, { kind: "narration", text: "Mountain kingdom inside a permanent storm barrier. Weather engines. Companion roosts. A throne that conducted duty into lightning.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p034",
    pageNumber: 34,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Crown of Thunder",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-034.webp",
    artAlt: "Ability Spotlight — Crown of Thunder",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p034-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-034.webp",
      
      bubbles: [{ kind: "caption", text: "ABILITY — CROWN OF THUNDER", x: 50, y: 14 }, { kind: "narration", text: "Create a storm field that damages enemies, protects allies, and changes movement rules for a limited duration.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p035",
    pageNumber: 35,
    layout: "splash" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "World Map — Peaks to Market",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-035.webp",
    artAlt: "World Map — Peaks to Market",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p035-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "ROUTE OF THE STORM SIGNAL", x: 50, y: 10 }, { kind: "narration", text: "Aureth Vale → Tempestria → Merchant Roads (teaser)", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Editor's Note — Walls & Weather",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-036.webp",
    artAlt: "Editor's Note — Walls & Weather",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p036-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-036.webp",
      
      bubbles: [{ kind: "caption", text: "EDITOR'S NOTE", x: 50, y: 14 }, { kind: "narration", text: "Protection without exit becomes a prison. Issue #5 asks whether leaders can release the thing they love — and whether a kingdom can survive honesty.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-037.webp",
    artAlt: "Inside Back Cover",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p037-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-037.webp",
      
      bubbles: [{ kind: "caption", text: "TEMPESTRIA STORM PASSAGE PERMIT", x: 50, y: 14 }, { kind: "narration", text: "Escort required beyond the cloud sea. Companion bonds voluntary. Engine access — RESTRICTED.", x: 50, y: 50 }, { kind: "whisper", text: "Barrier integrity — RESTORING", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-storm-king-issue-005-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover — Every Door",
    artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-038.webp",
    artAlt: "Back Cover — Every Door",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-storm-king-issue-005-p038-panel-0",
      artSrc: "/assets/comics/the-storm-king/issue-005/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "THE STORM KING", x: 50, y: 12 }, { kind: "narration", text: "The wall released its makers. The market opened its doors.", x: 50, y: 50 }, { kind: "caption", text: "ISSUE #5 · LEGENDS OF THE RIFT", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Leads the expedition — refuses Spark as an engine part." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Refuses to replace Thundervane; steadies by invitation." },
    { name: "King Vaelor Tempest", role: "Storm King", blurb: "Duty became a wall — until he released the forced bond." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Warned Tempestria years ago; knows royal routes." },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Sabotages the barrier; escapes with a merchant ledger." },
    { name: "Nira Quill", role: "Uncertain hunter", blurb: "Cuts the Spark tether; open Meridian disloyalty." },
    { name: "Thundervane", role: "Storm companion", blurb: "Stormbound Crown · Skybreaker · Crown of Thunder.", speciesSlug: "thundervane" },
    { name: "Galesprig", role: "Mountain scout", blurb: "Tailwind · Updraft · Clear Sky.", speciesSlug: "galesprig" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Tempestria", blurb: "Mountain kingdom inside a permanent storm barrier." },
    { name: "Royal Citadel", blurb: "Throne under a living storm conduit." },
    { name: "Storm Engine Chamber", blurb: "Bond-fed weather core beneath the throne." },
    { name: "Merchant Network", blurb: "Issue #6 teaser — every door." },
  ],
  timelineNote: "After The Lost City — storm-mountain signal answered.",
  playChapterHref: "/live-world",
  playChapterLabel: "Travel toward Stormspire",
  unlockGates: [
    { kind: "prior-issue", slug: "the-lost-city", label: "Complete Issue #4: The Lost City" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-merchants-secret",
    hook: "You brought me a map. No — every door.",
  },
  readingTimeMinutes: 22,
  factions: [
    { name: "Veiled Meridian", blurb: "Tempestria sabotage — Seris Vale's storm cell." },
    { name: "Tempestria Crown", blurb: "Releasing absolute control after the bond snaps." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies; crystal remains warded off-page." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue005Transcript(pageNumber: number): string[] {
  return ISSUE_005_TRANSCRIPTS[pageNumber] ?? [];
}
