/**
 * Authoritative emote catalog — original IP, family-friendly, cosmetic only.
 */

import type { EmoteDef } from "@/game/live-world/systems/emotes/types";

const icon = (key: string) => `/assets/game/emotes/icons/${key}.png`;
const preview = (key: string) => `/assets/game/emotes/previews/${key}.png`;
const audio = (key: string) => `/assets/game/emotes/audio/${key}.ogg`;

function def(
  partial: Omit<EmoteDef, "iconPath" | "previewPath" | "audioStub"> & {
    audioStub?: string;
  },
): EmoteDef {
  return {
    ...partial,
    iconPath: icon(partial.key),
    previewPath: preview(partial.key),
    audioStub: partial.audioStub ?? audio(partial.key),
  };
}

/** Starter free solo + signal set — always unlocked. */
export const STARTER_EMOTE_KEYS = [
  "wave",
  "hello",
  "nod",
  "bow",
  "cheer",
  "clap",
  "laugh",
  "shrug",
  "think",
  "salute",
  "point",
  "sit",
  "dance",
  "celebrate",
  "ready",
  "not_ready",
  "thanks",
  "sorry",
] as const;

export const EMOTE_CATALOG: EmoteDef[] = [
  def({
    key: "wave",
    label: "Wave",
    description: "A friendly overworld wave.",
    category: "greeting",
    kind: "solo",
    tier: "free",
    animationKey: "emote_wave",
    durationMs: 1800,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "👋",
    unlockHint: "Default",
    tags: ["greeting", "safe"],
    aliases: ["hi"],
  }),
  def({
    key: "hello",
    label: "Hello",
    description: "Bright hello gesture with a soft nod.",
    category: "greeting",
    kind: "solo",
    tier: "free",
    animationKey: "emote_hello",
    durationMs: 1600,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "✨",
    unlockHint: "Default",
    tags: ["greeting", "safe"],
  }),
  def({
    key: "nod",
    label: "Nod",
    description: "Simple yes / acknowledgement.",
    category: "reaction",
    kind: "solo",
    tier: "free",
    animationKey: "emote_nod",
    durationMs: 900,
    cooldownMs: 800,
    requiresConsent: false,
    glyph: "🙂",
    unlockHint: "Default",
    tags: ["reaction", "safe"],
    aliases: ["yes"],
  }),
  def({
    key: "bow",
    label: "Keeper Bow",
    description: "Respectful keepers' bow.",
    category: "greeting",
    kind: "solo",
    tier: "free",
    animationKey: "emote_bow",
    durationMs: 2000,
    cooldownMs: 1500,
    requiresConsent: false,
    glyph: "🙇",
    unlockHint: "Default",
    tags: ["greeting", "safe"],
  }),
  def({
    key: "cheer",
    label: "Cheer",
    description: "Arms up celebration.",
    category: "celebration",
    kind: "solo",
    tier: "free",
    animationKey: "emote_cheer",
    durationMs: 2000,
    cooldownMs: 1500,
    requiresConsent: false,
    glyph: "🎉",
    unlockHint: "Default",
    tags: ["celebration", "safe"],
  }),
  def({
    key: "clap",
    label: "Clap",
    description: "Encouraging applause.",
    category: "celebration",
    kind: "solo",
    tier: "free",
    animationKey: "emote_clap",
    durationMs: 1600,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "👏",
    unlockHint: "Default",
    tags: ["celebration", "safe"],
  }),
  def({
    key: "laugh",
    label: "Laugh",
    description: "Light-hearted laugh.",
    category: "reaction",
    kind: "solo",
    tier: "free",
    animationKey: "emote_laugh",
    durationMs: 1800,
    cooldownMs: 1400,
    requiresConsent: false,
    glyph: "😄",
    unlockHint: "Default",
    tags: ["reaction", "safe"],
  }),
  def({
    key: "shrug",
    label: "Shrug",
    description: "Not sure — friendly shrug.",
    category: "reaction",
    kind: "solo",
    tier: "free",
    animationKey: "emote_shrug",
    durationMs: 1400,
    cooldownMs: 1000,
    requiresConsent: false,
    glyph: "🤷",
    unlockHint: "Default",
    tags: ["reaction", "safe"],
  }),
  def({
    key: "think",
    label: "Think",
    description: "Pondering pose.",
    category: "stance",
    kind: "solo",
    tier: "free",
    animationKey: "emote_think",
    durationMs: 2200,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "💭",
    unlockHint: "Default",
    tags: ["stance", "safe"],
  }),
  def({
    key: "salute",
    label: "Salute",
    description: "Crisp keepers' salute.",
    category: "greeting",
    kind: "solo",
    tier: "free",
    animationKey: "emote_salute",
    durationMs: 1500,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "🫡",
    unlockHint: "Default",
    tags: ["greeting", "safe"],
  }),
  def({
    key: "point",
    label: "Point",
    description: "Point toward something interesting.",
    category: "signal",
    kind: "solo",
    tier: "free",
    animationKey: "emote_point",
    durationMs: 1400,
    cooldownMs: 1000,
    requiresConsent: false,
    glyph: "👉",
    unlockHint: "Default",
    tags: ["signal", "safe"],
  }),
  def({
    key: "sit",
    label: "Sit",
    description: "Rest on the plaza for a moment.",
    category: "stance",
    kind: "solo",
    tier: "free",
    animationKey: "emote_sit",
    durationMs: 4000,
    cooldownMs: 2000,
    requiresConsent: false,
    glyph: "🪑",
    unlockHint: "Default",
    tags: ["stance", "safe"],
  }),
  def({
    key: "dance",
    label: "Dance",
    description: "Solo celebratory dance — cosmetic only.",
    category: "celebration",
    kind: "solo",
    tier: "free",
    animationKey: "emote_dance",
    durationMs: 3200,
    cooldownMs: 2500,
    requiresConsent: false,
    glyph: "💃",
    unlockHint: "Default",
    tags: ["celebration", "safe"],
  }),
  def({
    key: "celebrate",
    label: "Celebrate",
    description: "Spark burst celebration.",
    category: "celebration",
    kind: "solo",
    tier: "free",
    animationKey: "emote_celebrate",
    durationMs: 2200,
    cooldownMs: 1800,
    requiresConsent: false,
    glyph: "🌟",
    unlockHint: "Default",
    tags: ["celebration", "safe"],
  }),
  def({
    key: "ready",
    label: "Ready",
    description: "Signal you are ready.",
    category: "signal",
    kind: "solo",
    tier: "free",
    animationKey: "emote_ready",
    durationMs: 1400,
    cooldownMs: 1500,
    requiresConsent: false,
    glyph: "✅",
    unlockHint: "Default",
    tags: ["signal", "safe", "ping"],
    aliases: ["rdy"],
  }),
  def({
    key: "not_ready",
    label: "Not Ready",
    description: "Signal you need a moment.",
    category: "signal",
    kind: "solo",
    tier: "free",
    animationKey: "emote_not_ready",
    durationMs: 1400,
    cooldownMs: 1500,
    requiresConsent: false,
    glyph: "⏳",
    unlockHint: "Default",
    tags: ["signal", "safe", "ping"],
    aliases: ["wait"],
  }),
  def({
    key: "thanks",
    label: "Thanks",
    description: "Grateful gesture.",
    category: "reaction",
    kind: "solo",
    tier: "free",
    animationKey: "emote_thanks",
    durationMs: 1600,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "🙏",
    unlockHint: "Default",
    tags: ["reaction", "safe"],
    aliases: ["ty"],
  }),
  def({
    key: "sorry",
    label: "Sorry",
    description: "Apologetic bowlet.",
    category: "reaction",
    kind: "solo",
    tier: "free",
    animationKey: "emote_sorry",
    durationMs: 1600,
    cooldownMs: 1200,
    requiresConsent: false,
    glyph: "😔",
    unlockHint: "Default",
    tags: ["reaction", "safe"],
  }),

  // Quick pings (rate-limited separately)
  def({
    key: "ping_follow",
    label: "Follow Me",
    description: "Quick ping — follow this way.",
    category: "ping",
    kind: "ping",
    tier: "free",
    animationKey: "emote_ping_follow",
    durationMs: 2000,
    cooldownMs: 4000,
    requiresConsent: false,
    glyph: "➡️",
    unlockHint: "Default",
    tags: ["ping", "safe"],
    aliases: ["follow"],
  }),
  def({
    key: "ping_help",
    label: "Help",
    description: "Quick ping — need a hand.",
    category: "ping",
    kind: "ping",
    tier: "free",
    animationKey: "emote_ping_help",
    durationMs: 2000,
    cooldownMs: 5000,
    requiresConsent: false,
    glyph: "❗",
    unlockHint: "Default",
    tags: ["ping", "safe"],
    aliases: ["help"],
  }),
  def({
    key: "ping_look",
    label: "Look Here",
    description: "Quick ping — check this out.",
    category: "ping",
    kind: "ping",
    tier: "free",
    animationKey: "emote_ping_look",
    durationMs: 1800,
    cooldownMs: 3500,
    requiresConsent: false,
    glyph: "👀",
    unlockHint: "Default",
    tags: ["ping", "safe"],
  }),
  def({
    key: "ping_danger",
    label: "Caution",
    description: "Quick ping — be careful (cosmetic warning).",
    category: "ping",
    kind: "ping",
    tier: "free",
    animationKey: "emote_ping_danger",
    durationMs: 2000,
    cooldownMs: 5000,
    requiresConsent: false,
    glyph: "⚠️",
    unlockHint: "Default",
    tags: ["ping", "safe"],
  }),

  // Synchronized social — consent required
  def({
    key: "handshake",
    label: "Handshake",
    description: "Mutual handshake — both players must accept.",
    category: "social",
    kind: "social",
    tier: "free",
    animationKey: "emote_handshake",
    durationMs: 2800,
    cooldownMs: 4000,
    requiresConsent: true,
    glyph: "🤝",
    unlockHint: "Default",
    tags: ["social", "consent", "safe"],
  }),
  def({
    key: "high_five",
    label: "High Five",
    description: "Mutual high-five — consent required.",
    category: "social",
    kind: "social",
    tier: "free",
    animationKey: "emote_high_five",
    durationMs: 2200,
    cooldownMs: 3500,
    requiresConsent: true,
    glyph: "🖐️",
    unlockHint: "Default",
    tags: ["social", "consent", "safe"],
  }),
  def({
    key: "hug",
    label: "Hug",
    description: "Friendly hug — consent required. Family-safe only.",
    category: "social",
    kind: "social",
    tier: "free",
    animationKey: "emote_hug",
    durationMs: 3000,
    cooldownMs: 5000,
    requiresConsent: true,
    glyph: "🤗",
    unlockHint: "Default",
    tags: ["social", "consent", "safe"],
  }),
  def({
    key: "fist_bump",
    label: "Fist Bump",
    description: "Mutual fist bump — consent required.",
    category: "social",
    kind: "social",
    tier: "free",
    animationKey: "emote_fist_bump",
    durationMs: 2000,
    cooldownMs: 3000,
    requiresConsent: true,
    glyph: "👊",
    unlockHint: "Default",
    tags: ["social", "consent", "safe"],
  }),
  def({
    key: "sync_dance",
    label: "Sync Dance",
    description: "Paired dance — both must consent. Cosmetic only.",
    category: "social",
    kind: "social",
    tier: "free",
    animationKey: "emote_sync_dance",
    durationMs: 4000,
    cooldownMs: 6000,
    requiresConsent: true,
    glyph: "🪩",
    unlockHint: "Default",
    tags: ["social", "consent", "safe", "celebration"],
  }),

  // Credits unlockable cosmetics (no gameplay advantage)
  def({
    key: "rift_spark",
    label: "Rift Spark",
    description: "Cosmetic spark flourish. No combat or economy bonus.",
    category: "celebration",
    kind: "solo",
    tier: "credits",
    animationKey: "emote_spark",
    durationMs: 2400,
    cooldownMs: 2000,
    requiresConsent: false,
    glyph: "⚡",
    unlockHint: "Unlock with Credits",
    creditsCost: 250,
    tags: ["celebration", "safe", "cosmetic"],
  }),
  def({
    key: "bloom_twirl",
    label: "Bloom Twirl",
    description: "Festival twirl — purely cosmetic.",
    category: "celebration",
    kind: "solo",
    tier: "credits",
    animationKey: "emote_bloom_twirl",
    durationMs: 2600,
    cooldownMs: 2200,
    requiresConsent: false,
    glyph: "🌸",
    unlockHint: "Unlock with Credits",
    creditsCost: 400,
    tags: ["celebration", "safe", "cosmetic"],
  }),
  def({
    key: "keeper_flourish",
    label: "Keeper Flourish",
    description: "Premium cosmetic flourish — clearly labeled, no power.",
    category: "celebration",
    kind: "solo",
    tier: "premium_cosmetic",
    animationKey: "emote_keeper_flourish",
    durationMs: 2800,
    cooldownMs: 2500,
    requiresConsent: false,
    glyph: "💠",
    unlockHint: "Premium cosmetic (no advantages)",
    creditsCost: 800,
    tags: ["celebration", "safe", "cosmetic", "premium"],
  }),
];

const byKey = new Map(EMOTE_CATALOG.map((e) => [e.key, e]));
const byAlias = new Map<string, EmoteDef>();
for (const e of EMOTE_CATALOG) {
  byAlias.set(e.key, e);
  for (const a of e.aliases ?? []) byAlias.set(a.toLowerCase(), e);
}

export function getEmoteDef(key: string): EmoteDef | undefined {
  return byKey.get(key) ?? byAlias.get(key.toLowerCase());
}

export function resolveEmoteKey(raw: string): string | null {
  const def = getEmoteDef(raw.trim().toLowerCase().replace(/\s+/g, "_"));
  return def?.key ?? null;
}

export function listEmotes(filter?: {
  kind?: EmoteDef["kind"];
  tier?: EmoteDef["tier"];
  starterOnly?: boolean;
}): EmoteDef[] {
  return EMOTE_CATALOG.filter((e) => {
    if (filter?.kind && e.kind !== filter.kind) return false;
    if (filter?.tier && e.tier !== filter.tier) return false;
    if (filter?.starterOnly && !STARTER_EMOTE_KEYS.includes(e.key as (typeof STARTER_EMOTE_KEYS)[number])) {
      return false;
    }
    return true;
  });
}

export function defaultWheelSlots(): (string | null)[] {
  return ["wave", "hello", "nod", "cheer", "dance", "ready", "thanks", "salute"];
}

/** Legacy stub shape for social hub. */
export function emoteCatalogForSocialStub() {
  return EMOTE_CATALOG.filter((e) => e.kind === "solo").slice(0, 8).map((e) => ({
    key: e.key,
    label: e.label,
    animationKey: e.animationKey,
    unlockHint: e.unlockHint,
  }));
}
