export * from "@/lib/social/types";
export * from "@/lib/social/rules";
export * from "@/lib/social/sanitize";
export {
  listAvailableAvatars,
  listPetAvatarOptions,
  listSpeciesAvatarOptions,
  listCharacterAvatarOptions,
  listBrandAvatarOptions,
  setSocialAvatar,
  parseAvatarKey,
  petAvatarKey,
  speciesAvatarKey,
  npcAvatarKey,
  loreAvatarKey,
  brandAvatarKey,
  STARTER_RIFTLING_AVATAR_SLUGS,
  STARTER_CHARACTER_NPC_SLUGS,
  STARTER_LORE_AVATAR_IDS,
  isStarterRiftlingAvatarSlug,
  isStarterCharacterNpcSlug,
  isStarterLoreAvatarId,
} from "@/lib/social/avatars";
export type {
  SocialAvatarCatalog,
  SocialAvatarKind,
  SocialAvatarOption,
  SocialAvatarSection,
  SetAvatarInput,
} from "@/lib/social/avatars";
export {
  listRiftlingAvatarSlugs,
  isRiftlingAvatarSlug,
  isFreeStarterAvatarSlug,
  evaluateSpeciesAvatarUnlock,
  evaluateCharacterAvatarUnlock,
  purchaseSpeciesAvatarWithCredits,
  purchaseSpeciesAvatarWithSol,
  purchaseCharacterAvatarWithCredits,
  purchaseCharacterAvatarWithSol,
  grantSpeciesAvatarUnlock,
  grantAvatarUnlockKey,
  avatarUnlockSummary,
  creditsPriceForSpecies,
  solPriceForSpecies,
  characterAvatarRarity,
  creditsPriceForCharacterRarity,
  solPriceForCharacterRarity,
  AVATAR_CREDITS_BY_RARITY,
  AVATAR_SOL_BY_RARITY,
} from "@/lib/social/avatar-unlocks";
export type {
  AvatarTaskProgress,
  AvatarUnlockPaths,
  AvatarUnlockEval,
} from "@/lib/social/avatar-unlocks";
export {
  resetSocialStoreForTests,
  ensureSystemKeepersSeeded,
  getSocialStore,
} from "@/lib/social/store";
export {
  ensureSocialProfile,
  setDisplayName,
  setHandle,
  setMessagePrivacy,
  getAvatarCatalog,
  setAvatar,
  resolveOwnerByHandle,
  areFriends,
  isBlockedEitherWay,
  sendFriendRequest,
  acceptFriendRequest,
  declineFriendRequest,
  removeFriend,
  blockPlayer,
  unblockPlayer,
  reportPlayer,
  sendPrivateMessage,
  listThreadMessages,
  markThreadRead,
  listFriends,
  listFriendRequests,
  listDmThreads,
  getSocialSummary,
  getSocialHubData,
  partyInviteStub,
} from "@/lib/social/service";
