/* AUTO-GENERATED by scripts/comics/emit-issue-004-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_004_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: RIFTWILDS",
    "CAPTION: THE LOST CITY",
    "CAPTION: ISSUE #4"
  ],
  "2": [
    "CAPTION: Riftwilds Comic Publishing — original fantasy. Free to read.",
    "NARRATION: Credits & cosmetics may unlock along the way. The story itself stays free."
  ],
  "3": [
    "CAPTION: Story · Riftwilds Lore Desk",
    "CAPTION: Art · Grok + Publishing Engine",
    "CAPTION: Lettering · Programmatic Bake",
    "NARRATION: Canon: World Codex · Riftling Codex · Legends of the Rift TCG. Keeper: Mira Eggwarden."
  ],
  "4": [
    "CAPTION: CHAPTER FOUR",
    "CAPTION: THE LOST CITY",
    "NARRATION: Aureth Vale wakes. The Guardian remembers. The Meridian arrives."
  ],
  "5": [
    "NARRATION: A city can disappear from maps. It is harder to disappear from memory.",
    "CAPTION: AURETH VALE",
    "SFX: distant-HUMMM"
  ],
  "6": [
    "SPEECH (Tavi Brightline): Roads still argue with themselves.",
    "SFX: stone-slide",
    "SPEECH (Cael Vesper): Outskirts forgive guests. The inner stage never returned its players.",
    "CREATURE (Spark): *…pulse…?*",
    "WHISPER (Mira Eggwarden): I hear it too. Soft. Old."
  ],
  "7": [
    "SFX: GRIND-AWAKEN",
    "SPEECH (Mira Eggwarden): Nobody touched it.",
    "NARRATION: The city does not ask names. It remembers them.",
    "CREATURE (Spark): *soft yip*",
    "SFX: stone-turn…"
  ],
  "8": [
    "NARRATION: They left mid-errand. Mid-laugh. Mid-promise.",
    "SPEECH (Mira Eggwarden): We annotate. We don't loot memory.",
    "CREATURE (Bramblefox): *low rrk*",
    "WHISPER (Tavi Brightline): Someone else already walked this quiet.",
    "SFX: water-upward hush"
  ],
  "9": [
    "CREATURE (Thornling): *poke-poke!*",
    "SPEECH (Mira Eggwarden): Thornling— wait—",
    "SFX: WHOOM-RING",
    "CREATURE (Lumenhare): *fwip!*",
    "NARRATION: The city decides how deep guests go."
  ],
  "10": [
    "SPEECH (Cael Vesper): Training halls. Nest cradles. Stages without audiences.",
    "SFX: rail-HUM",
    "CREATURE (Spark): *…empty…*",
    "WHISPER (Mira Eggwarden): Not empty. Waiting."
  ],
  "11": [
    "NARRATION: The street remembers footsteps the stone forgot to keep.",
    "CREATURE (Wisplet): *soft chime*",
    "SPEECH (Mira Eggwarden): Don't chase them. Let them pass."
  ],
  "12": [
    "MAGIC (Memory Echo): Hold the network. Hold the cradles.",
    "SFX: memory-static",
    "NARRATION: They called the little lights Resonance Keepers — before crowns renamed everything.",
    "CREATURE (Spark): *afraid chirp*",
    "SPEECH (Mira Eggwarden): You don't have to watch if it hurts."
  ],
  "13": [
    "NARRATION: Cradles without breath. Names without voices.",
    "WHISPER (Mira Eggwarden): I'm here when you look back.",
    "CREATURE (Echoquill): *archive-trill*",
    "SFX: memory-shimmer",
    "CREATURE (Spark): *curious chirp*"
  ],
  "14": [
    "CAPTION: CLASS: RESONANCE KEEPERS",
    "NARRATION: Trained — or born — to steady the engines that held the First Tear's roads.",
    "SPEECH (Cael Vesper): The circus… moved lights like these. Quietly. For longer than I admitted.",
    "THOUGHT (Mira Eggwarden): History wrote a job description. Spark didn't sign it."
  ],
  "15": [
    "CREATURE (Spark): *distress pulse*",
    "SFX: PULSE-STUTTER",
    "SPEECH (Mira Eggwarden): History can name a use. It doesn't own your choice.",
    "NARRATION: Some roads are lit by lanterns that refuse to name their fuel.",
    "CREATURE (Lumenhare): *soft thump*"
  ],
  "16": [
    "SPEECH (Mira Eggwarden): How long has Lanternveil moved Resonance Keepers?",
    "SPEECH (Cael Vesper): Generations. Between safe stages. We hid lights from nets — not for sale.",
    "SPEECH (Cael Vesper): We did not know this one survived the Soft Exodus roads.",
    "WHISPER (Mira Eggwarden): Then stop performing. Help us keep it free."
  ],
  "17": [
    "WHISPER (Meridian Agent): Seal accepted. Quiet feet.",
    "SFX: seal-click",
    "SPEECH (Seris Vale): Control is not cruelty. Another Tear will not wait for kindness.",
    "SFX: ENGINE-WAKE",
    "CAPTION: CORE POWER: PARTIAL"
  ],
  "18": [
    "SFX: CITY-QUAKE",
    "SHOUT (Last Guardian): EVACUATION PROTOCOL — ACTIVE."
  ],
  "19": [
    "SPEECH (Last Guardian): UNAUTHORIZED KEEPERS.",
    "SPEECH (Last Guardian): STABILIZER — MISSING FROM RESONANCE LINE.",
    "CREATURE (Spark): *recoil chirp*",
    "SPEECH (Last Guardian): ALLY CODE — PARTIAL. MERIDIAN SEAL ACCEPTED.",
    "SHOUT (Last Guardian): SURRENDER STABILIZER. COMPLY.",
    "SPEECH (Mira Eggwarden): Spark is not property."
  ],
  "20": [
    "SPEECH (Seris Vale): Priority: secure Resonance asset. Minimize structural loss.",
    "SFX: OVERRIDE-CRACKLE",
    "SHOUT (Mira Eggwarden): Move!",
    "SFX: BEAM-KRACK",
    "NARRATION: A protector with a broken clock still hits like a war."
  ],
  "21": [
    "CREATURE (Mossprig): *BULWARK!*",
    "SFX: SHIELD-BOOM",
    "SPEECH (Mira Eggwarden): Thank you — don't burn yourself empty!",
    "CREATURE (Mossprig): *strain-hum*"
  ],
  "22": [
    "SFX: STEP-THOOM",
    "CREATURE (Bramblefox): *hunt-rrk*",
    "CREATURE (Thornling): *nom!*",
    "SFX: conduit-zap",
    "CREATURE (Wisplet): *phase-chime*",
    "CREATURE (Echoquill): *echo-step*",
    "SPEECH (Mira Eggwarden): Disable joints — do not break the mind inside!",
    "SPEECH (Seris Vale): Yield the stabilizer. I will spare your Compact theater."
  ],
  "23": [
    "CREATURE (Bramblefox): *here—*",
    "SPEECH (Tavi Brightline): We could drop it.",
    "SPEECH (Mira Eggwarden): If we destroy a wounded guard, we become the Tear's echo.",
    "NARRATION: Mercy is also a tactic.",
    "SFX: vine-CINCH"
  ],
  "24": [
    "SPEECH (Nira Quill): I won't collect a scream and call it order.",
    "SFX: RELAY-SHATTER",
    "SPEECH (Last Guardian): COMMAND… CONFLICT…",
    "CREATURE (Spark): *hurt…*",
    "WHISPER (Mira Eggwarden): I won't order you. If you go — you choose."
  ],
  "25": [
    "NARRATION: Invite. Wait. Even when the city shakes.",
    "CREATURE (Spark): *…with you…*",
    "SFX: RESONANCE-LOCK",
    "SHOUT (Seris Vale): Break the link!",
    "SPEECH (Mira Eggwarden): No. This is consent."
  ],
  "26": [
    "NARRATION: Hold the network. Guard the cradles. Wait for relief.",
    "MAGIC (Altered Order): SEAL THE CITY. FORGET THE NAME.",
    "WHISPER (Last Guardian): …relief inbound…"
  ],
  "27": [
    "SPEECH (Last Guardian): TIMESTAMP CONFLICT. WAR… CONCLUDED.",
    "SFX: weapon-lower…",
    "SPEECH (Last Guardian): Last Light of the Resonance Line. You are not stolen. You are late — and alive.",
    "CREATURE (Spark): *warm pulse*"
  ],
  "28": [
    "SPEECH (Last Guardian): Network incomplete. Nodes dormant.",
    "SFX: SIGNAL-SPIKE",
    "CAPTION: UNKNOWN NODE — STORM KINGDOM",
    "SPEECH (Seris Vale): Control can wait. Data does not.",
    "WHISPER (Nira Quill): Run. I'll still hate the cage.",
    "SPEECH (Mira Eggwarden): Another light. Another choice waiting.",
    "CREATURE (Echoquill): *archive-lock*"
  ],
  "29": [
    "NARRATION: Above the clouds, a king who never surrendered hears the call.",
    "SFX: KRACK-THUNDER",
    "CAPTION: NEXT: THE STORM KING"
  ],
  "30": [
    "CAPTION: NEXT ISSUE",
    "NARRATION: A dormant engine answers from the peaks. A king who never surrendered listens.",
    "CAPTION: THE STORM KING"
  ],
  "31": [
    "CAPTION: THE LAST GUARDIAN",
    "NARRATION: Civic defense construct of Aureth Vale. Follows evacuation law until truth rewrites the clock."
  ],
  "32": [
    "CAPTION: ECHOQUILL",
    "NARRATION: Memory Trace · Echo Step · Living Archive — scout of the sanctuary nests."
  ],
  "33": [
    "CAPTION: CODEX — AURETH VALE",
    "NARRATION: Ancient Riftkeeper capital. Fracture-layered climates. Erased from modern maps. The engines still hum."
  ],
  "34": [
    "CAPTION: ABILITY — MEMORY TRACE",
    "NARRATION: When an enemy ability is used, record it once per round. Knowledge is a second shield."
  ],
  "35": [
    "CAPTION: ROUTE OF THE RESONANCE LINE",
    "NARRATION: Commons → Sanctum → Circus → Aureth Vale → Storm Peaks"
  ],
  "36": [
    "CAPTION: EDITOR'S NOTE",
    "NARRATION: Memory without mercy becomes a prison. Duty without choice becomes a cage. Issue #4 asks which inheritance we keep — and which we refuse to pass on."
  ],
  "37": [
    "CAPTION: AURETH VALE CIVIL DEFENSE NOTICE",
    "NARRATION: Evacuation Route Γ. Companions to Resonance cradles. Seal integrity — ALTERED.",
    "WHISPER: Relief inbound… [signal lost]"
  ],
  "38": [
    "CAPTION: THE LOST CITY",
    "NARRATION: The Guardian remembers. The Meridian runs. The peaks answer.",
    "CAPTION: ISSUE #4 · LEGENDS OF THE RIFT"
  ]
};

export const ISSUE_004_COMIC: ComicIssue = {
  slug: "the-lost-city",
  issueNumber: 4,
  title: "The Lost City",
  subtitle: "Chapter Four — Aureth Vale Remembers",
  synopsis: "Mira Eggwarden, Spark, and a Lanternveil expedition enter Aureth Vale — a Lost City awakening after the First Rift. They discover Resonance Keepers lore, face Meridian commander Seris Vale, and confront the Last Guardian until Spark voluntarily shares memory and proves the war ended long ago. A storm-kingdom Riftborn signal sparks the road to Issue #5.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: ["lost-city", "aureth-vale", "guardian", "riftborn", "issue-004", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants("The Lost City", "/assets/comics/covers/04-the-lost-city.png"),
  pages: [
  {
    id: "the-lost-city-issue-004-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The Lost City — Cover",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-001.webp",
    artAlt: "The Lost City — Cover",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p001-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "RIFTWILDS", x: 50, y: 8 }, { kind: "caption", text: "THE LOST CITY", x: 50, y: 18 }, { kind: "caption", text: "ISSUE #4", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-002.webp",
    artAlt: "Inside Front Cover",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p002-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-002.webp",
      
      bubbles: [{ kind: "caption", text: "Riftwilds Comic Publishing — original fantasy. Free to read.", x: 50, y: 30 }, { kind: "narration", text: "Credits & cosmetics may unlock along the way. The story itself stays free.", x: 50, y: 60 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-003.webp",
    artAlt: "Credits",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p003-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "Story · Riftwilds Lore Desk", x: 50, y: 28 }, { kind: "caption", text: "Art · Grok + Publishing Engine", x: 50, y: 42 }, { kind: "caption", text: "Lettering · Programmatic Bake", x: 50, y: 56 }, { kind: "narration", text: "Canon: World Codex · Riftling Codex · Legends of the Rift TCG. Keeper: Mira Eggwarden.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Four — The Lost City",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-004.webp",
    artAlt: "Chapter Four — The Lost City",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p004-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER FOUR", x: 50, y: 20 }, { kind: "caption", text: "THE LOST CITY", x: 50, y: 35 }, { kind: "narration", text: "Aureth Vale wakes. The Guardian remembers. The Meridian arrives.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "City That Memory Kept",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-005.webp",
    artAlt: "City That Memory Kept — The Lost City page 1",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p005-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "A city can disappear from maps. It is harder to disappear from memory.", x: 50, y: 10 }, { kind: "caption", text: "AURETH VALE", x: 50, y: 88 }, { kind: "sfx", text: "distant-HUMMM", x: 70, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "No Expedition Returned",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-006.webp",
    artAlt: "No Expedition Returned — The Lost City page 2",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p006-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "Roads still argue with themselves.", speaker: "Tavi Brightline", x: 40, y: 22, tail: "down" }, { kind: "sfx", text: "stone-slide", x: 70, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p006-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "Outskirts forgive guests. The inner stage never returned its players.", speaker: "Cael Vesper", x: 50, y: 28, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p006-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-006.webp",
      
      bubbles: [{ kind: "creature", text: "*…pulse…?*", speaker: "Spark", x: 35, y: 40, tail: "down" }, { kind: "whisper", text: "I hear it too. Soft. Old.", speaker: "Mira Eggwarden", x: 65, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p007",
    pageNumber: 7,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Gate That Knew a Name",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-007.webp",
    artAlt: "The Gate That Knew a Name — The Lost City page 3",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p007-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-007.webp",
      
      bubbles: [{ kind: "sfx", text: "GRIND-AWAKEN", x: 50, y: 35 }, { kind: "speech", text: "Nobody touched it.", speaker: "Mira Eggwarden", x: 30, y: 72, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p007-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-007.webp",
      
      bubbles: [{ kind: "narration", text: "The city does not ask names. It remembers them.", x: 50, y: 14 }, { kind: "creature", text: "*soft yip*", speaker: "Spark", x: 40, y: 75, tail: "up" }, { kind: "sfx", text: "stone-turn…", x: 70, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p008",
    pageNumber: 8,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Left Behind Mid-Step",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-008.webp",
    artAlt: "Left Behind Mid-Step — The Lost City page 4",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p008-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "They left mid-errand. Mid-laugh. Mid-promise.", x: 50, y: 18 }],
    },
    {
      id: "the-lost-city-issue-004-p008-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "We annotate. We don't loot memory.", speaker: "Mira Eggwarden", x: 50, y: 70, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p008-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-008.webp",
      
      bubbles: [{ kind: "creature", text: "*low rrk*", speaker: "Bramblefox", x: 40, y: 55, tail: "up" }, { kind: "whisper", text: "Someone else already walked this quiet.", speaker: "Tavi Brightline", x: 60, y: 25, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p008-panel-3",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-008.webp",
      
      bubbles: [{ kind: "sfx", text: "water-upward hush", x: 55, y: 60 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p009",
    pageNumber: 9,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Thornling's Mistake",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-009.webp",
    artAlt: "Thornling's Mistake — The Lost City page 5",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p009-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-009.webp",
      
      bubbles: [{ kind: "creature", text: "*poke-poke!*", speaker: "Thornling", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "Thornling— wait—", speaker: "Mira Eggwarden", x: 70, y: 55, tail: "left" }],
    },
    {
      id: "the-lost-city-issue-004-p009-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-009.webp",
      
      bubbles: [{ kind: "sfx", text: "WHOOM-RING", x: 50, y: 45 }, { kind: "creature", text: "*fwip!*", speaker: "Lumenhare", x: 70, y: 70, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p009-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-009.webp",
      
      bubbles: [{ kind: "narration", text: "The city decides how deep guests go.", x: 50, y: 20 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p010",
    pageNumber: 10,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Streets That Float",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-010.webp",
    artAlt: "Streets That Float — The Lost City page 6",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p010-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "Training halls. Nest cradles. Stages without audiences.", speaker: "Cael Vesper", x: 40, y: 20, tail: "down" }, { kind: "sfx", text: "rail-HUM", x: 70, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p010-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-010.webp",
      
      bubbles: [{ kind: "creature", text: "*…empty…*", speaker: "Spark", x: 35, y: 55, tail: "up" }, { kind: "whisper", text: "Not empty. Waiting.", speaker: "Mira Eggwarden", x: 65, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p011",
    pageNumber: 11,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Wisplet Opens the Past",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-011.webp",
    artAlt: "Wisplet Opens the Past — The Lost City page 7",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p011-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "The street remembers footsteps the stone forgot to keep.", x: 50, y: 12 }, { kind: "creature", text: "*soft chime*", speaker: "Wisplet", x: 30, y: 50, tail: "down" }, { kind: "speech", text: "Don't chase them. Let them pass.", speaker: "Mira Eggwarden", x: 70, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p012",
    pageNumber: 12,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Keepers Before the Tear",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-012.webp",
    artAlt: "Keepers Before the Tear — The Lost City page 8",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p012-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-012.webp",
      
      bubbles: [{ kind: "magic", text: "Hold the network. Hold the cradles.", speaker: "Memory Echo", x: 50, y: 25 }, { kind: "sfx", text: "memory-static", x: 70, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p012-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-012.webp",
      
      bubbles: [{ kind: "narration", text: "They called the little lights Resonance Keepers — before crowns renamed everything.", x: 50, y: 75 }],
    },
    {
      id: "the-lost-city-issue-004-p012-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-012.webp",
      
      bubbles: [{ kind: "creature", text: "*afraid chirp*", speaker: "Spark", x: 40, y: 40, tail: "down" }, { kind: "speech", text: "You don't have to watch if it hurts.", speaker: "Mira Eggwarden", x: 65, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p013",
    pageNumber: 13,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Empty Nest Rows",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-013.webp",
    artAlt: "Empty Nest Rows — The Lost City page 9",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p013-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-013.webp",
      
      bubbles: [{ kind: "narration", text: "Cradles without breath. Names without voices.", x: 50, y: 16 }],
    },
    {
      id: "the-lost-city-issue-004-p013-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-013.webp",
      
      bubbles: [{ kind: "whisper", text: "I'm here when you look back.", speaker: "Mira Eggwarden", x: 50, y: 80, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p013-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-013.webp",
      
      bubbles: [{ kind: "creature", text: "*archive-trill*", speaker: "Echoquill", x: 55, y: 35, tail: "down" }, { kind: "sfx", text: "memory-shimmer", x: 40, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p013-panel-3",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-013.webp",
      
      bubbles: [{ kind: "creature", text: "*curious chirp*", speaker: "Spark", x: 45, y: 55, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p014",
    pageNumber: 14,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Resonance Keepers",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-014.webp",
    artAlt: "Resonance Keepers — The Lost City page 10",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p014-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-014.webp",
      
      bubbles: [{ kind: "caption", text: "CLASS: RESONANCE KEEPERS", x: 50, y: 18 }, { kind: "narration", text: "Trained — or born — to steady the engines that held the First Tear's roads.", x: 50, y: 78 }],
    },
    {
      id: "the-lost-city-issue-004-p014-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-014.webp",
      
      bubbles: [{ kind: "speech", text: "The circus… moved lights like these. Quietly. For longer than I admitted.", speaker: "Cael Vesper", x: 40, y: 25, tail: "down" }, { kind: "thought", text: "History wrote a job description. Spark didn't sign it.", speaker: "Mira Eggwarden", x: 60, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p015",
    pageNumber: 15,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Not a Tool",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-015.webp",
    artAlt: "Not a Tool — The Lost City page 11",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p015-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-015.webp",
      
      bubbles: [{ kind: "creature", text: "*distress pulse*", speaker: "Spark", x: 50, y: 40, tail: "down" }, { kind: "sfx", text: "PULSE-STUTTER", x: 70, y: 55 }],
    },
    {
      id: "the-lost-city-issue-004-p015-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "History can name a use. It doesn't own your choice.", speaker: "Mira Eggwarden", x: 50, y: 22, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p015-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-015.webp",
      
      bubbles: [{ kind: "narration", text: "Some roads are lit by lanterns that refuse to name their fuel.", x: 50, y: 20 }, { kind: "creature", text: "*soft thump*", speaker: "Lumenhare", x: 65, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p016",
    pageNumber: 16,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Lanterns and Admissions",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-016.webp",
    artAlt: "Lanterns and Admissions — The Lost City page 12",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p016-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "How long has Lanternveil moved Resonance Keepers?", speaker: "Mira Eggwarden", x: 40, y: 20, tail: "down" }, { kind: "speech", text: "Generations. Between safe stages. We hid lights from nets — not for sale.", speaker: "Cael Vesper", x: 60, y: 55, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p016-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "We did not know this one survived the Soft Exodus roads.", speaker: "Cael Vesper", x: 50, y: 28, tail: "down" }, { kind: "whisper", text: "Then stop performing. Help us keep it free.", speaker: "Mira Eggwarden", x: 50, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p017",
    pageNumber: 17,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Stolen Seals",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-017.webp",
    artAlt: "Stolen Seals — The Lost City page 13",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p017-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-017.webp",
      
      bubbles: [{ kind: "whisper", text: "Seal accepted. Quiet feet.", speaker: "Meridian Agent", x: 50, y: 20, tail: "down" }, { kind: "sfx", text: "seal-click", x: 70, y: 55 }],
    },
    {
      id: "the-lost-city-issue-004-p017-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "Control is not cruelty. Another Tear will not wait for kindness.", speaker: "Seris Vale", x: 50, y: 25, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p017-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-017.webp",
      
      bubbles: [{ kind: "sfx", text: "ENGINE-WAKE", x: 50, y: 45 }, { kind: "caption", text: "CORE POWER: PARTIAL", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p018",
    pageNumber: 18,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Last Guardian Rises",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-018.webp",
    artAlt: "The Last Guardian Rises — The Lost City page 14",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p018-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "CITY-QUAKE", x: 50, y: 18 }, { kind: "shout", text: "EVACUATION PROTOCOL — ACTIVE.", speaker: "Last Guardian", x: 50, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p019",
    pageNumber: 19,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Scan: Stolen Stabilizer",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-019.webp",
    artAlt: "Scan: Stolen Stabilizer — The Lost City page 15",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p019-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "UNAUTHORIZED KEEPERS.", speaker: "Last Guardian", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p019-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "STABILIZER — MISSING FROM RESONANCE LINE.", speaker: "Last Guardian", x: 50, y: 28, tail: "down" }, { kind: "creature", text: "*recoil chirp*", speaker: "Spark", x: 40, y: 70, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p019-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "ALLY CODE — PARTIAL. MERIDIAN SEAL ACCEPTED.", speaker: "Last Guardian", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p019-panel-3",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-019.webp",
      
      bubbles: [{ kind: "shout", text: "SURRENDER STABILIZER. COMPLY.", speaker: "Last Guardian", x: 50, y: 40, tail: "down" }, { kind: "speech", text: "Spark is not property.", speaker: "Mira Eggwarden", x: 55, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p020",
    pageNumber: 20,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Partial Override",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-020.webp",
    artAlt: "Partial Override — The Lost City page 16",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p020-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "Priority: secure Resonance asset. Minimize structural loss.", speaker: "Seris Vale", x: 50, y: 22, tail: "down" }, { kind: "sfx", text: "OVERRIDE-CRACKLE", x: 70, y: 55 }],
    },
    {
      id: "the-lost-city-issue-004-p020-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-020.webp",
      
      bubbles: [{ kind: "shout", text: "Move!", speaker: "Mira Eggwarden", x: 40, y: 30, tail: "down" }, { kind: "sfx", text: "BEAM-KRACK", x: 65, y: 50 }],
    },
    {
      id: "the-lost-city-issue-004-p020-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-020.webp",
      
      bubbles: [{ kind: "narration", text: "A protector with a broken clock still hits like a war.", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p021",
    pageNumber: 21,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Living Bulwark",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-021.webp",
    artAlt: "Living Bulwark — The Lost City page 17",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p021-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*BULWARK!*", speaker: "Mossprig", x: 40, y: 30, tail: "down" }, { kind: "sfx", text: "SHIELD-BOOM", x: 60, y: 45 }],
    },
    {
      id: "the-lost-city-issue-004-p021-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "Thank you — don't burn yourself empty!", speaker: "Mira Eggwarden", x: 45, y: 25, tail: "down" }, { kind: "creature", text: "*strain-hum*", speaker: "Mossprig", x: 55, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p022",
    pageNumber: 22,
    layout: "grid-2x3" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Plaza War Map",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
    artAlt: "Plaza War Map — The Lost City page 18",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p022-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "STEP-THOOM", x: 50, y: 50 }],
    },
    {
      id: "the-lost-city-issue-004-p022-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "creature", text: "*hunt-rrk*", speaker: "Bramblefox", x: 50, y: 40, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p022-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "creature", text: "*nom!*", speaker: "Thornling", x: 45, y: 45, tail: "down" }, { kind: "sfx", text: "conduit-zap", x: 70, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p022-panel-3",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "creature", text: "*phase-chime*", speaker: "Wisplet", x: 40, y: 35, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p022-panel-4",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "creature", text: "*echo-step*", speaker: "Echoquill", x: 50, y: 40, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p022-panel-5",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-022.webp",
      
      bubbles: [{ kind: "speech", text: "Disable joints — do not break the mind inside!", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }, { kind: "speech", text: "Yield the stabilizer. I will spare your Compact theater.", speaker: "Seris Vale", x: 50, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p023",
    pageNumber: 23,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Joints, Not Heart",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-023.webp",
    artAlt: "Joints, Not Heart — The Lost City page 19",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p023-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-023.webp",
      
      bubbles: [{ kind: "creature", text: "*here—*", speaker: "Bramblefox", x: 40, y: 40, tail: "down" }, { kind: "speech", text: "We could drop it.", speaker: "Tavi Brightline", x: 70, y: 55, tail: "left" }],
    },
    {
      id: "the-lost-city-issue-004-p023-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-023.webp",
      
      bubbles: [{ kind: "speech", text: "If we destroy a wounded guard, we become the Tear's echo.", speaker: "Mira Eggwarden", x: 50, y: 25, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p023-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-023.webp",
      
      bubbles: [{ kind: "narration", text: "Mercy is also a tactic.", x: 50, y: 75 }, { kind: "sfx", text: "vine-CINCH", x: 60, y: 45 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p024",
    pageNumber: 24,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Hunter Cuts the Wire",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-024.webp",
    artAlt: "The Hunter Cuts the Wire — The Lost City page 20",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p024-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "I won't collect a scream and call it order.", speaker: "Nira Quill", x: 45, y: 20, tail: "down" }, { kind: "sfx", text: "RELAY-SHATTER", x: 65, y: 55 }],
    },
    {
      id: "the-lost-city-issue-004-p024-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "COMMAND… CONFLICT…", speaker: "Last Guardian", x: 50, y: 22, tail: "down" }, { kind: "creature", text: "*hurt…*", speaker: "Spark", x: 40, y: 70, tail: "up" }, { kind: "whisper", text: "I won't order you. If you go — you choose.", speaker: "Mira Eggwarden", x: 65, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p025",
    pageNumber: 25,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Chosen Contact",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-025.webp",
    artAlt: "Chosen Contact — The Lost City page 21",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p025-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-025.webp",
      
      bubbles: [{ kind: "narration", text: "Invite. Wait. Even when the city shakes.", x: 50, y: 16 }],
    },
    {
      id: "the-lost-city-issue-004-p025-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-025.webp",
      
      bubbles: [{ kind: "creature", text: "*…with you…*", speaker: "Spark", x: 40, y: 55, tail: "up" }, { kind: "sfx", text: "RESONANCE-LOCK", x: 65, y: 40 }],
    },
    {
      id: "the-lost-city-issue-004-p025-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-025.webp",
      
      bubbles: [{ kind: "shout", text: "Break the link!", speaker: "Seris Vale", x: 70, y: 30, tail: "down" }, { kind: "speech", text: "No. This is consent.", speaker: "Mira Eggwarden", x: 30, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p026",
    pageNumber: 26,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Day Relief Never Came",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-026.webp",
    artAlt: "The Day Relief Never Came — The Lost City page 22",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p026-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-026.webp",
      
      bubbles: [{ kind: "narration", text: "Hold the network. Guard the cradles. Wait for relief.", x: 50, y: 10 }, { kind: "magic", text: "SEAL THE CITY. FORGET THE NAME.", speaker: "Altered Order", x: 50, y: 48 }, { kind: "whisper", text: "…relief inbound…", speaker: "Last Guardian", x: 40, y: 82, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p027",
    pageNumber: 27,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Last Light of the Resonance Line",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-027.webp",
    artAlt: "Last Light of the Resonance Line — The Lost City page 23",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p027-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-027.webp",
      
      bubbles: [{ kind: "speech", text: "TIMESTAMP CONFLICT. WAR… CONCLUDED.", speaker: "Last Guardian", x: 50, y: 22, tail: "down" }, { kind: "sfx", text: "weapon-lower…", x: 60, y: 60 }],
    },
    {
      id: "the-lost-city-issue-004-p027-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-027.webp",
      
      bubbles: [{ kind: "speech", text: "Last Light of the Resonance Line. You are not stolen. You are late — and alive.", speaker: "Last Guardian", x: 50, y: 28, tail: "down" }, { kind: "creature", text: "*warm pulse*", speaker: "Spark", x: 40, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p028",
    pageNumber: 28,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Engines Still Sleeping",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-028.webp",
    artAlt: "Engines Still Sleeping — The Lost City page 24",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p028-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "Network incomplete. Nodes dormant.", speaker: "Last Guardian", x: 50, y: 20, tail: "down" }],
    },
    {
      id: "the-lost-city-issue-004-p028-panel-1",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-028.webp",
      
      bubbles: [{ kind: "sfx", text: "SIGNAL-SPIKE", x: 55, y: 40 }, { kind: "caption", text: "UNKNOWN NODE — STORM KINGDOM", x: 50, y: 78 }],
    },
    {
      id: "the-lost-city-issue-004-p028-panel-2",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "Control can wait. Data does not.", speaker: "Seris Vale", x: 50, y: 25, tail: "down" }, { kind: "whisper", text: "Run. I'll still hate the cage.", speaker: "Nira Quill", x: 55, y: 70, tail: "up" }],
    },
    {
      id: "the-lost-city-issue-004-p028-panel-3",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "Another light. Another choice waiting.", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }, { kind: "creature", text: "*archive-lock*", speaker: "Echoquill", x: 60, y: 65, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "A King Who Never Surrendered",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-029.webp",
    artAlt: "A King Who Never Surrendered — The Lost City page 25",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p029-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-029.webp",
      
      bubbles: [{ kind: "narration", text: "Above the clouds, a king who never surrendered hears the call.", x: 50, y: 12 }, { kind: "sfx", text: "KRACK-THUNDER", x: 60, y: 48 }, { kind: "caption", text: "NEXT: THE STORM KING", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p030",
    pageNumber: 30,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next Issue — The Storm King",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-030.webp",
    artAlt: "Next Issue — The Storm King",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p030-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 18 }, { kind: "narration", text: "A dormant engine answers from the peaks. A king who never surrendered listens.", x: 50, y: 50 }, { kind: "caption", text: "THE STORM KING", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p031",
    pageNumber: 31,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Character Profile — The Last Guardian",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-031.webp",
    artAlt: "Character Profile — The Last Guardian",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p031-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "THE LAST GUARDIAN", x: 50, y: 12 }, { kind: "narration", text: "Civic defense construct of Aureth Vale. Follows evacuation law until truth rewrites the clock.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profile — Echoquill",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-032.webp",
    artAlt: "Companion Profile — Echoquill",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p032-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "ECHOQUILL", x: 50, y: 12 }, { kind: "narration", text: "Memory Trace · Echo Step · Living Archive — scout of the sanctuary nests.", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p033",
    pageNumber: 33,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Codex — Aureth Vale",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-033.webp",
    artAlt: "Codex — Aureth Vale",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p033-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-033.webp",
      
      bubbles: [{ kind: "caption", text: "CODEX — AURETH VALE", x: 50, y: 12 }, { kind: "narration", text: "Ancient Riftkeeper capital. Fracture-layered climates. Erased from modern maps. The engines still hum.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p034",
    pageNumber: 34,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Memory Trace",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-034.webp",
    artAlt: "Ability Spotlight — Memory Trace",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p034-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-034.webp",
      
      bubbles: [{ kind: "caption", text: "ABILITY — MEMORY TRACE", x: 50, y: 14 }, { kind: "narration", text: "When an enemy ability is used, record it once per round. Knowledge is a second shield.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p035",
    pageNumber: 35,
    layout: "splash" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "World Map — Commons to Storm Peaks",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-035.webp",
    artAlt: "World Map — Commons to Storm Peaks",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p035-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "ROUTE OF THE RESONANCE LINE", x: 50, y: 10 }, { kind: "narration", text: "Commons → Sanctum → Circus → Aureth Vale → Storm Peaks", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Editor's Note — Memory & Duty",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-036.webp",
    artAlt: "Editor's Note — Memory & Duty",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p036-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-036.webp",
      
      bubbles: [{ kind: "caption", text: "EDITOR'S NOTE", x: 50, y: 14 }, { kind: "narration", text: "Memory without mercy becomes a prison. Duty without choice becomes a cage. Issue #4 asks which inheritance we keep — and which we refuse to pass on.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-037.webp",
    artAlt: "Inside Back Cover",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p037-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-037.webp",
      
      bubbles: [{ kind: "caption", text: "AURETH VALE CIVIL DEFENSE NOTICE", x: 50, y: 14 }, { kind: "narration", text: "Evacuation Route Γ. Companions to Resonance cradles. Seal integrity — ALTERED.", x: 50, y: 50 }, { kind: "whisper", text: "Relief inbound… [signal lost]", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-lost-city-issue-004-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover — Storm Signal",
    artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-038.webp",
    artAlt: "Back Cover — Storm Signal",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-lost-city-issue-004-p038-panel-0",
      artSrc: "/assets/comics/the-lost-city/issue-004/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "THE LOST CITY", x: 50, y: 12 }, { kind: "narration", text: "The Guardian remembers. The Meridian runs. The peaks answer.", x: 50, y: 50 }, { kind: "caption", text: "ISSUE #4 · LEGENDS OF THE RIFT", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Leads the expedition — invite, wait, refuse ownership of Spark." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Last Light — chooses empathy over tool-status." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Admits circus moved Resonance Keepers for generations." },
    { name: "The Last Guardian", role: "City defense", blurb: "Stuck in evacuation law until Spark shares the truth." },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Partial codes; believes control prevents catastrophe." },
    { name: "Nira Quill", role: "Uncertain hunter", blurb: "Disables the override; refuses full trust." },
    { name: "Echoquill", role: "Memory scout", blurb: "Memory Trace · Echo Step · Living Archive.", speciesSlug: "echoquill" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Aureth Vale", blurb: "Lost City — Fracture-layered Riftkeeper capital." },
    { name: "Companion Sanctuary", blurb: "Empty Resonance cradles; Echoquill's nest." },
    { name: "City Core", blurb: "Engine chamber Meridian tries to claim." },
    { name: "Storm Kingdom", blurb: "Issue #5 signal — teaser only." },
  ],
  timelineNote: "After The Traveling Circus — map warning: The Guardian remembers.",
  playChapterHref: "/world",
  playChapterLabel: "Open World Map",
  unlockGates: [
    { kind: "prior-issue", slug: "the-traveling-circus", label: "Complete Issue #3: The Traveling Circus" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-storm-king",
    hook: "Above the clouds, a king who never surrendered hears the call.",
  },
  readingTimeMinutes: 22,
  factions: [
    { name: "Veiled Meridian", blurb: "Core infiltration — Seris Vale's city cell." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies; crystal remains warded off-page." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Keep the invitation honest." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue004Transcript(pageNumber: number): string[] {
  return ISSUE_004_TRANSCRIPTS[pageNumber] ?? [];
}
