import type { FurnitureSku } from "@/lib/housing/types";

/** Production starter catalog — dozens of SKUs; hundreds tracked in backlog. */
export const FURNITURE_SKUS: FurnitureSku[] = [
  // Structure
  { key: "wall_timber", name: "Timber Wall", category: "walls", rarity: "common", creditsCost: 15, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Warm bark-tone wall panel.", thumbKey: "furn-wall-timber" },
  { key: "wall_stone", name: "Sandstone Wall", category: "walls", rarity: "common", creditsCost: 22, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Plaza stone wall plate.", thumbKey: "furn-wall-stone" },
  { key: "wall_moss", name: "Moss Wall", category: "walls", rarity: "uncommon", creditsCost: 30, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Living moss veneer.", thumbKey: "furn-wall-moss" },
  { key: "floor_plank", name: "Plank Floor", category: "floors", rarity: "common", creditsCost: 12, footprint: { w: 1, h: 1 }, rotatable: false, scalable: false, collides: false, roomTags: ["*"], description: "Worn timber planks.", thumbKey: "furn-floor-plank" },
  { key: "floor_tile", name: "Clay Tile Floor", category: "floors", rarity: "common", creditsCost: 18, footprint: { w: 1, h: 1 }, rotatable: false, scalable: false, collides: false, roomTags: ["*"], description: "Warm clay tiles.", thumbKey: "furn-floor-tile" },
  { key: "floor_crystal", name: "Crystal Floor", category: "floors", rarity: "rare", creditsCost: 55, footprint: { w: 1, h: 1 }, rotatable: false, scalable: false, collides: false, roomTags: ["underground", "observatory"], description: "Soft rift shimmer underfoot.", thumbKey: "furn-floor-crystal" },
  { key: "roof_thatch", name: "Thatch Roof", category: "roofs", rarity: "common", creditsCost: 28, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["exterior"], description: "Cottage thatch plate.", thumbKey: "furn-roof-thatch", exteriorOk: true },
  { key: "roof_slate", name: "Slate Roof", category: "roofs", rarity: "uncommon", creditsCost: 40, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["exterior"], description: "Townhouse slate.", thumbKey: "furn-roof-slate", exteriorOk: true },
  { key: "door_oak", name: "Oak Door", category: "doors", rarity: "common", creditsCost: 35, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Entry door with latch.", thumbKey: "furn-door-oak" },
  { key: "door_secret", name: "Bookcase Door", category: "doors", rarity: "epic", creditsCost: 120, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["secret"], description: "Hides a secret room.", thumbKey: "furn-door-secret" },
  { key: "window_lattice", name: "Lattice Window", category: "windows", rarity: "common", creditsCost: 25, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Weather shows through panes.", thumbKey: "furn-window-lattice" },
  { key: "window_stained", name: "Aurora Stained Window", category: "windows", rarity: "rare", creditsCost: 70, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["observatory", "manor"], description: "Cyan-amber glass.", thumbKey: "furn-window-stained" },
  { key: "stairs_wood", name: "Wood Stairs", category: "stairs", rarity: "common", creditsCost: 45, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Connects floors.", thumbKey: "furn-stairs-wood" },
  { key: "fence_picket", name: "Picket Fence", category: "fences", rarity: "common", creditsCost: 14, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["exterior", "garden"], description: "Yard edge — cannot block roads.", thumbKey: "furn-fence-picket", exteriorOk: true },
  { key: "fence_stone", name: "Stone Low Wall", category: "fences", rarity: "uncommon", creditsCost: 24, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["exterior"], description: "Decorative plot border.", thumbKey: "furn-fence-stone", exteriorOk: true },

  // Seating / tables / beds
  { key: "bench_visitor", name: "Visitor Bench", category: "seating", rarity: "common", creditsCost: 30, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["guest", "garden"], description: "Sit / emote spot for guests.", thumbKey: "furn-bench-visitor" },
  { key: "chair_hearth", name: "Hearth Chair", category: "seating", rarity: "common", creditsCost: 28, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Soft leather seat.", thumbKey: "furn-chair-hearth" },
  { key: "sofa_moss", name: "Moss Sofa", category: "seating", rarity: "uncommon", creditsCost: 60, footprint: { w: 3, h: 1 }, rotatable: true, scalable: true, collides: true, roomTags: ["guest", "manor"], description: "Lounge seating.", thumbKey: "furn-sofa-moss" },
  { key: "table_oak", name: "Oak Table", category: "tables", rarity: "common", creditsCost: 40, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["*"], description: "Dining / craft surface.", thumbKey: "furn-table-oak" },
  { key: "table_tea", name: "Tea Table", category: "tables", rarity: "uncommon", creditsCost: 48, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["guest"], description: "Small social table.", thumbKey: "furn-table-tea" },
  { key: "bed_moss", name: "Moss Nest Bed", category: "beds", rarity: "common", creditsCost: 55, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["care", "pet-house"], description: "Keeper rest + Riftling nest.", thumbKey: "furn-bed-moss", stationTrack: "care" },
  { key: "bed_canopy", name: "Canopy Bed", category: "beds", rarity: "rare", creditsCost: 110, footprint: { w: 3, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["manor"], description: "Luxury rest furniture.", thumbKey: "furn-bed-canopy" },

  // Storage / lighting / decor
  { key: "crate_keeper", name: "Keeper Crate", category: "storage", rarity: "common", creditsCost: 20, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["storage"], description: "Home storage prop.", thumbKey: "furn-crate-keeper" },
  { key: "chest_iron", name: "Ironbound Chest", category: "storage", rarity: "uncommon", creditsCost: 65, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["storage"], description: "Secure storage visual.", thumbKey: "furn-chest-iron" },
  { key: "shelf_wall", name: "Wall Shelf", category: "storage", rarity: "common", creditsCost: 22, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Display + light storage.", thumbKey: "furn-shelf-wall", displaySlot: true },
  { key: "lantern_ember", name: "Ember Lantern", category: "lighting", rarity: "common", creditsCost: 35, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Warm torch pool light.", thumbKey: "furn-lantern-ember" },
  { key: "lantern_rift", name: "Rift Lantern", category: "lighting", rarity: "uncommon", creditsCost: 55, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Cyan accent lamp.", thumbKey: "furn-lantern-rift" },
  { key: "chandelier_manor", name: "Manor Chandelier", category: "lighting", rarity: "rare", creditsCost: 140, footprint: { w: 2, h: 2 }, rotatable: false, scalable: false, collides: false, roomTags: ["manor", "guest"], description: "Ceiling light fixture.", thumbKey: "furn-chandelier" },
  { key: "rug_moss", name: "Moss Rug", category: "decor", rarity: "common", creditsCost: 40, footprint: { w: 2, h: 2 }, rotatable: true, scalable: true, collides: false, roomTags: ["*"], description: "Soft floor rug.", thumbKey: "furn-rug-moss" },
  { key: "rug_aurora", name: "Aurora Rug", category: "decor", rarity: "rare", creditsCost: 95, footprint: { w: 3, h: 2 }, rotatable: true, scalable: true, collides: false, roomTags: ["observatory"], description: "Star-pattern textile.", thumbKey: "furn-rug-aurora" },
  { key: "banner_keeper", name: "Keeper Banner", category: "decor", rarity: "uncommon", creditsCost: 45, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Wall crest banner.", thumbKey: "furn-banner-keeper" },
  { key: "painting_grove", name: "Grove Painting", category: "decor", rarity: "uncommon", creditsCost: 50, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Original IP landscape art.", thumbKey: "furn-painting-grove" },
  { key: "fountain_tide", name: "Tide Fountain", category: "decor", rarity: "rare", creditsCost: 90, footprint: { w: 2, h: 2 }, rotatable: false, scalable: false, collides: true, roomTags: ["garden", "exterior"], description: "Outdoor water feature.", thumbKey: "furn-fountain-tide", exteriorOk: true },
  { key: "mailbox_plot", name: "Plot Mailbox", category: "exterior", rarity: "common", creditsCost: 25, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["exterior"], description: "Neighborhood mailbox stub.", thumbKey: "furn-mailbox", exteriorOk: true },

  // Display / plants / music
  { key: "plinth_trophy", name: "Trophy Plinth", category: "display", rarity: "rare", creditsCost: 80, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["trophy"], description: "Displays collectibles.", thumbKey: "furn-plinth-trophy", displaySlot: true },
  { key: "case_relic", name: "Relic Case", category: "display", rarity: "epic", creditsCost: 160, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["trophy", "manor"], description: "Glass case for rare finds.", thumbKey: "furn-case-relic", displaySlot: true },
  { key: "comic_cover_frame", name: "Comic Cover Frame", category: "display", rarity: "uncommon", creditsCost: 70, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["guest", "trophy"], description: "Integrates comic cover displays.", thumbKey: "furn-comic-frame", displaySlot: true },
  { key: "planter_herb", name: "Herb Planter", category: "plants", rarity: "common", creditsCost: 32, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["garden"], description: "Hosts grove herbs.", thumbKey: "furn-planter-herb", stationTrack: "farming" },
  { key: "tree_potted", name: "Potted Grove Sapling", category: "plants", rarity: "uncommon", creditsCost: 48, footprint: { w: 1, h: 1 }, rotatable: true, scalable: true, collides: true, roomTags: ["garden", "exterior"], description: "Indoor/outdoor sapling.", thumbKey: "furn-tree-potted", exteriorOk: true },
  { key: "vine_curtain", name: "Vine Curtain", category: "plants", rarity: "uncommon", creditsCost: 38, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: false, roomTags: ["*"], description: "Living doorway accent.", thumbKey: "furn-vine-curtain" },
  { key: "music_lyre", name: "Hearth Lyre Stand", category: "music", rarity: "uncommon", creditsCost: 75, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["guest", "music"], description: "Ambient music source.", thumbKey: "furn-music-lyre" },
  { key: "music_drum", name: "Festival Drum", category: "music", rarity: "rare", creditsCost: 95, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["guest", "exterior"], description: "Party event prop.", thumbKey: "furn-music-drum", exteriorOk: true },

  // Care / riftling / farming / workshop
  { key: "egg_cradle", name: "Incubator Cradle", category: "care", rarity: "uncommon", creditsCost: 70, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["egg-incubator", "care"], description: "Egg care station.", thumbKey: "furn-egg-cradle", stationTrack: "care" },
  { key: "healing_basin", name: "Healing Basin", category: "care", rarity: "rare", creditsCost: 100, footprint: { w: 2, h: 2 }, rotatable: false, scalable: false, collides: true, roomTags: ["healing"], description: "Care recovery flavor.", thumbKey: "furn-healing-basin", stationTrack: "care" },
  { key: "riftling_bed", name: "Riftling Nest Pad", category: "riftling", rarity: "common", creditsCost: 45, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["pet-house", "riftling"], description: "Dedicated Riftling room pad.", thumbKey: "furn-riftling-bed", stationTrack: "care" },
  { key: "riftling_toy", name: "Crystal Play Toy", category: "riftling", rarity: "uncommon", creditsCost: 40, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["pet-house", "garden"], description: "Outdoor/indoor play prop.", thumbKey: "furn-riftling-toy" },
  { key: "riftling_park_post", name: "Riftling Park Post", category: "riftling", rarity: "rare", creditsCost: 85, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["exterior", "garden"], description: "Neighborhood park tether stub.", thumbKey: "furn-riftling-park", exteriorOk: true },
  { key: "farm_row", name: "Crop Row Box", category: "farming", rarity: "common", creditsCost: 50, footprint: { w: 3, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["garden", "farm"], description: "Functional farm plot stub.", thumbKey: "furn-farm-row", stationTrack: "farming" },
  { key: "farm_scarecrow", name: "Friendly Scarecrow", category: "farming", rarity: "uncommon", creditsCost: 42, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["garden", "exterior"], description: "Farm accent NPC-adjacent.", thumbKey: "furn-scarecrow", exteriorOk: true },
  { key: "anvil_crater", name: "Crater Anvil", category: "workshop", rarity: "rare", creditsCost: 120, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["forge", "workshop"], description: "Crafting station stub.", thumbKey: "furn-anvil", stationTrack: "crafting" },
  { key: "alchemy_table", name: "Alchemy Table", category: "workshop", rarity: "rare", creditsCost: 130, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["potion", "workshop"], description: "Brew station stub.", thumbKey: "furn-alchemy", stationTrack: "crafting" },
  { key: "loom_keeper", name: "Keeper Loom", category: "workshop", rarity: "uncommon", creditsCost: 90, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["workshop"], description: "Textile craft stub.", thumbKey: "furn-loom", stationTrack: "crafting" },
  { key: "training_dummy", name: "Training Dummy", category: "workshop", rarity: "uncommon", creditsCost: 70, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["training"], description: "Yard practice prop.", thumbKey: "furn-dummy" },

  // Secret / observatory / specialty
  { key: "secret_hatch", name: "Trapdoor Hatch", category: "secret", rarity: "epic", creditsCost: 150, footprint: { w: 1, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["secret"], description: "Unlocks secret room entry.", thumbKey: "furn-secret-hatch" },
  { key: "crystal_scope", name: "Crystal Scope", category: "decor", rarity: "epic", creditsCost: 180, footprint: { w: 1, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["observatory"], description: "Observatory centerpiece.", thumbKey: "furn-crystal-scope" },
  { key: "star_chart", name: "Star Chart Desk", category: "tables", rarity: "rare", creditsCost: 100, footprint: { w: 2, h: 1 }, rotatable: true, scalable: false, collides: true, roomTags: ["observatory"], description: "Study furniture.", thumbKey: "furn-star-chart" },
  { key: "stall_awning", name: "Stall Awning", category: "exterior", rarity: "uncommon", creditsCost: 60, footprint: { w: 3, h: 1 }, rotatable: true, scalable: false, collides: false, roomTags: ["marketplace", "exterior"], description: "Player shop facade accent.", thumbKey: "furn-awning", exteriorOk: true },
  { key: "display_window", name: "Shop Display Window", category: "exterior", rarity: "rare", creditsCost: 110, footprint: { w: 2, h: 2 }, rotatable: true, scalable: false, collides: true, roomTags: ["marketplace", "exterior"], description: "Storefront display glass.", thumbKey: "furn-display-window", exteriorOk: true, displaySlot: true },
];

export function getFurnitureSku(key: string): FurnitureSku | undefined {
  return FURNITURE_SKUS.find((s) => s.key === key);
}

export function listFurnitureByCategory(category?: string): FurnitureSku[] {
  if (!category) return FURNITURE_SKUS;
  return FURNITURE_SKUS.filter((s) => s.category === category);
}

export const FURNITURE_CATALOG_COUNT = FURNITURE_SKUS.length;
