import type { PropertyDef } from "@/lib/housing/types";

/** Data-driven property shells — Credits primary; SOL optional vanity only. */
export const PROPERTY_CATALOG: PropertyDef[] = [
  {
    tier: "starter_cabin",
    name: "Starter Cabin",
    blurb: "Timber hearth for new keepers — pet house + storage.",
    creditsCost: 100,
    solOptionalLamports: null,
    maxRooms: 4,
    maxFurniture: 40,
    plotSlots: 1,
    buildLimit: 80,
    decorLimit: 60,
    biomeHint: "commons_grove",
    thumbKey: "prop-starter-cabin",
    supportsFarm: false,
    supportsWorkshop: false,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "cottage",
    name: "Moss Cottage",
    blurb: "Thatched roof, garden bed, visitor porch.",
    creditsCost: 220,
    solOptionalLamports: null,
    maxRooms: 6,
    maxFurniture: 80,
    plotSlots: 2,
    buildLimit: 140,
    decorLimit: 100,
    biomeHint: "commons_grove",
    thumbKey: "prop-cottage",
    supportsFarm: true,
    supportsWorkshop: false,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "townhouse",
    name: "Keeper Townhouse",
    blurb: "Two-story street-facing shell with stall window.",
    creditsCost: 360,
    solOptionalLamports: null,
    maxRooms: 8,
    maxFurniture: 120,
    plotSlots: 1,
    buildLimit: 180,
    decorLimit: 140,
    biomeHint: "commons_plaza",
    thumbKey: "prop-townhouse",
    supportsFarm: false,
    supportsWorkshop: true,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt"],
  },
  {
    tier: "farmstead",
    name: "Rift Farmstead",
    blurb: "Barn yard, crop rows, and outdoor Riftling run.",
    creditsCost: 480,
    solOptionalLamports: null,
    maxRooms: 7,
    maxFurniture: 140,
    plotSlots: 4,
    buildLimit: 220,
    decorLimit: 120,
    biomeHint: "meadow",
    thumbKey: "prop-farmstead",
    supportsFarm: true,
    supportsWorkshop: true,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "manor",
    name: "Lantern Manor",
    blurb: "Stone wings, trophy hall, and guest gallery.",
    creditsCost: 900,
    solOptionalLamports: 50_000_000,
    maxRooms: 12,
    maxFurniture: 220,
    plotSlots: 3,
    buildLimit: 320,
    decorLimit: 260,
    biomeHint: "commons_plaza",
    thumbKey: "prop-manor",
    supportsFarm: true,
    supportsWorkshop: true,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt"],
  },
  {
    tier: "treehouse",
    name: "Canopy Treehouse",
    blurb: "Elevated walkways through grove canopy.",
    creditsCost: 520,
    solOptionalLamports: null,
    maxRooms: 5,
    maxFurniture: 90,
    plotSlots: 2,
    buildLimit: 160,
    decorLimit: 130,
    biomeHint: "deep_grove",
    thumbKey: "prop-treehouse",
    supportsFarm: true,
    supportsWorkshop: false,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "lakeside_lodge",
    name: "Lakeside Lodge",
    blurb: "Dock access, fishing nook, weather windows.",
    creditsCost: 640,
    solOptionalLamports: null,
    maxRooms: 7,
    maxFurniture: 130,
    plotSlots: 3,
    buildLimit: 200,
    decorLimit: 160,
    biomeHint: "lakefront",
    thumbKey: "prop-lakeside",
    supportsFarm: false,
    supportsWorkshop: false,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "cliffside_villa",
    name: "Cliffside Villa",
    blurb: "Wind-cut stone terraces with dramatic overlooks.",
    creditsCost: 780,
    solOptionalLamports: 25_000_000,
    maxRooms: 9,
    maxFurniture: 160,
    plotSlots: 2,
    buildLimit: 240,
    decorLimit: 200,
    biomeHint: "cliff",
    thumbKey: "prop-cliffside",
    supportsFarm: false,
    supportsWorkshop: true,
    supportsObservatory: true,
    acquisition: ["buy_prebuilt"],
  },
  {
    tier: "underground_hideout",
    name: "Underground Hideout",
    blurb: "Crystal cavern rooms and secret passages.",
    creditsCost: 700,
    solOptionalLamports: null,
    maxRooms: 8,
    maxFurniture: 150,
    plotSlots: 1,
    buildLimit: 210,
    decorLimit: 180,
    biomeHint: "cavern",
    thumbKey: "prop-hideout",
    supportsFarm: false,
    supportsWorkshop: true,
    supportsObservatory: false,
    acquisition: ["buy_prebuilt", "claim_land_build"],
  },
  {
    tier: "observatory",
    name: "Aurora Observatory",
    blurb: "Dome scope, star charts, and quiet study.",
    creditsCost: 1100,
    solOptionalLamports: 80_000_000,
    maxRooms: 6,
    maxFurniture: 110,
    plotSlots: 2,
    buildLimit: 180,
    decorLimit: 220,
    biomeHint: "ridge",
    thumbKey: "prop-observatory",
    supportsFarm: false,
    supportsWorkshop: false,
    supportsObservatory: true,
    acquisition: ["buy_prebuilt"],
  },
];

export function getPropertyDef(tier: string): PropertyDef | undefined {
  return PROPERTY_CATALOG.find((p) => p.tier === tier);
}

/** Must satisfy HOUSING_FEE minAmount (25) and stay starter-affordable. */
export const EMPTY_LAND_CLAIM_CREDITS = 100;
export const EXPANSION_LEVEL_CREDITS = [0, 120, 200, 320, 480];
