/* AUTO-GENERATED by scripts/comics/emit-issue-008-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_008_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: LEGENDS OF THE RIFT",
    "CAPTION: THE FORGE OF RIFTS",
    "CAPTION: ISSUE #8"
  ],
  "2": [
    "NARRATION: Previously: Cael Vesper's coercion broke at the Traitor's Gate — Lumenhare freed, Nira cleared, egg cracked once. Gate open. Meridian Road lit. A voice from the Forge: Begin the second creation.",
    "CAPTION: CONTINUE THE FRACTURE DAWN"
  ],
  "3": [
    "CAPTION: THE FORGE OF RIFTS",
    "NARRATION: Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden. Cal Reed is not canon.",
    "CAPTION: ORIGINAL RIFTWILDS IP"
  ],
  "4": [
    "CAPTION: CHAPTER EIGHT",
    "CAPTION: THE FORGE OF RIFTS",
    "NARRATION: Progress without ethics leaves a wound that looks like a doorway."
  ],
  "5": [
    "NARRATION: The Gate had opened. The second creation had already begun. Beyond Meridian Road waited the machine that made the First Rift possible.",
    "CREATURE (Spark): *violent-RECOIL*",
    "SHOUT (Mira Eggwarden): Spark—!",
    "SFX: FORGE-HUMMMM",
    "CAPTION: THE FORGE OF RIFTS"
  ],
  "6": [
    "NARRATION: The egg did not wake. It recognized something.",
    "CREATURE (Spark): *pain-bond-chirp*",
    "SPEECH (Mira Eggwarden): Steady. You're not alone in there.",
    "SFX: egg-PULSE",
    "WHISPER (Cael Vesper): Artificial resonance. Louder than Tempestria's engine.",
    "SPEECH (Nira Quill): Louder means Meridian wants it more."
  ],
  "7": [
    "NARRATION: Half ancient city. Half impossible factory.",
    "SFX: gear-CLANK",
    "SPEECH (Mira Eggwarden): Stay close. Nothing here was built for visitors.",
    "CREATURE (Spirit Moth): *pattern-search*"
  ],
  "8": [
    "CREATURE (Bramblefox): *scent-grief*",
    "SPEECH (Nira Quill): Bramblefox found something.",
    "SPEECH (Mira Eggwarden): They tried to make Keepers… out of companions.",
    "CREATURE (Spark): *mourn-chirp*",
    "NARRATION: Progress without ethics leaves rooms full of almosts."
  ],
  "9": [
    "SFX: CHAIN-SNAP",
    "CREATURE (Mossprig): *root-BRACE*",
    "SHOUT (Mira Eggwarden): Mossprig!",
    "SPEECH (Mira Eggwarden): You don't own them. You protect them. That's the difference.",
    "NARRATION: Even failed light deserves a keeper."
  ],
  "10": [
    "CREATURE (Thornling): *curious-prick*",
    "SFX: click-WHIRRR",
    "SHOUT (Cael Vesper): That woke a whole ring!",
    "SPEECH (Nira Quill): Then Meridian just heard us.",
    "CREATURE (Spark): *alarm-chirp*",
    "THOUGHT (Mira Eggwarden): They built a hunger that looks like a welcome."
  ],
  "11": [
    "CAPTION: MEMORY VAULT",
    "CREATURE (Wisplet): *phase-in*",
    "NARRATION: The First Rift was planned. Not by accident. Not by storm.",
    "WHISPER (Mira Eggwarden): Someone wrote the fracture like a command.",
    "SPEECH (Mira Eggwarden): Enough. Knowledge that burns still burns.",
    "SFX: crystal-CRACK"
  ],
  "12": [
    "CREATURE (Spirit Moth): *code-unlock*",
    "SPEECH (Cael Vesper): Those aren't weapons.",
    "SPEECH (Mira Eggwarden): They built this to heal unstable dimensions.",
    "NARRATION: Someone later taught the machine how to wound."
  ],
  "13": [
    "CAPTION: COMPANION INCUBATOR ALPHA",
    "NARRATION: Here, protectors were grown — not soldiers.",
    "CREATURE (Spark): *home-ache-chirp*",
    "SPEECH (Mira Eggwarden): This is where your kind began… to keep, not to obey."
  ],
  "14": [
    "SFX: stasis-HISS",
    "SPEECH (Arkan): Visitors. Living ones. How… rude of the centuries.",
    "SPEECH (Mira Eggwarden): Stay back. We're Keepers — not spare parts.",
    "SPEECH (Arkan): Good. The Forge forgot that difference. I have not.",
    "WHISPER (Arkan): I am Chief Engineer Arkan. Last architect who stayed.",
    "CREATURE (Spark): *wary-curious*"
  ],
  "15": [
    "SPEECH (Arkan): We made Resonance Keepers. Guardians. City Engines. Stabilizers.",
    "SPEECH (Arkan): Someone rewrote the Forge protocols. The Riftwright never intended genocide.",
    "NARRATION: The Riftwright vanished before activation. Someone else pushed the final command.",
    "SPEECH (Mira Eggwarden): Then the enemy may not be the original creators.",
    "WHISPER (Arkan): Knowledge without conscience is just a prettier knife."
  ],
  "16": [
    "SFX: proto-CHIME",
    "CREATURE (Axiom): *query-trill*",
    "SPEECH (Arkan): Axiom. Adaptive Matrix. Built to copy protection — never ownership.",
    "CREATURE (Spark): *welcome-chirp*",
    "CREATURE (Axiom): *matrix-hum*",
    "SPEECH (Mira Eggwarden): Invite only. Same rule — even for prototypes.",
    "NARRATION: A companion that remembers repair is already choosing a side."
  ],
  "17": [
    "SFX: BLAST-DOORS",
    "SHOUT (Seris Vale): The Resonance component is here. Secure the egg.",
    "SPEECH (Mira Eggwarden): You don't get to manufacture living light!",
    "SPEECH (Cael Vesper): I'll hold the lane — don't thank me yet.",
    "SPEECH (Arkan): They want to restart what we buried. I will not watch twice."
  ],
  "18": [
    "SFX: ARTIFICIAL-TEAR",
    "NARRATION: Natural Rifts bleed. Artificial Rifts cut.",
    "SHOUT (Seris Vale): Engine Alpha — answer the Meridian!",
    "CREATURE (Spark): *component-pain!*"
  ],
  "19": [
    "SFX: POD-BURST",
    "CREATURE (Axiom): *pulse-repair*",
    "SPEECH (Mira Eggwarden): Don't harm them — guide them!",
    "NARRATION: Security remembered oaths older than Meridian uniforms.",
    "SFX: guardian-LOCK",
    "SPEECH (Nira Quill): The Forge is choosing sides — and none of them are calm!"
  ],
  "20": [
    "SFX: CLASH-BOOM",
    "CREATURE (Bramblefox): *vine-SNAP*",
    "CREATURE (Thornling): *short-circuit!*",
    "SHOUT (Seris Vale): Override! Perfect Riftborn require perfect control!",
    "CREATURE (Axiom): *adaptive-matrix*",
    "SPEECH (Mira Eggwarden): Protect — don't obey a thief!"
  ],
  "21": [
    "SFX: FIELD-LOCK",
    "CREATURE (Spark): *struggle-yelp*",
    "SHOUT (Mira Eggwarden): He chooses! He is not a component!",
    "SPEECH (Cael Vesper): I opened doors for them once. Not this one.",
    "SPEECH (Nira Quill): Then cut the wire — don't write a speech!",
    "NARRATION: Choice is a kind of armor. Meridian never forged that."
  ],
  "22": [
    "SFX: REACTOR-ROAR",
    "CREATURE (Spark): *last-light-flare*",
    "CREATURE (Axiom): *system-restore!*",
    "NARRATION: The Forge shook like a heart deciding whether to keep beating."
  ],
  "23": [
    "SHOUT (Arkan): Someone can finally fix my mistakes—!",
    "SPEECH (Arkan): Protect. Don't obey.",
    "SFX: SACRIFICE-BLOOM",
    "CREATURE (Spark): *grief-bright*"
  ],
  "24": [
    "SFX: COLLAPSE-RUMBLE",
    "NARRATION: Machines die louder than men — and quieter than guilt.",
    "SPEECH (Mira Eggwarden): Arkan bought us a path. We use it.",
    "CREATURE (Axiom): *system-restore*",
    "WHISPER (Cael Vesper): He stayed centuries… and still chose us over the machine."
  ],
  "25": [
    "SPEECH (Mira Eggwarden): Only if you want to. Invite. Wait.",
    "CREATURE (Spark): *choose-stabilize*",
    "SFX: reactor-SETTLE",
    "NARRATION: Spark's species was created to protect — not obey.",
    "THOUGHT (Mira Eggwarden): Why you survived: you were never finished as a weapon."
  ],
  "26": [
    "CREATURE (Truthwing): *path-gleam*",
    "SHOUT (Nira Quill): Bridge left — go!",
    "SPEECH (Cael Vesper): I still don't deserve trust. I can still deserve your backs.",
    "SPEECH (Mira Eggwarden): Then keep earning. Move!",
    "SFX: GATE-SLAM",
    "NARRATION: They escaped with light — and with questions heavier than steel."
  ],
  "27": [
    "WHISPER (Seris Vale): One Forge dies. The project does not.",
    "SFX: vault-SNATCH",
    "SHOUT (Nira Quill): She's running with a scroll!",
    "SPEECH (Mira Eggwarden): We can't chase and keep the egg safe.",
    "NARRATION: Some victories leave the villain holding tomorrow."
  ],
  "28": [
    "CREATURE (Axiom): *map-projection*",
    "SPEECH (Mira Eggwarden): There's another one.",
    "NARRATION: Deep beneath another continent, a second Forge listened.",
    "WHISPER (Cael Vesper): If Meridian has the blueprint… they'll find it first."
  ],
  "29": [
    "NARRATION: Inside, a figure walked toward the central reactor.",
    "SPEECH: So… after all this time… someone finally reached my Forge.",
    "CAPTION: THE RIFTWRIGHT IS ALIVE",
    "CAPTION: NEXT: THE RIFTWRIGHT"
  ],
  "30": [
    "CAPTION: NEXT ISSUE",
    "CAPTION: THE RIFTWRIGHT",
    "NARRATION: Alive. Waiting. And the Meridian already holds a key."
  ],
  "31": [
    "CAPTION: CHIEF ENGINEER ARKAN",
    "NARRATION: Last surviving Forge architect. Memory-preserved for centuries. Brilliant. Regretful. Not evil — not absolved. Died believing someone could finally fix his mistakes.",
    "CAPTION: ROLE: Support NPC · Sacrifice"
  ],
  "32": [
    "CAPTION: AXIOM — PROTOTYPE COMPANION",
    "NARRATION: Passive: Adaptive Matrix — copy one ally passive briefly. Active: Pulse Repair — restore durability. Ultimate: System Restore — dampen corrupted Rift effects.",
    "CAPTION: ROLE: Support / Utility / Resonance"
  ],
  "33": [
    "CAPTION: CODEX — THE FORGE OF RIFTS",
    "NARRATION: Underground civilization around a machine that manufactures artificial Rift energy. Built to heal unstable dimensions. Weaponized after protocol rewrite. Primary site vented in Issue #8; a second Forge remains."
  ],
  "34": [
    "CAPTION: BLUEPRINT GALLERY",
    "NARRATION: Riftborn were grown as protectors. Artificial Rifts cut; natural Rifts bleed. Spark and the dormant egg survived because their lines were never finished as weapons.",
    "CAPTION: PROTOTYPE RIFTBORN"
  ],
  "35": [
    "CAPTION: RIFT ENGINE ALPHA",
    "NARRATION: Primary Forge reactor. Stabilized by Spark through voluntary invitation — never forced bond. City Engines and Guardian constructs once drew safe power here."
  ],
  "36": [
    "CAPTION: ROUTE OF THE FORGE ROAD",
    "NARRATION: Traitor's Gate → Meridian Road → Forge of Rifts (vented) → Second Forge (active)"
  ],
  "37": [
    "CAPTION: EDITOR'S NOTE",
    "NARRATION: Issue #8 asks whether knowledge itself can be dangerous — and answers that danger lives in the hands that rewrite purpose. Create to protect. Never to own."
  ],
  "38": [
    "CAPTION: BEHIND THE LORE",
    "NARRATION: Guardian Cities ran on Forge Engines. Artificial Rifts differ by geometry and intent. The saboteur who rewrote protocols remains unnamed — for now.",
    "WHISPER: Archive Shelf unlocks after Issue #7 — or admin/dev override."
  ],
  "39": [
    "CAPTION: THE FORGE OF RIFTS",
    "NARRATION: Someone finally reached the Forge. Someone else was already home.",
    "CAPTION: ISSUE #8 · LEGENDS OF THE RIFT"
  ]
};

export const ISSUE_008_COMIC: ComicIssue = {
  slug: "the-forge-of-rifts",
  issueNumber: 8,
  title: "The Forge of Rifts",
  subtitle: "Chapter Eight — Protect. Don't Obey.",
  synopsis: "Beyond the Traitor's Gate, Mira Eggwarden, Spark, and the supervised expedition enter the Forge of Rifts — an underground civilization built around a machine that manufactures artificial Rift energy. Chief Engineer Arkan reveals the Forge was meant to heal dimensions before someone rewrote its protocols; prototype companion Axiom awakens. Seris Vale restarts Engine Alpha to mass-produce Riftborn, nearly capturing Spark. In a double-page battle Arkan sacrifices his preserved body; Spark stabilizes the reactor; the team escapes as Seris steals a Second Forge blueprint. Cliffhanger: another Forge activates — the Riftwright is alive.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: ["forge-of-rifts", "arkan", "axiom", "riftborn", "issue-008", "veiled-meridian", "mira-eggwarden", "riftwright"],
  covers: expandCoverVariants("The Forge of Rifts", "/assets/comics/covers/08-the-forge-of-rifts.png"),
  pages: [
  {
    id: "the-forge-of-rifts-issue-008-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The Forge of Rifts — Cover",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-001.webp",
    artAlt: "The Forge of Rifts — Cover",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p001-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 10 }, { kind: "caption", text: "THE FORGE OF RIFTS", x: 50, y: 48 }, { kind: "caption", text: "ISSUE #8", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-002.webp",
    artAlt: "Inside Front Cover",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p002-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-002.webp",
      
      bubbles: [{ kind: "narration", text: "Previously: Cael Vesper's coercion broke at the Traitor's Gate — Lumenhare freed, Nira cleared, egg cracked once. Gate open. Meridian Road lit. A voice from the Forge: Begin the second creation.", x: 50, y: 40 }, { kind: "caption", text: "CONTINUE THE FRACTURE DAWN", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-003.webp",
    artAlt: "Credits",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p003-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "THE FORGE OF RIFTS", x: 50, y: 14 }, { kind: "narration", text: "Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden. Cal Reed is not canon.", x: 50, y: 50 }, { kind: "caption", text: "ORIGINAL RIFTWILDS IP", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Eight — The Forge of Rifts",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-004.webp",
    artAlt: "Chapter Eight — The Forge of Rifts",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p004-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER EIGHT", x: 50, y: 18 }, { kind: "caption", text: "THE FORGE OF RIFTS", x: 50, y: 42 }, { kind: "narration", text: "Progress without ethics leaves a wound that looks like a doorway.", x: 50, y: 72 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Forge Threshold",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-005.webp",
    artAlt: "Forge Threshold — The Forge of Rifts page 1",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p005-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "The Gate had opened. The second creation had already begun. Beyond Meridian Road waited the machine that made the First Rift possible.", x: 50, y: 8 }, { kind: "creature", text: "*violent-RECOIL*", speaker: "Spark", x: 38, y: 55, tail: "down" }, { kind: "shout", text: "Spark—!", speaker: "Mira Eggwarden", x: 55, y: 70, tail: "up" }, { kind: "sfx", text: "FORGE-HUMMMM", x: 78, y: 35 }, { kind: "caption", text: "THE FORGE OF RIFTS", x: 50, y: 92 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Egg Glow",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-006.webp",
    artAlt: "Egg Glow — The Forge of Rifts page 2",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p006-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-006.webp",
      
      bubbles: [{ kind: "narration", text: "The egg did not wake. It recognized something.", x: 50, y: 18 }, { kind: "creature", text: "*pain-bond-chirp*", speaker: "Spark", x: 40, y: 60, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p006-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "Steady. You're not alone in there.", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "egg-PULSE", x: 70, y: 65 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p006-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-006.webp",
      
      bubbles: [{ kind: "whisper", text: "Artificial resonance. Louder than Tempestria's engine.", speaker: "Cael Vesper", x: 35, y: 28, tail: "down" }, { kind: "speech", text: "Louder means Meridian wants it more.", speaker: "Nira Quill", x: 65, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p007",
    pageNumber: 7,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Machine City",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-007.webp",
    artAlt: "Machine City — The Forge of Rifts page 3",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p007-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-007.webp",
      
      bubbles: [{ kind: "narration", text: "Half ancient city. Half impossible factory.", x: 50, y: 12 }, { kind: "sfx", text: "gear-CLANK", x: 72, y: 50 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p007-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-007.webp",
      
      bubbles: [{ kind: "speech", text: "Stay close. Nothing here was built for visitors.", speaker: "Mira Eggwarden", x: 45, y: 30, tail: "down" }, { kind: "creature", text: "*pattern-search*", speaker: "Spirit Moth", x: 65, y: 68, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p008",
    pageNumber: 8,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Abandoned Companions",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-008.webp",
    artAlt: "Abandoned Companions — The Forge of Rifts page 4",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p008-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-008.webp",
      
      bubbles: [{ kind: "creature", text: "*scent-grief*", speaker: "Bramblefox", x: 40, y: 28, tail: "down" }, { kind: "speech", text: "Bramblefox found something.", speaker: "Nira Quill", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p008-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "They tried to make Keepers… out of companions.", speaker: "Mira Eggwarden", x: 50, y: 25, tail: "down" }, { kind: "creature", text: "*mourn-chirp*", speaker: "Spark", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p008-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "Progress without ethics leaves rooms full of almosts.", x: 50, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p009",
    pageNumber: 9,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Living Bulwark",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-009.webp",
    artAlt: "Living Bulwark — The Forge of Rifts page 5",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p009-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-009.webp",
      
      bubbles: [{ kind: "sfx", text: "CHAIN-SNAP", x: 70, y: 20 }, { kind: "creature", text: "*root-BRACE*", speaker: "Mossprig", x: 40, y: 45, tail: "down" }, { kind: "shout", text: "Mossprig!", speaker: "Mira Eggwarden", x: 60, y: 75, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p009-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "You don't own them. You protect them. That's the difference.", speaker: "Mira Eggwarden", x: 50, y: 28, tail: "down" }, { kind: "narration", text: "Even failed light deserves a keeper.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p010",
    pageNumber: 10,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Power Restored",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-010.webp",
    artAlt: "Power Restored — The Forge of Rifts page 6",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p010-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-010.webp",
      
      bubbles: [{ kind: "creature", text: "*curious-prick*", speaker: "Thornling", x: 45, y: 30, tail: "down" }, { kind: "sfx", text: "click-WHIRRR", x: 68, y: 55 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p010-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-010.webp",
      
      bubbles: [{ kind: "shout", text: "That woke a whole ring!", speaker: "Cael Vesper", x: 50, y: 30, tail: "down" }, { kind: "speech", text: "Then Meridian just heard us.", speaker: "Nira Quill", x: 55, y: 70, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p010-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-010.webp",
      
      bubbles: [{ kind: "creature", text: "*alarm-chirp*", speaker: "Spark", x: 40, y: 35, tail: "down" }, { kind: "thought", text: "They built a hunger that looks like a welcome.", speaker: "Mira Eggwarden", x: 60, y: 72 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p011",
    pageNumber: 11,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Memory Crystals",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-011.webp",
    artAlt: "Memory Crystals — The Forge of Rifts page 7",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p011-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-011.webp",
      
      bubbles: [{ kind: "caption", text: "MEMORY VAULT", x: 50, y: 12 }, { kind: "creature", text: "*phase-in*", speaker: "Wisplet", x: 40, y: 40, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p011-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "The First Rift was planned. Not by accident. Not by storm.", x: 50, y: 20 }, { kind: "whisper", text: "Someone wrote the fracture like a command.", speaker: "Mira Eggwarden", x: 55, y: 72, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p011-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-011.webp",
      
      bubbles: [{ kind: "speech", text: "Enough. Knowledge that burns still burns.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "sfx", text: "crystal-CRACK", x: 70, y: 60 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p012",
    pageNumber: 12,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Hidden Blueprints",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-012.webp",
    artAlt: "Hidden Blueprints — The Forge of Rifts page 8",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p012-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-012.webp",
      
      bubbles: [{ kind: "creature", text: "*code-unlock*", speaker: "Spirit Moth", x: 35, y: 25, tail: "down" }, { kind: "speech", text: "Those aren't weapons.", speaker: "Cael Vesper", x: 60, y: 55, tail: "left" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p012-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "They built this to heal unstable dimensions.", speaker: "Mira Eggwarden", x: 45, y: 28, tail: "down" }, { kind: "narration", text: "Someone later taught the machine how to wound.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p013",
    pageNumber: 13,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Incubator Alpha",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-013.webp",
    artAlt: "Incubator Alpha — The Forge of Rifts page 9",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p013-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-013.webp",
      
      bubbles: [{ kind: "caption", text: "COMPANION INCUBATOR ALPHA", x: 50, y: 10 }, { kind: "narration", text: "Here, protectors were grown — not soldiers.", x: 50, y: 22 }, { kind: "creature", text: "*home-ache-chirp*", speaker: "Spark", x: 42, y: 60, tail: "down" }, { kind: "speech", text: "This is where your kind began… to keep, not to obey.", speaker: "Mira Eggwarden", x: 58, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p014",
    pageNumber: 14,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Chief Engineer",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-014.webp",
    artAlt: "Chief Engineer — The Forge of Rifts page 10",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p014-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-014.webp",
      
      bubbles: [{ kind: "sfx", text: "stasis-HISS", x: 70, y: 25 }, { kind: "speech", text: "Visitors. Living ones. How… rude of the centuries.", speaker: "Arkan", x: 45, y: 55, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p014-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-014.webp",
      
      bubbles: [{ kind: "speech", text: "Stay back. We're Keepers — not spare parts.", speaker: "Mira Eggwarden", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "Good. The Forge forgot that difference. I have not.", speaker: "Arkan", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p014-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-014.webp",
      
      bubbles: [{ kind: "whisper", text: "I am Chief Engineer Arkan. Last architect who stayed.", speaker: "Arkan", x: 50, y: 40, tail: "down" }, { kind: "creature", text: "*wary-curious*", speaker: "Spark", x: 55, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p015",
    pageNumber: 15,
    layout: "four-grid" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Forge History",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-015.webp",
    artAlt: "Forge History — The Forge of Rifts page 11",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p015-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "We made Resonance Keepers. Guardians. City Engines. Stabilizers.", speaker: "Arkan", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p015-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "Someone rewrote the Forge protocols. The Riftwright never intended genocide.", speaker: "Arkan", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p015-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-015.webp",
      
      bubbles: [{ kind: "narration", text: "The Riftwright vanished before activation. Someone else pushed the final command.", x: 50, y: 40 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p015-panel-3",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "Then the enemy may not be the original creators.", speaker: "Mira Eggwarden", x: 45, y: 30, tail: "down" }, { kind: "whisper", text: "Knowledge without conscience is just a prettier knife.", speaker: "Arkan", x: 55, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p016",
    pageNumber: 16,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Axiom Awakens",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-016.webp",
    artAlt: "Axiom Awakens — The Forge of Rifts page 12",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p016-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-016.webp",
      
      bubbles: [{ kind: "sfx", text: "proto-CHIME", x: 65, y: 25 }, { kind: "creature", text: "*query-trill*", speaker: "Axiom", x: 50, y: 50, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p016-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "Axiom. Adaptive Matrix. Built to copy protection — never ownership.", speaker: "Arkan", x: 50, y: 22, tail: "down" }, { kind: "creature", text: "*welcome-chirp*", speaker: "Spark", x: 40, y: 65, tail: "right" }, { kind: "creature", text: "*matrix-hum*", speaker: "Axiom", x: 60, y: 70, tail: "left" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p016-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-016.webp",
      
      bubbles: [{ kind: "speech", text: "Invite only. Same rule — even for prototypes.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "narration", text: "A companion that remembers repair is already choosing a side.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p017",
    pageNumber: 17,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Meridian Assault",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-017.webp",
    artAlt: "Meridian Assault — The Forge of Rifts page 13",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p017-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-017.webp",
      
      bubbles: [{ kind: "sfx", text: "BLAST-DOORS", x: 70, y: 20 }, { kind: "shout", text: "The Resonance component is here. Secure the egg.", speaker: "Seris Vale", x: 45, y: 45, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p017-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "You don't get to manufacture living light!", speaker: "Mira Eggwarden", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "I'll hold the lane — don't thank me yet.", speaker: "Cael Vesper", x: 65, y: 65, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p017-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-017.webp",
      
      bubbles: [{ kind: "speech", text: "They want to restart what we buried. I will not watch twice.", speaker: "Arkan", x: 50, y: 40, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p018",
    pageNumber: 18,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Artificial Rift",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-018.webp",
    artAlt: "Artificial Rift — The Forge of Rifts page 14",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p018-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "ARTIFICIAL-TEAR", x: 70, y: 28 }, { kind: "narration", text: "Natural Rifts bleed. Artificial Rifts cut.", x: 50, y: 12 }, { kind: "shout", text: "Engine Alpha — answer the Meridian!", speaker: "Seris Vale", x: 45, y: 70, tail: "up" }, { kind: "creature", text: "*component-pain!*", speaker: "Spark", x: 35, y: 55, tail: "right" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p019",
    pageNumber: 19,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Escaped Experiments",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-019.webp",
    artAlt: "Escaped Experiments — The Forge of Rifts page 15",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p019-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-019.webp",
      
      bubbles: [{ kind: "sfx", text: "POD-BURST", x: 68, y: 22 }, { kind: "creature", text: "*pulse-repair*", speaker: "Axiom", x: 40, y: 45, tail: "down" }, { kind: "speech", text: "Don't harm them — guide them!", speaker: "Mira Eggwarden", x: 55, y: 75, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p019-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-019.webp",
      
      bubbles: [{ kind: "narration", text: "Security remembered oaths older than Meridian uniforms.", x: 50, y: 20 }, { kind: "sfx", text: "guardian-LOCK", x: 65, y: 60 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p019-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "The Forge is choosing sides — and none of them are calm!", speaker: "Nira Quill", x: 50, y: 40, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p020",
    pageNumber: 20,
    layout: "montage" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Giant Battle",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-020.webp",
    artAlt: "Giant Battle — The Forge of Rifts page 16",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p020-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-020.webp",
      
      bubbles: [{ kind: "sfx", text: "CLASH-BOOM", x: 70, y: 20 }, { kind: "creature", text: "*vine-SNAP*", speaker: "Bramblefox", x: 30, y: 40, tail: "right" }, { kind: "creature", text: "*short-circuit!*", speaker: "Thornling", x: 55, y: 55, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p020-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-020.webp",
      
      bubbles: [{ kind: "shout", text: "Override! Perfect Riftborn require perfect control!", speaker: "Seris Vale", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p020-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-020.webp",
      
      bubbles: [{ kind: "creature", text: "*adaptive-matrix*", speaker: "Axiom", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "Protect — don't obey a thief!", speaker: "Mira Eggwarden", x: 60, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p021",
    pageNumber: 21,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Near Capture",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-021.webp",
    artAlt: "Near Capture — The Forge of Rifts page 17",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p021-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-021.webp",
      
      bubbles: [{ kind: "sfx", text: "FIELD-LOCK", x: 70, y: 25 }, { kind: "creature", text: "*struggle-yelp*", speaker: "Spark", x: 40, y: 50, tail: "down" }, { kind: "shout", text: "He chooses! He is not a component!", speaker: "Mira Eggwarden", x: 55, y: 75, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p021-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "I opened doors for them once. Not this one.", speaker: "Cael Vesper", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "Then cut the wire — don't write a speech!", speaker: "Nira Quill", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p021-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-021.webp",
      
      bubbles: [{ kind: "narration", text: "Choice is a kind of armor. Meridian never forged that.", x: 50, y: 35 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p022",
    pageNumber: 22,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Forge War — Left",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-022.webp",
    artAlt: "Forge War — Left — The Forge of Rifts page 18",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p022-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "REACTOR-ROAR", x: 70, y: 18 }, { kind: "creature", text: "*last-light-flare*", speaker: "Spark", x: 35, y: 45, tail: "down" }, { kind: "creature", text: "*system-restore!*", speaker: "Axiom", x: 55, y: 55, tail: "left" }, { kind: "narration", text: "The Forge shook like a heart deciding whether to keep beating.", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p023",
    pageNumber: 23,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Forge War — Sacrifice",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-023.webp",
    artAlt: "Forge War — Sacrifice — The Forge of Rifts page 19",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p023-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-023.webp",
      
      bubbles: [{ kind: "shout", text: "Someone can finally fix my mistakes—!", speaker: "Arkan", x: 40, y: 28, tail: "down" }, { kind: "speech", text: "Protect. Don't obey.", speaker: "Arkan", x: 55, y: 48, tail: "up" }, { kind: "sfx", text: "SACRIFICE-BLOOM", x: 72, y: 60 }, { kind: "creature", text: "*grief-bright*", speaker: "Spark", x: 30, y: 70, tail: "right" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p024",
    pageNumber: 24,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Collapse",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-024.webp",
    artAlt: "Collapse — The Forge of Rifts page 20",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p024-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-024.webp",
      
      bubbles: [{ kind: "sfx", text: "COLLAPSE-RUMBLE", x: 65, y: 25 }, { kind: "narration", text: "Machines die louder than men — and quieter than guilt.", x: 50, y: 70 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p024-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "Arkan bought us a path. We use it.", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }, { kind: "creature", text: "*system-restore*", speaker: "Axiom", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p024-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-024.webp",
      
      bubbles: [{ kind: "whisper", text: "He stayed centuries… and still chose us over the machine.", speaker: "Cael Vesper", x: 50, y: 45, tail: "down" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p025",
    pageNumber: 25,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Reactor Alpha",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-025.webp",
    artAlt: "Reactor Alpha — The Forge of Rifts page 21",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p025-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-025.webp",
      
      bubbles: [{ kind: "speech", text: "Only if you want to. Invite. Wait.", speaker: "Mira Eggwarden", x: 40, y: 25, tail: "down" }, { kind: "creature", text: "*choose-stabilize*", speaker: "Spark", x: 55, y: 50, tail: "down" }, { kind: "sfx", text: "reactor-SETTLE", x: 72, y: 70 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p025-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-025.webp",
      
      bubbles: [{ kind: "narration", text: "Spark's species was created to protect — not obey.", x: 50, y: 20 }, { kind: "thought", text: "Why you survived: you were never finished as a weapon.", speaker: "Mira Eggwarden", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p026",
    pageNumber: 26,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Escape",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-026.webp",
    artAlt: "Escape — The Forge of Rifts page 22",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p026-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-026.webp",
      
      bubbles: [{ kind: "creature", text: "*path-gleam*", speaker: "Truthwing", x: 40, y: 25, tail: "down" }, { kind: "shout", text: "Bridge left — go!", speaker: "Nira Quill", x: 60, y: 55, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p026-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "I still don't deserve trust. I can still deserve your backs.", speaker: "Cael Vesper", x: 50, y: 35, tail: "down" }, { kind: "speech", text: "Then keep earning. Move!", speaker: "Mira Eggwarden", x: 55, y: 72, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p026-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-026.webp",
      
      bubbles: [{ kind: "sfx", text: "GATE-SLAM", x: 65, y: 40 }, { kind: "narration", text: "They escaped with light — and with questions heavier than steel.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p027",
    pageNumber: 27,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Stolen Blueprint",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-027.webp",
    artAlt: "Stolen Blueprint — The Forge of Rifts page 23",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p027-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-027.webp",
      
      bubbles: [{ kind: "whisper", text: "One Forge dies. The project does not.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "vault-SNATCH", x: 68, y: 55 }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p027-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-027.webp",
      
      bubbles: [{ kind: "shout", text: "She's running with a scroll!", speaker: "Nira Quill", x: 45, y: 35, tail: "down" }, { kind: "speech", text: "We can't chase and keep the egg safe.", speaker: "Mira Eggwarden", x: 55, y: 70, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p027-panel-2",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-027.webp",
      
      bubbles: [{ kind: "narration", text: "Some victories leave the villain holding tomorrow.", x: 50, y: 45 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p028",
    pageNumber: 28,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Second Forge",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-028.webp",
    artAlt: "Second Forge — The Forge of Rifts page 24",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p028-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-028.webp",
      
      bubbles: [{ kind: "creature", text: "*map-projection*", speaker: "Axiom", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "There's another one.", speaker: "Mira Eggwarden", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-forge-of-rifts-issue-008-p028-panel-1",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-028.webp",
      
      bubbles: [{ kind: "narration", text: "Deep beneath another continent, a second Forge listened.", x: 50, y: 18 }, { kind: "whisper", text: "If Meridian has the blueprint… they'll find it first.", speaker: "Cael Vesper", x: 50, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Riftwright",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-029.webp",
    artAlt: "The Riftwright — The Forge of Rifts page 25",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p029-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-029.webp",
      
      bubbles: [{ kind: "narration", text: "Inside, a figure walked toward the central reactor.", x: 50, y: 10 }, { kind: "speech", text: "So… after all this time… someone finally reached my Forge.", x: 50, y: 48 }, { kind: "caption", text: "THE RIFTWRIGHT IS ALIVE", x: 50, y: 78 }, { kind: "caption", text: "NEXT: THE RIFTWRIGHT", x: 50, y: 90 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p030",
    pageNumber: 30,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next Issue — The Riftwright",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-030.webp",
    artAlt: "Next Issue — The Riftwright",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p030-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 14 }, { kind: "caption", text: "THE RIFTWRIGHT", x: 50, y: 40 }, { kind: "narration", text: "Alive. Waiting. And the Meridian already holds a key.", x: 50, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p031",
    pageNumber: 31,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Character Profile — Chief Engineer Arkan",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-031.webp",
    artAlt: "Character Profile — Chief Engineer Arkan",
    atmosphere: "ruin" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p031-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "CHIEF ENGINEER ARKAN", x: 50, y: 12 }, { kind: "narration", text: "Last surviving Forge architect. Memory-preserved for centuries. Brilliant. Regretful. Not evil — not absolved. Died believing someone could finally fix his mistakes.", x: 50, y: 55 }, { kind: "caption", text: "ROLE: Support NPC · Sacrifice", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profile — Axiom",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-032.webp",
    artAlt: "Companion Profile — Axiom",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p032-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "AXIOM — PROTOTYPE COMPANION", x: 50, y: 12 }, { kind: "narration", text: "Passive: Adaptive Matrix — copy one ally passive briefly. Active: Pulse Repair — restore durability. Ultimate: System Restore — dampen corrupted Rift effects.", x: 50, y: 50 }, { kind: "caption", text: "ROLE: Support / Utility / Resonance", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p033",
    pageNumber: 33,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Codex — The Forge of Rifts",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-033.webp",
    artAlt: "Codex — The Forge of Rifts",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p033-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-033.webp",
      
      bubbles: [{ kind: "caption", text: "CODEX — THE FORGE OF RIFTS", x: 50, y: 10 }, { kind: "narration", text: "Underground civilization around a machine that manufactures artificial Rift energy. Built to heal unstable dimensions. Weaponized after protocol rewrite. Primary site vented in Issue #8; a second Forge remains.", x: 50, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p034",
    pageNumber: 34,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Blueprint Gallery — Prototype Riftborn",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-034.webp",
    artAlt: "Blueprint Gallery — Prototype Riftborn",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p034-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-034.webp",
      
      bubbles: [{ kind: "caption", text: "BLUEPRINT GALLERY", x: 50, y: 10 }, { kind: "narration", text: "Riftborn were grown as protectors. Artificial Rifts cut; natural Rifts bleed. Spark and the dormant egg survived because their lines were never finished as weapons.", x: 50, y: 48 }, { kind: "caption", text: "PROTOTYPE RIFTBORN", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p035",
    pageNumber: 35,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Rift Engine Alpha",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-035.webp",
    artAlt: "Ability Spotlight — Rift Engine Alpha",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p035-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "RIFT ENGINE ALPHA", x: 50, y: 12 }, { kind: "narration", text: "Primary Forge reactor. Stabilized by Spark through voluntary invitation — never forced bond. City Engines and Guardian constructs once drew safe power here.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "World Map — Meridian Road to Twin Forges",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-036.webp",
    artAlt: "World Map — Meridian Road to Twin Forges",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p036-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-036.webp",
      
      bubbles: [{ kind: "caption", text: "ROUTE OF THE FORGE ROAD", x: 50, y: 10 }, { kind: "narration", text: "Traitor's Gate → Meridian Road → Forge of Rifts (vented) → Second Forge (active)", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Editor's Note — Responsibility in Creation",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-037.webp",
    artAlt: "Editor's Note — Responsibility in Creation",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p037-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-037.webp",
      
      bubbles: [{ kind: "caption", text: "EDITOR'S NOTE", x: 50, y: 14 }, { kind: "narration", text: "Issue #8 asks whether knowledge itself can be dangerous — and answers that danger lives in the hands that rewrite purpose. Create to protect. Never to own.", x: 50, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-038.webp",
    artAlt: "Inside Back Cover",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p038-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "BEHIND THE LORE", x: 50, y: 14 }, { kind: "narration", text: "Guardian Cities ran on Forge Engines. Artificial Rifts differ by geometry and intent. The saboteur who rewrote protocols remains unnamed — for now.", x: 50, y: 50 }, { kind: "whisper", text: "Archive Shelf unlocks after Issue #7 — or admin/dev override.", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-forge-of-rifts-issue-008-p039",
    pageNumber: 39,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover — The Riftwright",
    artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-039.webp",
    artAlt: "Back Cover — The Riftwright",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-forge-of-rifts-issue-008-p039-panel-0",
      artSrc: "/assets/comics/the-forge-of-rifts/issue-008/pages/page-039.webp",
      
      bubbles: [{ kind: "caption", text: "THE FORGE OF RIFTS", x: 50, y: 12 }, { kind: "narration", text: "Someone finally reached the Forge. Someone else was already home.", x: 50, y: 50 }, { kind: "caption", text: "ISSUE #8 · LEGENDS OF THE RIFT", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Discovers how the First Rift was engineered — protects Spark and the egg." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Missing Forge component who chooses to stabilize — protect, not obey." },
    { name: "Chief Engineer Arkan", role: "Forge architect", blurb: "Last surviving engineer — sacrifices his preserved body." },
    { name: "Axiom", role: "Prototype companion", blurb: "Adaptive Matrix · Pulse Repair · System Restore.", speciesSlug: "axiom" },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Restarts the Forge; steals the Second Forge blueprint." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Supervised redemption from Issue #7 — not instantly trusted." },
    { name: "Nira Quill", role: "Allied hunter", blurb: "Field support after Gate judgment." },
    { name: "The Riftwright", role: "Cliffhanger", blurb: "Alive — silhouette only; identity withheld." },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "The Forge of Rifts", blurb: "Underground civilization that manufactures artificial Rift energy." },
    { name: "Companion Incubator Alpha", blurb: "Origin line of Resonance Keepers." },
    { name: "Rift Engine Alpha", blurb: "Primary reactor — Spark-stabilized." },
    { name: "Second Forge", blurb: "Hidden under another continent — cliffhanger." },
  ],
  timelineNote: "After The Traitor's Gate — Meridian Road into the Forge.",
  playChapterHref: "/live-world",
  playChapterLabel: "Travel the Meridian Road",
  unlockGates: [{"kind":"prior-issue","slug":"the-traitors-gate","label":"Complete Issue #7: The Traitor's Gate"},{"kind":"admin-dev","label":"Admin / COMICS_DEV_UNLOCK override"}],
  nextIssueTeaser: {
    slug: "the-riftwright",
    hook: "So… after all this time… someone finally reached my Forge.",
  },
  readingTimeMinutes: 20,
  factions: [
    { name: "Veiled Meridian", blurb: "Restart Forge; mass-produce artificial Riftborn." },
    { name: "Forge Architects", blurb: "Defunct — Arkan last survivor." },
    { name: "Hatchery Compact", blurb: "Invite. Wait. Protect — don't own." },
    { name: "Lanternveil Circus", blurb: "Uneasy allies — wards off-page." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "keepers-road",
  volumeId: "volume-2",
};

export function getIssue008Transcript(pageNumber: number): string[] {
  return ISSUE_008_TRANSCRIPTS[pageNumber] ?? [];
}
