import type { AbilityCatalogItem } from "@/lib/items/types";

export const ABILITY_CATALOG: AbilityCatalogItem[] = [
  // Attack magic
  { id: "ember-bolt", name: "Ember Bolt", description: "A focused ember projectile.", affinity: "EMBER", category: "ATTACK", rarity: "COMMON", power: 40, energyCost: 10, cooldown: 0, iconPath: "/assets/items/abilities/icons/ember-bolt.png", scrollId: "scroll-ember-bolt" },
  { id: "tide-spiral", name: "Tide Spiral", description: "Spiraling water lance.", affinity: "TIDE", category: "ATTACK", rarity: "COMMON", power: 40, energyCost: 10, cooldown: 0, iconPath: "/assets/items/abilities/icons/tide-spiral.png", scrollId: "scroll-tide-spiral" },
  { id: "thorn-burst", name: "Thorn Burst", description: "Explosive thorn cluster.", affinity: "GROVE", category: "ATTACK", rarity: "UNCOMMON", power: 45, energyCost: 12, cooldown: 1, iconPath: "/assets/items/abilities/icons/thorn-burst.png", scrollId: "scroll-thorn-burst" },
  { id: "lightning-arc", name: "Lightning Arc", description: "Quick arcing bolt.", affinity: "STORM", category: "ATTACK", rarity: "UNCOMMON", power: 48, energyCost: 14, cooldown: 1, iconPath: "/assets/items/abilities/icons/lightning-arc.png", scrollId: "scroll-lightning-arc" },
  { id: "stone-crash", name: "Stone Crash", description: "Heavy mineral smash.", affinity: "STONE", category: "ATTACK", rarity: "COMMON", power: 42, energyCost: 12, cooldown: 0, iconPath: "/assets/items/abilities/icons/stone-crash.png", scrollId: "scroll-stone-crash" },
  { id: "frost-shard", name: "Frost Shard", description: "Piercing ice shard.", affinity: "FROST", category: "ATTACK", rarity: "COMMON", power: 41, energyCost: 11, cooldown: 0, iconPath: "/assets/items/abilities/icons/frost-shard.png", scrollId: "scroll-frost-shard" },
  { id: "radiant-beam", name: "Radiant Beam", description: "Focused dawn beam.", affinity: "RADIANT", category: "ATTACK", rarity: "RARE", power: 52, energyCost: 16, cooldown: 2, iconPath: "/assets/items/abilities/icons/radiant-beam.png", scrollId: "scroll-radiant-beam" },
  { id: "void-pulse", name: "Void Pulse", description: "Short-range void thump.", affinity: "VOID", category: "ATTACK", rarity: "RARE", power: 50, energyCost: 15, cooldown: 1, iconPath: "/assets/items/abilities/icons/void-pulse.png", scrollId: "scroll-void-pulse" },
  { id: "alloy-wave", name: "Alloy Wave", description: "Metallic energy wave.", affinity: "ALLOY", category: "ATTACK", rarity: "UNCOMMON", power: 46, energyCost: 13, cooldown: 1, iconPath: "/assets/items/abilities/icons/alloy-wave.png", scrollId: "scroll-alloy-wave" },
  { id: "spirit-flame", name: "Spirit Flame", description: "Gentle spiritfire bolt.", affinity: "SPIRIT", category: "ATTACK", rarity: "UNCOMMON", power: 44, energyCost: 12, cooldown: 1, iconPath: "/assets/items/abilities/icons/spirit-flame.png", scrollId: "scroll-spirit-flame" },
  // Defensive
  { id: "ember-shield", name: "Ember Shield", description: "Heat barrier.", affinity: "EMBER", category: "DEFENSIVE", rarity: "COMMON", power: 0, energyCost: 10, cooldown: 2, iconPath: "/assets/items/abilities/icons/ember-shield.png" },
  { id: "tide-barrier", name: "Tide Barrier", description: "Water wall.", affinity: "TIDE", category: "DEFENSIVE", rarity: "COMMON", power: 0, energyCost: 10, cooldown: 2, iconPath: "/assets/items/abilities/icons/tide-barrier.png" },
  { id: "bark-wall", name: "Bark Wall", description: "Living bark guard.", affinity: "GROVE", category: "DEFENSIVE", rarity: "UNCOMMON", power: 0, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/bark-wall.png" },
  { id: "storm-veil", name: "Storm Veil", description: "Static veil.", affinity: "STORM", category: "DEFENSIVE", rarity: "UNCOMMON", power: 0, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/storm-veil.png" },
  { id: "stone-guard", name: "Stone Guard", description: "Mineral brace.", affinity: "STONE", category: "DEFENSIVE", rarity: "COMMON", power: 0, energyCost: 8, cooldown: 2, iconPath: "/assets/items/abilities/icons/stone-guard.png" },
  { id: "frost-shell", name: "Frost Shell", description: "Icy shell.", affinity: "FROST", category: "DEFENSIVE", rarity: "UNCOMMON", power: 0, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/frost-shell.png" },
  { id: "radiant-ward", name: "Radiant Ward", description: "Light ward.", affinity: "RADIANT", category: "DEFENSIVE", rarity: "RARE", power: 0, energyCost: 14, cooldown: 2, iconPath: "/assets/items/abilities/icons/radiant-ward.png" },
  { id: "void-cloak", name: "Void Cloak", description: "Shadow cloak.", affinity: "VOID", category: "DEFENSIVE", rarity: "RARE", power: 0, energyCost: 14, cooldown: 2, iconPath: "/assets/items/abilities/icons/void-cloak.png" },
  { id: "alloy-barrier", name: "Alloy Barrier", description: "Hex barrier.", affinity: "ALLOY", category: "DEFENSIVE", rarity: "UNCOMMON", power: 0, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/alloy-barrier.png" },
  { id: "spirit-protection", name: "Spirit Protection", description: "Soft spirit shield.", affinity: "SPIRIT", category: "DEFENSIVE", rarity: "UNCOMMON", power: 0, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/spirit-protection.png" },
  // Healing / control / support (sample)
  { id: "grove-mend", name: "Grove Mend", description: "Rooted healing.", affinity: "GROVE", category: "HEALING", rarity: "COMMON", power: 34, energyCost: 14, cooldown: 2, iconPath: "/assets/items/abilities/icons/grove-mend.png" },
  { id: "moonwater-healing", name: "Moonwater Healing", description: "Tidal mend.", affinity: "TIDE", category: "HEALING", rarity: "UNCOMMON", power: 38, energyCost: 15, cooldown: 2, iconPath: "/assets/items/abilities/icons/moonwater-healing.png" },
  { id: "root-bind", name: "Root Bind", description: "Roots the foe briefly.", affinity: "GROVE", category: "CONTROL", rarity: "UNCOMMON", power: 20, energyCost: 12, cooldown: 2, iconPath: "/assets/items/abilities/icons/root-bind.png" },
  { id: "frost-slow", name: "Frost Slow", description: "Chills movement.", affinity: "FROST", category: "CONTROL", rarity: "COMMON", power: 18, energyCost: 10, cooldown: 1, iconPath: "/assets/items/abilities/icons/frost-slow.png" },
  { id: "battle-focus", name: "Battle Focus", description: "Raises accuracy briefly.", affinity: null, category: "SUPPORT", rarity: "COMMON", power: 0, energyCost: 8, cooldown: 2, iconPath: "/assets/items/abilities/icons/battle-focus.png" },
  { id: "speed-wind", name: "Speed Wind", description: "Brief speed breeze.", affinity: "STORM", category: "SUPPORT", rarity: "UNCOMMON", power: 0, energyCost: 10, cooldown: 2, iconPath: "/assets/items/abilities/icons/speed-wind.png" },
  // Ultimates (one per affinity)
  { id: "volcanic-heartburst", name: "Volcanic Heartburst", description: "Signature Ember ultimate — strong, counterable, not an instant KO.", affinity: "EMBER", category: "ULTIMATE", rarity: "LEGENDARY", power: 85, energyCost: 45, cooldown: 5, iconPath: "/assets/items/abilities/icons/volcanic-heartburst.png", scrollId: "scroll-volcanic-heartburst" },
  { id: "moon-tide-collapse", name: "Moon-Tide Collapse", description: "Signature Tide ultimate.", affinity: "TIDE", category: "ULTIMATE", rarity: "LEGENDARY", power: 85, energyCost: 45, cooldown: 5, iconPath: "/assets/items/abilities/icons/moon-tide-collapse.png", scrollId: "scroll-moon-tide-collapse" },
  { id: "worldroot-awakening", name: "Worldroot Awakening", description: "Signature Grove ultimate.", affinity: "GROVE", category: "ULTIMATE", rarity: "LEGENDARY", power: 80, energyCost: 45, cooldown: 5, iconPath: "/assets/items/abilities/icons/worldroot-awakening.png", scrollId: "scroll-worldroot-awakening" },
  { id: "sky-rift-tempest", name: "Sky Rift Tempest", description: "Signature Storm ultimate.", affinity: "STORM", category: "ULTIMATE", rarity: "LEGENDARY", power: 88, energyCost: 48, cooldown: 5, iconPath: "/assets/items/abilities/icons/sky-rift-tempest.png", scrollId: "scroll-sky-rift-tempest" },
  { id: "ancient-mountain-guard", name: "Ancient Mountain Guard", description: "Signature Stone ultimate (defensive).", affinity: "STONE", category: "ULTIMATE", rarity: "LEGENDARY", power: 0, energyCost: 40, cooldown: 5, iconPath: "/assets/items/abilities/icons/ancient-mountain-guard.png", scrollId: "scroll-ancient-mountain-guard" },
  { id: "eternal-winter-ring", name: "Eternal Winter Ring", description: "Signature Frost ultimate.", affinity: "FROST", category: "ULTIMATE", rarity: "LEGENDARY", power: 82, energyCost: 45, cooldown: 5, iconPath: "/assets/items/abilities/icons/eternal-winter-ring.png", scrollId: "scroll-eternal-winter-ring" },
  { id: "dawnstar-ascension", name: "Dawnstar Ascension", description: "Signature Radiant ultimate.", affinity: "RADIANT", category: "ULTIMATE", rarity: "LEGENDARY", power: 86, energyCost: 46, cooldown: 5, iconPath: "/assets/items/abilities/icons/dawnstar-ascension.png", scrollId: "scroll-dawnstar-ascension" },
  { id: "eclipse-singularity", name: "Eclipse Singularity", description: "Signature Void ultimate.", affinity: "VOID", category: "ULTIMATE", rarity: "LEGENDARY", power: 87, energyCost: 48, cooldown: 5, iconPath: "/assets/items/abilities/icons/eclipse-singularity.png", scrollId: "scroll-eclipse-singularity" },
  { id: "titan-core-overdrive", name: "Titan Core Overdrive", description: "Signature Alloy ultimate.", affinity: "ALLOY", category: "ULTIMATE", rarity: "LEGENDARY", power: 84, energyCost: 46, cooldown: 5, iconPath: "/assets/items/abilities/icons/titan-core-overdrive.png", scrollId: "scroll-titan-core-overdrive" },
  { id: "ancestral-lantern-parade", name: "Ancestral Lantern Parade", description: "Signature Spirit ultimate.", affinity: "SPIRIT", category: "ULTIMATE", rarity: "LEGENDARY", power: 78, energyCost: 44, cooldown: 5, iconPath: "/assets/items/abilities/icons/ancestral-lantern-parade.png", scrollId: "scroll-ancestral-lantern-parade" },
];

export function getAbilityById(id: string) {
  return ABILITY_CATALOG.find((a) => a.id === id);
}
