import type { ArmorCatalogItem, ItemRarity, AttachmentPoint } from "@/lib/items/types";

function a(partial: {
  id: string;
  name: string;
  rarity: ItemRarity;
  armorClass: ArmorCatalogItem["armorClass"];
  affinity: ArmorCatalogItem["affinity"];
  description: string;
  weightClass: ArmorCatalogItem["weightClass"];
  defense: number;
  maxHp: number;
  anatomy: string[];
  attachment: AttachmentPoint;
  affixes?: ArmorCatalogItem["affixes"];
  passive?: string;
  cosmeticEffect?: string;
}): ArmorCatalogItem {
  return {
    id: partial.id,
    name: partial.name,
    description: partial.description,
    family: "ARMOR",
    shopCategory: "ARMOR",
    rarity: partial.rarity,
    affinity: partial.affinity,
    levelRequirement: 1,
    tradeability: "TRADEABLE",
    ownership: "OFF_CHAIN",
    stackable: false,
    maxStack: 1,
    priceKey: partial.id,
    supply: "UNLIMITED",
    affixes: partial.affixes ?? [],
    iconPath: `/assets/items/armor/icons/${partial.id}.png`,
    inventoryPath: `/assets/items/armor/icons/${partial.id}.png`,
    compatibleAnatomy: partial.anatomy,
    attachment: partial.attachment,
    armorClass: partial.armorClass,
    weightClass: partial.weightClass,
    stats: {
      defense: partial.defense,
      maxHp: partial.maxHp,
      affinityResistBps: 200,
      critResistBps: 100,
      statusResistBps: 100,
      energyRecovery: 0,
      evasion: partial.weightClass === "LIGHT" ? 2 : 0,
    },
    passive: partial.passive,
    cosmeticEffect: partial.cosmeticEffect,
  };
}

export const ARMOR_CATALOG: ArmorCatalogItem[] = [
  a({
    id: "cloth-pet-vest",
    name: "Cloth Pet Vest",
    rarity: "COMMON",
    armorClass: "CHEST",
    affinity: null,
    description: "Soft training vest that barely slows a Riftling.",
    weightClass: "LIGHT",
    defense: 3,
    maxHp: 4,
    anatomy: ["chest"],
    attachment: "chest",
  }),
  a({
    id: "wooden-barkguard",
    name: "Wooden Barkguard",
    rarity: "COMMON",
    armorClass: "CHEST",
    affinity: "GROVE",
    description: "Thin bark plates for first defenses.",
    weightClass: "MEDIUM",
    defense: 5,
    maxHp: 2,
    anatomy: ["chest"],
    attachment: "chest",
  }),
  a({
    id: "simple-headband",
    name: "Simple Headband",
    rarity: "COMMON",
    armorClass: "HEAD",
    affinity: null,
    description: "Cloth band that keeps focus steady.",
    weightClass: "LIGHT",
    defense: 1,
    maxHp: 2,
    anatomy: ["head"],
    attachment: "head",
  }),
  a({
    id: "training-paw-wraps",
    name: "Training Paw Wraps",
    rarity: "COMMON",
    armorClass: "PAW",
    affinity: null,
    description: "Soft wraps for paw protection in drills.",
    weightClass: "LIGHT",
    defense: 2,
    maxHp: 0,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
  }),
  a({
    id: "mossguard-vest",
    name: "Mossguard Vest",
    rarity: "UNCOMMON",
    armorClass: "CHEST",
    affinity: "GROVE",
    description: "Living moss padding that cushions blows.",
    weightClass: "MEDIUM",
    defense: 6,
    maxHp: 6,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded"],
  }),
  a({
    id: "emberhide-wrap",
    name: "Emberhide Wrap",
    rarity: "UNCOMMON",
    armorClass: "CHEST",
    affinity: "EMBER",
    description: "Warm hide wrap stitched with ember thread.",
    weightClass: "LIGHT",
    defense: 5,
    maxHp: 5,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Resistant"],
  }),
  a({
    id: "tide-scale-guard",
    name: "Tide Scale Guard",
    rarity: "UNCOMMON",
    armorClass: "CHEST",
    affinity: "TIDE",
    description: "Overlapping tide scales that shed water.",
    weightClass: "MEDIUM",
    defense: 6,
    maxHp: 4,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Restorative"],
  }),
  a({
    id: "stoneplate-collar",
    name: "Stoneplate Collar",
    rarity: "UNCOMMON",
    armorClass: "HEAD",
    affinity: "STONE",
    description: "Mineral collar that steadies the neck.",
    weightClass: "HEAVY",
    defense: 7,
    maxHp: 2,
    anatomy: ["neck"],
    attachment: "neck",
    affixes: ["Guarded"],
  }),
  a({
    id: "stormweave-armor",
    name: "Stormweave Armor",
    rarity: "RARE",
    armorClass: "CHEST",
    affinity: "STORM",
    description: "Woven storm-thread plates crackling softly.",
    weightClass: "LIGHT",
    defense: 8,
    maxHp: 6,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Swift", "Energized"],
  }),
  a({
    id: "frostshell-vest",
    name: "Frostshell Vest",
    rarity: "RARE",
    armorClass: "CHEST",
    affinity: "FROST",
    description: "Rime shell plating that chills impacts.",
    weightClass: "MEDIUM",
    defense: 9,
    maxHp: 5,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Resistant", "Guarded"],
  }),
  a({
    id: "spiritveil-cloak",
    name: "Spiritveil Cloak",
    rarity: "RARE",
    armorClass: "BACK",
    affinity: "SPIRIT",
    description: "Translucent cloak that softens status hits.",
    weightClass: "LIGHT",
    defense: 6,
    maxHp: 8,
    anatomy: ["back", "neck"],
    attachment: "back",
    affixes: ["Bonded", "Resistant"],
  }),
  a({
    id: "alloy-chestplate",
    name: "Alloy Chestplate",
    rarity: "RARE",
    armorClass: "CHEST",
    affinity: "ALLOY",
    description: "Hex-panel alloy plate with teal seams.",
    weightClass: "HEAVY",
    defense: 10,
    maxHp: 4,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Strong"],
  }),
  a({
    id: "volcanic-guardian-plate",
    name: "Volcanic Guardian Plate",
    rarity: "EPIC",
    armorClass: "CHEST",
    affinity: "EMBER",
    description: "Obsidian plates laced with living magma veins.",
    weightClass: "HEAVY",
    defense: 12,
    maxHp: 8,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Resistant", "Strong"],
    cosmeticEffect: "Ember edge glow",
  }),
  a({
    id: "moonwater-battle-robe",
    name: "Moonwater Battle Robe",
    rarity: "EPIC",
    armorClass: "CHEST",
    affinity: "TIDE",
    description: "Flowing robe that sheds moonlit spray.",
    weightClass: "LIGHT",
    defense: 9,
    maxHp: 10,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Restorative", "Focused", "Swift"],
  }),
  a({
    id: "elder-grove-armor",
    name: "Elder Grove Armor",
    rarity: "EPIC",
    armorClass: "CHEST",
    affinity: "GROVE",
    description: "Bark and vine lattice from elder groves.",
    weightClass: "MEDIUM",
    defense: 11,
    maxHp: 9,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Bonded", "Restorative"],
  }),
  a({
    id: "voidwalker-mantle",
    name: "Voidwalker Mantle",
    rarity: "EPIC",
    armorClass: "BACK",
    affinity: "VOID",
    description: "Mantle that drinks ambient light.",
    weightClass: "LIGHT",
    defense: 8,
    maxHp: 8,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Swift", "Focused", "Resistant"],
  }),
  a({
    id: "sunforged-aegis",
    name: "Sunforged Aegis",
    rarity: "LEGENDARY",
    armorClass: "BARRIER",
    affinity: "RADIANT",
    description: "Radiant barrier plate forged at dawn.",
    weightClass: "MEDIUM",
    defense: 13,
    maxHp: 10,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Bonded"],
    passive: "Unique dawn shimmer (cosmetic).",
  }),
  a({
    id: "deep-rift-plate",
    name: "Deep Rift Plate",
    rarity: "LEGENDARY",
    armorClass: "CHEST",
    affinity: "VOID",
    description: "Plate etched with quiet rift seams.",
    weightClass: "HEAVY",
    defense: 14,
    maxHp: 8,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Resistant"],
  }),
  a({
    id: "armor-of-the-rift-guardian",
    name: "Armor of the Rift Guardian",
    rarity: "MYTHIC",
    armorClass: "COSMETIC_SET",
    affinity: null,
    description: "Specialized guardian set — combat values capped.",
    weightClass: "MEDIUM",
    defense: 14,
    maxHp: 12,
    anatomy: ["chest", "back"],
    attachment: "chest",
    affixes: ["Guarded", "Bonded"],
    cosmeticEffect: "Dimensional sheen",
  }),
  a({
    id: "constellation-armor",
    name: "Constellation Armor",
    rarity: "CELESTIAL",
    armorClass: "COSMETIC_SET",
    affinity: "RADIANT",
    description: "Cosmic prestige set — primarily visual.",
    weightClass: "LIGHT",
    defense: 12,
    maxHp: 10,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Bonded"],
    cosmeticEffect: "Constellation particles",
  }),
  // Expansion batch — pet armor & cosmetics
  a({
    id: "linen-ear-hood",
    name: "Linen Ear Hood",
    rarity: "COMMON",
    armorClass: "HEAD",
    affinity: null,
    description: "Soft linen hood that keeps ears cozy in drills.",
    weightClass: "LIGHT",
    defense: 2,
    maxHp: 2,
    anatomy: ["head"],
    attachment: "head",
  }),
  a({
    id: "reed-chest-wrap",
    name: "Reed Chest Wrap",
    rarity: "COMMON",
    armorClass: "CHEST",
    affinity: "GROVE",
    description: "Braided reed wrap for light chest cover.",
    weightClass: "LIGHT",
    defense: 3,
    maxHp: 3,
    anatomy: ["chest"],
    attachment: "chest",
  }),
  a({
    id: "mossy-back-cape",
    name: "Mossy Back Cape",
    rarity: "COMMON",
    armorClass: "BACK",
    affinity: "GROVE",
    description: "Damp moss cape that cushions rear blows.",
    weightClass: "LIGHT",
    defense: 2,
    maxHp: 3,
    anatomy: ["back"],
    attachment: "back",
  }),
  a({
    id: "pebble-paw-boots",
    name: "Pebble Paw Boots",
    rarity: "COMMON",
    armorClass: "PAW",
    affinity: "STONE",
    description: "Stone-bead boots for rocky trail practice.",
    weightClass: "MEDIUM",
    defense: 3,
    maxHp: 1,
    anatomy: ["frontPaw", "rearPaw"],
    attachment: "frontPawLeft",
  }),
  a({
    id: "soft-tail-sleeve",
    name: "Soft Tail Sleeve",
    rarity: "COMMON",
    armorClass: "TAIL",
    affinity: null,
    description: "Padded sleeve that protects a swishing tip.",
    weightClass: "LIGHT",
    defense: 2,
    maxHp: 1,
    anatomy: ["tailBase", "tailMiddle"],
    attachment: "tailBase",
  }),
  a({
    id: "breeze-wing-bands",
    name: "Breeze Wing Bands",
    rarity: "COMMON",
    armorClass: "WING",
    affinity: "STORM",
    description: "Airy bands that steady wingbeats in training.",
    weightClass: "LIGHT",
    defense: 1,
    maxHp: 2,
    anatomy: ["wingLeft", "wingRight"],
    attachment: "wingLeft",
  }),
  a({
    id: "tidefoam-collar",
    name: "Tidefoam Collar",
    rarity: "UNCOMMON",
    armorClass: "HEAD",
    affinity: "TIDE",
    description: "Foam-bright collar that cools the neck.",
    weightClass: "LIGHT",
    defense: 3,
    maxHp: 4,
    anatomy: ["neck", "head"],
    attachment: "neck",
    affixes: ["Restorative"],
  }),
  a({
    id: "ember-scale-vest",
    name: "Ember Scale Vest",
    rarity: "UNCOMMON",
    armorClass: "CHEST",
    affinity: "EMBER",
    description: "Overlapping ember scales that shed sparks.",
    weightClass: "MEDIUM",
    defense: 7,
    maxHp: 5,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Resistant"],
  }),
  a({
    id: "frost-pelt-cloak",
    name: "Frost Pelt Cloak",
    rarity: "UNCOMMON",
    armorClass: "BACK",
    affinity: "FROST",
    description: "Chilled pelt cloak that muffles cold bites.",
    weightClass: "MEDIUM",
    defense: 5,
    maxHp: 6,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Resistant"],
  }),
  a({
    id: "storm-grip-wraps",
    name: "Storm Grip Wraps",
    rarity: "UNCOMMON",
    armorClass: "PAW",
    affinity: "STORM",
    description: "Static-laced wraps that tighten mid-leap.",
    weightClass: "LIGHT",
    defense: 3,
    maxHp: 2,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
    affixes: ["Swift"],
  }),
  a({
    id: "grove-tail-guard",
    name: "Grove Tail Guard",
    rarity: "UNCOMMON",
    armorClass: "TAIL",
    affinity: "GROVE",
    description: "Bark-ring guard that steadies wild thrashing.",
    weightClass: "MEDIUM",
    defense: 4,
    maxHp: 3,
    anatomy: ["tailBase"],
    attachment: "tailBase",
    affixes: ["Guarded"],
  }),
  a({
    id: "radiant-wing-veils",
    name: "Radiant Wing Veils",
    rarity: "RARE",
    armorClass: "WING",
    affinity: "RADIANT",
    description: "Sheer dawn veils that catch soft sunfire.",
    weightClass: "LIGHT",
    defense: 4,
    maxHp: 6,
    anatomy: ["wingLeft", "wingRight"],
    attachment: "wingLeft",
    affixes: ["Bonded", "Swift"],
    cosmeticEffect: "Soft dawn wing shimmer",
  }),
  a({
    id: "alloy-rib-cuirass",
    name: "Alloy Rib Cuirass",
    rarity: "RARE",
    armorClass: "CHEST",
    affinity: "ALLOY",
    description: "Ribbed hex cuirass with teal rivet seams.",
    weightClass: "HEAVY",
    defense: 11,
    maxHp: 5,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Strong"],
  }),
  a({
    id: "voidmist-hood",
    name: "Voidmist Hood",
    rarity: "RARE",
    armorClass: "HEAD",
    affinity: "VOID",
    description: "Hood that veils the face in quiet mist.",
    weightClass: "LIGHT",
    defense: 5,
    maxHp: 5,
    anatomy: ["head"],
    attachment: "head",
    affixes: ["Focused", "Resistant"],
  }),
  a({
    id: "spiritweave-sash",
    name: "Spiritweave Sash",
    rarity: "RARE",
    armorClass: "BACK",
    affinity: "SPIRIT",
    description: "Sash of woven spirit thread across the back.",
    weightClass: "LIGHT",
    defense: 5,
    maxHp: 7,
    anatomy: ["back", "chest"],
    attachment: "back",
    affixes: ["Restorative", "Bonded"],
  }),
  a({
    id: "glacial-barrier-shell",
    name: "Glacial Barrier Shell",
    rarity: "EPIC",
    armorClass: "BARRIER",
    affinity: "FROST",
    description: "Curved ice shell that rings when struck.",
    weightClass: "HEAVY",
    defense: 12,
    maxHp: 8,
    anatomy: ["chest"],
    attachment: "chest",
    affixes: ["Guarded", "Resistant", "Strong"],
    cosmeticEffect: "Frost rim flash",
  }),
  a({
    id: "constellation-paw-slippers",
    name: "Constellation Paw Slippers",
    rarity: "MYTHIC",
    armorClass: "COSMETIC_SET",
    affinity: "RADIANT",
    description: "Prestige paw slippers that leave star-print trails.",
    weightClass: "LIGHT",
    defense: 8,
    maxHp: 8,
    anatomy: ["frontPaw", "rearPaw"],
    attachment: "frontPawLeft",
    affixes: ["Bonded", "Swift"],
    cosmeticEffect: "Starlit paw prints",
  }),
  a({
    id: "dawnstar-plume-mantle",
    name: "Dawnstar Plume Mantle",
    rarity: "CELESTIAL",
    armorClass: "COSMETIC_SET",
    affinity: "RADIANT",
    description: "Celestial mantle of dawn plumes — prestige first.",
    weightClass: "LIGHT",
    defense: 11,
    maxHp: 11,
    anatomy: ["back", "chest"],
    attachment: "back",
    affixes: ["Bonded"],
    cosmeticEffect: "Dawn plume particles",
  }),
];

export function getArmorById(id: string) {
  return ARMOR_CATALOG.find((x) => x.id === id);
}
