import type { PotionCatalogItem, ItemRarity } from "@/lib/items/types";

function p(partial: {
  id: string;
  name: string;
  rarity: ItemRarity;
  potionType: PotionCatalogItem["potionType"];
  shopCategory: PotionCatalogItem["shopCategory"];
  family: PotionCatalogItem["family"];
  affinity: PotionCatalogItem["affinity"];
  description: string;
  effect: string;
  battleUsesMax?: number;
  statusRemoved?: string;
  careEffects?: PotionCatalogItem["careEffects"];
  stack?: number;
}): PotionCatalogItem {
  return {
    id: partial.id,
    name: partial.name,
    description: partial.description,
    family: partial.family,
    shopCategory: partial.shopCategory,
    rarity: partial.rarity,
    affinity: partial.affinity,
    levelRequirement: 1,
    tradeability: "TRADEABLE",
    ownership: "OFF_CHAIN",
    stackable: true,
    maxStack: partial.stack ?? 20,
    priceKey: partial.id,
    supply: "UNLIMITED",
    affixes: [],
    iconPath: `/assets/items/potions/icons/${partial.id}.png`,
    inventoryPath: `/assets/items/potions/icons/${partial.id}.png`,
    compatibleAnatomy: ["any"],
    potionType: partial.potionType,
    effect: partial.effect,
    battleUsesMax: partial.battleUsesMax,
    statusRemoved: partial.statusRemoved,
    careEffects: partial.careEffects,
  };
}

export const POTION_CATALOG: PotionCatalogItem[] = [
  p({
    id: "small-healing-salve",
    name: "Small Healing Salve",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "GROVE",
    description: "A modest salve for battle scrapes.",
    effect: "Restores a small percentage of battle health.",
    battleUsesMax: 2,
  }),
  p({
    id: "riftberry-tonic",
    name: "Riftberry Tonic",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Sweet berry tonic with a spark of energy.",
    effect: "Restores health and a small amount of energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "moonwater-flask",
    name: "Moonwater Flask",
    rarity: "UNCOMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "TIDE",
    description: "Cool moonwater in a crescent flask.",
    effect: "Restores moderate health.",
    battleUsesMax: 2,
  }),
  p({
    id: "grove-restoration-brew",
    name: "Grove Restoration Brew",
    rarity: "RARE",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "GROVE",
    description: "Slow-healing brew of wild herbs.",
    effect: "Restores health over several turns.",
    battleUsesMax: 1,
  }),
  p({
    id: "emberheart-elixir",
    name: "Emberheart Elixir",
    rarity: "RARE",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Warm elixir that steadies the strike.",
    effect: "Restores health and temporarily improves attack.",
    battleUsesMax: 1,
  }),
  p({
    id: "spirit-renewal-potion",
    name: "Spirit Renewal Potion",
    rarity: "EPIC",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Soft spirit draught that eases ailments.",
    effect: "Restores health and removes one negative status.",
    battleUsesMax: 1,
  }),
  p({
    id: "radiant-recovery-flask",
    name: "Radiant Recovery Flask",
    rarity: "LEGENDARY",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "RADIANT",
    description: "Dawnlight flask with a temporary shield.",
    effect: "Restores significant health and grants a temporary shield.",
    battleUsesMax: 1,
  }),
  p({
    id: "celestial-renewal",
    name: "Celestial Renewal",
    rarity: "MYTHIC",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "RADIANT",
    description: "Mythic renewal with a cosmetic celestial aura.",
    effect: "Restores health, cleanses statuses, grants cosmetic aura. Does not revive permanently deceased pets.",
    battleUsesMax: 1,
  }),
  // Energy
  p({
    id: "sparkfruit-juice",
    name: "Sparkfruit Juice",
    rarity: "COMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STORM",
    description: "Zesty juice that tops up ability energy.",
    effect: "Restores a small amount of battle energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "focus-tonic",
    name: "Focus Tonic",
    rarity: "UNCOMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Clear tonic that sharpens focus energy.",
    effect: "Restores moderate energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "storm-energy-flask",
    name: "Storm Energy Flask",
    rarity: "RARE",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STORM",
    description: "Crackling flask of bottled storm charge.",
    effect: "Restores large energy; short cooldown.",
    battleUsesMax: 1,
  }),
  p({
    id: "spirit-charge",
    name: "Spirit Charge",
    rarity: "EPIC",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Spirit-packed vial for late-round plays.",
    effect: "Restores energy and slight focus.",
    battleUsesMax: 1,
  }),
  p({
    id: "astral-energy-elixir",
    name: "Astral Energy Elixir",
    rarity: "LEGENDARY",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "VOID",
    description: "Starlit elixir for ultimate setups.",
    effect: "Restores significant energy once per battle.",
    battleUsesMax: 1,
  }),
  // Status
  ...[
    ["burn-relief-salve", "Burn Relief Salve", "EMBER", "BURN"],
    ["frost-thaw-brew", "Frost Thaw Brew", "FROST", "CHILLED"],
    ["rootbreak-tonic", "Rootbreak Tonic", "GROVE", "ROOTED"],
    ["static-cleanser", "Static Cleanser", "STORM", "CHARGED"],
    ["void-purification-flask", "Void Purification Flask", "VOID", "SHROUDED"],
    ["spirit-calm-tea", "Spirit Calm Tea", "SPIRIT", "WEAKENED"],
    ["radiant-cleanse-potion", "Radiant Cleanse Potion", "RADIANT", "SILENCED"],
    ["alloy-repair-oil", "Alloy Repair Oil", "ALLOY", "SLOWED"],
  ].map(([id, name, aff, status]) =>
    p({
      id: id!,
      name: name!,
      rarity: "UNCOMMON",
      potionType: "STATUS",
      shopCategory: "POTIONS",
      family: "POTION",
      affinity: aff as PotionCatalogItem["affinity"],
      description: `Clears ${status} with a soft secondary calm.`,
      effect: `Removes ${status}; minor secondary soothe.`,
      statusRemoved: status,
      battleUsesMax: 1,
    }),
  ),
  // Care
  p({
    id: "basic-pet-meal",
    name: "Basic Pet Meal",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description:
      "Companion Care food — restores hunger outside battle. Not a combat spell.",
    effect: "Feed Companion: restore hunger, +bond, small care XP.",
    careEffects: { hunger: 25, happiness: 5, bond: 3 },
    stack: 50,
  }),
  p({
    id: "premium-pet-meal",
    name: "Premium Pet Meal",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Larger meal for convenience — not required to keep pets healthy.",
    effect: "Restores more hunger and happiness.",
    careEffects: { hunger: 40, happiness: 15 },
  }),
  p({
    id: "fresh-water-flask",
    name: "Fresh Water Flask",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "TIDE",
    description: "Clean water for hydration care.",
    effect: "Improves hydration/energy lightly.",
    careEffects: { energy: 10, hygiene: 5 },
  }),
  p({
    id: "cleaning-kit",
    name: "Cleaning Kit",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Brushes and soft cloths for hygiene.",
    effect: "Improves hygiene.",
    careEffects: { hygiene: 30 },
  }),
  p({
    id: "rift-toy",
    name: "Rift Toy",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "A playful toy that lifts spirits.",
    effect: "Improves happiness.",
    careEffects: { happiness: 25 },
  }),
  p({
    id: "comfortable-nest",
    name: "Comfortable Nest",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Soft nest for restful recovery.",
    effect: "Improves energy and happiness.",
    careEffects: { energy: 20, happiness: 10 },
  }),
  p({
    id: "medicine-pack",
    name: "Medicine Pack",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Out-of-battle recovery for tired pets.",
    effect: "Restores care health. Cannot revive permanently deceased pets.",
    careEffects: { health: 25 },
  }),
  p({
    id: "happiness-treat",
    name: "Happiness Treat",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "A small treat for bonding moments.",
    effect: "Improves happiness and bond.",
    careEffects: { happiness: 15, bond: 5 },
  }),
  p({
    id: "bonding-charm",
    name: "Bonding Charm",
    rarity: "RARE",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "SPIRIT",
    description: "Charm that deepens keeper-pet bond.",
    effect: "Improves bond significantly.",
    careEffects: { bond: 20, happiness: 10 },
  }),
  p({
    id: "recovery-blanket",
    name: "Recovery Blanket",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: null,
    description: "Warm blanket for post-battle rest.",
    effect: "Restores energy and comfort.",
    careEffects: { energy: 25, happiness: 10 },
  }),
  p({
    id: "dormancy-revival-bloom",
    name: "Dormancy Revival Bloom",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "GROVE",
    description: "Helps wake dormant pets — never permanent death revival.",
    effect: "Assists recovery from dormancy when permanent death is disabled.",
    careEffects: { health: 40, energy: 20, happiness: 15 },
  }),
  // Expansion batch — potions, toys, care & recovery
  p({
    id: "spark-healing-draught",
    name: "Spark Healing Draught",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Warm draught that knits light battle scrapes.",
    effect: "Restores a small amount of battle health.",
    battleUsesMax: 2,
  }),
  p({
    id: "tide-mend-vial",
    name: "Tide Mend Vial",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "TIDE",
    description: "Cool vial that soothes tide-worn hides.",
    effect: "Restores a small amount of battle health.",
    battleUsesMax: 2,
  }),
  p({
    id: "storm-surge-sip",
    name: "Storm Surge Sip",
    rarity: "UNCOMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STORM",
    description: "Crackling sip that wakes tired storm affinity.",
    effect: "Restores moderate battle energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "frost-focus-brew",
    name: "Frost Focus Brew",
    rarity: "UNCOMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "FROST",
    description: "Chilled brew that sharpens casting focus.",
    effect: "Restores energy and lightly steadies aim.",
    battleUsesMax: 1,
  }),
  p({
    id: "ember-soothe-balm",
    name: "Ember Soothe Balm",
    rarity: "UNCOMMON",
    potionType: "STATUS",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Cooling balm for overheated ember burns.",
    effect: "Removes BURN; minor calm.",
    statusRemoved: "BURN",
    battleUsesMax: 1,
  }),
  p({
    id: "stone-steady-draught",
    name: "Stone Steady Draught",
    rarity: "UNCOMMON",
    potionType: "STATUS",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STONE",
    description: "Earthen draught that settles rattled footing.",
    effect: "Removes SLOWED; minor footing steadiness.",
    statusRemoved: "SLOWED",
    battleUsesMax: 1,
  }),
  p({
    id: "crystal-berry-snack",
    name: "Crystal Berry Snack",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Crunchy crystal berries for happy snacks.",
    effect: "Restores hunger and a touch of happiness.",
    careEffects: { hunger: 20, happiness: 12 },
    stack: 40,
  }),
  p({
    id: "glowmoss-chew",
    name: "Glowmoss Chew",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "GROVE",
    description: "Soft glowing moss stick for chewing play.",
    effect: "Improves happiness and lightly eases stress.",
    careEffects: { happiness: 18, hygiene: 5 },
  }),
  p({
    id: "ripple-ball-toy",
    name: "Ripple Ball Toy",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "TIDE",
    description: "Bouncy toy that leaves soft ripple trails.",
    effect: "Improves happiness through play.",
    careEffects: { happiness: 28, bond: 4 },
  }),
  p({
    id: "whisper-bell-toy",
    name: "Whisper Bell Toy",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "SPIRIT",
    description: "Tiny bell that chimes soft spirit notes.",
    effect: "Improves happiness and bond.",
    careEffects: { happiness: 22, bond: 10 },
  }),
  p({
    id: "nest-fluff-pillow",
    name: "Nest Fluff Pillow",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Cloud-soft pillow for nest naps.",
    effect: "Improves energy and happiness.",
    careEffects: { energy: 25, happiness: 12 },
  }),
  p({
    id: "grooming-comb-set",
    name: "Grooming Comb Set",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Fine combs and soft brushes for coat care.",
    effect: "Improves hygiene and calm.",
    careEffects: { hygiene: 35, happiness: 8 },
  }),
  p({
    id: "bond-ribbon",
    name: "Bond Ribbon",
    rarity: "RARE",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "SPIRIT",
    description: "Woven ribbon worn during bonding rituals.",
    effect: "Deepens keeper-pet bond.",
    careEffects: { bond: 25, happiness: 12 },
  }),
  p({
    id: "aurora-treat",
    name: "Aurora Treat",
    rarity: "RARE",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "RADIANT",
    description: "Shimmering treat dusted with dawn sugar.",
    effect: "Restores hunger and lifts spirits brightly.",
    careEffects: { hunger: 30, happiness: 25, bond: 8 },
  }),
  p({
    id: "moonpetal-bath-salts",
    name: "Moonpetal Bath Salts",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "TIDE",
    description: "Fragrant salts for a moonlit rinse.",
    effect: "Improves hygiene and soothes stress.",
    careEffects: { hygiene: 40, happiness: 10 },
  }),
  p({
    id: "vitality-petal-tea",
    name: "Vitality Petal Tea",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "GROVE",
    description: "Warm petal tea for post-adventure rest.",
    effect: "Restores care health and energy lightly.",
    careEffects: { health: 20, energy: 15, happiness: 8 },
  }),
  p({
    id: "rift-salve-kit",
    name: "Rift Salve Kit",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Field kit of salves for tired companions.",
    effect: "Restores care health substantially.",
    careEffects: { health: 35, energy: 10 },
  }),
  p({
    id: "starlit-lullaby-charm",
    name: "Starlit Lullaby Charm",
    rarity: "EPIC",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "RADIANT",
    description: "Charm that hums a soft lullaby at nesttime.",
    effect: "Improves energy, bond, and happiness.",
    careEffects: { energy: 30, bond: 15, happiness: 20 },
  }),
  // ─── Spirit recovery items (Downed → Recovered; never Hardcore permadeath) ──
  p({
    id: "spirit-crystal",
    name: "Spirit Crystal",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Faceted crystal that steadies a Downed Riftling's breath.",
    effect: "Recovers a Downed or Spirit Form Riftling. Cannot reverse Hardcore permadeath.",
    careEffects: { health: 55, stress: -20 },
  }),
  p({
    id: "phoenix-feather",
    name: "Phoenix Feather",
    rarity: "EPIC",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "EMBER",
    description: "Warm feather that calls companions back from the lantern shore.",
    effect: "Recovers a Downed Riftling. Never required to use SOL.",
    careEffects: { health: 70, happiness: 15 },
  }),
  p({
    id: "ancient-heart",
    name: "Ancient Heart",
    rarity: "LEGENDARY",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Stone heart humming with ancestral warmth.",
    effect: "Powerful recovery from Spirit Form.",
    careEffects: { health: 80, bond: 10 },
  }),
  p({
    id: "revival-herb",
    name: "Revival Herb",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "GROVE",
    description: "Bitter herb used by Commons healers.",
    effect: "Recovers a Downed Riftling.",
    careEffects: { health: 45 },
  }),
  p({
    id: "healing-stone",
    name: "Healing Stone",
    rarity: "COMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "STONE",
    description: "Smooth river stone warmed at the Recovery Center.",
    effect: "Modest recovery from Downed state.",
    careEffects: { health: 35 },
  }),
  p({
    id: "soul-bloom",
    name: "Soul Bloom",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Bloom that opens only in the Spirit Realm mist.",
    effect: "Recovers Spirit Form companions.",
    careEffects: { health: 50, stress: -15 },
  }),
  p({
    id: "moon-tear",
    name: "Moon Tear",
    rarity: "EPIC",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "TIDE",
    description: "Cool droplet said to remember every keeper's name.",
    effect: "Recovers Downed Riftlings; bond dialogue softens.",
    careEffects: { health: 60, bond: 8 },
  }),
  p({
    id: "heart-flame",
    name: "Heart Flame",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "EMBER",
    description: "Gentle flame that never burns fur or feather.",
    effect: "Recovers a Downed Riftling.",
    careEffects: { health: 55, energy: 15 },
  }),
  p({
    id: "sacred-feather",
    name: "Sacred Feather",
    rarity: "EPIC",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "RADIANT",
    description: "Feather left at Ancestor Council gatherings.",
    effect: "Recovers Spirit Form; unlocks soft ancestor dialogue.",
    careEffects: { health: 65, happiness: 12 },
  }),
  p({
    id: "ancestor-stone",
    name: "Ancestor Stone",
    rarity: "LEGENDARY",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Carved stone of family history — lore only, never combat power.",
    effect: "Recovers and marks a memory for museum lore.",
    careEffects: { health: 75, bond: 12 },
  }),
  p({
    id: "ancient-bell",
    name: "Ancient Bell",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "STORM",
    description: "Bell tone that orients lost spirits toward home.",
    effect: "Recovers Downed Riftlings.",
    careEffects: { health: 50 },
  }),
  p({
    id: "revival-water",
    name: "Revival Water",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "TIDE",
    description: "Clear water drawn from temple basins.",
    effect: "Recovers a Downed Riftling.",
    careEffects: { health: 40, thirst: 20 },
  }),
  p({
    id: "healing-rune",
    name: "Healing Rune",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "VOID",
    description: "Rune etched with return-breath glyphs.",
    effect: "Recovers Spirit Form companions.",
    careEffects: { health: 55, stress: -10 },
  }),
  p({
    id: "spirit-lantern-charm",
    name: "Spirit Lantern Charm",
    rarity: "EPIC",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Tiny lantern charm for keepers walking the Realm.",
    effect: "Recovers Downed Riftlings; cosmetic lantern glow.",
    careEffects: { health: 60, happiness: 10 },
  }),
];

export function getPotionById(id: string) {
  return POTION_CATALOG.find((x) => x.id === id);
}
