import type { PotionCatalogItem, ItemRarity } from "@/lib/items/types";

function p(partial: {
  id: string;
  name: string;
  rarity: ItemRarity;
  potionType: PotionCatalogItem["potionType"];
  shopCategory: PotionCatalogItem["shopCategory"];
  family: PotionCatalogItem["family"];
  affinity: PotionCatalogItem["affinity"];
  description: string;
  effect: string;
  battleUsesMax?: number;
  statusRemoved?: string;
  careEffects?: PotionCatalogItem["careEffects"];
  stack?: number;
}): PotionCatalogItem {
  return {
    id: partial.id,
    name: partial.name,
    description: partial.description,
    family: partial.family,
    shopCategory: partial.shopCategory,
    rarity: partial.rarity,
    affinity: partial.affinity,
    levelRequirement: 1,
    tradeability: "TRADEABLE",
    ownership: "OFF_CHAIN",
    stackable: true,
    maxStack: partial.stack ?? 20,
    priceKey: partial.id,
    supply: "UNLIMITED",
    affixes: [],
    iconPath: `/assets/items/potions/icons/${partial.id}.png`,
    inventoryPath: `/assets/items/potions/icons/${partial.id}.png`,
    compatibleAnatomy: ["any"],
    potionType: partial.potionType,
    effect: partial.effect,
    battleUsesMax: partial.battleUsesMax,
    statusRemoved: partial.statusRemoved,
    careEffects: partial.careEffects,
  };
}

export const POTION_CATALOG: PotionCatalogItem[] = [
  p({
    id: "small-healing-salve",
    name: "Small Healing Salve",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "GROVE",
    description: "A modest salve for battle scrapes.",
    effect: "Restores a small percentage of battle health.",
    battleUsesMax: 2,
  }),
  p({
    id: "riftberry-tonic",
    name: "Riftberry Tonic",
    rarity: "COMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Sweet berry tonic with a spark of energy.",
    effect: "Restores health and a small amount of energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "moonwater-flask",
    name: "Moonwater Flask",
    rarity: "UNCOMMON",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "TIDE",
    description: "Cool moonwater in a crescent flask.",
    effect: "Restores moderate health.",
    battleUsesMax: 2,
  }),
  p({
    id: "grove-restoration-brew",
    name: "Grove Restoration Brew",
    rarity: "RARE",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "GROVE",
    description: "Slow-healing brew of wild herbs.",
    effect: "Restores health over several turns.",
    battleUsesMax: 1,
  }),
  p({
    id: "emberheart-elixir",
    name: "Emberheart Elixir",
    rarity: "RARE",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "EMBER",
    description: "Warm elixir that steadies the strike.",
    effect: "Restores health and temporarily improves attack.",
    battleUsesMax: 1,
  }),
  p({
    id: "spirit-renewal-potion",
    name: "Spirit Renewal Potion",
    rarity: "EPIC",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Soft spirit draught that eases ailments.",
    effect: "Restores health and removes one negative status.",
    battleUsesMax: 1,
  }),
  p({
    id: "radiant-recovery-flask",
    name: "Radiant Recovery Flask",
    rarity: "LEGENDARY",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "RADIANT",
    description: "Dawnlight flask with a temporary shield.",
    effect: "Restores significant health and grants a temporary shield.",
    battleUsesMax: 1,
  }),
  p({
    id: "celestial-renewal",
    name: "Celestial Renewal",
    rarity: "MYTHIC",
    potionType: "HEALTH",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "RADIANT",
    description: "Mythic renewal with a cosmetic celestial aura.",
    effect: "Restores health, cleanses statuses, grants cosmetic aura. Does not revive permanently deceased pets.",
    battleUsesMax: 1,
  }),
  // Energy
  p({
    id: "sparkfruit-juice",
    name: "Sparkfruit Juice",
    rarity: "COMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STORM",
    description: "Zesty juice that tops up ability energy.",
    effect: "Restores a small amount of battle energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "focus-tonic",
    name: "Focus Tonic",
    rarity: "UNCOMMON",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Clear tonic that sharpens focus energy.",
    effect: "Restores moderate energy.",
    battleUsesMax: 2,
  }),
  p({
    id: "storm-energy-flask",
    name: "Storm Energy Flask",
    rarity: "RARE",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "STORM",
    description: "Crackling flask of bottled storm charge.",
    effect: "Restores large energy; short cooldown.",
    battleUsesMax: 1,
  }),
  p({
    id: "spirit-charge",
    name: "Spirit Charge",
    rarity: "EPIC",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "SPIRIT",
    description: "Spirit-packed vial for late-round plays.",
    effect: "Restores energy and slight focus.",
    battleUsesMax: 1,
  }),
  p({
    id: "astral-energy-elixir",
    name: "Astral Energy Elixir",
    rarity: "LEGENDARY",
    potionType: "ENERGY",
    shopCategory: "POTIONS",
    family: "POTION",
    affinity: "VOID",
    description: "Starlit elixir for ultimate setups.",
    effect: "Restores significant energy once per battle.",
    battleUsesMax: 1,
  }),
  // Status
  ...[
    ["burn-relief-salve", "Burn Relief Salve", "EMBER", "BURN"],
    ["frost-thaw-brew", "Frost Thaw Brew", "FROST", "CHILLED"],
    ["rootbreak-tonic", "Rootbreak Tonic", "GROVE", "ROOTED"],
    ["static-cleanser", "Static Cleanser", "STORM", "CHARGED"],
    ["void-purification-flask", "Void Purification Flask", "VOID", "SHROUDED"],
    ["spirit-calm-tea", "Spirit Calm Tea", "SPIRIT", "WEAKENED"],
    ["radiant-cleanse-potion", "Radiant Cleanse Potion", "RADIANT", "SILENCED"],
    ["alloy-repair-oil", "Alloy Repair Oil", "ALLOY", "SLOWED"],
  ].map(([id, name, aff, status]) =>
    p({
      id: id!,
      name: name!,
      rarity: "UNCOMMON",
      potionType: "STATUS",
      shopCategory: "POTIONS",
      family: "POTION",
      affinity: aff as PotionCatalogItem["affinity"],
      description: `Clears ${status} with a soft secondary calm.`,
      effect: `Removes ${status}; minor secondary soothe.`,
      statusRemoved: status,
      battleUsesMax: 1,
    }),
  ),
  // Care
  p({
    id: "basic-pet-meal",
    name: "Basic Pet Meal",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Free-path compatible meal — also sold in convenience packs.",
    effect: "Restores hunger. Gameplay-earned meals also available.",
    careEffects: { hunger: 25, happiness: 5 },
    stack: 50,
  }),
  p({
    id: "premium-pet-meal",
    name: "Premium Pet Meal",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Larger meal for convenience — not required to keep pets healthy.",
    effect: "Restores more hunger and happiness.",
    careEffects: { hunger: 40, happiness: 15 },
  }),
  p({
    id: "fresh-water-flask",
    name: "Fresh Water Flask",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "TIDE",
    description: "Clean water for hydration care.",
    effect: "Improves hydration/energy lightly.",
    careEffects: { energy: 10, hygiene: 5 },
  }),
  p({
    id: "cleaning-kit",
    name: "Cleaning Kit",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Brushes and soft cloths for hygiene.",
    effect: "Improves hygiene.",
    careEffects: { hygiene: 30 },
  }),
  p({
    id: "rift-toy",
    name: "Rift Toy",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "A playful toy that lifts spirits.",
    effect: "Improves happiness.",
    careEffects: { happiness: 25 },
  }),
  p({
    id: "comfortable-nest",
    name: "Comfortable Nest",
    rarity: "UNCOMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "Soft nest for restful recovery.",
    effect: "Improves energy and happiness.",
    careEffects: { energy: 20, happiness: 10 },
  }),
  p({
    id: "medicine-pack",
    name: "Medicine Pack",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "SPIRIT",
    description: "Out-of-battle recovery for tired pets.",
    effect: "Restores care health. Cannot revive permanently deceased pets.",
    careEffects: { health: 25 },
  }),
  p({
    id: "happiness-treat",
    name: "Happiness Treat",
    rarity: "COMMON",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: null,
    description: "A small treat for bonding moments.",
    effect: "Improves happiness and bond.",
    careEffects: { happiness: 15, bond: 5 },
  }),
  p({
    id: "bonding-charm",
    name: "Bonding Charm",
    rarity: "RARE",
    potionType: "CARE",
    shopCategory: "CARE",
    family: "CARE",
    affinity: "SPIRIT",
    description: "Charm that deepens keeper-pet bond.",
    effect: "Improves bond significantly.",
    careEffects: { bond: 20, happiness: 10 },
  }),
  p({
    id: "recovery-blanket",
    name: "Recovery Blanket",
    rarity: "UNCOMMON",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: null,
    description: "Warm blanket for post-battle rest.",
    effect: "Restores energy and comfort.",
    careEffects: { energy: 25, happiness: 10 },
  }),
  p({
    id: "dormancy-revival-bloom",
    name: "Dormancy Revival Bloom",
    rarity: "RARE",
    potionType: "RECOVERY",
    shopCategory: "RECOVERY",
    family: "RECOVERY",
    affinity: "GROVE",
    description: "Helps wake dormant pets — never permanent death revival.",
    effect: "Assists recovery from dormancy when permanent death is disabled.",
    careEffects: { health: 40, energy: 20, happiness: 15 },
  }),
];

export function getPotionById(id: string) {
  return POTION_CATALOG.find((x) => x.id === id);
}
