import type { WeaponCatalogItem, ItemRarity, AttachmentPoint } from "@/lib/items/types";

function asset(id: string) {
  return {
    iconPath: `/assets/items/weapons/icons/${id}.png`,
    inventoryPath: `/assets/items/weapons/icons/${id}.png`,
  };
}

function w(partial: {
  id: string;
  name: string;
  rarity: ItemRarity;
  weaponClass: WeaponCatalogItem["weaponClass"];
  affinity: WeaponCatalogItem["affinity"];
  description: string;
  attack: number;
  defense: number;
  speed: number;
  anatomy: string[];
  attachment: AttachmentPoint;
  affixes?: WeaponCatalogItem["affixes"];
  passive?: string;
  supply?: WeaponCatalogItem["supply"];
  totalSupply?: number;
}): WeaponCatalogItem {
  return {
    id: partial.id,
    name: partial.name,
    description: partial.description,
    family: "WEAPON",
    shopCategory: "WEAPONS",
    rarity: partial.rarity,
    affinity: partial.affinity,
    levelRequirement: partial.rarity === "COMMON" ? 1 : partial.rarity === "UNCOMMON" ? 3 : 5,
    tradeability: partial.rarity === "CELESTIAL" ? "ACCOUNT_BOUND" : "TRADEABLE",
    ownership: ["MYTHIC", "CELESTIAL"].includes(partial.rarity)
      ? "ON_CHAIN_OPTIONAL"
      : "OFF_CHAIN",
    stackable: false,
    maxStack: 1,
    priceKey: partial.id,
    supply: partial.supply ?? "UNLIMITED",
    totalSupply: partial.totalSupply,
    remainingSupply: partial.totalSupply,
    affixes: partial.affixes ?? [],
    ...asset(partial.id),
    compatibleAnatomy: partial.anatomy,
    attachment: partial.attachment,
    weaponClass: partial.weaponClass,
    stats: {
      attack: partial.attack,
      defense: partial.defense,
      speed: partial.speed,
    },
    passive: partial.passive,
  };
}

/** Required starter weapon list (40) — original Riftwilds fantasy gear. */
export const WEAPON_CATALOG: WeaponCatalogItem[] = [
  // Common
  w({
    id: "wooden-paw-guard",
    name: "Wooden Paw Guard",
    rarity: "COMMON",
    weaponClass: "CLAW",
    affinity: "GROVE",
    description: "Sand-smooth wood caps for practice swipes.",
    attack: 2,
    defense: 1,
    speed: 0,
    anatomy: ["frontPaw", "quadruped", "biped"],
    attachment: "frontPawLeft",
  }),
  w({
    id: "smooth-stone-claw",
    name: "Smooth Stone Claw",
    rarity: "COMMON",
    weaponClass: "CLAW",
    affinity: "STONE",
    description: "River-polished stone tips for entry battles.",
    attack: 3,
    defense: 0,
    speed: 0,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
  }),
  w({
    id: "training-tail-ring",
    name: "Training Tail Ring",
    rarity: "COMMON",
    weaponClass: "TAIL",
    affinity: null,
    description: "Lightweight practice ring for tail control.",
    attack: 1,
    defense: 0,
    speed: 2,
    anatomy: ["tailBase", "tailTip"],
    attachment: "tailBase",
  }),
  w({
    id: "basic-focus-orb",
    name: "Basic Focus Orb",
    rarity: "COMMON",
    weaponClass: "FLOATING_FOCUS",
    affinity: "SPIRIT",
    description: "A dim hovering orb for first magic drills.",
    attack: 2,
    defense: 0,
    speed: 1,
    anatomy: ["floatingFocus", "spirit"],
    attachment: "floatingFocus",
  }),
  w({
    id: "cloth-battle-harness",
    name: "Cloth Battle Harness",
    rarity: "COMMON",
    weaponClass: "HARNESS",
    affinity: null,
    description: "Soft cloth rig that launches harmless training seeds.",
    attack: 2,
    defense: 1,
    speed: 0,
    anatomy: ["back", "harness"],
    attachment: "back",
  }),
  w({
    id: "grove-twig-wand",
    name: "Grove Twig Wand",
    rarity: "COMMON",
    weaponClass: "FLOATING_FOCUS",
    affinity: "GROVE",
    description: "A budding twig focus that floats beside the caster.",
    attack: 2,
    defense: 0,
    speed: 1,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
  }),
  w({
    id: "simple-horncap",
    name: "Simple Horncap",
    rarity: "COMMON",
    weaponClass: "HORN",
    affinity: "STONE",
    description: "Plain mineral caps for horned practice charges.",
    attack: 3,
    defense: 1,
    speed: 0,
    anatomy: ["horn", "head"],
    attachment: "horn",
  }),
  // Uncommon
  w({
    id: "ember-talons",
    name: "Ember Talons",
    rarity: "UNCOMMON",
    weaponClass: "CLAW",
    affinity: "EMBER",
    description: "Coal-black claw caps that spark on impact.",
    attack: 5,
    defense: 0,
    speed: 1,
    anatomy: ["frontPaw", "quadruped", "biped"],
    attachment: "frontPawLeft",
    affixes: ["Strong"],
  }),
  w({
    id: "tideglass-claws",
    name: "Tideglass Claws",
    rarity: "UNCOMMON",
    weaponClass: "CLAW",
    affinity: "TIDE",
    description: "Translucent claw sheaths with flowing runes.",
    attack: 4,
    defense: 1,
    speed: 1,
    anatomy: ["frontPaw", "biped"],
    attachment: "frontPawLeft",
    affixes: ["Focused"],
  }),
  w({
    id: "mossvine-grips",
    name: "Mossvine Grips",
    rarity: "UNCOMMON",
    weaponClass: "CLAW",
    affinity: "GROVE",
    description: "Living vine wraps that steady the strike.",
    attack: 4,
    defense: 2,
    speed: 0,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
    affixes: ["Guarded"],
  }),
  w({
    id: "spark-tail-ring",
    name: "Spark Tail Ring",
    rarity: "UNCOMMON",
    weaponClass: "TAIL",
    affinity: "STORM",
    description: "A crackling ribbon ring for quick lashes.",
    attack: 3,
    defense: 0,
    speed: 3,
    anatomy: ["tailBase"],
    attachment: "tailBase",
    affixes: ["Swift"],
  }),
  w({
    id: "frost-crystal-tip",
    name: "Frost Crystal Tip",
    rarity: "UNCOMMON",
    weaponClass: "TAIL",
    affinity: "FROST",
    description: "Icy tip that leaves a chill trail.",
    attack: 4,
    defense: 1,
    speed: 1,
    anatomy: ["tailTip"],
    attachment: "tailTip",
    affixes: ["Precise"],
  }),
  w({
    id: "spirit-glow-orb",
    name: "Spirit Glow Orb",
    rarity: "UNCOMMON",
    weaponClass: "FLOATING_FOCUS",
    affinity: "SPIRIT",
    description: "Warm lantern-light focus for spirit pets.",
    attack: 3,
    defense: 1,
    speed: 2,
    anatomy: ["floatingFocus", "spirit"],
    attachment: "floatingFocus",
    affixes: ["Bonded"],
  }),
  w({
    id: "alloy-training-blade",
    name: "Alloy Training Blade",
    rarity: "UNCOMMON",
    weaponClass: "TAIL",
    affinity: "ALLOY",
    description: "Segmented practice blade for alloy species.",
    attack: 5,
    defense: 0,
    speed: 1,
    anatomy: ["tailTip", "harness"],
    attachment: "tailTip",
    affixes: ["Strong"],
  }),
  // Rare
  w({
    id: "ashfang-talons",
    name: "Ashfang Talons",
    rarity: "RARE",
    weaponClass: "CLAW",
    affinity: "EMBER",
    description: "Ash-tempered fang claws with ember vents.",
    attack: 7,
    defense: 1,
    speed: 1,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
    affixes: ["Strong", "Affinity-Tuned"],
  }),
  w({
    id: "moonwater-pearl",
    name: "Moonwater Pearl",
    rarity: "RARE",
    weaponClass: "FLOATING_FOCUS",
    affinity: "TIDE",
    description: "Luminous pearl focus cradled in a water halo.",
    attack: 6,
    defense: 2,
    speed: 1,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Restorative", "Focused"],
  }),
  w({
    id: "thornroot-crusher",
    name: "Thornroot Crusher",
    rarity: "RARE",
    weaponClass: "HORN",
    affinity: "GROVE",
    description: "Rooted crest that channels thorny force.",
    attack: 7,
    defense: 3,
    speed: 0,
    anatomy: ["horn", "head"],
    attachment: "horn",
    affixes: ["Guarded", "Strong"],
  }),
  w({
    id: "stormcoil-harness",
    name: "Stormcoil Harness",
    rarity: "RARE",
    weaponClass: "HARNESS",
    affinity: "STORM",
    description: "Back pack of copper coils launching arc ribbons.",
    attack: 6,
    defense: 1,
    speed: 2,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Energized", "Swift"],
  }),
  w({
    id: "obsidian-tailblade",
    name: "Obsidian Tailblade",
    rarity: "RARE",
    weaponClass: "TAIL",
    affinity: "VOID",
    description: "Crescent volcanic glass blade for the tail tip.",
    attack: 8,
    defense: 0,
    speed: 1,
    anatomy: ["tailTip"],
    attachment: "tailTip",
    affixes: ["Precise", "Strong"],
  }),
  w({
    id: "radiant-sun-disk",
    name: "Radiant Sun Disk",
    rarity: "RARE",
    weaponClass: "FLOATING_FOCUS",
    affinity: "RADIANT",
    description: "Hovering sun-disk that flares on command.",
    attack: 6,
    defense: 1,
    speed: 2,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Focused", "Affinity-Tuned"],
  }),
  w({
    id: "voidshade-claws",
    name: "Voidshade Claws",
    rarity: "RARE",
    weaponClass: "CLAW",
    affinity: "VOID",
    description: "Shadow-edged claws that blur mid-swipe.",
    attack: 7,
    defense: 0,
    speed: 2,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
    affixes: ["Swift", "Precise"],
  }),
  // Epic
  w({
    id: "cinderstorm-gauntlets",
    name: "Cinderstorm Gauntlets",
    rarity: "EPIC",
    weaponClass: "CLAW",
    affinity: "EMBER",
    description: "Storm-fed ember gauntlets with swirling ash.",
    attack: 9,
    defense: 2,
    speed: 1,
    anatomy: ["frontPaw"],
    attachment: "frontPawLeft",
    affixes: ["Strong", "Energized", "Affinity-Tuned"],
    passive: "Minor burn chance on basic strikes.",
  }),
  w({
    id: "tidal-crescent-blade",
    name: "Tidal Crescent Blade",
    rarity: "EPIC",
    weaponClass: "TAIL",
    affinity: "TIDE",
    description: "Moonlit crescent that rides tidal currents.",
    attack: 8,
    defense: 2,
    speed: 2,
    anatomy: ["tailTip"],
    attachment: "tailTip",
    affixes: ["Swift", "Restorative", "Precise"],
  }),
  w({
    id: "ancient-grove-antlers",
    name: "Ancient Grove Antlers",
    rarity: "EPIC",
    weaponClass: "HORN",
    affinity: "GROVE",
    description: "Living antler guard humming with old roots.",
    attack: 7,
    defense: 4,
    speed: 0,
    anatomy: ["horn"],
    attachment: "horn",
    affixes: ["Guarded", "Bonded", "Resistant"],
  }),
  w({
    id: "thunder-rift-coil",
    name: "Thunder Rift Coil",
    rarity: "EPIC",
    weaponClass: "HARNESS",
    affinity: "STORM",
    description: "Rift-charged coil pack for arc barrages.",
    attack: 9,
    defense: 1,
    speed: 3,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Energized", "Swift", "Strong"],
  }),
  w({
    id: "glacial-moon-crest",
    name: "Glacial Moon Crest",
    rarity: "EPIC",
    weaponClass: "HORN",
    affinity: "FROST",
    description: "Icy crest that sheds soft moonlit frost.",
    attack: 7,
    defense: 3,
    speed: 1,
    anatomy: ["head", "horn"],
    attachment: "horn",
    affixes: ["Guarded", "Focused", "Resistant"],
  }),
  w({
    id: "spiritfire-lantern",
    name: "Spiritfire Lantern",
    rarity: "EPIC",
    weaponClass: "FLOATING_FOCUS",
    affinity: "SPIRIT",
    description: "Lantern focus burning with gentle spiritflame.",
    attack: 6,
    defense: 2,
    speed: 2,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Bonded", "Restorative", "Focused"],
  }),
  w({
    id: "alloy-pulse-cannon",
    name: "Alloy Pulse Cannon",
    rarity: "EPIC",
    weaponClass: "HARNESS",
    affinity: "ALLOY",
    description:
      "Fantasy magical-energy emitter that fires soft pulse orbs — not a firearm.",
    attack: 9,
    defense: 2,
    speed: 1,
    anatomy: ["back", "harness"],
    attachment: "back",
    affixes: ["Strong", "Precise", "Energized"],
    passive: "Pulse orbs slow slightly on hit.",
  }),
  // Legendary
  w({
    id: "heart-of-the-volcano",
    name: "Heart of the Volcano",
    rarity: "LEGENDARY",
    weaponClass: "FLOATING_FOCUS",
    affinity: "EMBER",
    description: "A hovering magma core that pulses like a living forge.",
    attack: 11,
    defense: 2,
    speed: 1,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Strong", "Affinity-Tuned"],
    passive: "Unique: Ember aura cosmetic + slight attack pulse.",
    supply: "LIMITED",
    totalSupply: 500,
  }),
  w({
    id: "crown-of-the-deep-tide",
    name: "Crown of the Deep Tide",
    rarity: "LEGENDARY",
    weaponClass: "HORN",
    affinity: "TIDE",
    description: "Deep-sea crown crest with pearl cascades.",
    attack: 9,
    defense: 4,
    speed: 1,
    anatomy: ["head", "horn"],
    attachment: "head",
    affixes: ["Guarded", "Restorative"],
    passive: "Unique: Tide mist cosmetic.",
    supply: "LIMITED",
    totalSupply: 500,
  }),
  w({
    id: "elderwood-battle-crest",
    name: "Elderwood Battle Crest",
    rarity: "LEGENDARY",
    weaponClass: "HORN",
    affinity: "GROVE",
    description: "Ancient wood crest etched with root-runes.",
    attack: 9,
    defense: 5,
    speed: 0,
    anatomy: ["horn"],
    attachment: "horn",
    affixes: ["Guarded", "Bonded"],
    passive: "Unique: Leaf-fall victory effect.",
    supply: "LIMITED",
    totalSupply: 400,
  }),
  w({
    id: "skybreaker-storm-harness",
    name: "Skybreaker Storm Harness",
    rarity: "LEGENDARY",
    weaponClass: "HARNESS",
    affinity: "STORM",
    description: "Storm-forged harness that opens a sky rift ribbon.",
    attack: 11,
    defense: 2,
    speed: 3,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Swift", "Energized"],
    passive: "Unique: Lightning ribbon trail.",
    supply: "LIMITED",
    totalSupply: 400,
  }),
  w({
    id: "radiant-dawn-halo",
    name: "Radiant Dawn Halo",
    rarity: "LEGENDARY",
    weaponClass: "FLOATING_FOCUS",
    affinity: "RADIANT",
    description: "Broken-ring dawn halo of light shards.",
    attack: 9,
    defense: 2,
    speed: 2,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Focused", "Bonded"],
    passive: "Unique: Sunrise equip animation.",
    supply: "LIMITED",
    totalSupply: 350,
  }),
  w({
    id: "void-eclipse-blade",
    name: "Void Eclipse Blade",
    rarity: "LEGENDARY",
    weaponClass: "TAIL",
    affinity: "VOID",
    description: "Eclipse-edged blade that dims ambient light.",
    attack: 12,
    defense: 1,
    speed: 2,
    anatomy: ["tailTip"],
    attachment: "tailTip",
    affixes: ["Precise", "Strong"],
    passive: "Unique: Eclipse slash VFX.",
    supply: "LIMITED",
    totalSupply: 350,
  }),
  // Mythic
  w({
    id: "riftmaker-prism",
    name: "Riftmaker Prism",
    rarity: "MYTHIC",
    weaponClass: "FLOATING_FOCUS",
    affinity: "VOID",
    description: "Dimensional prism that folds soft rift light.",
    attack: 12,
    defense: 2,
    speed: 2,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Affinity-Tuned", "Focused"],
    passive: "Specialized void interaction; ranked-normalized.",
    supply: "LIMITED",
    totalSupply: 100,
  }),
  w({
    id: "worldroot-relic",
    name: "Worldroot Relic",
    rarity: "MYTHIC",
    weaponClass: "HORN",
    affinity: "GROVE",
    description: "Relic crest grown from the Worldroot myth.",
    attack: 10,
    defense: 5,
    speed: 0,
    anatomy: ["horn"],
    attachment: "horn",
    affixes: ["Guarded", "Bonded"],
    passive: "Specialized grove defense interaction.",
    supply: "LIMITED",
    totalSupply: 100,
  }),
  w({
    id: "astral-tempest-core",
    name: "Astral Tempest Core",
    rarity: "MYTHIC",
    weaponClass: "HARNESS",
    affinity: "STORM",
    description: "Astral storm core harness with constellation arcs.",
    attack: 12,
    defense: 2,
    speed: 3,
    anatomy: ["back"],
    attachment: "back",
    affixes: ["Energized", "Swift"],
    passive: "Specialized storm energy interaction.",
    supply: "LIMITED",
    totalSupply: 80,
  }),
  // Celestial
  w({
    id: "starforged-halo",
    name: "Starforged Halo",
    rarity: "CELESTIAL",
    weaponClass: "FLOATING_FOCUS",
    affinity: "RADIANT",
    description: "Cosmic halo — prestige first, combat capped.",
    attack: 10,
    defense: 2,
    speed: 2,
    anatomy: ["floatingFocus"],
    attachment: "floatingFocus",
    affixes: ["Bonded"],
    passive: "Primarily cosmetic constellation aura.",
    supply: "LIMITED",
    totalSupply: 50,
  }),
  w({
    id: "celestial-riftblade",
    name: "Celestial Riftblade",
    rarity: "CELESTIAL",
    weaponClass: "TAIL",
    affinity: null,
    description: "Star-edged blade that opens soft rift trails.",
    attack: 11,
    defense: 2,
    speed: 2,
    anatomy: ["tailTip"],
    attachment: "tailTip",
    affixes: ["Precise"],
    passive: "Prestigious VFX; ranked stats normalized.",
    supply: "LIMITED",
    totalSupply: 40,
  }),
  w({
    id: "crown-of-ten-affinities",
    name: "Crown of Ten Affinities",
    rarity: "CELESTIAL",
    weaponClass: "HORN",
    affinity: null,
    description: "Collector crown shimmering with all ten affinities.",
    attack: 9,
    defense: 4,
    speed: 1,
    anatomy: ["head", "horn"],
    attachment: "head",
    affixes: ["Bonded"],
    passive: "Ultimate prestige cosmetic; not a win guarantee.",
    supply: "LIMITED",
    totalSupply: 25,
  }),
];

export function getWeaponById(id: string): WeaponCatalogItem | undefined {
  return WEAPON_CATALOG.find((x) => x.id === id);
}
