import { REGION_BY_SLUG } from "@/game/world-maps/regions";
import {
  TILE,
  building,
  enemyZone,
  finalizeBlueprint,
  npcAt,
  portalRing,
  resourceAt,
} from "@/game/world-maps/blueprint-helpers";
import type { MapBlueprint, MapZone, PathwayDef, WorldMapObject } from "@/game/world-maps/types";

const region = REGION_BY_SLUG["riftwild-commons"]!;

/** Playable hub — expanded plaza with portal circle + key facilities. */
export function buildRiftwildCommonsBlueprint(): MapBlueprint {
  const cols = 64;
  const rows = 48;
  const T = TILE;

  const zones: MapZone[] = [
    { id: "central-plaza", name: "Central Rift Plaza", x: 18 * T, y: 14 * T, width: 28 * T, height: 16 * T, kind: "safe", safe: true },
    { id: "hatchery-zone", name: "Hatchery", x: 3 * T, y: 3 * T, width: 12 * T, height: 9 * T, kind: "settlement", safe: true },
    { id: "arena-zone", name: "Arena Entrance", x: 48 * T, y: 3 * T, width: 12 * T, height: 9 * T, kind: "settlement", safe: true },
    { id: "market-zone", name: "Rift Exchange", x: 3 * T, y: 34 * T, width: 14 * T, height: 10 * T, kind: "settlement", safe: true },
    { id: "guild-zone", name: "Guild Hall", x: 46 * T, y: 34 * T, width: 14 * T, height: 10 * T, kind: "settlement", safe: true },
    { id: "craft-zone", name: "Crafting Workshop", x: 3 * T, y: 18 * T, width: 10 * T, height: 8 * T, kind: "settlement", safe: true },
    { id: "feeding-grove", name: "Feeding Grove", x: 50 * T, y: 16 * T, width: 10 * T, height: 8 * T, kind: "settlement", safe: true },
    { id: "training-yard", name: "Training Yard", x: 38 * T, y: 12 * T, width: 10 * T, height: 8 * T, kind: "settlement", safe: true },
    { id: "fishing-pond", name: "Fishing Pond", x: 22 * T, y: 36 * T, width: 12 * T, height: 8 * T, kind: "exploration", safe: true },
    { id: "public-farm", name: "Public Farm", x: 14 * T, y: 38 * T, width: 8 * T, height: 6 * T, kind: "settlement", safe: true },
    { id: "recovery", name: "Recovery Center", x: 40 * T, y: 38 * T, width: 8 * T, height: 6 * T, kind: "settlement", safe: true },
    { id: "portal-circle", name: "Portal Circle", x: 24 * T, y: 4 * T, width: 16 * T, height: 8 * T, kind: "pathway", safe: true },
    { id: "outer-woods", name: "Outer Woods", x: 2 * T, y: 2 * T, width: 8 * T, height: 8 * T, kind: "danger", safe: false },
    { id: "secret-garden", name: "Secret Garden", x: 56 * T, y: 26 * T, width: 6 * T, height: 5 * T, kind: "hidden", safe: true },
  ];

  const pathways: PathwayDef[] = [
    { id: "plaza-to-hatchery", from: "central-plaza", to: "hatchery-zone", waypoints: [{ x: 20 * T, y: 16 * T }, { x: 10 * T, y: 10 * T }] },
    { id: "plaza-to-arena", from: "central-plaza", to: "arena-zone", waypoints: [{ x: 42 * T, y: 16 * T }, { x: 52 * T, y: 10 * T }] },
    { id: "plaza-to-market", from: "central-plaza", to: "market-zone", waypoints: [{ x: 20 * T, y: 28 * T }, { x: 10 * T, y: 36 * T }] },
    { id: "plaza-to-guild", from: "central-plaza", to: "guild-zone", waypoints: [{ x: 42 * T, y: 28 * T }, { x: 52 * T, y: 36 * T }] },
    { id: "plaza-to-portals", from: "central-plaza", to: "portal-circle", waypoints: [{ x: 32 * T, y: 16 * T }, { x: 32 * T, y: 8 * T }] },
  ];

  const buildings = [
    building(region, "hatchery", "Hatchery", 4 * T, 4 * T, 10 * T, 7 * T, 0x3a8fd4),
    building(region, "arena", "Arena Gate", 49 * T, 4 * T, 10 * T, 6 * T, 0xd48a3a),
    building(region, "market", "Rift Exchange", 4 * T, 35 * T, 12 * T, 8 * T, 0x4adf7a),
    building(region, "guild", "Guild Hall", 47 * T, 35 * T, 12 * T, 8 * T, 0x9b7bff),
    building(region, "workshop", "Crafting Workshop", 4 * T, 19 * T, 8 * T, 6 * T, 0xc07040),
    building(region, "recovery-center", "Recovery Center", 41 * T, 39 * T, 7 * T, 5 * T, 0x60d0c0),
    building(region, "homestead-path", "Homestead Path", 2 * T, 14 * T, 5 * T, 5 * T, 0xff9ad5),
  ];

  const objects: WorldMapObject[] = [
    ...buildings.map((b) => b.object),
    {
      id: "riftstone",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 32 * T,
      y: 22 * T,
      width: 3 * T,
      height: 3 * T,
      collision: true,
      label: "Riftstone Monument",
      color: 0x3de7ff,
      metadata: { pulse: true },
    },
    {
      id: "fountain",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 28 * T,
      y: 20 * T,
      width: 3 * T,
      height: 3 * T,
      collision: true,
      label: "Plaza Fountain",
      color: 0x4aa0ff,
    },
    {
      id: "event-stage",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 34 * T,
      y: 18 * T,
      width: 5 * T,
      height: 3 * T,
      collision: true,
      label: "Community Stage",
      color: 0x6a5acd,
    },
    {
      id: "notice-board",
      type: "quest",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 30 * T,
      y: 26 * T,
      interactive: true,
      interactionRadius: 48,
      label: "Notice Board",
      metadata: { questBoard: true },
    },
    {
      id: "pet-play",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 36 * T,
      y: 24 * T,
      width: 4 * T,
      height: 3 * T,
      label: "Pet Play Area",
      color: 0xffb84d,
    },
    {
      id: "spawn-keeper",
      type: "spawn",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 32 * T,
      y: 24 * T,
      label: "Keeper Spawn",
    },
    {
      id: "waypoint-plaza",
      type: "waypoint",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 32 * T,
      y: 28 * T,
      interactive: true,
      interactionRadius: 40,
      label: "Plaza Waypoint",
      metadata: { fastTravel: true },
    },
    // Training posts
    {
      id: "training-dummy-a",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 40 * T,
      y: 14 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Training Dummy",
      color: 0x886644,
    },
    {
      id: "training-dummy-b",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 44 * T,
      y: 16 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Training Dummy",
      color: 0x886644,
    },
    // Farm plots
    {
      id: "farm-plot-1",
      type: "farm_plot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 15 * T,
      y: 40 * T,
      width: 2 * T,
      height: 2 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Starter Plot",
    },
    {
      id: "farm-plot-2",
      type: "farm_plot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 18 * T,
      y: 40 * T,
      width: 2 * T,
      height: 2 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Starter Plot",
    },
    {
      id: "fishing-dock",
      type: "fishing_spot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 26 * T,
      y: 40 * T,
      interactive: true,
      interactionRadius: 44,
      label: "Fishing Dock",
      metadata: { resourceId: "pond-fish" },
    },
    // Hidden
    {
      id: "hidden-secret-garden",
      type: "hidden_area",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 57 * T,
      y: 28 * T,
      width: 4 * T,
      height: 3 * T,
      label: "Secret Garden",
      metadata: { discoverable: true, clue: "Behind the feeding grove hedge" },
    },
    {
      id: "hidden-fountain-cave",
      type: "hidden_area",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 28 * T,
      y: 21 * T,
      label: "Fountain Cave",
      metadata: { discoverable: true, requiredAbility: "dive_shallow" },
    },
    {
      id: "chest-waterfall",
      type: "chest",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 8 * T,
      y: 8 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Mossy Chest",
      metadata: { lootTable: "commons-hidden-1" },
    },
    // Named Commons cast (playability prompt 1–10)
    npcAt(region, "elara-venn", 30 * T, 22 * T),
    npcAt(region, "rowan-vale", 34 * T, 25 * T),
    npcAt(region, "mira-shellbright", 10 * T, 12 * T),
    npcAt(region, "bram-ironroot", 10 * T, 26 * T),
    npcAt(region, "tessa-windmere", 12 * T, 38 * T),
    npcAt(region, "archivist-solen", 36 * T, 20 * T),
    npcAt(region, "captain-orren", 42 * T, 14 * T),
    npcAt(region, "nyla-brook", 44 * T, 42 * T),
    npcAt(region, "pip-gearwhistle", 28 * T, 10 * T),
    npcAt(region, "rook-emberfall", 52 * T, 12 * T),
    // Ambient citizens
    npcAt(region, "plaza-vendor-cal", 24 * T, 28 * T),
    npcAt(region, "plaza-musician-reo", 38 * T, 26 * T),
    npcAt(region, "plaza-child-mim", 33 * T, 27 * T),
    npcAt(region, "farm-hand-jot", 17 * T, 41 * T),
    npcAt(region, "dock-sweeper-ana", 27 * T, 39 * T),
    npcAt(region, "scribe-runner-kel", 31 * T, 18 * T),
    npcAt(region, "cook-pot-uma", 29 * T, 29 * T),
    npcAt(region, "gardener-sip", 50 * T, 22 * T),
    // Guards
    npcAt(region, "guard-east-ryn", 46 * T, 24 * T),
    npcAt(region, "guard-west-dao", 20 * T, 24 * T),
    npcAt(region, "guard-portal-hex", 32 * T, 12 * T),
    // Ambient-owned Riftlings
    npcAt(region, "riftling-plaza-emberkit", 35 * T, 25 * T),
    npcAt(region, "riftling-hatchery-glowpup", 12 * T, 14 * T),
    npcAt(region, "riftling-market-pouchling", 14 * T, 37 * T),
    resourceAt(region, "berry-bush", "res-berry-1", 52 * T, 20 * T),
    resourceAt(region, "berry-bush", "res-berry-2", 54 * T, 22 * T),
    resourceAt(region, "starter-herb", "res-herb-1", 20 * T, 30 * T),
    resourceAt(region, "pond-fish", "res-fish-1", 24 * T, 42 * T),
    enemyZone(region, "spawn-slimes", "rift-slime", 4 * T, 4 * T, 6 * T, 5 * T),
    enemyZone(region, "spawn-vines", "vine-sprout", 56 * T, 4 * T, 5 * T, 5 * T),
    ...portalRing(region, 32 * T, 7 * T, 5.5 * T),
  ];

  const colliders = [
    ...buildings.map((b) => b.collider),
    { id: "riftstone-col", x: 32 * T, y: 22 * T, width: 3 * T, height: 3 * T, kind: "building" as const },
    { id: "fountain-col", x: 28 * T, y: 20 * T, width: 3 * T, height: 3 * T, kind: "building" as const },
    { id: "stage-col", x: 34 * T, y: 18 * T, width: 5 * T, height: 3 * T, kind: "building" as const },
    { id: "dummy-a-col", x: 40 * T, y: 14 * T, width: 2 * T, height: 2 * T, kind: "building" as const },
    { id: "dummy-b-col", x: 44 * T, y: 16 * T, width: 2 * T, height: 2 * T, kind: "building" as const },
    // Pond water (non-walkable deep)
    { id: "pond-water", x: 23 * T, y: 38 * T, width: 10 * T, height: 5 * T, kind: "water" as const },
  ];

  return finalizeBlueprint(region, {
    cols,
    rows,
    zones,
    pathways,
    objects,
    colliders,
    safeZones: [
      { id: "plaza-safe", x: 18 * T, y: 14 * T, width: 28 * T, height: 16 * T },
      { id: "portal-safe", x: 24 * T, y: 4 * T, width: 16 * T, height: 8 * T },
    ],
    spawn: { x: 32 * T, y: 24 * T },
    portalHub: { x: 32 * T, y: 7 * T, radius: 5.5 * T },
    notes: [
      "Primary Live World entry map.",
      "Portal Circle encodes all 11 destination unlocks.",
      "Outer woods host optional beginner enemies only.",
    ],
    completeness: "FULL",
  });
}
