import { REGION_BY_SLUG } from "@/game/world-maps/regions";
import {
  TILE,
  building,
  enemyZone,
  finalizeBlueprint,
  gatewayStoneAt,
  npcAt,
  portalRing,
  resourceAt,
} from "@/game/world-maps/blueprint-helpers";
import type {
  CollisionRect,
  MapBlueprint,
  MapZone,
  PathwayDef,
  WorldMapObject,
} from "@/game/world-maps/types";

const region = REGION_BY_SLUG["riftwild-commons"]!;

/**
 * Riftwild Commons — Living Towns showcase.
 * City-planned districts: roads → intersections → plazas → hubs.
 * Walls/gates frame the settlement; empty grass is replaced by parks, wells, crofts, alleys.
 */
export function buildRiftwildCommonsBlueprint(): MapBlueprint {
  const cols = 64;
  const rows = 48;
  const T = TILE;

  // ── District zones (purpose-first urban blocks) ──────────────────────────
  const zones: MapZone[] = [
    // Civic hub — fountain plaza is the road hub of the city
    {
      id: "central-plaza",
      name: "Central Rift Plaza",
      x: 20 * T,
      y: 16 * T,
      width: 22 * T,
      height: 14 * T,
      kind: "safe",
      safe: true,
    },
    // Market — SW block with packing alleys
    {
      id: "market-zone",
      name: "Market District",
      x: 2 * T,
      y: 30 * T,
      width: 16 * T,
      height: 14 * T,
      kind: "settlement",
      safe: true,
    },
    // Residential — west spine homes + gardens
    {
      id: "residential",
      name: "Keeper Row",
      x: 2 * T,
      y: 12 * T,
      width: 12 * T,
      height: 10 * T,
      kind: "settlement",
      safe: true,
    },
    // Crafting — forge yard west of plaza
    {
      id: "craft-zone",
      name: "Ember Craft Quarter",
      x: 2 * T,
      y: 22 * T,
      width: 12 * T,
      height: 8 * T,
      kind: "settlement",
      safe: true,
    },
    // Entertainment — tavern / festival lane west-of-plaza
    {
      id: "entertainment-zone",
      name: "Festival Lane",
      x: 14 * T,
      y: 20 * T,
      width: 8 * T,
      height: 8 * T,
      kind: "settlement",
      safe: true,
    },
    // Noble terrace — archive + academy stair approach
    {
      id: "noble-zone",
      name: "Archive Terrace",
      x: 40 * T,
      y: 16 * T,
      width: 12 * T,
      height: 10 * T,
      kind: "settlement",
      safe: true,
    },
    {
      id: "academy-zone",
      name: "Player Academy",
      x: 46 * T,
      y: 22 * T,
      width: 8 * T,
      height: 6 * T,
      kind: "settlement",
      safe: true,
    },
    {
      id: "library-zone",
      name: "Rift Archive",
      x: 40 * T,
      y: 17 * T,
      width: 7 * T,
      height: 6 * T,
      kind: "settlement",
      safe: true,
    },
    // Temple / portal sanctum — north pilgrimage road
    {
      id: "portal-circle",
      name: "Portal Sanctum",
      x: 24 * T,
      y: 2 * T,
      width: 16 * T,
      height: 10 * T,
      kind: "pathway",
      safe: true,
    },
    // Military — NE arena + drill yard
    {
      id: "arena-zone",
      name: "Arena Gate",
      x: 48 * T,
      y: 2 * T,
      width: 12 * T,
      height: 9 * T,
      kind: "settlement",
      safe: true,
    },
    {
      id: "training-yard",
      name: "Southwatch Yard",
      x: 40 * T,
      y: 10 * T,
      width: 10 * T,
      height: 7 * T,
      kind: "settlement",
      safe: true,
    },
    // Dock — south waterfront
    {
      id: "fishing-pond",
      name: "Stonebay Dock",
      x: 22 * T,
      y: 36 * T,
      width: 14 * T,
      height: 9 * T,
      kind: "exploration",
      safe: true,
    },
    // Farmland crofts between market and dock
    {
      id: "public-farm",
      name: "Commons Crofts",
      x: 14 * T,
      y: 38 * T,
      width: 9 * T,
      height: 7 * T,
      kind: "settlement",
      safe: true,
    },
    // Guild quarter SE
    {
      id: "guild-zone",
      name: "Guild Quarter",
      x: 44 * T,
      y: 32 * T,
      width: 16 * T,
      height: 12 * T,
      kind: "settlement",
      safe: true,
    },
    {
      id: "recovery",
      name: "Recovery Gardens",
      x: 38 * T,
      y: 38 * T,
      width: 8 * T,
      height: 6 * T,
      kind: "settlement",
      safe: true,
    },
    // Hatchery NW nest
    {
      id: "hatchery-zone",
      name: "Hatchery Nest",
      x: 3 * T,
      y: 2 * T,
      width: 12 * T,
      height: 10 * T,
      kind: "settlement",
      safe: true,
    },
    // Grove / park east of plaza (no dead lawn)
    {
      id: "feeding-grove",
      name: "Lantern Grove Park",
      x: 50 * T,
      y: 16 * T,
      width: 10 * T,
      height: 8 * T,
      kind: "settlement",
      safe: true,
    },
    {
      id: "forest-entrance",
      name: "East Forest Gate",
      x: 54 * T,
      y: 10 * T,
      width: 8 * T,
      height: 7 * T,
      kind: "exploration",
      safe: true,
    },
    {
      id: "outer-woods",
      name: "Outer Woods",
      x: 1 * T,
      y: 1 * T,
      width: 6 * T,
      height: 6 * T,
      kind: "danger",
      safe: false,
    },
    {
      id: "secret-garden",
      name: "Secret Garden",
      x: 56 * T,
      y: 26 * T,
      width: 6 * T,
      height: 5 * T,
      kind: "hidden",
      safe: true,
    },
  ];

  // ── Road network: buildings create roads → plazas → hubs ─────────────────
  const pathways: PathwayDef[] = [
    // Cardinal spines from plaza hub
    {
      id: "plaza-north-spine",
      from: "central-plaza",
      to: "portal-circle",
      waypoints: [
        { x: 31 * T, y: 18 * T },
        { x: 31 * T, y: 14 * T },
        { x: 32 * T, y: 10 * T },
        { x: 32 * T, y: 7 * T },
      ],
    },
    {
      id: "plaza-south-spine",
      from: "central-plaza",
      to: "fishing-pond",
      waypoints: [
        { x: 31 * T, y: 28 * T },
        { x: 30 * T, y: 32 * T },
        { x: 28 * T, y: 36 * T },
        { x: 27 * T, y: 39 * T },
      ],
    },
    {
      id: "plaza-west-market",
      from: "central-plaza",
      to: "market-zone",
      waypoints: [
        { x: 22 * T, y: 24 * T },
        { x: 18 * T, y: 28 * T },
        { x: 14 * T, y: 32 * T },
        { x: 10 * T, y: 36 * T },
      ],
    },
    {
      id: "plaza-east-guild",
      from: "central-plaza",
      to: "guild-zone",
      waypoints: [
        { x: 40 * T, y: 24 * T },
        { x: 44 * T, y: 28 * T },
        { x: 48 * T, y: 32 * T },
        { x: 50 * T, y: 36 * T },
      ],
    },
    {
      id: "plaza-to-hatchery",
      from: "central-plaza",
      to: "hatchery-zone",
      waypoints: [
        { x: 22 * T, y: 18 * T },
        { x: 16 * T, y: 14 * T },
        { x: 12 * T, y: 10 * T },
        { x: 9 * T, y: 7 * T },
      ],
    },
    {
      id: "plaza-to-arena",
      from: "central-plaza",
      to: "arena-zone",
      waypoints: [
        { x: 38 * T, y: 18 * T },
        { x: 44 * T, y: 14 * T },
        { x: 50 * T, y: 10 * T },
        { x: 53 * T, y: 7 * T },
      ],
    },
    {
      id: "plaza-to-forge",
      from: "central-plaza",
      to: "craft-zone",
      waypoints: [
        { x: 22 * T, y: 24 * T },
        { x: 16 * T, y: 25 * T },
        { x: 10 * T, y: 25 * T },
      ],
    },
    {
      id: "plaza-to-tavern",
      from: "central-plaza",
      to: "entertainment-zone",
      waypoints: [
        { x: 24 * T, y: 24 * T },
        { x: 20 * T, y: 24 * T },
        { x: 17 * T, y: 24 * T },
      ],
    },
    {
      id: "plaza-to-terrace",
      from: "central-plaza",
      to: "noble-zone",
      waypoints: [
        { x: 38 * T, y: 22 * T },
        { x: 42 * T, y: 20 * T },
        { x: 44 * T, y: 19 * T },
      ],
    },
    {
      id: "terrace-to-academy",
      from: "noble-zone",
      to: "academy-zone",
      waypoints: [
        { x: 44 * T, y: 21 * T },
        { x: 46 * T, y: 23 * T },
        { x: 48 * T, y: 24 * T },
      ],
    },
    {
      id: "plaza-to-training",
      from: "central-plaza",
      to: "training-yard",
      waypoints: [
        { x: 36 * T, y: 18 * T },
        { x: 40 * T, y: 15 * T },
        { x: 43 * T, y: 13 * T },
      ],
    },
    {
      id: "residential-lane",
      from: "residential",
      to: "craft-zone",
      waypoints: [
        { x: 7 * T, y: 18 * T },
        { x: 7 * T, y: 21 * T },
        { x: 7 * T, y: 24 * T },
      ],
    },
    {
      id: "market-alley-to-farm",
      from: "market-zone",
      to: "public-farm",
      waypoints: [
        { x: 14 * T, y: 38 * T },
        { x: 16 * T, y: 40 * T },
        { x: 18 * T, y: 41 * T },
      ],
    },
    {
      id: "farm-to-dock",
      from: "public-farm",
      to: "fishing-pond",
      waypoints: [
        { x: 20 * T, y: 41 * T },
        { x: 23 * T, y: 40 * T },
        { x: 26 * T, y: 40 * T },
      ],
    },
    {
      id: "guild-to-recovery",
      from: "guild-zone",
      to: "recovery",
      waypoints: [
        { x: 48 * T, y: 38 * T },
        { x: 44 * T, y: 40 * T },
        { x: 41 * T, y: 41 * T },
      ],
    },
    {
      id: "grove-to-forest-gate",
      from: "feeding-grove",
      to: "forest-entrance",
      waypoints: [
        { x: 54 * T, y: 18 * T },
        { x: 56 * T, y: 14 * T },
        { x: 57 * T, y: 12 * T },
      ],
    },
    // Ring road — worn cobble circuit linking districts (no dead ends)
    {
      id: "ring-road-west",
      from: "hatchery-zone",
      to: "market-zone",
      waypoints: [
        { x: 8 * T, y: 10 * T },
        { x: 6 * T, y: 16 * T },
        { x: 6 * T, y: 24 * T },
        { x: 8 * T, y: 32 * T },
      ],
    },
    {
      id: "ring-road-east",
      from: "arena-zone",
      to: "guild-zone",
      waypoints: [
        { x: 54 * T, y: 10 * T },
        { x: 56 * T, y: 16 * T },
        { x: 54 * T, y: 24 * T },
        { x: 52 * T, y: 32 * T },
      ],
    },
  ];

  // ── Buildings — each belongs to a district; placement defines street edges ─
  const buildings = [
    // Hatchery Nest
    building(region, "hatchery", "Hatchery", 4 * T, 3 * T, 10 * T, 7 * T, 0x3a8fd4),
    // Keeper Row — nested footprints so roofs overlap (city fabric, not lonely boxes)
    building(region, "homestead-path", "Keeper Cottage", 3 * T, 13 * T, 5 * T, 5 * T, 0xc4a06a),
    building(region, "cottage-north", "Row House North", 7 * T, 12 * T, 5 * T, 5 * T, 0xb89060),
    building(region, "cottage-south", "Row House South", 3 * T, 17 * T, 5 * T, 5 * T, 0xa87850),
    // Ember Craft — butts against residential lane
    building(region, "workshop", "Ember Forge", 3 * T, 22 * T, 8 * T, 6 * T, 0xc07040),
    // Festival Lane tavern — edge of plaza street wall
    building(region, "tavern-tankard", "The Golden Tankard", 14 * T, 20 * T, 7 * T, 7 * T, 0xd4a05a),
    // Market block — annex shares wall with exchange
    building(region, "market", "Rift Exchange", 3 * T, 32 * T, 11 * T, 7 * T, 0x4adf7a),
    building(region, "market-annex", "Stall Master's Shed", 11 * T, 34 * T, 6 * T, 5 * T, 0x3aaa68),
    // Military
    building(region, "arena", "Arena Gate", 49 * T, 3 * T, 10 * T, 6 * T, 0xd48a3a),
    // Noble terrace
    building(region, "library", "Rift Archive", 40 * T, 17 * T, 6 * T, 5 * T, 0x5a90c8),
    building(region, "academy", "Player Academy", 47 * T, 23 * T, 6 * T, 5 * T, 0x3de7ff),
    // Guild + Recovery
    building(region, "guild", "Guild Hall", 48 * T, 34 * T, 11 * T, 7 * T, 0x8a7040),
    building(region, "recovery-center", "Recovery Center", 39 * T, 39 * T, 7 * T, 5 * T, 0x60d0c0),
  ];

  const objects: WorldMapObject[] = [
    ...buildings.map((b) => b.object),
    // ── Plaza landmarks (civic hub) ──
    {
      id: "riftstone",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 31 * T,
      y: 21 * T,
      width: 3 * T,
      height: 3 * T,
      collision: true,
      label: "Riftstone Monument",
      color: 0x3de7ff,
      metadata: { pulse: true, district: "central-plaza", landmark: true },
    },
    {
      id: "fountain",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 28 * T,
      y: 20 * T,
      width: 3 * T,
      height: 3 * T,
      collision: true,
      label: "Plaza Fountain",
      color: 0x4aa0ff,
      metadata: { district: "central-plaza", landmark: true },
    },
    {
      id: "event-stage",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 34 * T,
      y: 18 * T,
      width: 5 * T,
      height: 3 * T,
      collision: true,
      label: "Community Stage",
      color: 0x6a5acd,
      metadata: { district: "central-plaza", landmark: true },
    },
    {
      id: "notice-board",
      type: "quest",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 30 * T,
      y: 27 * T,
      interactive: true,
      interactionRadius: 48,
      label: "Notice Board",
      metadata: { questBoard: true, district: "central-plaza" },
    },
    {
      id: "pet-play",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 36 * T,
      y: 25 * T,
      width: 4 * T,
      height: 3 * T,
      label: "Pet Play Green",
      color: 0xffb84d,
      metadata: { district: "central-plaza", purpose: "park" },
    },
    {
      id: "plaza-well",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 24 * T,
      y: 22 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Civic Well",
      color: 0x708090,
      metadata: { district: "central-plaza", purpose: "well" },
    },
    {
      id: "spawn-keeper",
      type: "spawn",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 32 * T,
      y: 24 * T,
      label: "Keeper Spawn",
    },
    {
      id: "waypoint-plaza",
      type: "waypoint",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 32 * T,
      y: 28 * T,
      interactive: true,
      interactionRadius: 40,
      label: "Plaza Waypoint",
      metadata: { fastTravel: true },
    },
    // ── Temple / shrine ──
    {
      id: "sanctum-shrine",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 36 * T,
      y: 5 * T,
      width: 3 * T,
      height: 3 * T,
      collision: true,
      label: "Rift Shrine",
      color: 0x60d0e8,
      metadata: { district: "temple", purpose: "shrine", landmark: true },
    },
    // ── Residential well + garden ──
    {
      id: "keeper-well",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 9 * T,
      y: 17 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Neighborhood Well",
      color: 0x708090,
      metadata: { district: "residential", purpose: "well" },
    },
    {
      id: "row-garden",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 9 * T,
      y: 19 * T,
      width: 3 * T,
      height: 2 * T,
      label: "Cottage Garden",
      color: 0x4a9a5a,
      metadata: { district: "residential", purpose: "garden" },
    },
    // ── Market square (not just the exchange building) ──
    {
      id: "market-square",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 8 * T,
      y: 38 * T,
      width: 4 * T,
      height: 3 * T,
      label: "Trade Square",
      color: 0xc9a227,
      metadata: { district: "market", purpose: "square" },
    },
    // ── Terrace stairs (verticality) ──
    {
      id: "terrace-stairs",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 38 * T,
      y: 20 * T,
      width: 3 * T,
      height: 4 * T,
      label: "Archive Stairs",
      color: 0x8a8a90,
      metadata: { district: "noble", purpose: "stairs", verticality: true },
    },
    // ── Training posts ──
    {
      id: "training-dummy-a",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 41 * T,
      y: 12 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Training Dummy",
      color: 0x886644,
      metadata: { district: "military" },
    },
    {
      id: "training-dummy-b",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 45 * T,
      y: 13 * T,
      width: 2 * T,
      height: 2 * T,
      collision: true,
      label: "Training Dummy",
      color: 0x886644,
      metadata: { district: "military" },
    },
    // ── Farm plots ──
    {
      id: "farm-plot-1",
      type: "farm_plot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 15 * T,
      y: 40 * T,
      width: 2 * T,
      height: 2 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Starter Plot",
      metadata: { district: "farmland" },
    },
    {
      id: "farm-plot-2",
      type: "farm_plot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 18 * T,
      y: 40 * T,
      width: 2 * T,
      height: 2 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Starter Plot",
      metadata: { district: "farmland" },
    },
    {
      id: "farm-plot-3",
      type: "farm_plot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 16 * T,
      y: 42 * T,
      width: 2 * T,
      height: 2 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Herb Plot",
      metadata: { district: "farmland" },
    },
    {
      id: "fishing-dock",
      type: "fishing_spot",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 26 * T,
      y: 40 * T,
      interactive: true,
      interactionRadius: 44,
      label: "Stonebay Pier",
      metadata: { resourceId: "pond-fish", district: "dock" },
    },
    {
      id: "dock-boat",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 29 * T,
      y: 41 * T,
      width: 3 * T,
      height: 2 * T,
      label: "Moored Skiff",
      color: 0x6a4a30,
      metadata: { district: "dock", purpose: "boat" },
    },
    // City gates (landmarks + interaction stubs)
    {
      id: "gate-north",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 30 * T,
      y: 2 * T,
      width: 4 * T,
      height: 2 * T,
      label: "North Pilgrim Gate",
      color: 0x706050,
      metadata: { district: "temple", purpose: "gate", landmark: true },
    },
    {
      id: "gate-east",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 58 * T,
      y: 12 * T,
      width: 2 * T,
      height: 4 * T,
      label: "East Forest Gate",
      color: 0x706050,
      metadata: { district: "forest-gate", purpose: "gate", landmark: true },
    },
    {
      id: "gate-south",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 30 * T,
      y: 44 * T,
      width: 4 * T,
      height: 2 * T,
      label: "South Bay Gate",
      color: 0x706050,
      metadata: { district: "dock", purpose: "gate", landmark: true },
    },
    {
      id: "gate-west",
      type: "decoration",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 2 * T,
      y: 22 * T,
      width: 2 * T,
      height: 4 * T,
      label: "West Craft Gate",
      color: 0x706050,
      metadata: { district: "crafting", purpose: "gate", landmark: true },
    },
    // Hidden
    {
      id: "hidden-secret-garden",
      type: "hidden_area",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 57 * T,
      y: 28 * T,
      width: 4 * T,
      height: 3 * T,
      label: "Secret Garden",
      metadata: { discoverable: true, clue: "Behind the lantern grove hedge" },
    },
    {
      id: "hidden-fountain-cave",
      type: "hidden_area",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 28 * T,
      y: 21 * T,
      label: "Fountain Cave",
      metadata: { discoverable: true, requiredAbility: "dive_shallow" },
    },
    {
      id: "chest-waterfall",
      type: "chest",
      regionId: region.id,
      sceneId: region.sceneKey,
      x: 5 * T,
      y: 5 * T,
      interactive: true,
      interactionRadius: 36,
      label: "Mossy Chest",
      metadata: { lootTable: "commons-hidden-1" },
    },
    // ── Named cast (district-anchored) ──
    npcAt(region, "elara-venn", 30 * T, 22 * T),
    npcAt(region, "rowan-vale", 34 * T, 26 * T),
    npcAt(region, "mira-shellbright", 10 * T, 10 * T),
    npcAt(region, "bram-ironroot", 9 * T, 26 * T),
    npcAt(region, "tessa-windmere", 10 * T, 36 * T),
    npcAt(region, "archivist-solen", 42 * T, 19 * T),
    npcAt(region, "captain-orren", 43 * T, 13 * T),
    npcAt(region, "nyla-brook", 42 * T, 41 * T),
    npcAt(region, "pip-gearwhistle", 28 * T, 9 * T),
    npcAt(region, "rook-emberfall", 52 * T, 11 * T),
    // Ambient citizens — denser per district
    npcAt(region, "plaza-vendor-cal", 24 * T, 27 * T),
    npcAt(region, "plaza-musician-reo", 16 * T, 25 * T),
    npcAt(region, "plaza-child-mim", 36 * T, 27 * T),
    npcAt(region, "farm-hand-jot", 17 * T, 41 * T),
    npcAt(region, "dock-sweeper-ana", 27 * T, 39 * T),
    npcAt(region, "scribe-runner-kel", 31 * T, 17 * T),
    npcAt(region, "cook-pot-uma", 17 * T, 23 * T),
    npcAt(region, "gardener-sip", 52 * T, 20 * T),
    // Guards at gates + plaza
    npcAt(region, "guard-east-ryn", 56 * T, 14 * T),
    npcAt(region, "guard-west-dao", 5 * T, 24 * T),
    npcAt(region, "guard-portal-hex", 32 * T, 11 * T),
    // Ambient Riftlings
    npcAt(region, "riftling-plaza-emberkit", 37 * T, 23 * T),
    npcAt(region, "riftling-hatchery-glowpup", 12 * T, 12 * T),
    npcAt(region, "riftling-market-pouchling", 12 * T, 35 * T),
    resourceAt(region, "berry-bush", "res-berry-1", 52 * T, 20 * T),
    resourceAt(region, "berry-bush", "res-berry-2", 54 * T, 22 * T),
    resourceAt(region, "starter-herb", "res-herb-1", 19 * T, 39 * T),
    resourceAt(region, "pond-fish", "res-fish-1", 24 * T, 42 * T),
    enemyZone(region, "spawn-slimes", "rift-slime", 2 * T, 2 * T, 5 * T, 4 * T),
    enemyZone(region, "spawn-vines", "vine-sprout", 57 * T, 3 * T, 5 * T, 5 * T),
    ...portalRing(region, 32 * T, 7 * T, 5.5 * T),
    gatewayStoneAt(region, 32 * T, 11 * T),
  ];

  // ── City walls with gate openings (major settlement frame) ───────────────
  const wallThickness = 1.25 * T;
  const cityWalls: CollisionRect[] = [
    // North wall segments (gap at pilgrim gate ~28–36)
    {
      id: "wall-n-west",
      x: 2 * T,
      y: 1.5 * T,
      width: 26 * T,
      height: wallThickness,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the North Pilgrim Gate." },
    },
    {
      id: "wall-n-east",
      x: 36 * T,
      y: 1.5 * T,
      width: 24 * T,
      height: wallThickness,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the North Pilgrim Gate." },
    },
    // South wall (gap at bay gate ~28–36)
    {
      id: "wall-s-west",
      x: 2 * T,
      y: 45.5 * T,
      width: 26 * T,
      height: wallThickness,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the South Bay Gate." },
    },
    {
      id: "wall-s-east",
      x: 36 * T,
      y: 45.5 * T,
      width: 24 * T,
      height: wallThickness,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the South Bay Gate." },
    },
    // West wall (gap at craft gate ~20–28)
    {
      id: "wall-w-north",
      x: 1.5 * T,
      y: 2 * T,
      width: wallThickness,
      height: 18 * T,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the West Craft Gate." },
    },
    {
      id: "wall-w-south",
      x: 1.5 * T,
      y: 28 * T,
      width: wallThickness,
      height: 17 * T,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the West Craft Gate." },
    },
    // East wall (gap at forest gate ~10–16)
    {
      id: "wall-e-north",
      x: 60.5 * T,
      y: 2 * T,
      width: wallThickness,
      height: 8 * T,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the East Forest Gate." },
    },
    {
      id: "wall-e-south",
      x: 60.5 * T,
      y: 16 * T,
      width: wallThickness,
      height: 29 * T,
      kind: "wall",
      metadata: { barrierStyle: "gate", message: "City wall — use the East Forest Gate." },
    },
  ];

  const colliders: CollisionRect[] = [
    ...buildings.map((b) => b.collider),
    ...cityWalls,
    { id: "riftstone-col", x: 31 * T, y: 21 * T, width: 3 * T, height: 3 * T, kind: "building" },
    { id: "fountain-col", x: 28 * T, y: 20 * T, width: 3 * T, height: 3 * T, kind: "building" },
    { id: "stage-col", x: 34 * T, y: 18 * T, width: 5 * T, height: 3 * T, kind: "building" },
    { id: "plaza-well-col", x: 24 * T, y: 22 * T, width: 2 * T, height: 2 * T, kind: "building" },
    { id: "keeper-well-col", x: 9 * T, y: 17 * T, width: 2 * T, height: 2 * T, kind: "building" },
    { id: "shrine-col", x: 36 * T, y: 5 * T, width: 3 * T, height: 3 * T, kind: "building" },
    { id: "dummy-a-col", x: 41 * T, y: 12 * T, width: 2 * T, height: 2 * T, kind: "building" },
    { id: "dummy-b-col", x: 45 * T, y: 13 * T, width: 2 * T, height: 2 * T, kind: "building" },
    {
      id: "pond-water",
      x: 23 * T,
      y: 38 * T,
      width: 10 * T,
      height: 5 * T,
      kind: "deep_water",
    },
    {
      id: "forest-gate-thicket",
      x: 61 * T,
      y: 16 * T,
      width: 2 * T,
      height: 8 * T,
      kind: "blocker",
      metadata: {
        barrierStyle: "forest",
        message: "Outer woods thicken here — keep to the marked trails.",
      },
    },
  ];

  return finalizeBlueprint(region, {
    cols,
    rows,
    zones,
    pathways,
    objects,
    colliders,
    safeZones: [
      { id: "plaza-safe", x: 20 * T, y: 16 * T, width: 22 * T, height: 14 * T },
      { id: "portal-safe", x: 24 * T, y: 2 * T, width: 16 * T, height: 10 * T },
      { id: "market-safe", x: 2 * T, y: 30 * T, width: 16 * T, height: 14 * T },
    ],
    spawn: { x: 32 * T, y: 24 * T },
    portalHub: { x: 32 * T, y: 7 * T, radius: 5.5 * T },
    notes: [
      "Living Towns showcase — handcrafted districts, not random scatter.",
      "Districts: plaza, market, residential, crafting, entertainment, noble/academy, temple/portals, military, dock, farmland, guild, recovery, hatchery, grove park.",
      "City walls with N/E/S/W gates; roads radiate from Central Rift Plaza.",
      "Portal Circle encodes all 11 destination unlocks.",
      "Outer woods host optional beginner enemies only.",
    ],
    completeness: "FULL",
  });
}
