import type { SpeciesKit } from "@/game/creatures/rpg-types";

/**
 * Per-species RPG kits: base stats, signature abilities, and traits.
 * Original Riftwilds IP — not Nintendo/Square names.
 */

export const SPECIES_KITS: Record<string, SpeciesKit> = {
  "cindercub": {
    baseStats: { hp: 92, attack: 39, defense: 26, speed: 32, energy: 100 },
    abilities: [
      {
        id: "spark-claw",
        name: "Spark Claw",
        description: "Heated claws rake the foe.",
        category: "ATTACK",
        power: 42,
        energyCost: 10,
        cooldown: 0,
        status: { id: "BURN", chanceBps: 2200, duration: 2 },
      },
      {
        id: "kindling-guard",
        name: "Kindling Guard",
        description: "Fur flares into a warm barrier.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "cub-rush",
        name: "Cub Rush",
        description: "A brave rush that builds momentum.",
        category: "ATTACK",
        power: 50,
        energyCost: 14,
        cooldown: 1,
      }
    ],
    traits: [
      {
        id: "kindling-coat",
        name: "Kindling Coat",
        description: "Warm fur softens chill and lifts spirits.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "brave-heart",
        name: "Brave Heart",
        description: "Courage sharpens every strike.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 3 },
      },
      {
        id: "ember-kin",
        name: "Ember Kin",
        description: "Affinity techniques hit a little harder.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      }
    ],
  },
  "mossprig": {
    baseStats: { hp: 102, attack: 26, defense: 34, speed: 26, energy: 102 },
    abilities: [
      {
        id: "moss-needle",
        name: "Moss Needle",
        description: "A sharp living thorn.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ROOTED", chanceBps: 1800, duration: 1 },
      },
      {
        id: "soft-bark",
        name: "Soft Bark",
        description: "Moss thickens into bark.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "sprout-mend",
        name: "Sprout Mend",
        description: "Green light knits small wounds.",
        category: "HEAL",
        power: 32,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "living-moss",
        name: "Living Moss",
        description: "Slow natural recovery while resting.",
        hook: { kind: "CARE_BONUS", care: "health", amount: 3 },
      },
      {
        id: "gentle-roots",
        name: "Gentle Roots",
        description: "Bond grows easier with patience.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 4 },
      },
      {
        id: "grove-resilience",
        name: "Grove Resilience",
        description: "Sturdier frame than it looks.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      }
    ],
  },
  "bubbloon": {
    baseStats: { hp: 96, attack: 31, defense: 29, speed: 32, energy: 104 },
    abilities: [
      {
        id: "brine-bubble",
        name: "Brine Bubble",
        description: "Pops a pressurized brine orb.",
        category: "ATTACK",
        power: 38,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SOAKED", chanceBps: 2500, duration: 2 },
      },
      {
        id: "drift-veil",
        name: "Drift Veil",
        description: "Bubbles blur the outline.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "SHROUDED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "surge-pop",
        name: "Surge Pop",
        description: "A playful burst of tideforce.",
        category: "ATTACK",
        power: 52,
        energyCost: 15,
        cooldown: 2,
      }
    ],
    traits: [
      {
        id: "buoyant-core",
        name: "Buoyant Core",
        description: "Harder to pin down in a clash.",
        hook: { kind: "EVASION_BONUS", amount: 4 },
      },
      {
        id: "playful-tide",
        name: "Playful Tide",
        description: "Joyful nature restores energy faster in care.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 4 },
      },
      {
        id: "moonwater-skin",
        name: "Moonwater Skin",
        description: "Slightly higher vitality.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 6 },
      }
    ],
  },
  "voltkit": {
    baseStats: { hp: 86, attack: 36, defense: 22, speed: 41, energy: 114 },
    abilities: [
      {
        id: "static-nip",
        name: "Static Nip",
        description: "A crackling bite.",
        category: "ATTACK",
        power: 44,
        energyCost: 11,
        cooldown: 0,
        status: { id: "CHARGED", chanceBps: 2000, duration: 2 },
      },
      {
        id: "ridge-dash",
        name: "Ridge Dash",
        description: "Lightning-quick reposition.",
        category: "SUPPORT",
        power: 0,
        energyCost: 8,
        cooldown: 1,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 1 },
      },
      {
        id: "arc-flare",
        name: "Arc Flare",
        description: "Unleashes stored static.",
        category: "ULTIMATE",
        power: 72,
        energyCost: 36,
        cooldown: 4,
        status: { id: "CHARGED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "static-fur",
        name: "Static Fur",
        description: "Crits come easier when charged.",
        hook: { kind: "CRIT_BONUS", bps: 500 },
      },
      {
        id: "storm-sprint",
        name: "Storm Sprint",
        description: "Naturally swift.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "live-wire",
        name: "Live Wire",
        description: "More battle energy in reserve.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 6 },
      }
    ],
  },
  "pebblit": {
    baseStats: { hp: 110, attack: 30, defense: 41, speed: 19, energy: 95 },
    abilities: [
      {
        id: "pebble-roll",
        name: "Pebble Roll",
        description: "Tucks in and rolls hard.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
      },
      {
        id: "mineral-brace",
        name: "Mineral Brace",
        description: "Stone body locks tight.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "canyon-thump",
        name: "Canyon Thump",
        description: "A heavy ground slam.",
        category: "ATTACK",
        power: 56,
        energyCost: 16,
        cooldown: 2,
        status: { id: "SLOWED", chanceBps: 2000, duration: 1 },
      }
    ],
    traits: [
      {
        id: "stone-shell",
        name: "Stone Shell",
        description: "Dense mineral plating.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 5 },
      },
      {
        id: "steady-core",
        name: "Steady Core",
        description: "Calm temperament steadies health.",
        hook: { kind: "CARE_BONUS", care: "health", amount: 3 },
      },
      {
        id: "heavy-frame",
        name: "Heavy Frame",
        description: "Extra bulk.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 8 },
      }
    ],
  },
  "wisplet": {
    baseStats: { hp: 92, attack: 30, defense: 29, speed: 34, energy: 107 },
    abilities: [
      {
        id: "lantern-flick",
        name: "Lantern Flick",
        description: "A soft spirit spark.",
        category: "ATTACK",
        power: 36,
        energyCost: 9,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2500, duration: 2 },
      },
      {
        id: "dusk-hum",
        name: "Dusk Hum",
        description: "Soothing hum mends vitality.",
        category: "HEAL",
        power: 30,
        energyCost: 13,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "veil-step",
        name: "Veil Step",
        description: "Slips half into the marsh mist.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "SHROUDED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "lantern-soft",
        name: "Lantern Soft",
        description: "Gentle aura eases stress through care.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 5 },
      },
      {
        id: "spirit-curious",
        name: "Spirit Curious",
        description: "Learns techniques a touch more sharply.",
        hook: { kind: "AFFINITY_POWER", bps: 500 },
      },
      {
        id: "marshlight",
        name: "Marshlight",
        description: "Slight focus edge in battle.",
        hook: { kind: "CRIT_BONUS", bps: 300 },
      }
    ],
  },
  "frostnip": {
    baseStats: { hp: 90, attack: 31, defense: 32, speed: 31, energy: 100 },
    abilities: [
      {
        id: "powder-paw",
        name: "Powder Paw",
        description: "Icy pawstrike leaves frost.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "CHILLED", chanceBps: 2500, duration: 2 },
      },
      {
        id: "snow-curl",
        name: "Snow Curl",
        description: "Tucks into a powdery shell.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "ice-print",
        name: "Ice Print",
        description: "Freezing prints slow the foe.",
        category: "SUPPORT",
        power: 22,
        energyCost: 12,
        cooldown: 2,
        status: { id: "SLOWED", chanceBps: 6000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "powder-coat",
        name: "Powder Coat",
        description: "Shy nature makes it slippery.",
        hook: { kind: "EVASION_BONUS", amount: 5 },
      },
      {
        id: "frostveil-kin",
        name: "Frostveil Kin",
        description: "Affinity bite is colder.",
        hook: { kind: "AFFINITY_POWER", bps: 500 },
      },
      {
        id: "quiet-heart",
        name: "Quiet Heart",
        description: "Bond deepens with gentle care.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 4 },
      }
    ],
  },
  "luminara": {
    baseStats: { hp: 96, attack: 33, defense: 31, speed: 29, energy: 104 },
    abilities: [
      {
        id: "prism-gleam",
        name: "Prism Gleam",
        description: "Refracted dawn light.",
        category: "ATTACK",
        power: 44,
        energyCost: 12,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "dawn-ward",
        name: "Dawn Ward",
        description: "A floating prism shield.",
        category: "DEFEND",
        power: 0,
        energyCost: 11,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "citadel-ray",
        name: "Citadel Ray",
        description: "Concentrated radiant lance.",
        category: "ULTIMATE",
        power: 78,
        energyCost: 40,
        cooldown: 5,
        status: { id: "ILLUMINATED", chanceBps: 5000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "hover-prism",
        name: "Hover Prism",
        description: "Harder to land clean hits on.",
        hook: { kind: "EVASION_BONUS", amount: 3 },
      },
      {
        id: "dawn-calm",
        name: "Dawn Calm",
        description: "Stable radiant core.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "lightwoven",
        name: "Lightwoven",
        description: "Affinity techniques shine brighter.",
        hook: { kind: "AFFINITY_POWER", bps: 700 },
      }
    ],
  },
  "hollowshade": {
    baseStats: { hp: 86, attack: 40, defense: 26, speed: 40, energy: 106 },
    abilities: [
      {
        id: "rift-slip",
        name: "Rift Slip",
        description: "A shadowy lash from nowhere.",
        category: "ATTACK",
        power: 46,
        energyCost: 12,
        cooldown: 0,
        status: { id: "WEAKENED", chanceBps: 2000, duration: 2 },
      },
      {
        id: "soft-eclipse",
        name: "Soft Eclipse",
        description: "Wraps itself in void hush.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "SHROUDED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "hollow-bite",
        name: "Hollow Bite",
        description: "Drains vigor through a rift seam.",
        category: "ULTIMATE",
        power: 80,
        energyCost: 42,
        cooldown: 5,
        status: { id: "WEAKENED", chanceBps: 4500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "shadow-soft",
        name: "Shadow Soft",
        description: "Slips past glancing blows.",
        hook: { kind: "EVASION_BONUS", amount: 6 },
      },
      {
        id: "independent-rift",
        name: "Independent Rift",
        description: "Self-sufficient energy reserves.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "void-edge",
        name: "Void Edge",
        description: "Critical seams open easier.",
        hook: { kind: "CRIT_BONUS", bps: 600 },
      }
    ],
  },
  "gearling": {
    baseStats: { hp: 104, attack: 33, defense: 39, speed: 22, energy: 98 },
    abilities: [
      {
        id: "cog-strike",
        name: "Cog Strike",
        description: "Spinning gear teeth bite.",
        category: "ATTACK",
        power: 42,
        energyCost: 11,
        cooldown: 0,
      },
      {
        id: "scrap-plate",
        name: "Scrap Plate",
        description: "Locks hex plating in place.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "clockwork-pulse",
        name: "Clockwork Pulse",
        description: "Overclocked alloy surge.",
        category: "ATTACK",
        power: 58,
        energyCost: 18,
        cooldown: 2,
        status: { id: "CHARGED", chanceBps: 2000, duration: 1 },
      }
    ],
    traits: [
      {
        id: "clockwork-heart",
        name: "Clockwork Heart",
        description: "Reliable mechanical stamina.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 6 },
      },
      {
        id: "guardian-gears",
        name: "Guardian Gears",
        description: "Protective instinct hardens defense.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "alloy-tune",
        name: "Alloy Tune",
        description: "Affinity resonance is cleaner.",
        hook: { kind: "AFFINITY_POWER", bps: 500 },
      }
    ],
  },
  "bramblefox": {
    baseStats: { hp: 96, attack: 31, defense: 30, speed: 30, energy: 102 },
    abilities: [
      {
        id: "bramblefox-thorn-whip",
        name: "Bramblefox's Thorn Whip",
        description: "Thorn-tailed scout signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ROOTED", chanceBps: 2432, duration: 2 },
      },
      {
        id: "bramblefox-fern-ward",
        name: "Fern Ward",
        description: "A defensive art of the Bramblefox line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "bramblefox-grove-mend",
        name: "Grove Mend",
        description: "Restores vitality with affinity light.",
        category: "HEAL",
        power: 30,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "sap-blood",
        name: "Sap Blood",
        description: "Natural vitality.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 5 },
      },
      {
        id: "bramblefox-essence",
        name: "Bramblefox Essence",
        description: "Signature passive of the Bramblefox line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "coralurge": {
    baseStats: { hp: 100, attack: 31, defense: 35, speed: 26, energy: 102 },
    abilities: [
      {
        id: "coralurge-reef-bash",
        name: "Coralurge's Reef Bash",
        description: "Reef-plated guardian signature strike.",
        category: "ATTACK",
        power: 44,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SOAKED", chanceBps: 2300, duration: 2 },
      },
      {
        id: "coralurge-reef-guard",
        name: "Reef Guard",
        description: "A defensive art of the Coralurge line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "coralurge-rift-focus",
        name: "Rift Focus",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "tidal-lungs",
        name: "Tidal Lungs",
        description: "Stronger stamina pool.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 4 },
      },
      {
        id: "slick-scales",
        name: "Slick Scales",
        description: "Water-slick evasion.",
        hook: { kind: "EVASION_BONUS", amount: 3 },
      },
      {
        id: "coralurge-essence",
        name: "Coralurge Essence",
        description: "Signature passive of the Coralurge line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "ashwing": {
    baseStats: { hp: 92, attack: 39, defense: 26, speed: 32, energy: 100 },
    abilities: [
      {
        id: "ashwing-cinder-bite",
        name: "Ashwing's Cinder Bite",
        description: "Ash-feathered glider opening technique.",
        category: "ATTACK",
        power: 39,
        energyCost: 10,
        cooldown: 0,
        status: { id: "BURN", chanceBps: 1800, duration: 2 },
      },
      {
        id: "ashwing-ash-lash",
        name: "Ash Lash",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 51,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "ashwing-heartburst-rush",
        name: "Ashwing Heartburst Rush",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 71,
        energyCost: 38,
        cooldown: 4,
        status: { id: "BURN", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "kindled-spirit",
        name: "Kindled Spirit",
        description: "Happiness rises easier near warmth.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 3 },
      },
      {
        id: "ashwing-essence",
        name: "Ashwing Essence",
        description: "Signature passive of the Ashwing line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "quartzhorn": {
    baseStats: { hp: 112, attack: 31, defense: 43, speed: 18, energy: 95 },
    abilities: [
      {
        id: "quartzhorn-canyon-edge",
        name: "Quartzhorn's Canyon Edge",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 43,
        energyCost: 11,
        cooldown: 0,
        status: { id: "SLOWED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "quartzhorn-quartz-shell",
        name: "Quartz Shell",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "quartzhorn-canyon-quake",
        name: "Quartzhorn Canyon Quake",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 80,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "steady-keeper",
        name: "Steady Keeper",
        description: "Health holds under care.",
        hook: { kind: "CARE_BONUS", care: "health", amount: 3 },
      },
      {
        id: "bedrock",
        name: "Bedrock",
        description: "Massive resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 5 },
      },
      {
        id: "quartzhorn-essence",
        name: "Quartzhorn Essence",
        description: "Signature passive of the Quartzhorn line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "staticat": {
    baseStats: { hp: 88, attack: 35, defense: 24, speed: 39, energy: 110 },
    abilities: [
      {
        id: "staticat-static-bolt",
        name: "Staticat's Static Bolt",
        description: "Spark-whiskered climber opening technique.",
        category: "ATTACK",
        power: 39,
        energyCost: 10,
        cooldown: 0,
        status: { id: "CHARGED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "staticat-moth-zap",
        name: "Moth Zap",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 53,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "staticat-tempest-dive",
        name: "Staticat Tempest Dive",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 71,
        energyCost: 38,
        cooldown: 4,
        status: { id: "CHARGED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "gale-step",
        name: "Gale Step",
        description: "Moves like wind.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "livewire",
        name: "Livewire",
        description: "Extra spark in reserve.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "staticat-essence",
        name: "Staticat Essence",
        description: "Signature passive of the Staticat line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "glimmerp": {
    baseStats: { hp: 94, attack: 34, defense: 27, speed: 34, energy: 106 },
    abilities: [
      {
        id: "glimmerp-prism-tip",
        name: "Glimmerp's Prism Tip",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 43,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "glimmerp-dawn-mend",
        name: "Dawn Mend",
        description: "Affinity healing art.",
        category: "HEAL",
        power: 34,
        energyCost: 15,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "glimmerp-citadel-guard",
        name: "Citadel Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "glimmerp-aura-nova",
        name: "Glimmerp Aura Nova",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 83,
        energyCost: 42,
        cooldown: 5,
        status: { id: "ILLUMINATED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "dawn-joy",
        name: "Dawn Joy",
        description: "Care lifts the spirit.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "halo-edge",
        name: "Halo Edge",
        description: "Affinity light cuts cleaner.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "glimmerp-essence",
        name: "Glimmerp Essence",
        description: "Signature passive of the Glimmerp line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "mistwraith": {
    baseStats: { hp: 86, attack: 39, defense: 27, speed: 42, energy: 112 },
    abilities: [
      {
        id: "mistwraith-shade-flick",
        name: "Mistwraith's Shade Flick",
        description: "Mist-bodied wanderer signature strike.",
        category: "ATTACK",
        power: 44,
        energyCost: 10,
        cooldown: 0,
        status: { id: "WEAKENED", chanceBps: 2244, duration: 2 },
      },
      {
        id: "mistwraith-void-cloak",
        name: "Void Cloak",
        description: "A defensive art of the Mistwraith line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "mistwraith-blink-out",
        name: "Blink Out",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "echo-mind",
        name: "Echo Mind",
        description: "Affinity voids bite deeper.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "rift-skin",
        name: "Rift Skin",
        description: "Hard to track.",
        hook: { kind: "EVASION_BONUS", amount: 5 },
      },
      {
        id: "mistwraith-essence",
        name: "Mistwraith Essence",
        description: "Signature passive of the Mistwraith line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "ironbloom": {
    baseStats: { hp: 104, attack: 30, defense: 36, speed: 24, energy: 100 },
    abilities: [
      {
        id: "ironbloom-cog-rush",
        name: "Ironbloom's Cog Rush",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "ironbloom-oil-mend",
        name: "Oil Mend",
        description: "Affinity healing art.",
        category: "HEAL",
        power: 34,
        energyCost: 15,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "ironbloom-hex-plate",
        name: "Hex Plate",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "ironbloom-scrapstorm",
        name: "Ironbloom Scrapstorm",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "CHARGED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "hex-core",
        name: "Hex Core",
        description: "Stable power cell.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 4 },
      },
      {
        id: "tempered-frame",
        name: "Tempered Frame",
        description: "Forged resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "ironbloom-essence",
        name: "Ironbloom Essence",
        description: "Signature passive of the Ironbloom line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "riftpup": {
    baseStats: { hp: 94, attack: 29, defense: 29, speed: 33, energy: 109 },
    abilities: [
      {
        id: "riftpup-wisp-dart",
        name: "Riftpup's Wisp Dart",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 45,
        energyCost: 11,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "riftpup-spirit-ward",
        name: "Spirit Ward",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "riftpup-marsh-awakening",
        name: "Riftpup Marsh Awakening",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 78,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "ancestral-echo",
        name: "Ancestral Echo",
        description: "Affinity spirit techniques swell.",
        hook: { kind: "AFFINITY_POWER", bps: 550 },
      },
      {
        id: "wisp-step",
        name: "Wisp Step",
        description: "Half-here mobility.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 3 },
      },
      {
        id: "riftpup-essence",
        name: "Riftpup Essence",
        description: "Signature passive of the Riftpup line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "tidewisp": {
    baseStats: { hp: 102, attack: 28, defense: 34, speed: 24, energy: 100 },
    abilities: [
      {
        id: "tidewisp-otter-whirl",
        name: "Tidewisp's Otter Whirl",
        description: "Floating droplet opening technique.",
        category: "ATTACK",
        power: 41,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SOAKED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "tidewisp-reef-bash",
        name: "Reef Bash",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 51,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "tidewisp-mooncollapse",
        name: "Tidewisp Mooncollapse",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 38,
        cooldown: 4,
        status: { id: "SOAKED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "slick-scales",
        name: "Slick Scales",
        description: "Water-slick evasion.",
        hook: { kind: "EVASION_BONUS", amount: 3 },
      },
      {
        id: "moon-calm",
        name: "Moon Calm",
        description: "Gentle care soothes deeply.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 3 },
      },
      {
        id: "tidewisp-essence",
        name: "Tidewisp Essence",
        description: "Signature passive of the Tidewisp line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "embernewt": {
    baseStats: { hp: 92, attack: 37, defense: 26, speed: 33, energy: 102 },
    abilities: [
      {
        id: "embernewt-lava-flick",
        name: "Embernewt's Lava Flick",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "embernewt-rift-focus",
        name: "Rift Focus",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "BURN", chanceBps: 5000, duration: 2 },
      },
      {
        id: "embernewt-ash-mantle",
        name: "Ash Mantle",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "embernewt-craterflare",
        name: "Embernewt Craterflare",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "BURN", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "ashen-hide",
        name: "Ashen Hide",
        description: "Heat-toughened hide.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      },
      {
        id: "kindled-spirit",
        name: "Kindled Spirit",
        description: "Happiness rises easier near warmth.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 3 },
      },
      {
        id: "embernewt-essence",
        name: "Embernewt Essence",
        description: "Signature passive of the Embernewt line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "groveowl": {
    baseStats: { hp: 100, attack: 28, defense: 35, speed: 25, energy: 100 },
    abilities: [
      {
        id: "groveowl-leaf-dart",
        name: "Groveowl's Leaf Dart",
        description: "Leaf-winged watcher opening technique.",
        category: "ATTACK",
        power: 41,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ROOTED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "groveowl-bramble-snap",
        name: "Bramble Snap",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 49,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "groveowl-worldroot-pulse",
        name: "Groveowl Worldroot Pulse",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 38,
        cooldown: 4,
        status: { id: "ROOTED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "deep-roots",
        name: "Deep Roots",
        description: "Hard to topple.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "green-heart",
        name: "Green Heart",
        description: "Bond with keepers grows steadily.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 4 },
      },
      {
        id: "groveowl-essence",
        name: "Groveowl Essence",
        description: "Signature passive of the Groveowl line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "stormmoth": {
    baseStats: { hp: 86, attack: 36, defense: 22, speed: 41, energy: 114 },
    abilities: [
      {
        id: "stormmoth-wind-horn",
        name: "Stormmoth's Wind Horn",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 43,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "stormmoth-ozone-breath",
        name: "Ozone Breath",
        description: "Affinity healing art.",
        category: "HEAL",
        power: 34,
        energyCost: 15,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "stormmoth-static-guard",
        name: "Static Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "stormmoth-tempest-dive",
        name: "Stormmoth Tempest Dive",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 83,
        energyCost: 42,
        cooldown: 5,
        status: { id: "CHARGED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "gale-step",
        name: "Gale Step",
        description: "Moves like wind.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "stormmoth-essence",
        name: "Stormmoth Essence",
        description: "Signature passive of the Stormmoth line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "stonegrub": {
    baseStats: { hp: 114, attack: 28, defense: 42, speed: 16, energy: 93 },
    abilities: [
      {
        id: "stonegrub-hearth-slam",
        name: "Stonegrub's Hearth Slam",
        description: "Burrowing mineral grub opening technique.",
        category: "ATTACK",
        power: 43,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SLOWED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "stonegrub-beetle-ram",
        name: "Beetle Ram",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 55,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "stonegrub-canyon-quake",
        name: "Stonegrub Canyon Quake",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 75,
        energyCost: 38,
        cooldown: 4,
        status: { id: "SLOWED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "steady-keeper",
        name: "Steady Keeper",
        description: "Health holds under care.",
        hook: { kind: "CARE_BONUS", care: "health", amount: 3 },
      },
      {
        id: "heavy-ore",
        name: "Heavy Ore",
        description: "Dense body.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 7 },
      },
      {
        id: "stonegrub-essence",
        name: "Stonegrub Essence",
        description: "Signature passive of the Stonegrub line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "frostfin": {
    baseStats: { hp: 90, attack: 34, defense: 31, speed: 30, energy: 100 },
    abilities: [
      {
        id: "frostfin-flurry-jab",
        name: "Frostfin's Flurry Jab",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 43,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "frostfin-rift-focus",
        name: "Rift Focus",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "CHILLED", chanceBps: 5000, duration: 2 },
      },
      {
        id: "frostfin-frost-shell",
        name: "Frost Shell",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "frostfin-winter-ring",
        name: "Frostfin Winter Ring",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 83,
        energyCost: 42,
        cooldown: 5,
        status: { id: "CHILLED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "rime-coat",
        name: "Rime Coat",
        description: "Icy outer layer.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      },
      {
        id: "powder-step",
        name: "Powder Step",
        description: "Vanishes into flurries.",
        hook: { kind: "EVASION_BONUS", amount: 4 },
      },
      {
        id: "frostfin-essence",
        name: "Frostfin Essence",
        description: "Signature passive of the Frostfin line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "radiantkit": {
    baseStats: { hp: 96, attack: 33, defense: 28, speed: 32, energy: 108 },
    abilities: [
      {
        id: "radiantkit-moth-dust",
        name: "Radiantkit's Moth Dust",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "radiantkit-dawn-mend",
        name: "Dawn Mend",
        description: "Affinity healing art.",
        category: "HEAL",
        power: 34,
        energyCost: 15,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "radiantkit-radiant-ward",
        name: "Radiant Ward",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "radiantkit-dawnstar-ray",
        name: "Radiantkit Dawnstar Ray",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "ILLUMINATED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "sun-core",
        name: "Sun Core",
        description: "Bright energy reserves.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "halo-edge",
        name: "Halo Edge",
        description: "Affinity light cuts cleaner.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "radiantkit-essence",
        name: "Radiantkit Essence",
        description: "Signature passive of the Radiantkit line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "voidling": {
    baseStats: { hp: 84, attack: 38, defense: 23, speed: 38, energy: 108 },
    abilities: [
      {
        id: "voidling-hollow-sting",
        name: "Voidling's Hollow Sting",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 48,
        energyCost: 11,
        cooldown: 0,
        status: { id: "WEAKENED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "voidling-void-cloak",
        name: "Void Cloak",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "voidling-eclipse-pulse",
        name: "Voidling Eclipse Pulse",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 80,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "rift-skin",
        name: "Rift Skin",
        description: "Hard to track.",
        hook: { kind: "EVASION_BONUS", amount: 5 },
      },
      {
        id: "echo-mind",
        name: "Echo Mind",
        description: "Affinity voids bite deeper.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "voidling-essence",
        name: "Voidling Essence",
        description: "Signature passive of the Voidling line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "cogpup": {
    baseStats: { hp: 104, attack: 33, defense: 39, speed: 22, energy: 98 },
    abilities: [
      {
        id: "cogpup-gear-bite",
        name: "Cogpup's Gear Bite",
        description: "Scrap-yard pup signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "CHARGED", chanceBps: 2624, duration: 2 },
      },
      {
        id: "cogpup-alloy-barrier",
        name: "Alloy Barrier",
        description: "A defensive art of the Cogpup line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "cogpup-rift-focus",
        name: "Rift Focus",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "tempered-frame",
        name: "Tempered Frame",
        description: "Forged resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "hex-core",
        name: "Hex Core",
        description: "Stable power cell.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 4 },
      },
      {
        id: "cogpup-essence",
        name: "Cogpup Essence",
        description: "Signature passive of the Cogpup line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "lanternjay": {
    baseStats: { hp: 92, attack: 30, defense: 29, speed: 34, energy: 107 },
    abilities: [
      {
        id: "lanternjay-loom-lash",
        name: "Lanternjay's Loom Lash",
        description: "Lantern-crest bird signature strike.",
        category: "ATTACK",
        power: 44,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2636, duration: 2 },
      },
      {
        id: "lanternjay-spirit-ward",
        name: "Spirit Ward",
        description: "A defensive art of the Lanternjay line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "lanternjay-rift-focus",
        name: "Rift Focus",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "lantern-soul",
        name: "Lantern Soul",
        description: "Soft spiritual presence.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "ancestral-echo",
        name: "Ancestral Echo",
        description: "Affinity spirit techniques swell.",
        hook: { kind: "AFFINITY_POWER", bps: 550 },
      },
      {
        id: "lanternjay-essence",
        name: "Lanternjay Essence",
        description: "Signature passive of the Lanternjay line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "craterhorn": {
    baseStats: { hp: 96, attack: 37, defense: 31, speed: 28, energy: 100 },
    abilities: [
      {
        id: "craterhorn-heat-spike",
        name: "Craterhorn's Heat Spike",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 44,
        energyCost: 11,
        cooldown: 0,
        status: { id: "BURN", chanceBps: 2200, duration: 2 },
      },
      {
        id: "craterhorn-cinder-plate",
        name: "Cinder Plate",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "craterhorn-heartburst-rush",
        name: "Craterhorn Heartburst Rush",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 76,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "kindled-spirit",
        name: "Kindled Spirit",
        description: "Happiness rises easier near warmth.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 3 },
      },
      {
        id: "craterhorn-essence",
        name: "Craterhorn Essence",
        description: "Signature passive of the Craterhorn line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "moonray": {
    baseStats: { hp: 100, attack: 28, defense: 32, speed: 28, energy: 104 },
    abilities: [
      {
        id: "moonray-brine-lance",
        name: "Moonray's Brine Lance",
        description: "Moonlit gliding ray opening technique.",
        category: "ATTACK",
        power: 41,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SOAKED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "moonray-wave-crest",
        name: "Wave Crest",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 53,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "moonray-mooncollapse",
        name: "Moonray Mooncollapse",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 38,
        cooldown: 4,
        status: { id: "SOAKED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "slick-scales",
        name: "Slick Scales",
        description: "Water-slick evasion.",
        hook: { kind: "EVASION_BONUS", amount: 3 },
      },
      {
        id: "moon-calm",
        name: "Moon Calm",
        description: "Gentle care soothes deeply.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 3 },
      },
      {
        id: "moonray-essence",
        name: "Moonray Essence",
        description: "Signature passive of the Moonray line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "rootling": {
    baseStats: { hp: 98, attack: 27, defense: 34, speed: 29, energy: 100 },
    abilities: [
      {
        id: "rootling-thorn-whip",
        name: "Rootling's Thorn Whip",
        description: "Walking root cluster signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ROOTED", chanceBps: 2600, duration: 2 },
      },
      {
        id: "rootling-thicket-plate",
        name: "Thicket Plate",
        description: "A defensive art of the Rootling line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "rootling-rift-focus",
        name: "Rift Focus",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "green-heart",
        name: "Green Heart",
        description: "Bond with keepers grows steadily.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 4 },
      },
      {
        id: "sap-blood",
        name: "Sap Blood",
        description: "Natural vitality.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 5 },
      },
      {
        id: "rootling-essence",
        name: "Rootling Essence",
        description: "Signature passive of the Rootling line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "spirekite": {
    baseStats: { hp: 88, attack: 37, defense: 24, speed: 38, energy: 108 },
    abilities: [
      {
        id: "spirekite-thunder-tip",
        name: "Spirekite's Thunder Tip",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 48,
        energyCost: 11,
        cooldown: 0,
        status: { id: "CHARGED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "spirekite-storm-veil",
        name: "Storm Veil",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "spirekite-peak-thunder",
        name: "Spirekite Peak Thunder",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 74,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "charged-wits",
        name: "Charged Wits",
        description: "Sharper critical arcs.",
        hook: { kind: "CRIT_BONUS", bps: 450 },
      },
      {
        id: "gale-step",
        name: "Gale Step",
        description: "Moves like wind.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "spirekite-essence",
        name: "Spirekite Essence",
        description: "Signature passive of the Spirekite line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "canyonbeetle": {
    baseStats: { hp: 110, attack: 30, defense: 41, speed: 19, energy: 95 },
    abilities: [
      {
        id: "canyonbeetle-beetle-ram",
        name: "Canyonbeetle's Beetle Ram",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "canyonbeetle-rift-focus",
        name: "Rift Focus",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "SLOWED", chanceBps: 5000, duration: 2 },
      },
      {
        id: "canyonbeetle-stone-guard",
        name: "Stone Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "canyonbeetle-mountain-guard",
        name: "Canyonbeetle Mountain Guard",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "SLOWED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "bedrock",
        name: "Bedrock",
        description: "Massive resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 5 },
      },
      {
        id: "heavy-ore",
        name: "Heavy Ore",
        description: "Dense body.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 7 },
      },
      {
        id: "canyonbeetle-essence",
        name: "Canyonbeetle Essence",
        description: "Signature passive of the Canyonbeetle line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "snowpuff": {
    baseStats: { hp: 90, attack: 33, defense: 29, speed: 32, energy: 102 },
    abilities: [
      {
        id: "snowpuff-frost-bite",
        name: "Snowpuff's Frost Bite",
        description: "Rolling snow fluff signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "CHILLED", chanceBps: 2168, duration: 2 },
      },
      {
        id: "snowpuff-rime-plate",
        name: "Rime Plate",
        description: "A defensive art of the Snowpuff line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "snowpuff-cold-mend",
        name: "Cold Mend",
        description: "Restores vitality with affinity light.",
        category: "HEAL",
        power: 30,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "cold-focus",
        name: "Cold Focus",
        description: "Piercing chill crits.",
        hook: { kind: "CRIT_BONUS", bps: 400 },
      },
      {
        id: "rime-coat",
        name: "Rime Coat",
        description: "Icy outer layer.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      },
      {
        id: "snowpuff-essence",
        name: "Snowpuff Essence",
        description: "Signature passive of the Snowpuff line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "citadelmoth": {
    baseStats: { hp: 96, attack: 33, defense: 31, speed: 29, energy: 104 },
    abilities: [
      {
        id: "citadelmoth-star-needle",
        name: "Citadelmoth's Star Needle",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 43,
        energyCost: 11,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "citadelmoth-citadel-guard",
        name: "Citadel Guard",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "citadelmoth-aura-nova",
        name: "Citadelmoth Aura Nova",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 74,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "dawn-joy",
        name: "Dawn Joy",
        description: "Care lifts the spirit.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "halo-edge",
        name: "Halo Edge",
        description: "Affinity light cuts cleaner.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "citadelmoth-essence",
        name: "Citadelmoth Essence",
        description: "Signature passive of the Citadelmoth line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "riftslug": {
    baseStats: { hp: 92, attack: 33, defense: 29, speed: 30, energy: 104 },
    abilities: [
      {
        id: "riftslug-echo-bite",
        name: "Riftslug's Echo Bite",
        description: "Star-trail serpentine signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "WEAKENED", chanceBps: 2688, duration: 2 },
      },
      {
        id: "riftslug-void-cloak",
        name: "Void Cloak",
        description: "A defensive art of the Riftslug line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "riftslug-hollow-mend",
        name: "Hollow Mend",
        description: "Restores vitality with affinity light.",
        category: "HEAL",
        power: 30,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "silent-bond",
        name: "Silent Bond",
        description: "Quiet companionship builds bond.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 3 },
      },
      {
        id: "echo-mind",
        name: "Echo Mind",
        description: "Affinity voids bite deeper.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "riftslug-essence",
        name: "Riftslug Essence",
        description: "Signature passive of the Riftslug line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "scrapfinch": {
    baseStats: { hp: 98, attack: 35, defense: 32, speed: 28, energy: 100 },
    abilities: [
      {
        id: "scrapfinch-plate-cut",
        name: "Scrapfinch's Plate Cut",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 43,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "scrapfinch-magnet-field",
        name: "Magnet Field",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "CHARGED", chanceBps: 5000, duration: 2 },
      },
      {
        id: "scrapfinch-cog-guard",
        name: "Cog Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "scrapfinch-hex-overdrive",
        name: "Scrapfinch Hex Overdrive",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 83,
        energyCost: 42,
        cooldown: 5,
        status: { id: "CHARGED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "loyal-gears",
        name: "Loyal Gears",
        description: "Protective loyalty.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      },
      {
        id: "hex-core",
        name: "Hex Core",
        description: "Stable power cell.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 4 },
      },
      {
        id: "scrapfinch-essence",
        name: "Scrapfinch Essence",
        description: "Signature passive of the Scrapfinch line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "marshloom": {
    baseStats: { hp: 96, attack: 27, defense: 31, speed: 31, energy: 107 },
    abilities: [
      {
        id: "marshloom-loom-lash",
        name: "Marshloom's Loom Lash",
        description: "Blooming marsh spirit signature strike.",
        category: "ATTACK",
        power: 44,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2628, duration: 2 },
      },
      {
        id: "marshloom-spirit-ward",
        name: "Spirit Ward",
        description: "A defensive art of the Marshloom line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "marshloom-rift-focus",
        name: "Rift Focus",
        description: "Shapes the field in its favor.",
        category: "SUPPORT",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "INSPIRED", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "lantern-soul",
        name: "Lantern Soul",
        description: "Soft spiritual presence.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "ancestral-echo",
        name: "Ancestral Echo",
        description: "Affinity spirit techniques swell.",
        hook: { kind: "AFFINITY_POWER", bps: 550 },
      },
      {
        id: "marshloom-essence",
        name: "Marshloom Essence",
        description: "Signature passive of the Marshloom line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "commonspark": {
    baseStats: { hp: 86, attack: 36, defense: 22, speed: 41, energy: 114 },
    abilities: [
      {
        id: "commonspark-gale-slash",
        name: "Commonspark's Gale Slash",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 45,
        energyCost: 11,
        cooldown: 0,
        status: { id: "CHARGED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "commonspark-storm-veil",
        name: "Storm Veil",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "commonspark-sky-rift-bolt",
        name: "Commonspark Sky Rift Bolt",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 82,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "livewire",
        name: "Livewire",
        description: "Extra spark in reserve.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "gale-step",
        name: "Gale Step",
        description: "Moves like wind.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "commonspark-essence",
        name: "Commonspark Essence",
        description: "Signature passive of the Commonspark line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "hearthstone": {
    baseStats: { hp: 112, attack: 31, defense: 43, speed: 18, energy: 95 },
    abilities: [
      {
        id: "hearthstone-beetle-ram",
        name: "Hearthstone's Beetle Ram",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "hearthstone-rift-focus",
        name: "Rift Focus",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "SLOWED", chanceBps: 5000, duration: 2 },
      },
      {
        id: "hearthstone-stone-guard",
        name: "Stone Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "hearthstone-mountain-guard",
        name: "Hearthstone Mountain Guard",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "SLOWED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "bedrock",
        name: "Bedrock",
        description: "Massive resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 5 },
      },
      {
        id: "heavy-ore",
        name: "Heavy Ore",
        description: "Dense body.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 7 },
      },
      {
        id: "hearthstone-essence",
        name: "Hearthstone Essence",
        description: "Signature passive of the Hearthstone line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "tideotter": {
    baseStats: { hp: 98, attack: 30, defense: 30, speed: 30, energy: 106 },
    abilities: [
      {
        id: "tideotter-ray-glide",
        name: "Tideotter's Ray Glide",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 47,
        energyCost: 11,
        cooldown: 0,
        status: { id: "SOAKED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "tideotter-tide-shell",
        name: "Tide Shell",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "tideotter-mooncollapse",
        name: "Tideotter Mooncollapse",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 80,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "slick-scales",
        name: "Slick Scales",
        description: "Water-slick evasion.",
        hook: { kind: "EVASION_BONUS", amount: 3 },
      },
      {
        id: "tidal-lungs",
        name: "Tidal Lungs",
        description: "Stronger stamina pool.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 4 },
      },
      {
        id: "tideotter-essence",
        name: "Tideotter Essence",
        description: "Signature passive of the Tideotter line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "emberfox": {
    baseStats: { hp: 90, attack: 39, defense: 24, speed: 34, energy: 102 },
    abilities: [
      {
        id: "emberfox-ash-lash",
        name: "Emberfox's Ash Lash",
        description: "Foxfire-tailed scout signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "BURN", chanceBps: 2296, duration: 2 },
      },
      {
        id: "emberfox-ember-shell",
        name: "Ember Shell",
        description: "A defensive art of the Emberfox line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "emberfox-warm-mend",
        name: "Warm Mend",
        description: "Restores vitality with affinity light.",
        category: "HEAL",
        power: 30,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "ashen-hide",
        name: "Ashen Hide",
        description: "Heat-toughened hide.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      },
      {
        id: "kindled-spirit",
        name: "Kindled Spirit",
        description: "Happiness rises easier near warmth.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 3 },
      },
      {
        id: "emberfox-essence",
        name: "Emberfox Essence",
        description: "Signature passive of the Emberfox line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "elderfern": {
    baseStats: { hp: 100, attack: 28, defense: 35, speed: 25, energy: 100 },
    abilities: [
      {
        id: "elderfern-owl-talon",
        name: "Elderfern's Owl Talon",
        description: "Ancient fern biped opening technique.",
        category: "ATTACK",
        power: 41,
        energyCost: 10,
        cooldown: 0,
        status: { id: "ROOTED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "elderfern-thorn-whip",
        name: "Thorn Whip",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 55,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "elderfern-worldroot-pulse",
        name: "Elderfern Worldroot Pulse",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 38,
        cooldown: 4,
        status: { id: "ROOTED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "deep-roots",
        name: "Deep Roots",
        description: "Hard to topple.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "sap-blood",
        name: "Sap Blood",
        description: "Natural vitality.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 5 },
      },
      {
        id: "elderfern-essence",
        name: "Elderfern Essence",
        description: "Signature passive of the Elderfern line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "peakibex": {
    baseStats: { hp: 88, attack: 37, defense: 24, speed: 38, energy: 108 },
    abilities: [
      {
        id: "peakibex-spire-dive",
        name: "Peakibex's Spire Dive",
        description: "Reliable opening hit.",
        category: "ATTACK",
        power: 39,
        energyCost: 9,
        cooldown: 0,
      },
      {
        id: "peakibex-rift-focus",
        name: "Rift Focus",
        description: "Tactical field craft.",
        category: "SUPPORT",
        power: 18,
        energyCost: 11,
        cooldown: 2,
        status: { id: "CHARGED", chanceBps: 5000, duration: 2 },
      },
      {
        id: "peakibex-static-guard",
        name: "Static Guard",
        description: "Protective stance.",
        category: "DEFEND",
        power: 0,
        energyCost: 10,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "peakibex-tempest-dive",
        name: "Peakibex Tempest Dive",
        description: "Named ultimate technique.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 42,
        cooldown: 5,
        status: { id: "CHARGED", chanceBps: 4000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "gale-step",
        name: "Gale Step",
        description: "Moves like wind.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 4 },
      },
      {
        id: "livewire",
        name: "Livewire",
        description: "Extra spark in reserve.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 5 },
      },
      {
        id: "peakibex-essence",
        name: "Peakibex Essence",
        description: "Signature passive of the Peakibex line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "fossilhound": {
    baseStats: { hp: 112, attack: 31, defense: 43, speed: 18, energy: 95 },
    abilities: [
      {
        id: "fossilhound-rock-bite",
        name: "Fossilhound's Rock Bite",
        description: "Fossil-plated hound signature strike.",
        category: "ATTACK",
        power: 40,
        energyCost: 10,
        cooldown: 0,
        status: { id: "SLOWED", chanceBps: 2440, duration: 2 },
      },
      {
        id: "fossilhound-fossil-plate",
        name: "Fossil Plate",
        description: "A defensive art of the Fossilhound line.",
        category: "DEFEND",
        power: 0,
        energyCost: 9,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "fossilhound-mineral-mend",
        name: "Mineral Mend",
        description: "Restores vitality with affinity light.",
        category: "HEAL",
        power: 30,
        energyCost: 14,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      }
    ],
    traits: [
      {
        id: "heavy-ore",
        name: "Heavy Ore",
        description: "Dense body.",
        hook: { kind: "STAT_BONUS", stat: "hp", amount: 7 },
      },
      {
        id: "bedrock",
        name: "Bedrock",
        description: "Massive resilience.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 5 },
      },
      {
        id: "fossilhound-essence",
        name: "Fossilhound Essence",
        description: "Signature passive of the Fossilhound line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "veilhare": {
    baseStats: { hp: 90, attack: 31, defense: 32, speed: 31, energy: 100 },
    abilities: [
      {
        id: "veilhare-rime-tip",
        name: "Veilhare's Rime Tip",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 48,
        energyCost: 11,
        cooldown: 0,
        status: { id: "CHILLED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "veilhare-rime-plate",
        name: "Rime Plate",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "veilhare-crystal-flood",
        name: "Veilhare Crystal Flood",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 80,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "cold-focus",
        name: "Cold Focus",
        description: "Piercing chill crits.",
        hook: { kind: "CRIT_BONUS", bps: 400 },
      },
      {
        id: "rime-coat",
        name: "Rime Coat",
        description: "Icy outer layer.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 3 },
      },
      {
        id: "veilhare-essence",
        name: "Veilhare Essence",
        description: "Signature passive of the Veilhare line.",
        hook: { kind: "CARE_BONUS", care: "energy", amount: 3 },
      }
    ],
  },
  "auralynx": {
    baseStats: { hp: 94, attack: 39, defense: 29, speed: 35, energy: 104 },
    abilities: [
      {
        id: "auralynx-aura-slash",
        name: "Auralynx's Aura Slash",
        description: "Primary affinity assault.",
        category: "ATTACK",
        power: 45,
        energyCost: 11,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2200, duration: 2 },
      },
      {
        id: "auralynx-dawn-veil",
        name: "Dawn Veil",
        description: "Brace and endure.",
        category: "DEFEND",
        power: 0,
        energyCost: 8,
        cooldown: 2,
        target: "SELF",
        status: { id: "FORTIFIED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "auralynx-celestial-parade",
        name: "Auralynx Celestial Parade",
        description: "High-cost dramatic technique.",
        category: "ULTIMATE",
        power: 82,
        energyCost: 40,
        cooldown: 5,
      }
    ],
    traits: [
      {
        id: "halo-edge",
        name: "Halo Edge",
        description: "Affinity light cuts cleaner.",
        hook: { kind: "AFFINITY_POWER", bps: 600 },
      },
      {
        id: "dawn-joy",
        name: "Dawn Joy",
        description: "Care lifts the spirit.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 4 },
      },
      {
        id: "auralynx-essence",
        name: "Auralynx Essence",
        description: "Signature passive of the Auralynx line.",
        hook: { kind: "STAT_BONUS", stat: "speed", amount: 2 },
      }
    ],
  },
  "hollowmoth": {
    baseStats: { hp: 86, attack: 36, defense: 25, speed: 37, energy: 108 },
    abilities: [
      {
        id: "hollowmoth-void-tip",
        name: "Hollowmoth's Void Tip",
        description: "Echo-feeding moth opening technique.",
        category: "ATTACK",
        power: 41,
        energyCost: 10,
        cooldown: 0,
        status: { id: "WEAKENED", chanceBps: 1800, duration: 2 },
      },
      {
        id: "hollowmoth-echo-bite",
        name: "Echo Bite",
        description: "A second-string assault.",
        category: "ATTACK",
        power: 53,
        energyCost: 14,
        cooldown: 1,
      },
      {
        id: "hollowmoth-eclipse-pulse",
        name: "Hollowmoth Eclipse Pulse",
        description: "Dramatic signature finisher.",
        category: "ULTIMATE",
        power: 79,
        energyCost: 38,
        cooldown: 4,
        status: { id: "WEAKENED", chanceBps: 3500, duration: 2 },
      }
    ],
    traits: [
      {
        id: "rift-skin",
        name: "Rift Skin",
        description: "Hard to track.",
        hook: { kind: "EVASION_BONUS", amount: 5 },
      },
      {
        id: "silent-bond",
        name: "Silent Bond",
        description: "Quiet companionship builds bond.",
        hook: { kind: "CARE_BONUS", care: "bond", amount: 3 },
      },
      {
        id: "hollowmoth-essence",
        name: "Hollowmoth Essence",
        description: "Signature passive of the Hollowmoth line.",
        hook: { kind: "STAT_BONUS", stat: "attack", amount: 2 },
      }
    ],
  },
  "celestora": {
    baseStats: { hp: 108, attack: 39, defense: 35, speed: 33, energy: 112 },
    abilities: [
      {
        id: "star-silk",
        name: "Star Silk",
        description: "Threads of riftlight cut the air.",
        category: "ATTACK",
        power: 48,
        energyCost: 12,
        cooldown: 0,
        status: { id: "ILLUMINATED", chanceBps: 2800, duration: 2 },
      },
      {
        id: "aurora-veil",
        name: "Aurora Veil",
        description: "Starlight silk folds into a ward.",
        category: "DEFEND",
        power: 0,
        energyCost: 12,
        cooldown: 2,
        target: "SELF",
        status: { id: "ARMORED", chanceBps: 10000, duration: 2 },
      },
      {
        id: "celestial-mend",
        name: "Celestial Mend",
        description: "Soft starfall restores allies' form.",
        category: "HEAL",
        power: 40,
        energyCost: 16,
        cooldown: 2,
        target: "SELF",
        status: { id: "REGENERATING", chanceBps: 10000, duration: 2 },
      },
      {
        id: "rift-ascension",
        name: "Rift Ascension",
        description: "Endgame bloom of pure dawnforce.",
        category: "ULTIMATE",
        power: 88,
        energyCost: 48,
        cooldown: 5,
        status: { id: "ILLUMINATED", chanceBps: 6000, duration: 3 },
      }
    ],
    traits: [
      {
        id: "starlight-silk",
        name: "Starlight Silk",
        description: "Celestial weave resists pressure.",
        hook: { kind: "STAT_BONUS", stat: "defense", amount: 4 },
      },
      {
        id: "endgame-aura",
        name: "Endgame Aura",
        description: "Vast energy well.",
        hook: { kind: "STAT_BONUS", stat: "energy", amount: 10 },
      },
      {
        id: "dawn-sovereign",
        name: "Dawn Sovereign",
        description: "Radiant techniques crest higher.",
        hook: { kind: "AFFINITY_POWER", bps: 900 },
      },
      {
        id: "calm-orbit",
        name: "Calm Orbit",
        description: "Serene presence eases care stress.",
        hook: { kind: "CARE_BONUS", care: "happiness", amount: 5 },
      }
    ],
  },
};

export function getSpeciesKit(slug: string): SpeciesKit | undefined {
  return SPECIES_KITS[slug];
}
