import type { MapGoalDef } from "@/content/map-goals/types";

/** Riftwild Commons — three starter recommendations + supporting goals. */
export const COMMONS_MAP_GOALS: MapGoalDef[] = [
  {
    id: "commons-goal-awaken",
    regionId: "riftwild-commons",
    title: "Awaken with Keeper Rowan",
    summary: "Complete the starter awakening chain and earn your first Credits.",
    kind: "story",
    creditHintMin: 25,
    creditHintMax: 50,
    suggestedSink: "NPC_SHOP_BUY",
    linkedKeys: ["starter-q1-awakening", "starter-q2-fragments"],
    priority: 1,
    starterRecommended: true,
    iconAsset: "/assets/ui/map-goals/story.svg",
  },
  {
    id: "commons-goal-hatch",
    regionId: "riftwild-commons",
    title: "Hatch a Waiting Heart",
    summary: "Visit Mira's Hatchery, gather mossmeal, and hatch your first Riftling.",
    kind: "care",
    creditHintMin: 40,
    creditHintMax: 80,
    suggestedSink: "NPC_SHOP_BUY",
    linkedKeys: ["starter-q3-waiting-heart", "starter-q4-new-bond"],
    priority: 2,
    starterRecommended: true,
    iconAsset: "/assets/ui/map-goals/care.svg",
  },
  {
    id: "commons-goal-plaza-jobs",
    regionId: "riftwild-commons",
    title: "Take a Plaza Job",
    summary: "Pick a Commons job-board task, spend a travel/service fee, earn capped Credits.",
    kind: "job",
    creditHintMin: 30,
    creditHintMax: 75,
    suggestedSink: "SERVICE_FEE",
    linkedKeys: ["job-commons-lanterns", "job-commons-courier"],
    priority: 3,
    starterRecommended: true,
    iconAsset: "/assets/ui/map-goals/job.svg",
  },
  {
    id: "commons-goal-gather-moss",
    regionId: "riftwild-commons",
    title: "Gather Grove Moss",
    summary: "Harvest commons moss nodes on cooldown — Credits funnel into craft fees.",
    kind: "gather",
    creditHintMin: 5,
    creditHintMax: 15,
    suggestedSink: "CRAFT_FEE",
    linkedKeys: ["gather-commons-moss"],
    priority: 4,
    iconAsset: "/assets/ui/map-goals/gather.svg",
  },
  {
    id: "commons-goal-restore-lanterns",
    regionId: "riftwild-commons",
    title: "Donate to Lantern Restoration",
    summary: "Burn Credits into Commons lantern restoration — leaves circulation.",
    kind: "restoration",
    creditHintMin: 0,
    creditHintMax: 0,
    suggestedSink: "RESTORATION_DONATION",
    linkedKeys: ["restore-commons-lanterns"],
    priority: 5,
    iconAsset: "/assets/ui/map-goals/restoration.svg",
  },
  {
    id: "commons-goal-train-yard",
    regionId: "riftwild-commons",
    title: "Training Yard Spar",
    summary: "Complete a light training bout, then repair gear with Credits.",
    kind: "combat",
    creditHintMin: 20,
    creditHintMax: 40,
    suggestedSink: "REPAIR",
    linkedKeys: ["starter-q5-first-steps", "event-commons-spar"],
    priority: 6,
    iconAsset: "/assets/ui/map-goals/combat.svg",
  },
];
