/**
 * AUTO-GENERATED by scripts/comics/emit-issue-001-catalog.mts — do not hand-edit.
 * Source of truth: src/content/comics/the-first-rift/issue-001/
 */
import { COVER } from "@/content/comics/art";
import { expandCoverVariants } from "@/content/comics/publishing-engine";
import type {
  ComicIssue,
  ComicPage,
  ComicPageRole,
  ComicPanelLayout,
} from "@/content/comics/types";

const coverSrc = COVER["the-first-rift"];

export const ISSUE_001_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "LEGENDS OF THE RIFT",
    "THE FIRST RIFT",
    "When the Prime broke, a courier chose to keep."
  ],
  "2": [
    "Riftwilds Comic Publishing — original fantasy. No crypto required to read.",
    "Credits & cosmetics may unlock along the way. The story itself stays free."
  ],
  "3": [
    "Story · Riftwilds Lore Desk",
    "Art · Commons Archive plates + Grok pipeline",
    "Lettering · Issue #001 engine (flattened)",
    "Canon · World Codex · Riftling Codex · Legends of the Rift TCG"
  ],
  "4": [
    "LEGENDS OF THE RIFT · ISSUE #001",
    "THE PULSE BELOW",
    "A present-day Keeper touches an ancient tear — and the First Rift answers."
  ],
  "5": [
    "Riftwild Commons. Dusk. The cobbles remember a scream the town pretends was weather.",
    "Mira Eggwarden: That's not a cart. That's a pulse.",
    "Mira Eggwarden: Compact law says invite. It doesn't say ignore the floor when it answers.",
    "THRUMMM"
  ],
  "6": [
    "Beyond the last honest lamp, the fringe still argues with the Fracture.",
    "Mira Eggwarden: You're not on any survey map. Good. Maps lie when roads rewrite.",
    "RIFT-HUMMM"
  ],
  "7": [
    "FWOOOM",
    "Mira Eggwarden: —wait—!",
    "The tear does not ask permission.",
    "VISION — AGE OF FIRST EGGS",
    "Unknown: Keep…"
  ],
  "8": [
    "Nine days before the Commons had a name.",
    "Elara Venn: The egg is warm. That is enough to keep walking.",
    "Stranger: Take the crown road — safer.",
    "Elara Venn: Safer for whom?"
  ],
  "9": [
    "She shared waybread with a child who had lost a name.",
    "Elara Venn: Call the creature yours to keep — not yours to own.",
    "CODEX ECHO — Waybread on the First Night",
    "SHELL-SONG"
  ],
  "10": [
    "Hearts were living cores. Stones are travel shards.",
    "The Commons Riftstone is a fragment of the Prime — maps of places not yet found."
  ],
  "11": [
    "Farmers, healers, and Keepers gathered where stable paths still intersected.",
    "KRRRAAAK"
  ],
  "12": [
    "Child: Is it… looking at me?",
    "Elara Venn: It is remembering the world. Help it stay gentle.",
    "HATCH—!",
    "The Soft Exodus had closed into eggs. Battle culture would come later.",
    "Village elder: What do we call you?",
    "Elara Venn: Courier. Keeper, if the egg agrees.",
    "First Riftling: …keep…",
    "FIRST-LIGHT-01"
  ],
  "13": [
    "When Bramblefox chooses a Keeper, the grove answers with green thread — Forest Bond, not a leash.",
    "Bramblefox: *vine-hum…*",
    "LEAF-SNAP",
    "Grove: Bond accepted — roots remember both names.",
    "Elara Venn: Softly. Bonds break when shouted at.",
    "Village kid: It glowed!",
    "Elara Venn: It agreed. That is rarer than glowing."
  ],
  "14": [
    "Mossprig does not charge first. It becomes the wall the egg deserves.",
    "WHUMP",
    "Elara Venn: Thank you for choosing the cradle over the chase.",
    "Mossprig: *soft moss-settle*"
  ],
  "15": [
    "Thornling's answer is growth with teeth — Sprouting Energy to trip cruelty, not crown it.",
    "CRACKLE-VASH",
    "Scavenger: Just a shell—!",
    "Elara Venn: It is a promise!",
    "Thornling: *root-snap*"
  ],
  "16": [
    "Wisplet does not blind the dark. It teaches the dark where feet may land.",
    "Elara Venn: Stay with us, little light. The Compact starts with honesty — even to fog.",
    "soft lantern whoosh"
  ],
  "17": [
    "Heat that guards. Fire that listens.",
    "Emberfox: *ash-ruff*",
    "Ashwing: *cinder-cry*",
    "Elara Venn: None of you are weapons. You are the reason weapons can wait."
  ],
  "18": [
    "LEAF-SNAP",
    "WHUMP",
    "FWOOOM",
    "Elara Venn: Hold the cradle!",
    "Loyalty is a formation."
  ],
  "19": [
    "Mud took bootprints. The Riftstone took names.",
    "Healer: We can raise walls. Or we can raise Keepers.",
    "Elara Venn: Raise Keepers who know which wall is a cradle.",
    "soft dawn wind"
  ],
  "20": [
    "Child: Will the egg leave if I am scared?",
    "Elara Venn: Fear is allowed. Force is not.",
    "That was the first Compact law — spoken before ink existed.",
    "First Riftling: …stay…"
  ],
  "21": [
    "On the seventh night the Fracture roads rearranged again.",
    "Scout: East gate is west. West gate is… soup.",
    "Elara Venn: Then we walk by warmth, not by map.",
    "First Riftling: …warm…",
    "Codex stub — Fracture roads",
    "path rewrite… hum"
  ],
  "22": [
    "A stranger offered a crown-shard for the egg — bright, legal-looking, wrong.",
    "Crown courier: Name a price. The realm will keep it safer than mud.",
    "Elara Venn: If safety needs a price, it is already theft.",
    "shard reject — clink"
  ],
  "23": [
    "Beyond the tear, something practiced patience.",
    "Beyond: …who keeps the invitation…",
    "SECOND PULSE"
  ],
  "24": [
    "Elara Venn: If you are listening from later — do not sell the story's consent.",
    "Mira Eggwarden: I'm here— I'm here—!",
    "The vision loosens. The pulse does not."
  ],
  "25": [
    "Under the moss: a mark that was not weather.",
    "Mira Eggwarden: Someone opened this on purpose.",
    "Mira Eggwarden: Elara kept an egg. Who kept the knife?"
  ],
  "26": [
    "Responsibility is not a crown. It is a walk you finish.",
    "Mira Eggwarden: Hatchery Compact still holds. Invite. Wait. Tell the truth about the tear.",
    "Theme — loyalty · responsibility · ancient betrayal",
    "Mira Eggwarden: I will not make the egg pay for someone else's curiosity."
  ],
  "27": [
    "The First Rift was not an accident.",
    "CLIFFHANGER",
    "Beyond: We opened a door. You only named a town.",
    "SECOND-PULSE"
  ],
  "28": [
    "A pale moth drifts the lamp-line — archive weather, not a weapon.",
    "Spirit Moth — cameo (TCG silhouette)",
    "Mira Eggwarden: Log it. Unstable ancient Rift. Deliberate tooling. Vision confirmed Elara's road.",
    "Mira Eggwarden: And something still listening."
  ],
  "29": [
    "The Commons keeps its name. The pulse keeps its secret.",
    "Mira Eggwarden: I'm still inviting. Don't make me regret waiting.",
    "END OF ISSUE #001 — THE PULSE BELOW"
  ],
  "30": [
    "NEXT ISSUE",
    "SPARK'S JOURNEY",
    "A Glowpup learns the road between hatchery and heart."
  ],
  "31": [
    "LETTERS FROM THE COMMONS",
    "Write the Lore Desk. Keep invitations honest."
  ],
  "32": [
    "LEGENDS OF THE RIFT",
    "Play the chapter in Live World when you are ready."
  ]
};

export const ISSUE_001_COMIC: ComicIssue = {
  slug: "the-first-rift",
  issueNumber: 1,
  title: "The First Rift",
  subtitle: "THE PULSE BELOW",
  synopsis: "Present-day Hatchery mentor Mira Eggwarden finds an unstable ancient Rift near Riftwild Commons and is pulled into visions of Elara Venn's First Rift — egg, companions, Compact — until a cliffhanger reveals the opening was deliberate.",
  publishedAt: "2026-07-20",
  readingTimeMinutes: 18,
  status: "published",
  covers: expandCoverVariants("The First Rift", coverSrc),
  tags: ["first-rift", "elara", "mira", "compact", "issue-001", "pulse-below"],
  playChapterHref: "/live-world",
  playChapterLabel: "Enter Live World",
  collectibles: [
    {
      id: "col-first-rift-cover",
      kind: "cover",
      label: "The First Rift — Standard",
      description: "Issue #001 cover collectible",
      coverKind: "standard",
    },
  ],
  rewards: [
    {
      id: "rw-first-rift-complete",
      label: "Pulse Witness",
      description: "Finished The Pulse Below",
      kind: "badge",
    },
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Present POV", blurb: "Hatchery mentor who finds the pulse." },
    { name: "Elara Venn", role: "First Keeper", blurb: "Courier who chose to keep.", speciesSlug: undefined },
    { name: "First Riftling", role: "Soft archive", blurb: "Becoming, not inventory." },
    { name: "Bramblefox", role: "Companion", blurb: "Forest Bond.", speciesSlug: "bramblefox" },
    { name: "Mossprig", role: "Companion", blurb: "Living Bulwark.", speciesSlug: "mossprig" },
    { name: "Thornling", role: "Companion", blurb: "Sprouting Energy.", speciesSlug: "thornling" },
  ],
  locations: [
    { name: "Riftwild Commons", blurb: "Present-day hearth of the Compact." },
    { name: "Commons fringe Rift", blurb: "Unstable ancient tear." },
  ],
  timelineNote: "Present Compact era + Age of First Eggs vision.",
  unlockGates: [{ kind: "free" }],
  nextIssueTeaser: {
    slug: "sparks-journey",
    hook: "A Glowpup learns the road between hatchery and heart.",
  },
  arcId: "fracture-dawn",
  volumeId: "volume-1",
  pages: [
    {
    id: "the-first-rift-issue-001-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The First Rift",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-001.webp",
    artAlt: "The First Rift p1",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p001-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 18 }, { kind: "caption", text: "THE FIRST RIFT", x: 50, y: 38 }, { kind: "narration", text: "When the Prime broke, a courier chose to keep.", x: 50, y: 62 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p002",
    pageNumber: 2,
    layout: "narrative" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside front",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-002.webp",
    artAlt: "The First Rift p2",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p002-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-002.webp",
      
      bubbles: [{ kind: "caption", text: "Riftwilds Comic Publishing — original fantasy. No crypto required to read.", x: 50, y: 30 }, { kind: "narration", text: "Credits & cosmetics may unlock along the way. The story itself stays free.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p003",
    pageNumber: 3,
    layout: "narrative" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-003.webp",
    artAlt: "The First Rift p3",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p003-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "Story · Riftwilds Lore Desk", x: 50, y: 25 }, { kind: "caption", text: "Art · Commons Archive plates + Grok pipeline", x: 50, y: 40 }, { kind: "caption", text: "Lettering · Issue #001 engine (flattened)", x: 50, y: 55 }, { kind: "narration", text: "Canon · World Codex · Riftling Codex · Legends of the Rift TCG", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "THE PULSE BELOW",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-004.webp",
    artAlt: "The First Rift p4",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p004-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT · ISSUE #001", x: 50, y: 22 }, { kind: "caption", text: "THE PULSE BELOW", x: 50, y: 42 }, { kind: "narration", text: "A present-day Keeper touches an ancient tear — and the First Rift answers.", x: 50, y: 68 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p005",
    pageNumber: 5,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-005.webp",
    artAlt: "The First Rift p5",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p005-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "Riftwild Commons. Dusk. The cobbles remember a scream the town pretends was weather.", x: 50, y: 12 }, { kind: "speech", text: "That's not a cart. That's a pulse.", speaker: "Mira Eggwarden", x: 28, y: 55, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p005-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-005.webp",
      
      bubbles: [{ kind: "thought", text: "Compact law says invite. It doesn't say ignore the floor when it answers.", speaker: "Mira Eggwarden", x: 70, y: 40, tail: "down-left" }, { kind: "sfx", text: "THRUMMM", x: 55, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p006",
    pageNumber: 6,
    layout: "wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-006.webp",
    artAlt: "The First Rift p6",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p006-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-006.webp",
      
      bubbles: [{ kind: "narration", text: "Beyond the last honest lamp, the fringe still argues with the Fracture.", x: 50, y: 10 }, { kind: "speech", text: "You're not on any survey map. Good. Maps lie when roads rewrite.", speaker: "Mira Eggwarden", x: 30, y: 62, tail: "up" }, { kind: "sfx", text: "RIFT-HUMMM", x: 72, y: 48 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p007",
    pageNumber: 7,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-007.webp",
    artAlt: "The First Rift p7",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p007-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-007.webp",
      
      bubbles: [{ kind: "sfx", text: "FWOOOM", x: 50, y: 40 }],
    },
    {
      id: "the-first-rift-issue-001-p007-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-007.webp",
      
      bubbles: [{ kind: "speech", text: "—wait—!", speaker: "Mira Eggwarden", x: 50, y: 50, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p007-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-007.webp",
      
      bubbles: [{ kind: "narration", text: "The tear does not ask permission.", x: 50, y: 30 }, { kind: "caption", text: "VISION — AGE OF FIRST EGGS", x: 50, y: 70 }],
    },
    {
      id: "the-first-rift-issue-001-p007-panel-3",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-007.webp",
      
      bubbles: [{ kind: "whisper", text: "Keep…", speaker: "Unknown", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p008",
    pageNumber: 8,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-008.webp",
    artAlt: "The First Rift p8",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p008-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "Nine days before the Commons had a name.", x: 50, y: 12 }, { kind: "speech", text: "The egg is warm. That is enough to keep walking.", speaker: "Elara Venn", x: 35, y: 58, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p008-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-008.webp",
      
      bubbles: [{ kind: "speech", text: "Take the crown road — safer.", speaker: "Stranger", x: 70, y: 30, tail: "down-left" }, { kind: "speech", text: "Safer for whom?", speaker: "Elara Venn", x: 32, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p009",
    pageNumber: 9,
    layout: "narrative" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-009.webp",
    artAlt: "The First Rift p9",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p009-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-009.webp",
      
      bubbles: [{ kind: "narration", text: "She shared waybread with a child who had lost a name.", x: 50, y: 12 }, { kind: "speech", text: "Call the creature yours to keep — not yours to own.", speaker: "Elara Venn", x: 40, y: 48, tail: "down" }, { kind: "caption", text: "CODEX ECHO — Waybread on the First Night", x: 50, y: 82 }, { kind: "sfx", text: "SHELL-SONG", x: 75, y: 65 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p010",
    pageNumber: 10,
    layout: "lore" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-010.webp",
    artAlt: "The First Rift p10",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p010-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-010.webp",
      
      bubbles: [{ kind: "narration", text: "Hearts were living cores. Stones are travel shards.", x: 50, y: 18 }, { kind: "caption", text: "The Commons Riftstone is a fragment of the Prime — maps of places not yet found.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p011",
    pageNumber: 11,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-011.webp",
    artAlt: "The First Rift p11",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p011-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-011.webp",
      
      bubbles: [{ kind: "narration", text: "Farmers, healers, and Keepers gathered where stable paths still intersected.", x: 50, y: 12 }, { kind: "sfx", text: "KRRRAAAK", x: 60, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p012",
    pageNumber: 12,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-012.webp",
    artAlt: "The First Rift p12",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p012-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "Is it… looking at me?", speaker: "Child", x: 40, y: 40, tail: "down" }, { kind: "speech", text: "It is remembering the world. Help it stay gentle.", speaker: "Elara Venn", x: 60, y: 65, tail: "up" }],
    },
    {
      id: "the-first-rift-issue-001-p012-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-012.webp",
      
      bubbles: [{ kind: "sfx", text: "HATCH—!", x: 50, y: 45 }, { kind: "narration", text: "The Soft Exodus had closed into eggs. Battle culture would come later.", x: 50, y: 75 }],
    },
    {
      id: "the-first-rift-issue-001-p012-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "What do we call you?", speaker: "Village elder", x: 40, y: 35, tail: "down" }, { kind: "speech", text: "Courier. Keeper, if the egg agrees.", speaker: "Elara Venn", x: 65, y: 60, tail: "up" }],
    },
    {
      id: "the-first-rift-issue-001-p012-panel-3",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-012.webp",
      
      bubbles: [{ kind: "thought", text: "…keep…", speaker: "First Riftling", x: 50, y: 50 }, { kind: "caption", text: "FIRST-LIGHT-01", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p013",
    pageNumber: 13,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-013.webp",
    artAlt: "The First Rift p13",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p013-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-013.webp",
      caption: "Ability — Forest Bond",
      bubbles: [{ kind: "narration", text: "When Bramblefox chooses a Keeper, the grove answers with green thread — Forest Bond, not a leash.", x: 50, y: 20 }, { kind: "creature", text: "*vine-hum…*", speaker: "Bramblefox", x: 30, y: 55 }, { kind: "sfx", text: "LEAF-SNAP", x: 72, y: 50 }],
    },
    {
      id: "the-first-rift-issue-001-p013-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-013.webp",
      
      bubbles: [{ kind: "magic", text: "Bond accepted — roots remember both names.", speaker: "Grove", x: 50, y: 40 }, { kind: "whisper", text: "Softly. Bonds break when shouted at.", speaker: "Elara Venn", x: 28, y: 70, tail: "up" }],
    },
    {
      id: "the-first-rift-issue-001-p013-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-013.webp",
      
      bubbles: [{ kind: "shout", text: "It glowed!", speaker: "Village kid", x: 40, y: 35, tail: "down" }, { kind: "speech", text: "It agreed. That is rarer than glowing.", speaker: "Elara Venn", x: 68, y: 55, tail: "down-left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p014",
    pageNumber: 14,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-014.webp",
    artAlt: "The First Rift p14",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p014-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-014.webp",
      caption: "Ability — Living Bulwark",
      bubbles: [{ kind: "narration", text: "Mossprig does not charge first. It becomes the wall the egg deserves.", x: 50, y: 14 }, { kind: "sfx", text: "WHUMP", x: 60, y: 55 }],
    },
    {
      id: "the-first-rift-issue-001-p014-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-014.webp",
      
      bubbles: [{ kind: "speech", text: "Thank you for choosing the cradle over the chase.", speaker: "Elara Venn", x: 45, y: 40, tail: "down" }, { kind: "creature", text: "*soft moss-settle*", speaker: "Mossprig", x: 70, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p015",
    pageNumber: 15,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-015.webp",
    artAlt: "The First Rift p15",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p015-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-015.webp",
      caption: "Ability — Sprouting Energy",
      bubbles: [{ kind: "narration", text: "Thornling's answer is growth with teeth — Sprouting Energy to trip cruelty, not crown it.", x: 50, y: 18 }, { kind: "sfx", text: "CRACKLE-VASH", x: 70, y: 50 }],
    },
    {
      id: "the-first-rift-issue-001-p015-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "Just a shell—!", speaker: "Scavenger", x: 30, y: 40, tail: "down" }, { kind: "shout", text: "It is a promise!", speaker: "Elara Venn", x: 65, y: 55, tail: "down-left" }],
    },
    {
      id: "the-first-rift-issue-001-p015-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-015.webp",
      
      bubbles: [{ kind: "creature", text: "*root-snap*", speaker: "Thornling", x: 50, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p016",
    pageNumber: 16,
    layout: "wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-016.webp",
    artAlt: "The First Rift p16",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p016-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-016.webp",
      caption: "Ability — Lantern Soft",
      bubbles: [{ kind: "narration", text: "Wisplet does not blind the dark. It teaches the dark where feet may land.", x: 50, y: 12 }, { kind: "speech", text: "Stay with us, little light. The Compact starts with honesty — even to fog.", speaker: "Elara Venn", x: 40, y: 60, tail: "up" }, { kind: "sfx", text: "soft lantern whoosh", x: 70, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p017",
    pageNumber: 17,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-017.webp",
    artAlt: "The First Rift p17",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p017-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-017.webp",
      caption: "Ashen Hide · Kindled Spirit",
      bubbles: [{ kind: "narration", text: "Heat that guards. Fire that listens.", x: 50, y: 12 }, { kind: "creature", text: "*ash-ruff*", speaker: "Emberfox", x: 35, y: 55 }],
    },
    {
      id: "the-first-rift-issue-001-p017-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-017.webp",
      
      bubbles: [{ kind: "creature", text: "*cinder-cry*", speaker: "Ashwing", x: 65, y: 40 }, { kind: "speech", text: "None of you are weapons. You are the reason weapons can wait.", speaker: "Elara Venn", x: 45, y: 70, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p018",
    pageNumber: 18,
    layout: "grid-2x2" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-018.webp",
    artAlt: "The First Rift p18",
    atmosphere: "storm" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p018-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "LEAF-SNAP", x: 50, y: 45 }],
    },
    {
      id: "the-first-rift-issue-001-p018-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "WHUMP", x: 50, y: 50 }],
    },
    {
      id: "the-first-rift-issue-001-p018-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-018.webp",
      
      bubbles: [{ kind: "sfx", text: "FWOOOM", x: 50, y: 45 }],
    },
    {
      id: "the-first-rift-issue-001-p018-panel-3",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "Hold the cradle!", speaker: "Elara Venn", x: 50, y: 40, tail: "down" }, { kind: "narration", text: "Loyalty is a formation.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p019",
    pageNumber: 19,
    layout: "narrative" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-019.webp",
    artAlt: "The First Rift p19",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p019-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-019.webp",
      
      bubbles: [{ kind: "narration", text: "Mud took bootprints. The Riftstone took names.", x: 50, y: 12 }, { kind: "speech", text: "We can raise walls. Or we can raise Keepers.", speaker: "Healer", x: 30, y: 45, tail: "down" }, { kind: "speech", text: "Raise Keepers who know which wall is a cradle.", speaker: "Elara Venn", x: 68, y: 58, tail: "down-left" }, { kind: "sfx", text: "soft dawn wind", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p020",
    pageNumber: 20,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-020.webp",
    artAlt: "The First Rift p20",
    atmosphere: "day" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p020-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "Will the egg leave if I am scared?", speaker: "Child", x: 40, y: 40, tail: "down" }, { kind: "speech", text: "Fear is allowed. Force is not.", speaker: "Elara Venn", x: 65, y: 60, tail: "up" }],
    },
    {
      id: "the-first-rift-issue-001-p020-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-020.webp",
      
      bubbles: [{ kind: "narration", text: "That was the first Compact law — spoken before ink existed.", x: 50, y: 30 }, { kind: "thought", text: "…stay…", speaker: "First Riftling", x: 50, y: 65 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p021",
    pageNumber: 21,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-021.webp",
    artAlt: "The First Rift p21",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p021-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-021.webp",
      
      bubbles: [{ kind: "narration", text: "On the seventh night the Fracture roads rearranged again.", x: 50, y: 18 }, { kind: "speech", text: "East gate is west. West gate is… soup.", speaker: "Scout", x: 40, y: 55, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p021-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "Then we walk by warmth, not by map.", speaker: "Elara Venn", x: 50, y: 45, tail: "down" }, { kind: "thought", text: "…warm…", speaker: "First Riftling", x: 70, y: 65 }],
    },
    {
      id: "the-first-rift-issue-001-p021-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-021.webp",
      
      bubbles: [{ kind: "caption", text: "Codex stub — Fracture roads", x: 50, y: 40 }, { kind: "sfx", text: "path rewrite… hum", x: 55, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p022",
    pageNumber: 22,
    layout: "narrative" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-022.webp",
    artAlt: "The First Rift p22",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p022-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-022.webp",
      
      bubbles: [{ kind: "narration", text: "A stranger offered a crown-shard for the egg — bright, legal-looking, wrong.", x: 50, y: 12 }, { kind: "speech", text: "Name a price. The realm will keep it safer than mud.", speaker: "Crown courier", x: 70, y: 40, tail: "down-left" }, { kind: "speech", text: "If safety needs a price, it is already theft.", speaker: "Elara Venn", x: 30, y: 62, tail: "up" }, { kind: "sfx", text: "shard reject — clink", x: 55, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p023",
    pageNumber: 23,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-023.webp",
    artAlt: "The First Rift p23",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p023-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-023.webp",
      
      bubbles: [{ kind: "narration", text: "Beyond the tear, something practiced patience.", x: 50, y: 14 }, { kind: "telepathy", text: "…who keeps the invitation…", speaker: "Beyond", x: 50, y: 48 }, { kind: "caption", text: "SECOND PULSE", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p024",
    pageNumber: 24,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-024.webp",
    artAlt: "The First Rift p24",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p024-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "If you are listening from later — do not sell the story's consent.", speaker: "Elara Venn", x: 40, y: 50, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p024-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-024.webp",
      
      bubbles: [{ kind: "shout", text: "I'm here— I'm here—!", speaker: "Mira Eggwarden", x: 55, y: 40, tail: "down" }, { kind: "narration", text: "The vision loosens. The pulse does not.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p025",
    pageNumber: 25,
    layout: "narrative" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-025.webp",
    artAlt: "The First Rift p25",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p025-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-025.webp",
      
      bubbles: [{ kind: "narration", text: "Under the moss: a mark that was not weather.", x: 50, y: 12 }, { kind: "speech", text: "Someone opened this on purpose.", speaker: "Mira Eggwarden", x: 40, y: 48, tail: "down" }, { kind: "thought", text: "Elara kept an egg. Who kept the knife?", speaker: "Mira Eggwarden", x: 65, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p026",
    pageNumber: 26,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-026.webp",
    artAlt: "The First Rift p26",
    atmosphere: "dawn" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p026-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-026.webp",
      
      bubbles: [{ kind: "narration", text: "Responsibility is not a crown. It is a walk you finish.", x: 50, y: 20 }, { kind: "speech", text: "Hatchery Compact still holds. Invite. Wait. Tell the truth about the tear.", speaker: "Mira Eggwarden", x: 45, y: 55, tail: "down" }],
    },
    {
      id: "the-first-rift-issue-001-p026-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-026.webp",
      
      bubbles: [{ kind: "caption", text: "Theme — loyalty · responsibility · ancient betrayal", x: 50, y: 50 }],
    },
    {
      id: "the-first-rift-issue-001-p026-panel-2",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-026.webp",
      
      bubbles: [{ kind: "speech", text: "I will not make the egg pay for someone else's curiosity.", speaker: "Mira Eggwarden", x: 50, y: 45, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p027",
    pageNumber: 27,
    layout: "wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-027.webp",
    artAlt: "The First Rift p27",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p027-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-027.webp",
      
      bubbles: [{ kind: "narration", text: "The First Rift was not an accident.", x: 50, y: 14 }, { kind: "caption", text: "CLIFFHANGER", x: 50, y: 40 }, { kind: "telepathy", text: "We opened a door. You only named a town.", speaker: "Beyond", x: 50, y: 62 }, { kind: "sfx", text: "SECOND-PULSE", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p028",
    pageNumber: 28,
    layout: "two-col" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-028.webp",
    artAlt: "The First Rift p28",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p028-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-028.webp",
      
      bubbles: [{ kind: "narration", text: "A pale moth drifts the lamp-line — archive weather, not a weapon.", x: 50, y: 20 }, { kind: "caption", text: "Spirit Moth — cameo (TCG silhouette)", x: 50, y: 70 }],
    },
    {
      id: "the-first-rift-issue-001-p028-panel-1",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "Log it. Unstable ancient Rift. Deliberate tooling. Vision confirmed Elara's road.", speaker: "Mira Eggwarden", x: 45, y: 45, tail: "down" }, { kind: "whisper", text: "And something still listening.", speaker: "Mira Eggwarden", x: 55, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-029.webp",
    artAlt: "The First Rift p29",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p029-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-029.webp",
      
      bubbles: [{ kind: "narration", text: "The Commons keeps its name. The pulse keeps its secret.", x: 50, y: 14 }, { kind: "speech", text: "I'm still inviting. Don't make me regret waiting.", speaker: "Mira Eggwarden", x: 40, y: 55, tail: "up" }, { kind: "caption", text: "END OF ISSUE #001 — THE PULSE BELOW", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p030",
    pageNumber: 30,
    layout: "narrative" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next: Spark's Journey",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-030.webp",
    artAlt: "The First Rift p30",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p030-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 20 }, { kind: "caption", text: "SPARK'S JOURNEY", x: 50, y: 40 }, { kind: "narration", text: "A Glowpup learns the road between hatchery and heart.", x: 50, y: 65 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p031",
    pageNumber: 31,
    layout: "narrative" as ComicPanelLayout,
    role: "inside-back" as ComicPageRole,
    title: "Inside back",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-031.webp",
    artAlt: "The First Rift p31",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p031-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "LETTERS FROM THE COMMONS", x: 50, y: 25 }, { kind: "narration", text: "Write the Lore Desk. Keep invitations honest.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
    {
    id: "the-first-rift-issue-001-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back cover",
    artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-032.webp",
    artAlt: "The First Rift p32",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-first-rift-issue-001-p032-panel-0",
      artSrc: "/assets/comics/the-first-rift/issue-001/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 30 }, { kind: "narration", text: "Play the chapter in Live World when you are ready.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
};

export function getIssue001Transcript(pageNumber: number): string[] {
  return ISSUE_001_TRANSCRIPTS[pageNumber] ?? [];
}
