import type { RegionContentPack } from "@/content/regions/types";

/** Authored Alloy Ruins — salvage, conduits, foundry restoration. */
export const ALLOY_RUINS_CONTENT_PACK: RegionContentPack = {
  regionId: "alloy-ruins",
  regionName: "Alloy Ruins",
  blurb:
    "Machine courtyards and rusted factories — scrap gather, foundry jobs, and foundry restoration.",
  questChainKeys: ["chain-alloy-ruins"],
  quests: [
    { questKey: "quest-alloy-intro", name: "Alloy Ruins: First Survey", creditReward: 45 },
    { questKey: "quest-alloy-salvage", name: "Cogwork Salvage", creditReward: 60 },
    { questKey: "quest-alloy-deep", name: "Alloy Ruins: Deep Path", creditReward: 75 },
    { questKey: "daily-alloy", name: "Alloy Ruins Daily", creditReward: 40 },
  ],
  activities: [
    {
      id: "gather-alloy-scrap",
      name: "Salvage Alloy Scrap",
      kind: "gather",
      creditReward: 13,
      cooldownMs: 32_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Scrap piles in the machine courtyard — cooldown-gated.",
    },
    {
      id: "craft-cog-core",
      name: "Craft Cog Core",
      kind: "craft",
      creditReward: 32,
      cooldownMs: 50_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Tech craft after station fee.",
    },
    {
      id: "explore-alloy-conduits",
      name: "Trace Energy Conduits",
      kind: "explore",
      creditReward: 24,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Conduit maps capped; travel fees apply.",
    },
    {
      id: "combat-alloy-spar",
      name: "Drone Spar",
      kind: "combat",
      creditReward: 20,
      cooldownMs: 90_000,
      dailyCapCredits: 60,
      sinkHint: "REPAIR",
      description: "Security drones — repairs absorb surplus.",
    },
  ],
  sinks: [
    {
      id: "sink-alloy-shop",
      reason: "NPC_SHOP_BUY",
      name: "Salvager Parts Stall",
      minCost: 25,
      maxCost: 230,
      leavesCirculation: true,
    },
    {
      id: "sink-alloy-travel",
      reason: "TRAVEL_FEE",
      name: "Ruins Trail Toll",
      minCost: 18,
      maxCost: 90,
      leavesCirculation: true,
    },
    {
      id: "sink-alloy-restore",
      reason: "RESTORATION_DONATION",
      name: "Foundry Restoration Fund",
      minCost: 10,
      maxCost: 12_000,
      leavesCirculation: true,
    },
    {
      id: "sink-alloy-repair",
      reason: "REPAIR",
      name: "Welder Repair Bench",
      minCost: 12,
      maxCost: 280,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-alloy-foundry"],
  eventKeys: ["event-alloy-sparkfall"],
  restorationKey: "restore-alloy-foundry",
  completeness: "full",
  theme: {
    lighting: "Cyan conduit glow, spark pits, gunmetal dusk",
    weatherDefault: "sparks_rain",
    vegetation: "Mechanical garden vines, rust moss on scrap",
    architecture: "Salvager sheds, gear courts, rusted factory frames",
  },
  pois: [
    {
      id: "poi-alloy-salvager",
      name: "Salvager Settlement",
      kind: "settlement",
      blurb: "Repair shop and scrap stalls.",
    },
    {
      id: "poi-alloy-gear",
      name: "Gear Court",
      kind: "landmark",
      blurb: "Courtyard of half-buried machine rings.",
    },
    {
      id: "poi-alloy-factory",
      name: "Rusted Factory",
      kind: "danger",
      blurb: "Drone patrols and spark hazards.",
    },
    {
      id: "poi-alloy-foundry",
      name: "Warframe Foundry",
      kind: "danger",
      blurb: "Boss approach for Alloy Warframe.",
    },
  ],
  npcSpawnIds: [
    "tinker-pax",
    "unit-ari-7",
    "salvager-knox",
    "professor-ferrum",
    "alloy-porter-cog",
  ],
  resourceNodeIds: ["alloy-fragment", "circuit-crystal", "gear-oil", "spark-coil"],
  enemyIds: ["security-drone", "scrap-mite", "arc-spider"],
  dangerZoneIds: ["factory", "conduits", "foundry"],
  portal: {
    id: "portal-alloy-gear",
    name: "Gear Court Gateway",
    arrivalNote: "Sparks pop overhead — metal floors hum with leftover conduit power.",
  },
  musicKey: "music-alloy",
  ambianceKey: "ambient-alloy",
  densityNote: "Midgame tech identity; deeper factory floors still backlog.",
};
