import type { RegionContentPack } from "@/content/regions/types";

/** Authored Celestial Rift — endgame starfields, observatory, gate restoration. */
export const CELESTIAL_RIFT_CONTENT_PACK: RegionContentPack = {
  regionId: "celestial-rift",
  regionName: "Celestial Rift",
  blurb:
    "Starfall fields and floating islands — gate surveys, starfall events, and celestial gate restoration.",
  questChainKeys: ["chain-celestial-rift"],
  quests: [
    { questKey: "quest-celestial-intro", name: "Celestial Rift: First Survey", creditReward: 55 },
    { questKey: "quest-celestial-gate", name: "Rift Gate Survey", creditReward: 90 },
    { questKey: "quest-celestial-deep", name: "Celestial Rift: Deep Path", creditReward: 100 },
    { questKey: "daily-celestial", name: "Celestial Rift Daily", creditReward: 45 },
  ],
  activities: [
    {
      id: "gather-star-dust",
      name: "Gather Star Dust",
      kind: "gather",
      creditReward: 18,
      cooldownMs: 45_000,
      dailyCapCredits: 90,
      sinkHint: "CRAFT_FEE",
      description: "Starfall field dust on strict cooldowns.",
    },
    {
      id: "craft-celestial-lens",
      name: "Craft Astral Lens",
      kind: "craft",
      creditReward: 36,
      cooldownMs: 60_000,
      dailyCapCredits: 110,
      sinkHint: "CRAFT_FEE",
      description: "Observatory craft after station fee.",
    },
    {
      id: "explore-celestial-islands",
      name: "Chart Floating Islands",
      kind: "explore",
      creditReward: 30,
      cooldownMs: 75_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Island charts capped; heavy travel fees.",
    },
    {
      id: "combat-celestial-spar",
      name: "Starborn Spar",
      kind: "combat",
      creditReward: 26,
      cooldownMs: 110_000,
      dailyCapCredits: 78,
      sinkHint: "REPAIR",
      description: "Starborn guardians — repairs absorb surplus.",
    },
  ],
  sinks: [
    {
      id: "sink-celestial-shop",
      reason: "NPC_SHOP_BUY",
      name: "Expedition Outfitter",
      minCost: 35,
      maxCost: 280,
      leavesCirculation: true,
    },
    {
      id: "sink-celestial-travel",
      reason: "TRAVEL_FEE",
      name: "Rift Crossing Toll",
      minCost: 25,
      maxCost: 120,
      leavesCirculation: true,
    },
    {
      id: "sink-celestial-restore",
      reason: "RESTORATION_DONATION",
      name: "Celestial Gate Fund",
      minCost: 20,
      maxCost: 20_000,
      leavesCirculation: true,
    },
    {
      id: "sink-celestial-repair",
      reason: "REPAIR",
      name: "Astral Repair Bench",
      minCost: 18,
      maxCost: 320,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-celestial-observatory"],
  eventKeys: ["event-celestial-starfall"],
  restorationKey: "restore-celestial-gate",
  completeness: "full",
  theme: {
    lighting: "Starfield shimmer, gold rift seams, observatory lens flares",
    weatherDefault: "starfall",
    vegetation: "Stargrass, crystalline flora on floating islands",
    architecture: "Expedition base, astral observatory, broken celestial city",
  },
  pois: [
    {
      id: "poi-celestial-landing",
      name: "Celestial Landing",
      kind: "settlement",
      blurb: "Expedition base and waypoint.",
    },
    {
      id: "poi-celestial-star",
      name: "Star Anchor",
      kind: "landmark",
      blurb: "Orientation pin in the starfall fields.",
    },
    {
      id: "poi-celestial-observatory",
      name: "Astral Observatory",
      kind: "landmark",
      blurb: "Constellation puzzles and craft lenses.",
    },
    {
      id: "poi-celestial-arena",
      name: "World Rift Arena",
      kind: "danger",
      blurb: "Boss approach for Celestial Rift Entity.",
    },
  ],
  npcSpawnIds: [
    "astronomer-caelis",
    "guardian-seraphine",
    "starforger-orion",
    "nameless-witness",
    "celestial-acolyte-nova",
  ],
  resourceNodeIds: ["celestial-shard", "star-dust", "orbit-glass", "rift-petal"],
  enemyIds: ["starborn-guardian", "comet-mite", "astral-wisp"],
  dangerZoneIds: ["islands", "heart", "world-rift"],
  portal: {
    id: "portal-celestial-gate",
    name: "World Rift Gateway",
    arrivalNote: "Gravity softens — starfall dust hangs in the air like slow rain.",
  },
  musicKey: "music-celestial",
  ambianceKey: "ambient-celestial",
  densityNote: "Endgame identity pack; full floating-island density still backlog.",
};
