import type { RegionContentPack } from "@/content/regions/types";

/** Fully authored Riftwild Commons content pack. */
export const COMMONS_CONTENT_PACK: RegionContentPack = {
  regionId: "riftwild-commons",
  regionName: "Riftwild Commons",
  blurb:
    "Hub of keeper life — starter quests, plaza jobs, moss gathering, care shops, and lantern restoration.",
  questChainKeys: ["starter"],
  quests: [
    { questKey: "starter-q1-awakening", name: "Awakening in the Commons", creditReward: 25 },
    { questKey: "starter-q2-fragments", name: "Fragments of the Past", creditReward: 30 },
    { questKey: "starter-q3-waiting-heart", name: "A Waiting Heart", creditReward: 50 },
    { questKey: "starter-q4-new-bond", name: "A New Bond", creditReward: 40 },
    { questKey: "starter-q5-first-steps", name: "First Steps Together", creditReward: 45 },
    { questKey: "commons-daily-plaza", name: "Plaza Sweep (Daily)", creditReward: 35 },
    { questKey: "commons-weekly-lanterns", name: "Lantern Week (Weekly)", creditReward: 120 },
  ],
  activities: [
    {
      id: "gather-commons-moss",
      name: "Gather Grove Moss",
      kind: "gather",
      creditReward: 8,
      cooldownMs: 25_000,
      dailyCapCredits: 80,
      sinkHint: "CRAFT_FEE",
      description: "Soft moss along the plaza edges — cooldown-gated.",
    },
    {
      id: "craft-commons-ration",
      name: "Craft Travel Ration",
      kind: "craft",
      creditReward: 20,
      cooldownMs: 40_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Station fee applies before completion Credits.",
    },
    {
      id: "care-commons-bond",
      name: "Commons Care Session",
      kind: "care",
      creditReward: 5,
      cooldownMs: 4 * 60 * 60 * 1000,
      dailyCapCredits: 15,
      sinkHint: "NPC_SHOP_BUY",
      description: "Capped Riftling care bonus — never unlimited.",
    },
    {
      id: "explore-commons-markers",
      name: "Repair Map Markers",
      kind: "explore",
      creditReward: 15,
      cooldownMs: 60_000,
      dailyCapCredits: 60,
      sinkHint: "REPAIR",
      description: "Earn a little, then spend on repair kits.",
    },
    {
      id: "social-commons-greet",
      name: "Plaza Greetings",
      kind: "social",
      creditReward: 10,
      cooldownMs: 120_000,
      dailyCapCredits: 30,
      sinkHint: "SERVICE_FEE",
      description: "Talk to named NPCs; services cost Credits.",
    },
  ],
  sinks: [
    {
      id: "sink-mira-shop",
      reason: "NPC_SHOP_BUY",
      name: "Mira's Care Supplies",
      minCost: 15,
      maxCost: 80,
      leavesCirculation: true,
    },
    {
      id: "sink-bram-repair",
      reason: "REPAIR",
      name: "Bram's Repair Bench",
      minCost: 10,
      maxCost: 120,
      leavesCirculation: true,
    },
    {
      id: "sink-commons-travel",
      reason: "TRAVEL_FEE",
      name: "Portal Toll (out of Commons)",
      minCost: 10,
      maxCost: 50,
      leavesCirculation: true,
    },
    {
      id: "sink-lantern-donate",
      reason: "RESTORATION_DONATION",
      name: "Commons Lantern Fund",
      minCost: 10,
      maxCost: 5000,
      leavesCirculation: true,
    },
    {
      id: "sink-craft-station",
      reason: "CRAFT_FEE",
      name: "Commons Craft Station",
      minCost: 5,
      maxCost: 40,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-commons-lanterns", "job-commons-courier", "job-commons-sweep"],
  eventKeys: ["event-commons-spar", "event-commons-market-day"],
  restorationKey: "restore-commons-lanterns",
  completeness: "full",
  theme: {
    lighting: "Warm lantern glow over teal rift haze; soft dusk plaza light",
    weatherDefault: "clear",
    vegetation: "Moss edges, berry shrubs, firefly borders",
    architecture: "Crystal-powered stone halls, hatchery, trading post, portal circle",
  },
  pois: [
    {
      id: "poi-commons-plaza",
      name: "Keeper Plaza",
      kind: "settlement",
      blurb: "Social heart — shops, jobs, and starter quests.",
    },
    {
      id: "poi-commons-hatchery",
      name: "Hatchery Terrace",
      kind: "landmark",
      blurb: "Egg care and first bonds begin here.",
    },
    {
      id: "poi-commons-portal",
      name: "Portal Circle",
      kind: "gateway",
      blurb: "Hub spokes to every open region.",
    },
    {
      id: "poi-commons-yard",
      name: "Training Yard",
      kind: "landmark",
      blurb: "Friendly spars and beginner foes.",
    },
  ],
  npcSpawnIds: [
    "elara-venn",
    "rowan-vale",
    "mira-shellbright",
    "bram-ironroot",
    "tessa-windmere",
    "archivist-solen",
  ],
  resourceNodeIds: ["berry-bush", "pond-fish", "starter-herb"],
  enemyIds: ["rift-slime", "spirit-spark", "vine-sprout"],
  dangerZoneIds: ["training-yard-edges"],
  portal: {
    id: "portal-commons-circle",
    name: "Commons Portal Circle",
    arrivalNote: "Arrive on warm stone under lantern light — the hub of Riftwilds.",
  },
  musicKey: "music-commons",
  ambianceKey: "ambient-commons",
  densityNote: "Richest starter hub; other regions match identity, not AAA density yet.",
};
