import type { RegionContentPack } from "@/content/regions/types";

/** Authored Elderwood Forest pack — grove gather, shrine restoration. */
export const ELDERWOOD_FOREST_CONTENT_PACK: RegionContentPack = {
  regionId: "elderwood-forest",
  regionName: "Elderwood Forest",
  blurb:
    "Root paths and singer groves — moss gather, shrine care, and grove restoration burns.",
  questChainKeys: ["chain-elderwood-forest"],
  quests: [
    { questKey: "quest-elder-intro", name: "Elderwood Forest: First Survey", creditReward: 40 },
    { questKey: "quest-elder-deep", name: "Elderwood Forest: Deep Path", creditReward: 70 },
    { questKey: "quest-elder-shrine", name: "Tend the Grove Shrine", creditReward: 55 },
    { questKey: "daily-elder", name: "Elderwood Forest Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-elder-moss",
      name: "Gather Elder Moss",
      kind: "gather",
      creditReward: 11,
      cooldownMs: 30_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Soft elder moss — cooldown and daily caps.",
    },
    {
      id: "craft-elder-salve",
      name: "Craft Grove Salve",
      kind: "craft",
      creditReward: 26,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Salve craft after station fee.",
    },
    {
      id: "explore-elder-roots",
      name: "Walk the Root Paths",
      kind: "explore",
      creditReward: 20,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Root exploration is capped; travel fees sink Credits.",
    },
    {
      id: "care-elder-bond",
      name: "Grove Care Session",
      kind: "care",
      creditReward: 5,
      cooldownMs: 4 * 60 * 60 * 1000,
      dailyCapCredits: 15,
      sinkHint: "CARE_ACTION",
      description: "Capped Riftling care bonus in the grove.",
    },
  ],
  sinks: [
    {
      id: "sink-elder-shop",
      reason: "NPC_SHOP_BUY",
      name: "Grove Supply Stall",
      minCost: 18,
      maxCost: 160,
      leavesCirculation: true,
    },
    {
      id: "sink-elder-travel",
      reason: "TRAVEL_FEE",
      name: "Forest Path Toll",
      minCost: 12,
      maxCost: 70,
      leavesCirculation: true,
    },
    {
      id: "sink-elder-restore",
      reason: "RESTORATION_DONATION",
      name: "Grove Shrine Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-elder-repair",
      reason: "REPAIR",
      name: "Carver Repair Bench",
      minCost: 10,
      maxCost: 220,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-elder-moss", "job-elder-shrine"],
  eventKeys: ["event-elder-chorus"],
  restorationKey: "restore-grove-shrine",
  completeness: "full",
  theme: {
    lighting: "Filtered canopy greens, glowcap underlight, mist shafts",
    weatherDefault: "mist",
    vegetation: "Ancient roots, moss arches, berry understory, glowcaps",
    architecture: "Ranger lodge timber, herb sheds, heartwood gate carvings",
  },
  pois: [
    {
      id: "poi-elder-camp",
      name: "Grove Camp",
      kind: "settlement",
      blurb: "Warden Sylvi's safe lodge and waypoint.",
    },
    {
      id: "poi-elder-heart",
      name: "Heartwood Marker",
      kind: "landmark",
      blurb: "Ancient trunk that hums before the dungeon.",
    },
    {
      id: "poi-elder-moss",
      name: "Moss Arch",
      kind: "landmark",
      blurb: "Herb trails and forager routes.",
    },
    {
      id: "poi-elder-arena",
      name: "Heartwood Arena",
      kind: "danger",
      blurb: "Boss approach for Elderwood Heartwood.",
    },
  ],
  npcSpawnIds: [
    "warden-sylvi",
    "mosskeeper-elden",
    "fenn-quickbranch",
    "grandmother-willowmere",
    "elder-forager-nim",
  ],
  resourceNodeIds: ["grove-herb", "ancient-bark", "mossmeal", "glowcap", "berry-bush"],
  enemyIds: ["grove-sprite", "bark-guardian", "vine-sprout"],
  dangerZoneIds: ["tree-dungeon", "heartwood-arena"],
  portal: {
    id: "portal-elder-roots",
    name: "Rootpath Gateway",
    arrivalNote: "Moss underfoot and canopy hush — the spine trail begins here.",
  },
  musicKey: "music-grove",
  ambianceKey: "ambient-elderwood",
};
