import type { RegionContentPack } from "@/content/regions/types";

/** Authored Ember Crater pack — forge economy, ash gather, restoration sinks. */
export const EMBER_CRATER_CONTENT_PACK: RegionContentPack = {
  regionId: "ember-crater",
  regionName: "Ember Crater",
  blurb:
    "Heat-shimmer forges and ash rim paths — bellows jobs, slag gather, and forge restoration burns.",
  questChainKeys: ["chain-ember-crater"],
  quests: [
    { questKey: "quest-ember-intro", name: "Ember Crater: First Survey", creditReward: 40 },
    { questKey: "quest-ember-deep", name: "Ember Crater: Deep Path", creditReward: 70 },
    { questKey: "quest-ember-forge", name: "Light the Rim Forge", creditReward: 55 },
    { questKey: "quest-ember-rim", name: "Scout the Ash Rim", creditReward: 45 },
    { questKey: "daily-ember", name: "Ember Crater Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-ember-slag",
      name: "Gather Rim Slag",
      kind: "gather",
      creditReward: 12,
      cooldownMs: 28_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Cool slag nodules along the crater rim — cooldown-gated.",
    },
    {
      id: "craft-ember-ingot",
      name: "Craft Ash Ingot",
      kind: "craft",
      creditReward: 28,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Station fee before forge completion Credits.",
    },
    {
      id: "explore-ember-vents",
      name: "Survey Heat Vents",
      kind: "explore",
      creditReward: 22,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Exploration grants capped; travel fees apply leaving the crater.",
    },
    {
      id: "combat-ember-spar",
      name: "Ash Yard Spar",
      kind: "combat",
      creditReward: 18,
      cooldownMs: 90_000,
      dailyCapCredits: 54,
      sinkHint: "REPAIR",
      description: "Practice spars — repairs absorb surplus Credits.",
    },
  ],
  sinks: [
    {
      id: "sink-ember-shop",
      reason: "NPC_SHOP_BUY",
      name: "Ember Supply Stall",
      minCost: 20,
      maxCost: 200,
      leavesCirculation: true,
    },
    {
      id: "sink-ember-travel",
      reason: "TRAVEL_FEE",
      name: "Crater Trail Toll",
      minCost: 15,
      maxCost: 80,
      leavesCirculation: true,
    },
    {
      id: "sink-ember-restore",
      reason: "RESTORATION_DONATION",
      name: "Forge Restoration Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-ember-repair",
      reason: "REPAIR",
      name: "Ember Repair Bench",
      minCost: 10,
      maxCost: 250,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-ember-bellows"],
  eventKeys: ["event-ember-public"],
  restorationKey: "restore-ember-forge",
  completeness: "full",
  theme: {
    lighting: "Orange underglow, ash haze, lava bridge shimmer",
    weatherDefault: "heat_shimmer",
    vegetation: "Burned grove stubs, flamecaps, cinder blooms",
    architecture: "Expedition camp, molten forge spire, caldera temple stone",
  },
  pois: [
    {
      id: "poi-ember-camp",
      name: "Crater Entrance Camp",
      kind: "settlement",
      blurb: "Safe ash-rim staging before the bridges.",
    },
    {
      id: "poi-ember-bridge",
      name: "Lava Bridge Network",
      kind: "danger",
      blurb: "Heat-scarred crossings over molten channels.",
    },
    {
      id: "poi-ember-forge",
      name: "Molten Forge",
      kind: "landmark",
      blurb: "Forgekeeper Vessa's bellows and ingot craft.",
    },
    {
      id: "poi-ember-arena",
      name: "Ashmaw Arena",
      kind: "danger",
      blurb: "Boss approach for Ashmaw Colossus.",
    },
  ],
  npcSpawnIds: [
    "kael-ashwalker",
    "forgekeeper-vessa",
    "cinder-sage-malrec",
    "warden-pyra",
    "ember-porter-ash",
  ],
  resourceNodeIds: ["ember-crystal", "charstone", "ashroot", "flamecap", "cinder-bloom"],
  enemyIds: ["cinder-crawler", "magma-beetle", "ash-hound", "ember-wisp"],
  dangerZoneIds: ["lava-bridges", "ashen-caverns", "boss-arena"],
  portal: {
    id: "portal-ember-rim",
    name: "Ash Rim Gateway",
    arrivalNote: "Heat hits first — black stone underfoot and forge smoke on the wind.",
  },
  musicKey: "music-ember",
  ambianceKey: "ambient-ember",
};
