import type { RegionContentPack } from "@/content/regions/types";

/** Authored Frostveil Basin — aurora, ice caves, observatory restoration. */
export const FROSTVEIL_BASIN_CONTENT_PACK: RegionContentPack = {
  regionId: "frostveil-basin",
  regionName: "Frostveil Basin",
  blurb:
    "Frozen lake and aurora shrine — ice blooms, survey jobs, and observatory restoration.",
  questChainKeys: ["chain-frostveil-basin"],
  quests: [
    { questKey: "quest-frost-intro", name: "Frostveil Basin: First Survey", creditReward: 40 },
    { questKey: "quest-frost-watch", name: "Aurora Watch", creditReward: 55 },
    { questKey: "quest-frost-deep", name: "Frostveil Basin: Deep Path", creditReward: 70 },
    { questKey: "daily-frost", name: "Frostveil Basin Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-frost-crystal",
      name: "Gather Frost Crystal",
      kind: "gather",
      creditReward: 12,
      cooldownMs: 30_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Brittle crystals along the frozen lake rim.",
    },
    {
      id: "craft-frost-salve",
      name: "Craft Warming Salve",
      kind: "craft",
      creditReward: 27,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Ice bloom salves after station fee.",
    },
    {
      id: "explore-frost-caves",
      name: "Chart Ice Caves",
      kind: "explore",
      creditReward: 22,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Cave charts capped; travel fees apply.",
    },
    {
      id: "care-frost-bond",
      name: "Lodge Care Session",
      kind: "care",
      creditReward: 5,
      cooldownMs: 4 * 60 * 60 * 1000,
      dailyCapCredits: 15,
      sinkHint: "NPC_SHOP_BUY",
      description: "Warm lodge care bonus — capped.",
    },
  ],
  sinks: [
    {
      id: "sink-frost-shop",
      reason: "NPC_SHOP_BUY",
      name: "Warm Lodge Outfitter",
      minCost: 20,
      maxCost: 180,
      leavesCirculation: true,
    },
    {
      id: "sink-frost-travel",
      reason: "TRAVEL_FEE",
      name: "Basin Trail Toll",
      minCost: 16,
      maxCost: 85,
      leavesCirculation: true,
    },
    {
      id: "sink-frost-restore",
      reason: "RESTORATION_DONATION",
      name: "Observatory Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-frost-repair",
      reason: "REPAIR",
      name: "Icewright Bench",
      minCost: 10,
      maxCost: 230,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-frost-survey"],
  eventKeys: ["event-frost-aurora"],
  restorationKey: "restore-frost-observatory",
  completeness: "full",
  theme: {
    lighting: "Pale aurora ribbons, blue ice glow, lodge hearth contrast",
    weatherDefault: "aurora",
    vegetation: "Ice blooms, snow pines, glacier lichen",
    architecture: "Warm lodge timber, aurora cairns, ice-cave bracing",
  },
  pois: [
    {
      id: "poi-frost-village",
      name: "Frostveil Village",
      kind: "settlement",
      blurb: "Warm lodge and knitters against the cold.",
    },
    {
      id: "poi-frost-aurora",
      name: "Aurora Cairn",
      kind: "landmark",
      blurb: "Watch site for seasonal aurora events.",
    },
    {
      id: "poi-frost-lake",
      name: "Frozen Lake",
      kind: "landmark",
      blurb: "Crystal gather paths across the basin.",
    },
    {
      id: "poi-frost-citadel",
      name: "Frostveil Citadel",
      kind: "danger",
      blurb: "Boss approach for Frostveil Warden.",
    },
  ],
  npcSpawnIds: [
    "freya-snowmark",
    "jori-icebloom",
    "hunter-varek",
    "aurora-linn",
    "frost-porter-yul",
  ],
  resourceNodeIds: ["frost-crystal", "ice-bloom", "snow-pine-resin", "glacier-glass"],
  enemyIds: ["frost-wolf", "ice-mite", "snow-lurker"],
  dangerZoneIds: ["caves", "aurora", "boss"],
  portal: {
    id: "portal-frost-lodge",
    name: "Frost Lodge Gateway",
    arrivalNote: "Breath fogs instantly — aurora light paints the warm lodge roof.",
  },
  musicKey: "music-frost",
  ambianceKey: "ambient-frostveil",
  densityNote: "Seasonal event hooks present; deeper ice-dungeon density backlog.",
};
