import type { RegionContentPack } from "@/content/regions/types";

/** Authored Moonwater Coast pack — pier jobs, tide gather, restoration. */
export const MOONWATER_COAST_CONTENT_PACK: RegionContentPack = {
  regionId: "moonwater-coast",
  regionName: "Moonwater Coast",
  blurb:
    "Tide piers and brine markets — courier jobs, kelp gather, and pier restoration donations.",
  questChainKeys: ["chain-moonwater-coast"],
  quests: [
    { questKey: "quest-moon-intro", name: "Moonwater Coast: First Survey", creditReward: 40 },
    { questKey: "quest-moon-deep", name: "Moonwater Coast: Deep Path", creditReward: 70 },
    { questKey: "quest-moon-piers", name: "Mend the Outer Pier", creditReward: 50 },
    { questKey: "quest-moon-tide", name: "Tide Pool Survey", creditReward: 45 },
    { questKey: "daily-moon", name: "Moonwater Coast Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-moon-kelp",
      name: "Gather Tide Kelp",
      kind: "gather",
      creditReward: 10,
      cooldownMs: 30_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Kelp along the moonlit tide line — daily caps apply.",
    },
    {
      id: "craft-moon-net",
      name: "Craft Brine Net",
      kind: "craft",
      creditReward: 25,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Craft after paying the pier station fee.",
    },
    {
      id: "explore-moon-coves",
      name: "Chart Hidden Coves",
      kind: "explore",
      creditReward: 20,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Cove charts earn a little; travel sinks the rest.",
    },
    {
      id: "social-moon-docks",
      name: "Dockside Greetings",
      kind: "social",
      creditReward: 12,
      cooldownMs: 120_000,
      dailyCapCredits: 36,
      sinkHint: "SERVICE_FEE",
      description: "Talk with coast keepers; services cost Credits.",
    },
  ],
  sinks: [
    {
      id: "sink-moon-shop",
      reason: "NPC_SHOP_BUY",
      name: "Coast Supply Stall",
      minCost: 20,
      maxCost: 180,
      leavesCirculation: true,
    },
    {
      id: "sink-moon-travel",
      reason: "TRAVEL_FEE",
      name: "Pier Ferry Toll",
      minCost: 15,
      maxCost: 70,
      leavesCirculation: true,
    },
    {
      id: "sink-moon-restore",
      reason: "RESTORATION_DONATION",
      name: "Tide Pier Restoration",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-moon-repair",
      reason: "REPAIR",
      name: "Netmender Bench",
      minCost: 10,
      maxCost: 200,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-coast-courier"],
  eventKeys: ["event-moon-tidefair"],
  restorationKey: "restore-tide-piers",
  completeness: "full",
  theme: {
    lighting: "Cool moonlit foam, lighthouse beam, wet-sand reflections",
    weatherDefault: "coastal_fog",
    vegetation: "Tide pools, kelp strands, driftwood piles",
    architecture: "Tide Inn, fish market stilt halls, cliff lighthouse",
  },
  pois: [
    {
      id: "poi-moon-village",
      name: "Coastal Village",
      kind: "settlement",
      blurb: "Inns, nets, and pier couriers.",
    },
    {
      id: "poi-moon-beach",
      name: "Moonlit Beach",
      kind: "landmark",
      blurb: "Tide markers and pearl gather lines.",
    },
    {
      id: "poi-moon-light",
      name: "Beacon Rock Lighthouse",
      kind: "landmark",
      blurb: "Signal puzzles and fog warnings.",
    },
    {
      id: "poi-moon-bay",
      name: "Leviathan Bay",
      kind: "danger",
      blurb: "Boss approach for Moonwater Leviathan.",
    },
  ],
  npcSpawnIds: [
    "luma-tidecrest",
    "finn-coralhand",
    "oracle-selene",
    "marina-drift",
    "coast-netmender-pli",
  ],
  resourceNodeIds: ["moon-pearl", "tide-shell", "seaweed-bundle", "coral-shard", "driftwood"],
  enemyIds: ["tide-crab", "reef-stalker"],
  dangerZoneIds: ["sea-caves", "underwater-ruins", "leviathan-bay"],
  portal: {
    id: "portal-moon-pier",
    name: "Tide Pier Gateway",
    arrivalNote: "Salt fog and gull cries — boards creak under the pier lanterns.",
  },
  musicKey: "music-tide",
  ambianceKey: "ambient-moonwater",
};
