import type { RegionContentPack } from "@/content/regions/types";

/** Authored Radiant Citadel — temples, archives, healing lore. */
export const RADIANT_CITADEL_CONTENT_PACK: RegionContentPack = {
  regionId: "radiant-citadel",
  regionName: "Radiant Citadel",
  blurb:
    "Sun temples and healing gardens — archive jobs, light quests, and archive restoration.",
  questChainKeys: ["chain-radiant-citadel"],
  quests: [
    { questKey: "quest-radiant-intro", name: "Radiant Citadel: First Survey", creditReward: 45 },
    { questKey: "quest-radiant-temple", name: "Temple Light Quests", creditReward: 70 },
    { questKey: "quest-radiant-deep", name: "Radiant Citadel: Deep Path", creditReward: 80 },
    { questKey: "daily-radiant", name: "Radiant Citadel Daily", creditReward: 40 },
  ],
  activities: [
    {
      id: "gather-sunpetal",
      name: "Gather Sunpetal",
      kind: "gather",
      creditReward: 12,
      cooldownMs: 30_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Garden petals under temple light — cooldown-gated.",
    },
    {
      id: "craft-radiant-balm",
      name: "Craft Radiant Balm",
      kind: "craft",
      creditReward: 30,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Healing craft after station fee.",
    },
    {
      id: "explore-radiant-walkways",
      name: "Walk Floating Paths",
      kind: "explore",
      creditReward: 24,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Walkway charts capped; travel fees apply.",
    },
    {
      id: "care-radiant-bond",
      name: "Garden Care Session",
      kind: "care",
      creditReward: 6,
      cooldownMs: 4 * 60 * 60 * 1000,
      dailyCapCredits: 18,
      sinkHint: "NPC_SHOP_BUY",
      description: "Healing gardens care bonus — capped.",
    },
  ],
  sinks: [
    {
      id: "sink-radiant-shop",
      reason: "NPC_SHOP_BUY",
      name: "Citadel Apothecary",
      minCost: 25,
      maxCost: 220,
      leavesCirculation: true,
    },
    {
      id: "sink-radiant-travel",
      reason: "TRAVEL_FEE",
      name: "Gate District Toll",
      minCost: 18,
      maxCost: 95,
      leavesCirculation: true,
    },
    {
      id: "sink-radiant-restore",
      reason: "RESTORATION_DONATION",
      name: "Archive Restoration Fund",
      minCost: 10,
      maxCost: 12_000,
      leavesCirculation: true,
    },
    {
      id: "sink-radiant-repair",
      reason: "REPAIR",
      name: "Sentinel Repair Bench",
      minCost: 12,
      maxCost: 260,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-radiant-archive"],
  eventKeys: ["event-radiant-solstice"],
  restorationKey: "restore-radiant-archives",
  completeness: "full",
  theme: {
    lighting: "Gold-white temple glare, mirror-pool reflections, soft garden glow",
    weatherDefault: "clear",
    vegetation: "Healing gardens, sunpetals, clipped citadel hedges",
    architecture: "Marble temples, floating walkways, hall of records",
  },
  pois: [
    {
      id: "poi-radiant-gate",
      name: "Golden Gate District",
      kind: "settlement",
      blurb: "Arrival plazas and sentinel posts.",
    },
    {
      id: "poi-radiant-sun",
      name: "Sun Dial",
      kind: "landmark",
      blurb: "Temple courtyard timekeeper.",
    },
    {
      id: "poi-radiant-gardens",
      name: "Healing Gardens",
      kind: "settlement",
      blurb: "Care and gather loops under soft light.",
    },
    {
      id: "poi-radiant-court",
      name: "Celestial Court",
      kind: "danger",
      blurb: "Boss approach for Radiant Sentinel.",
    },
  ],
  npcSpawnIds: [
    "chancellor-aurex",
    "scholar-lyra",
    "sentinel-cassian",
    "curator-verin",
    "citadel-scribe-omi",
  ],
  resourceNodeIds: ["radiant-crystal", "sunpetal", "mirror-sand", "halo-resin"],
  enemyIds: ["radiant-construct", "light-mote", "gilded-ward"],
  dangerZoneIds: ["temple", "walkways", "court"],
  portal: {
    id: "portal-radiant-gate",
    name: "Golden Gate Gateway",
    arrivalNote: "Light blooms across marble — the citadel greets you with a sun dial chime.",
  },
  musicKey: "music-radiant",
  ambianceKey: "ambient-radiant",
  densityNote: "Midgame identity pack; full temple dungeon loops still backlog.",
};
