import type { RegionContentPack } from "@/content/regions/types";

/** Authored Spirit Marsh — lanterns, memory shrines, spirit ways. */
export const SPIRIT_MARSH_CONTENT_PACK: RegionContentPack = {
  regionId: "spirit-marsh",
  regionName: "Spirit Marsh",
  blurb:
    "Lantern villages and whispering bogs — shrine jobs, memory gather, and spirit-way restoration.",
  questChainKeys: ["chain-spirit-marsh"],
  quests: [
    { questKey: "quest-spirit-intro", name: "Spirit Marsh: First Survey", creditReward: 45 },
    { questKey: "quest-spirit-lantern", name: "Lantern Path Walk", creditReward: 65 },
    { questKey: "quest-spirit-deep", name: "Spirit Marsh: Deep Path", creditReward: 75 },
    { questKey: "daily-spirit", name: "Spirit Marsh Daily", creditReward: 40 },
  ],
  activities: [
    {
      id: "gather-spirit-bloom",
      name: "Gather Spirit Bloom",
      kind: "gather",
      creditReward: 12,
      cooldownMs: 30_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Soft blooms along mist walkways — cooldown-gated.",
    },
    {
      id: "craft-spirit-oil",
      name: "Craft Lantern Oil",
      kind: "craft",
      creditReward: 28,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Oil craft after station fee.",
    },
    {
      id: "explore-spirit-shrines",
      name: "Tend Memory Shrines",
      kind: "explore",
      creditReward: 22,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "NPC_SHOP_BUY",
      description: "Shrine visits earn a little; oil shops sink Credits.",
    },
    {
      id: "social-spirit-ferry",
      name: "Ferry Greetings",
      kind: "social",
      creditReward: 14,
      cooldownMs: 120_000,
      dailyCapCredits: 42,
      sinkHint: "SERVICE_FEE",
      description: "Talk with ferrymen and mediums.",
    },
  ],
  sinks: [
    {
      id: "sink-spirit-shop",
      reason: "NPC_SHOP_BUY",
      name: "Lantern Oil Stall",
      minCost: 18,
      maxCost: 170,
      leavesCirculation: true,
    },
    {
      id: "sink-spirit-travel",
      reason: "TRAVEL_FEE",
      name: "Mist Ferry Toll",
      minCost: 14,
      maxCost: 80,
      leavesCirculation: true,
    },
    {
      id: "sink-spirit-restore",
      reason: "RESTORATION_DONATION",
      name: "Spirit Ways Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-spirit-repair",
      reason: "REPAIR",
      name: "Wick Repair Bench",
      minCost: 10,
      maxCost: 220,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-spirit-shrine"],
  eventKeys: ["event-spirit-vigil"],
  restorationKey: "restore-spirit-ways",
  completeness: "full",
  theme: {
    lighting: "Lantern gold through blue-green mist, soft bog phosphorescence",
    weatherDefault: "spirit_mist",
    vegetation: "Reeds, spirit blooms, hanging marsh moss",
    architecture: "Stilt lantern halls, shrine posts, sunken settlement roofs",
  },
  pois: [
    {
      id: "poi-spirit-village",
      name: "Lantern Village",
      kind: "settlement",
      blurb: "Safe stilts above the mist.",
    },
    {
      id: "poi-spirit-lantern",
      name: "Memory Lantern",
      kind: "landmark",
      blurb: "Path marker for shrine walks.",
    },
    {
      id: "poi-spirit-bog",
      name: "Whispering Bog",
      kind: "danger",
      blurb: "Marsh spirits and soft ground.",
    },
    {
      id: "poi-spirit-court",
      name: "Drowned Court",
      kind: "danger",
      blurb: "Boss approach for Spirit Lantern King.",
    },
  ],
  npcSpawnIds: [
    "medium-amara",
    "ferryman-grey",
    "lantern-keeper-sio",
    "echo-child-nimi",
    "marsh-porter-reed",
  ],
  resourceNodeIds: ["spirit-bloom", "memory-shard", "reed-wick", "mist-pearl"],
  enemyIds: ["marsh-spirit", "spirit-spark", "bog-wisp"],
  dangerZoneIds: ["bog", "sunken", "temple", "court"],
  portal: {
    id: "portal-spirit-lantern",
    name: "Lantern Path Gateway",
    arrivalNote: "Mist closes behind you — a memory lantern flickers to life.",
  },
  musicKey: "music-spirit",
  ambianceKey: "ambient-spirit",
  densityNote: "Midgame spirit identity; denser sunken dungeon still backlog.",
};
