import type { RegionContentPack } from "@/content/regions/types";

/** Authored Stoneheart Canyon — mining, fossils, bridge restoration. */
export const STONEHEART_CANYON_CONTENT_PACK: RegionContentPack = {
  regionId: "stoneheart-canyon",
  regionName: "Stoneheart Canyon",
  blurb:
    "Quarry paths and fossil shelves — ore digs, bridge jobs, and stone restoration burns.",
  questChainKeys: ["chain-stoneheart-canyon"],
  quests: [
    { questKey: "quest-stone-intro", name: "Stoneheart Canyon: First Survey", creditReward: 40 },
    { questKey: "quest-stone-ledger", name: "Fossil Ledger Run", creditReward: 55 },
    { questKey: "quest-stone-deep", name: "Stoneheart Canyon: Deep Path", creditReward: 70 },
    { questKey: "daily-stone", name: "Stoneheart Canyon Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-fossil",
      name: "Excavate Fossil Shard",
      kind: "gather",
      creditReward: 13,
      cooldownMs: 34_000,
      dailyCapCredits: 100,
      sinkHint: "MARKETPLACE_LISTING_FEE",
      description: "Careful digs on the fossil shelf — cooldown-gated.",
    },
    {
      id: "craft-stone-chisel",
      name: "Craft Canyon Chisel",
      kind: "craft",
      creditReward: 28,
      cooldownMs: 45_000,
      dailyCapCredits: 125,
      sinkHint: "CRAFT_FEE",
      description: "Ore to tools after station fee.",
    },
    {
      id: "explore-stone-ruins",
      name: "Survey Carved Ruins",
      kind: "explore",
      creditReward: 22,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Ruin markers earn a little; travel sinks the rest.",
    },
    {
      id: "combat-stone-spar",
      name: "Quarry Spar",
      kind: "combat",
      creditReward: 18,
      cooldownMs: 90_000,
      dailyCapCredits: 54,
      sinkHint: "REPAIR",
      description: "Rock crawlers — repairs absorb surplus.",
    },
  ],
  sinks: [
    {
      id: "sink-stone-shop",
      reason: "NPC_SHOP_BUY",
      name: "Canyon Supply Stall",
      minCost: 20,
      maxCost: 190,
      leavesCirculation: true,
    },
    {
      id: "sink-stone-travel",
      reason: "TRAVEL_FEE",
      name: "Canyon Trail Toll",
      minCost: 15,
      maxCost: 85,
      leavesCirculation: true,
    },
    {
      id: "sink-stone-restore",
      reason: "RESTORATION_DONATION",
      name: "Stone Bridge Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-stone-repair",
      reason: "REPAIR",
      name: "Mason Repair Bench",
      minCost: 10,
      maxCost: 240,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-stone-bridge"],
  eventKeys: ["event-stone-quarry"],
  restorationKey: "restore-stone-bridges",
  completeness: "full",
  theme: {
    lighting: "Harsh canyon sun, ochre cliff shadows, mine-lamp orange",
    weatherDefault: "clear",
    vegetation: "Dust scrub, fossil lichen, sparse rim pines",
    architecture: "Mining camp timber, carved ruin pillars, rope-and-stone bridges",
  },
  pois: [
    {
      id: "poi-stone-settlement",
      name: "Canyon Settlement",
      kind: "settlement",
      blurb: "Haulers, cooks, and gemwright stalls.",
    },
    {
      id: "poi-stone-fossil",
      name: "Fossil Shelf",
      kind: "landmark",
      blurb: "Excavation ledges with rare shards.",
    },
    {
      id: "poi-stone-quarry",
      name: "Quarry Paths",
      kind: "danger",
      blurb: "Unstable rims and rock crawlers.",
    },
    {
      id: "poi-stone-colosseum",
      name: "Canyon Colosseum",
      kind: "danger",
      blurb: "Boss approach for Stoneheart Behemoth.",
    },
  ],
  npcSpawnIds: [
    "doran-flint",
    "petra-stoneveil",
    "marshal-korr",
    "gemwright-opal",
    "stone-hauler-mog",
  ],
  resourceNodeIds: ["stoneheart-ore", "fossil-shard", "canyon-clay", "amber-vein"],
  enemyIds: ["rock-crawler", "dust-scorpion", "slate-bat"],
  dangerZoneIds: ["quarry", "ruins", "mine", "boss"],
  portal: {
    id: "portal-stone-arch",
    name: "Stone Arch Gateway",
    arrivalNote: "Dust and echo — canyon walls rise like a dry cathedral.",
  },
  musicKey: "music-stone",
  ambianceKey: "ambient-stoneheart",
  densityNote: "Spine step 2 identity pack; denser dungeon loops still backlog.",
};
