import type { RegionContentPack } from "@/content/regions/types";

/** Authored Stormspire Peaks — wind trials, lightning crystals, beacon restoration. */
export const STORMSPIRE_PEAKS_CONTENT_PACK: RegionContentPack = {
  regionId: "stormspire-peaks",
  regionName: "Stormspire Peaks",
  blurb:
    "Cliff paths and lightning spires — wind trials, beacon jobs, and storm restoration burns.",
  questChainKeys: ["chain-stormspire-peaks"],
  quests: [
    { questKey: "quest-storm-intro", name: "Stormspire Peaks: First Survey", creditReward: 40 },
    { questKey: "quest-storm-climb", name: "Crystal Ridge Climb", creditReward: 70 },
    { questKey: "quest-storm-deep", name: "Stormspire Peaks: Deep Path", creditReward: 75 },
    { questKey: "daily-storm", name: "Stormspire Peaks Daily", creditReward: 35 },
  ],
  activities: [
    {
      id: "gather-storm-crystal",
      name: "Gather Lightning Crystal",
      kind: "gather",
      creditReward: 14,
      cooldownMs: 32_000,
      dailyCapCredits: 100,
      sinkHint: "CRAFT_FEE",
      description: "Charge-scarred crystals along cliff ridges — cooldown-gated.",
    },
    {
      id: "craft-storm-charm",
      name: "Craft Wind Charm",
      kind: "craft",
      creditReward: 30,
      cooldownMs: 50_000,
      dailyCapCredits: 120,
      sinkHint: "CRAFT_FEE",
      description: "Station fee before wind-silk charms complete.",
    },
    {
      id: "explore-storm-trials",
      name: "Run Wind Trials",
      kind: "explore",
      creditReward: 24,
      cooldownMs: 60_000,
      dailyCapCredits: 80,
      sinkHint: "TRAVEL_FEE",
      description: "Trial gates grant capped Credits; travel sinks the rest.",
    },
    {
      id: "combat-storm-spar",
      name: "Summit Spar",
      kind: "combat",
      creditReward: 20,
      cooldownMs: 90_000,
      dailyCapCredits: 60,
      sinkHint: "REPAIR",
      description: "Raptors and repairs keep Credits from looping.",
    },
  ],
  sinks: [
    {
      id: "sink-storm-shop",
      reason: "NPC_SHOP_BUY",
      name: "Wind Camp Outfitter",
      minCost: 22,
      maxCost: 210,
      leavesCirculation: true,
    },
    {
      id: "sink-storm-travel",
      reason: "TRAVEL_FEE",
      name: "Peak Trail Toll",
      minCost: 18,
      maxCost: 90,
      leavesCirculation: true,
    },
    {
      id: "sink-storm-restore",
      reason: "RESTORATION_DONATION",
      name: "Storm Beacon Fund",
      minCost: 10,
      maxCost: 10_000,
      leavesCirculation: true,
    },
    {
      id: "sink-storm-repair",
      reason: "REPAIR",
      name: "Climber Repair Bench",
      minCost: 12,
      maxCost: 260,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-storm-beacon"],
  eventKeys: ["event-storm-tempest"],
  restorationKey: "restore-storm-beacons",
  completeness: "full",
  theme: {
    lighting: "Cold blue lightning flashes, thin air glare, cloud-shadow bands",
    weatherDefault: "sparks_rain",
    vegetation: "Wind-bent scrub, sky-moss, silk nests on spires",
    architecture: "Rope bridges, wind camp tents, storm beacon pylons",
  },
  pois: [
    {
      id: "poi-storm-camp",
      name: "Wind Camp",
      kind: "settlement",
      blurb: "Safe base before cliff paths.",
    },
    {
      id: "poi-storm-spire",
      name: "Storm Spire",
      kind: "landmark",
      blurb: "Lightning crystal crown above the ridges.",
    },
    {
      id: "poi-storm-trials",
      name: "Wind Trial Gates",
      kind: "dungeon",
      blurb: "Gated climb puzzles for keepers.",
    },
    {
      id: "poi-storm-summit",
      name: "Stormspire Summit",
      kind: "danger",
      blurb: "Boss approach for Stormspire Titan.",
    },
  ],
  npcSpawnIds: [
    "aeron-cloudstep",
    "engineer-volt",
    "skywarden-ilya",
    "hermit-thane",
    "storm-porter-zee",
  ],
  resourceNodeIds: ["lightning-crystal", "wind-silk", "sky-iron", "cloudcap"],
  enemyIds: ["storm-raptor", "spark-wisp", "gale-mite"],
  dangerZoneIds: ["cliff-paths", "wind-trials", "boss"],
  portal: {
    id: "portal-storm-beacon",
    name: "Beacon Gateway",
    arrivalNote: "Wind snatches your cloak — lightning ticks across the high camp pylons.",
  },
  musicKey: "music-storm",
  ambianceKey: "ambient-stormspire",
  densityNote: "Starter-tier density vs Commons; landmarks and cast are distinct.",
};
