import type { RegionContentPack } from "@/content/regions/types";

/** Authored Void Hollow — portal puzzles, echo materials, seal restoration. */
export const VOID_HOLLOW_CONTENT_PACK: RegionContentPack = {
  regionId: "void-hollow",
  regionName: "Void Hollow",
  blurb:
    "Shattered pathways and portal labyrinths — echo gather, puzzle chains, and void seal restoration.",
  questChainKeys: ["chain-void-hollow"],
  quests: [
    { questKey: "quest-void-intro", name: "Void Hollow: First Survey", creditReward: 50 },
    { questKey: "quest-void-portal", name: "Portal Puzzle Chain", creditReward: 80 },
    { questKey: "quest-void-deep", name: "Void Hollow: Deep Path", creditReward: 90 },
    { questKey: "daily-void", name: "Void Hollow Daily", creditReward: 40 },
  ],
  activities: [
    {
      id: "gather-void-echo",
      name: "Gather Void Echo",
      kind: "gather",
      creditReward: 16,
      cooldownMs: 40_000,
      dailyCapCredits: 90,
      sinkHint: "CRAFT_FEE",
      description: "Rift dust and echo shards on strict cooldowns.",
    },
    {
      id: "craft-void-lens",
      name: "Craft Null Lens",
      kind: "craft",
      creditReward: 34,
      cooldownMs: 55_000,
      dailyCapCredits: 110,
      sinkHint: "CRAFT_FEE",
      description: "Precision craft after station fee.",
    },
    {
      id: "explore-void-labyrinth",
      name: "Map Portal Labyrinth",
      kind: "explore",
      creditReward: 28,
      cooldownMs: 70_000,
      dailyCapCredits: 80,
      sinkHint: "REPAIR",
      description: "Labyrinth charts; repairs absorb surplus.",
    },
    {
      id: "combat-void-spar",
      name: "Echo Spar",
      kind: "combat",
      creditReward: 22,
      cooldownMs: 100_000,
      dailyCapCredits: 66,
      sinkHint: "REPAIR",
      description: "Rift stalkers — elite danger loops.",
    },
  ],
  sinks: [
    {
      id: "sink-void-shop",
      reason: "NPC_SHOP_BUY",
      name: "Rift Lab Supply",
      minCost: 30,
      maxCost: 250,
      leavesCirculation: true,
    },
    {
      id: "sink-void-travel",
      reason: "TRAVEL_FEE",
      name: "Hollow Trail Toll",
      minCost: 20,
      maxCost: 100,
      leavesCirculation: true,
    },
    {
      id: "sink-void-restore",
      reason: "RESTORATION_DONATION",
      name: "Void Seal Fund",
      minCost: 15,
      maxCost: 15_000,
      leavesCirculation: true,
    },
    {
      id: "sink-void-repair",
      reason: "REPAIR",
      name: "Null Repair Bench",
      minCost: 15,
      maxCost: 300,
      leavesCirculation: true,
    },
  ],
  jobBoardIds: ["job-void-seal"],
  eventKeys: ["event-void-eclipse"],
  restorationKey: "restore-void-seals",
  completeness: "full",
  theme: {
    lighting: "Violet rift glow, inverted shadows, null-purple haze",
    weatherDefault: "void_distortion",
    vegetation: "Echo forest silhouettes, wilted void flora",
    architecture: "Rift lab scaffolds, null obelisks, inverted ruin arches",
  },
  pois: [
    {
      id: "poi-void-camp",
      name: "Hollow Entrance Camp",
      kind: "settlement",
      blurb: "Safe staging before shattered paths.",
    },
    {
      id: "poi-void-obelisk",
      name: "Null Obelisk",
      kind: "landmark",
      blurb: "Orientation marker in distorted space.",
    },
    {
      id: "poi-void-labyrinth",
      name: "Portal Labyrinth",
      kind: "dungeon",
      blurb: "Color portal puzzle chain.",
    },
    {
      id: "poi-void-arena",
      name: "Riftborn Arena",
      kind: "danger",
      blurb: "Boss approach for Void Riftborn.",
    },
  ],
  npcSpawnIds: [
    "shadecaller-neris",
    "watcher-omen",
    "veya-dusk",
    "keeper-null",
    "void-porter-dim",
  ],
  resourceNodeIds: ["void-crystal", "rift-dust", "echo-thread", "null-shard"],
  enemyIds: ["rift-stalker", "void-mite", "echo-shade"],
  dangerZoneIds: ["shards", "labyrinth", "core", "boss"],
  portal: {
    id: "portal-void-seal",
    name: "Sealed Hollow Gateway",
    arrivalNote: "Sound thins — violet light bends around the null obelisk.",
  },
  musicKey: "music-void",
  ambianceKey: "ambient-void",
  densityNote: "Late-game identity pack; full labyrinth density still backlog.",
};
