/**
 * Riftwilds kids coloring pages — printable game-sketch line art.
 * Free for personal / kids use; not for resale.
 * Assets: public/assets/coloring/* (install via scripts/assets/install-coloring-sketches.mjs).
 */

export type ColoringSheet = {
  id: string;
  slug: string;
  title: string;
  shortLabel: string;
  description: string;
  /** Public URL for the printable PNG */
  pngSrc: string;
  /** Optional SVG source (also printable) */
  svgSrc: string;
  /** Optional single-page PDF */
  pdfSrc?: string;
  /** Optional colorful UI tile preview (distinct from the line-art printable) */
  thumbSrc?: string;
  tags: string[];
};

export const COLORING_CREDIT =
  "Free download for personal and kids’ use. Please do not resell or use commercially.";

export const COLORING_SHEETS: ColoringSheet[] = [
  {
    id: "spark",
    slug: "spark",
    title: "Spark coloring page",
    shortLabel: "Spark",
    description: "Spark the Glowpup — game-style sketch with backpack, scarf, and glowing-tip tail.",
    pngSrc: "/assets/coloring/spark.png",
    svgSrc: "/assets/coloring/spark.svg",
    pdfSrc: "/assets/coloring/spark.pdf",
    thumbSrc: "/assets/ui/comics/kids-spark.png",
    tags: ["riftling", "spark"],
  },
  {
    id: "riftwild-commons",
    slug: "riftwild-commons",
    title: "Riftwild Commons",
    shortLabel: "Commons",
    description: "Riftwild Commons plaza — timber halls, fountain, and the glowing gateway stone.",
    pngSrc: "/assets/coloring/riftwild-commons.png",
    svgSrc: "/assets/coloring/riftwild-commons.svg",
    pdfSrc: "/assets/coloring/riftwild-commons.pdf",
    thumbSrc: "/assets/ui/comics/kids-commons.png",
    tags: ["landmark", "commons"],
  },
  {
    id: "traveling-circus",
    slug: "traveling-circus",
    title: "Traveling Circus",
    shortLabel: "Circus",
    description: "Traveling Circus night — stage, wagon, banners, and a crowd of Riftlings.",
    pngSrc: "/assets/coloring/traveling-circus.png",
    svgSrc: "/assets/coloring/traveling-circus.svg",
    pdfSrc: "/assets/coloring/traveling-circus.pdf",
    thumbSrc: "/assets/ui/comics/kids-circus.png",
    tags: ["circus", "event"],
  },
  {
    id: "hatchery-egg",
    slug: "hatchery-egg",
    title: "Hatchery Egg",
    shortLabel: "Hatchery",
    description: "A hatchery egg with rift-scale plates in a mossy nest — almost ready to hatch!",
    pngSrc: "/assets/coloring/hatchery-egg.png",
    svgSrc: "/assets/coloring/hatchery-egg.svg",
    pdfSrc: "/assets/coloring/hatchery-egg.pdf",
    thumbSrc: "/assets/ui/comics/kids-hatchery.png",
    tags: ["egg", "hatchery"],
  },
  {
    id: "riftling-friends",
    slug: "riftling-friends",
    title: "Riftling Friends",
    shortLabel: "Friends",
    description: "Three Riftling friends in a meadow — Glowpup, berry-kin, and moss-kin.",
    pngSrc: "/assets/coloring/riftling-friends.png",
    svgSrc: "/assets/coloring/riftling-friends.svg",
    pdfSrc: "/assets/coloring/riftling-friends.pdf",
    tags: ["riftling", "group"],
  },
  {
    id: "elara-venn",
    slug: "elara-venn",
    title: "Elara Venn",
    shortLabel: "Elara",
    description: "Elara Venn, Commons guide — cloak, satchel, and the gateway stone behind her.",
    pngSrc: "/assets/coloring/elara-venn.png",
    svgSrc: "/assets/coloring/elara-venn.svg",
    pdfSrc: "/assets/coloring/elara-venn.pdf",
    tags: ["people", "commons"],
  },
  {
    id: "gateway-stones",
    slug: "gateway-stones",
    title: "Gateway Stones",
    shortLabel: "Gateways",
    description: "An ornate Gateway Stone with floating crystals and mossy steps.",
    pngSrc: "/assets/coloring/gateway-stones.png",
    svgSrc: "/assets/coloring/gateway-stones.svg",
    pdfSrc: "/assets/coloring/gateway-stones.pdf",
    tags: ["landmark", "history"],
  },
  {
    id: "elderwood-path",
    slug: "elderwood-path",
    title: "Elderwood Path",
    shortLabel: "Elderwood",
    description: "Elderwood path — ancient trees, lanterns, and a little bridge over a stream.",
    pngSrc: "/assets/coloring/elderwood-path.png",
    svgSrc: "/assets/coloring/elderwood-path.svg",
    pdfSrc: "/assets/coloring/elderwood-path.pdf",
    tags: ["region", "nature"],
  },
  {
    id: "keeper-guide",
    slug: "keeper-guide",
    title: "Keeper & Companion",
    shortLabel: "Keeper",
    description: "A Keeper explorer and Glowpup companion on the Commons path — travel leathers and crystal gateway beyond.",
    pngSrc: "/assets/coloring/keeper-guide.png",
    svgSrc: "/assets/coloring/keeper-guide.svg",
    pdfSrc: "/assets/coloring/keeper-guide.pdf",
    tags: ["people", "riftling"],
  },
  {
    id: "commons-arena",
    slug: "commons-arena",
    title: "Commons Arena",
    shortLabel: "Arena",
    description: "Friendly Commons sparring match — practice staves, banners, and cheering Riftling fans.",
    pngSrc: "/assets/coloring/commons-arena.png",
    svgSrc: "/assets/coloring/commons-arena.svg",
    pdfSrc: "/assets/coloring/commons-arena.pdf",
    tags: ["commons", "battle"],
  },
  {
    id: "player-academy",
    slug: "player-academy",
    title: "Player Academy",
    shortLabel: "Academy",
    description: "Timber academy courtyard — scrolls, fountain steps, and a Riftling perched on a book stack.",
    pngSrc: "/assets/coloring/player-academy.png",
    svgSrc: "/assets/coloring/player-academy.svg",
    pdfSrc: "/assets/coloring/player-academy.pdf",
    tags: ["landmark", "commons"],
  },
  {
    id: "moonwater-harbor",
    slug: "moonwater-harbor",
    title: "Moonwater Harbor",
    shortLabel: "Harbor",
    description: "Moonwater docks — boats, lighthouse, tide crystals, and a Keeper on the pier.",
    pngSrc: "/assets/coloring/moonwater-harbor.png",
    svgSrc: "/assets/coloring/moonwater-harbor.svg",
    pdfSrc: "/assets/coloring/moonwater-harbor.pdf",
    tags: ["region", "harbor"],
  },
  {
    id: "hatchery-care",
    slug: "hatchery-care",
    title: "Hatchery Care",
    shortLabel: "Nursery",
    description: "Hatchery nursery — nest pedestals, rift-scale eggs, and a caretaker with a brand-new hatchling.",
    pngSrc: "/assets/coloring/hatchery-care.png",
    svgSrc: "/assets/coloring/hatchery-care.svg",
    pdfSrc: "/assets/coloring/hatchery-care.pdf",
    tags: ["hatchery", "egg"],
  },
  {
    id: "ember-forge",
    slug: "ember-forge",
    title: "Ember Forge",
    shortLabel: "Forge",
    description: "Ember craft forge — anvil, amber crystals, and a smith with an Emberkit helper.",
    pngSrc: "/assets/coloring/ember-forge.png",
    svgSrc: "/assets/coloring/ember-forge.svg",
    pdfSrc: "/assets/coloring/ember-forge.pdf",
    tags: ["region", "ember"],
  },
  {
    id: "riftling-species",
    slug: "riftling-species",
    title: "Riftling Species",
    shortLabel: "Species",
    description: "Five Riftling friends in a meadow lineup — Glowpup, berry-kin, moss-kin, tide-kin, and Emberkit.",
    pngSrc: "/assets/coloring/riftling-species.png",
    svgSrc: "/assets/coloring/riftling-species.svg",
    pdfSrc: "/assets/coloring/riftling-species.pdf",
    tags: ["riftling", "group"],
  },
  {
    id: "glowpup-den",
    slug: "glowpup-den",
    title: "Glowpup Den",
    shortLabel: "Den",
    description: "A cozy Glowpup family den under mossy roots — lanterns, mushrooms, and fluffy tails.",
    pngSrc: "/assets/coloring/glowpup-den.png",
    svgSrc: "/assets/coloring/glowpup-den.svg",
    pdfSrc: "/assets/coloring/glowpup-den.pdf",
    tags: ["riftling", "spark"],
  },
  {
    id: "emberkit-scout",
    slug: "emberkit-scout",
    title: "Emberkit Scout",
    shortLabel: "Emberkit",
    description: "Emberkit scout on a basalt ridge — amber horn crystals and a satchel of star-sparks.",
    pngSrc: "/assets/coloring/emberkit-scout.png",
    svgSrc: "/assets/coloring/emberkit-scout.svg",
    pdfSrc: "/assets/coloring/emberkit-scout.pdf",
    tags: ["riftling", "ember"],
  },
  {
    id: "pouchling-market",
    slug: "pouchling-market",
    title: "Pouchling Market",
    shortLabel: "Pouchling",
    description: "A round Pouchling shopping the Commons stalls — fruit, ribbons, and a friendly vendor.",
    pngSrc: "/assets/coloring/pouchling-market.png",
    svgSrc: "/assets/coloring/pouchling-market.svg",
    pdfSrc: "/assets/coloring/pouchling-market.pdf",
    tags: ["riftling", "commons"],
  },
  {
    id: "stone-guardian",
    slug: "stone-guardian",
    title: "Stone Guardian",
    shortLabel: "Guardian",
    description: "Kid-safe boss silhouette — a majestic stone guardian at the Gateway ruins (friendly, not scary).",
    pngSrc: "/assets/coloring/stone-guardian.png",
    svgSrc: "/assets/coloring/stone-guardian.svg",
    pdfSrc: "/assets/coloring/stone-guardian.pdf",
    tags: ["boss", "landmark"],
  },
  {
    id: "rift-serpent",
    slug: "rift-serpent",
    title: "Rift Serpent",
    shortLabel: "Serpent",
    description: "Kid-safe boss silhouette — crystal rift serpent coiled around ancient pillars.",
    pngSrc: "/assets/coloring/rift-serpent.png",
    svgSrc: "/assets/coloring/rift-serpent.svg",
    pdfSrc: "/assets/coloring/rift-serpent.pdf",
    tags: ["boss", "riftling"],
  },
  {
    id: "circus-acrobat",
    slug: "circus-acrobat",
    title: "Circus Acrobat",
    shortLabel: "Acrobat",
    description: "Traveling Circus acrobat leap — stage, star banners, and a cheering crowd.",
    pngSrc: "/assets/coloring/circus-acrobat.png",
    svgSrc: "/assets/coloring/circus-acrobat.svg",
    pdfSrc: "/assets/coloring/circus-acrobat.pdf",
    tags: ["circus", "event"],
  },
  {
    id: "gateway-awaken",
    slug: "gateway-awaken",
    title: "Gateway Awakening",
    shortLabel: "Awaken",
    description: "Gateway Stone lighting up — floating crystals, mossy steps, and Keepers in awe.",
    pngSrc: "/assets/coloring/gateway-awaken.png",
    svgSrc: "/assets/coloring/gateway-awaken.svg",
    pdfSrc: "/assets/coloring/gateway-awaken.pdf",
    tags: ["landmark", "history"],
  },
  {
    id: "elderwood-camp",
    slug: "elderwood-camp",
    title: "Elderwood Camp",
    shortLabel: "Camp",
    description: "Forest camp under Elderwood trees — tent, campfire, lanterns, and a sleepy Glowpup.",
    pngSrc: "/assets/coloring/elderwood-camp.png",
    svgSrc: "/assets/coloring/elderwood-camp.svg",
    pdfSrc: "/assets/coloring/elderwood-camp.pdf",
    tags: ["region", "nature"],
  },
  {
    id: "market-day",
    slug: "market-day",
    title: "Market Day",
    shortLabel: "Market",
    description: "Busy Commons market — timber stalls, lanterns, barrels, and shoppers with Riftlings.",
    pngSrc: "/assets/coloring/market-day.png",
    svgSrc: "/assets/coloring/market-day.svg",
    pdfSrc: "/assets/coloring/market-day.pdf",
    tags: ["commons", "landmark"],
  },
  {
    id: "homestead-garden",
    slug: "homestead-garden",
    title: "Homestead Garden",
    shortLabel: "Garden",
    description: "Cozy homestead garden — cottage, well, flower beds, and a Riftling with a watering can.",
    pngSrc: "/assets/coloring/homestead-garden.png",
    svgSrc: "/assets/coloring/homestead-garden.svg",
    pdfSrc: "/assets/coloring/homestead-garden.pdf",
    tags: ["housing", "nature"],
  },
  {
    id: "riftstone-plaza",
    slug: "riftstone-plaza",
    title: "Riftstone Plaza",
    shortLabel: "Riftstone",
    description: "Central Riftstone medallion — carved runes, crystal core, and a gathering of Keepers.",
    pngSrc: "/assets/coloring/riftstone-plaza.png",
    svgSrc: "/assets/coloring/riftstone-plaza.svg",
    pdfSrc: "/assets/coloring/riftstone-plaza.pdf",
    tags: ["landmark", "commons"],
  },
  {
    id: "first-bond",
    slug: "first-bond",
    title: "First Bond",
    shortLabel: "Bond",
    description: "First hatchling bond — a Keeper cradling a newly hatched Riftling in a moss nest.",
    pngSrc: "/assets/coloring/first-bond.png",
    svgSrc: "/assets/coloring/first-bond.svg",
    pdfSrc: "/assets/coloring/first-bond.pdf",
    tags: ["hatchery", "people"],
  },
  {
    id: "lantern-night",
    slug: "lantern-night",
    title: "Lantern Night",
    shortLabel: "Lanterns",
    description: "Evening lantern walk through Commons streets — hanging lamps, timber shops, and Spark.",
    pngSrc: "/assets/coloring/lantern-night.png",
    svgSrc: "/assets/coloring/lantern-night.svg",
    pdfSrc: "/assets/coloring/lantern-night.pdf",
    tags: ["commons", "night"],
  },
];

export function listColoringSheets(): ColoringSheet[] {
  return COLORING_SHEETS;
}

/** Featured Kids Corner tiles (Spark, Commons, Circus, Hatchery). */
export function listFeaturedColoringSheets(limit = 4): ColoringSheet[] {
  return COLORING_SHEETS.slice(0, limit);
}

export function getColoringSheet(slug: string): ColoringSheet | undefined {
  return COLORING_SHEETS.find((s) => s.slug === slug);
}
