/* AUTO-GENERATED by scripts/comics/emit-issue-006-catalog.mts — do not edit by hand */
import type { ComicIssue, ComicPage, ComicPanelLayout, ComicPageRole } from "@/content/comics/types";
import { expandCoverVariants } from "@/content/comics/publishing-engine";

export const ISSUE_006_TRANSCRIPTS: Record<number, string[]> = {
  "1": [
    "CAPTION: LEGENDS OF THE RIFT",
    "CAPTION: THE MERCHANT'S SECRET",
    "CAPTION: ISSUE #6"
  ],
  "2": [
    "NARRATION: Previously: Tempestria released its wall. Seris stole every door. The market answered.",
    "CAPTION: CONTINUE THE FRACTURE DAWN"
  ],
  "3": [
    "CAPTION: THE MERCHANT'S SECRET",
    "NARRATION: Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden.",
    "CAPTION: ORIGINAL RIFTWILDS IP"
  ],
  "4": [
    "CAPTION: CHAPTER SIX",
    "CAPTION: THE MERCHANT'S SECRET",
    "NARRATION: Every door has a price. Some prices wear familiar faces."
  ],
  "5": [
    "NARRATION: Some markets move. This one moves through doors.",
    "CAPTION: GILDED CROSSROADS",
    "SFX: portal-HUMMMM"
  ],
  "6": [
    "SPEECH (Cael Vesper): No weapons drawn. No unregistered spells. No touching sealed merchandise.",
    "SPEECH (Mira Eggwarden): And companions?",
    "NARRATION: Living cores are not SKUs — on paper.",
    "WHISPER (Mira Eggwarden): Paper and cages disagree.",
    "SPEECH (Cael Vesper): I know the customs. Trust the route.",
    "THOUGHT (Mira Eggwarden): Routes are how doors get sold."
  ],
  "7": [
    "CREATURE (Spirit Moth): *pattern-blink*",
    "SPEECH (Cael Vesper): Follow the moth. It reads merchant codes.",
    "CREATURE (Bramblefox): *scent-alert*",
    "SPEECH (Mira Eggwarden): Meridian. Already inside.",
    "SFX: crate-scrape"
  ],
  "8": [
    "NARRATION: Legal trade glittered like a promise.",
    "WHISPER (Shopper): Credits for cosmetics — not souls.",
    "NARRATION: Predators wore the same gold.",
    "SFX: muted-chirp",
    "CREATURE (Spark): *distress-chirp*",
    "SPEECH (Mira Eggwarden): Not here. Not yet."
  ],
  "9": [
    "SPEECH (Shelter Keeper): We return freedom. That is the charter.",
    "CREATURE (Mossprig): *gentle-bulwark*",
    "SPEECH (Mira Eggwarden): This is what trade should look like.",
    "NARRATION: Rescue is not ownership.",
    "SFX: distant-CRY",
    "CREATURE (Echoquill): *archive-lock*",
    "SPEECH (Nira Quill): That wasn't a potion spill."
  ],
  "10": [
    "SPEECH (Aurelia Voss): You brought me a map.",
    "SPEECH (Seris Vale): No. I brought you every door.",
    "SPEECH (Aurelia Voss): Resonance is less cooperative when it chooses its Keeper.",
    "CREATURE (Lockjaw Wisp): *appraise-hum*",
    "WHISPER (Aurelia Voss): Lanternmaster. You still owe a door.",
    "SPEECH (Cael Vesper): …I pay my debts when I understand the price."
  ],
  "11": [
    "SPEECH (Aurelia Voss): I will give you the buyer's location. Not the buyer.",
    "SPEECH (Mira Eggwarden): And your price?",
    "SPEECH (Aurelia Voss): One favor. Unspecified. Compact-word.",
    "WHISPER (Nira Quill): Unspecified favors built this market."
  ],
  "12": [
    "SPEECH (Mira Eggwarden): You sell routes. Meridian sells cages. Where do you stand?",
    "SPEECH (Aurelia Voss): I preserve what profit would erase. Sometimes preservation looks like profit.",
    "SPEECH (Mira Eggwarden): Living cores are not SKUs. Not Spark. Not any egg.",
    "SFX: auction-DRUM"
  ],
  "13": [
    "CREATURE (Thornling): *lock-buzz*",
    "SFX: hidden-CLICK",
    "NARRATION: Rescue charters don't use pens.",
    "CREATURE (Cindermink): *defiant-hiss*",
    "SPEECH (Mira Eggwarden): This is trafficking. Not trade.",
    "SPEECH (Nira Quill): Meridian buyers. I know the marks."
  ],
  "14": [
    "CREATURE (Mossprig): *sense-captives*",
    "SPEECH (Mira Eggwarden): How many?",
    "CREATURE (Wisplet): *phase-reveal*",
    "NARRATION: Walls lied. The market lied with them.",
    "SFX: phase-HUM"
  ],
  "15": [
    "CREATURE (Echoquill): *record-trill*",
    "SPEECH (Nira Quill): That's… my recruitment age.",
    "NARRATION: They recruit children the way markets recruit hunger.",
    "WHISPER (Nira Quill): I wasn't saved. I was sorted.",
    "SPEECH (Mira Eggwarden): You cut their leash at Tempestria. That matters.",
    "SFX: auction-GONG"
  ],
  "16": [
    "CAPTION: LOT ONE — DORMANT RIFBORN EGG",
    "SPEECH (Auctioneer): Unhatched. Unbonded. Unregistered.",
    "CREATURE (Spark): *violent-flare!*",
    "SHOUT (Mira Eggwarden): Spark—!"
  ],
  "17": [
    "CREATURE (Lockjaw Wisp): *keyshift*",
    "SPEECH (Aurelia Voss): Meridian thinks this auction is theirs. It is mine.",
    "NARRATION: Every door had a architect. The name was sealed.",
    "SFX: vault-CHAIN"
  ],
  "18": [
    "SPEECH (Seris Vale): Lot one opens the Resonance line. Bid accordingly.",
    "SPEECH (Mira Eggwarden): The egg is bait.",
    "CREATURE (Wisplet): *barrier-flare*",
    "SPEECH (Nira Quill): Handlers. Not collectors.",
    "SHOUT (Seris Vale): Seize Subject One if it shows."
  ],
  "19": [
    "SPEECH (Seris Vale): Your network, Merchant. My keys.",
    "SFX: ledger-FLIP",
    "SPEECH (Aurelia Voss): Those doors are mine to close.",
    "SPEECH (Seris Vale): Not anymore.",
    "NARRATION: When a network outgrows its merchant, the market breaks.",
    "SFX: engine-WHINE"
  ],
  "20": [
    "SPEECH (Seris Vale): Doors are currency. This egg is a door.",
    "CAPTION: PRIVATE CIRCLE — MERIDIAN ONLY",
    "SFX: restraint-HUM"
  ],
  "21": [
    "SPEECH (Auctioneer): Bid for the unhatched door!",
    "CREATURE (Cindermink): *chain-rattle*",
    "SFX: captive-CRY",
    "SPEECH (Mira Eggwarden): They bid on one cage while others scream.",
    "SPEECH (Nira Quill): Then we break both.",
    "SFX: sigil-SNAP"
  ],
  "22": [
    "SFX: RESONANCE!",
    "SHOUT (Seris Vale): Subject One — seize!",
    "CREATURE (Spark): *protective-roar!*",
    "SPEECH (Mira Eggwarden): He chooses. You don't."
  ],
  "23": [
    "SFX: AUCTION-BREAK",
    "CREATURE (Bramblefox): *device-snap*",
    "CREATURE (Mossprig): *bulwark!*",
    "SHOUT (Mira Eggwarden): Companions first — always!"
  ],
  "24": [
    "SPEECH (Seris Vale): Every door Tempestria sealed — now mine.",
    "SFX: door-MAP",
    "SPEECH (Nira Quill): Not all of them.",
    "SFX: route-BURN",
    "SPEECH (Aurelia Voss): She closed a door I wanted shut slower.",
    "SPEECH (Mira Eggwarden): Close the cages next."
  ],
  "25": [
    "SFX: BREAK THE CHAIN",
    "CREATURE (Cindermink): *ember-cut!*",
    "CREATURE (Lockjaw Wisp): *closed-contract*",
    "SPEECH (Aurelia Voss): Vault sealed. Debts collected.",
    "SPEECH (Mira Eggwarden): Freedom is not a receipt.",
    "CREATURE (Spark): *guard-hum*"
  ],
  "26": [
    "NARRATION: When the engine breaks schedule, the market breaks geography.",
    "SFX: SHIFT-ROOOAR",
    "SHOUT (Seris Vale): You moved my exit!"
  ],
  "27": [
    "SFX: STABILIZE",
    "SPEECH (Mira Eggwarden): Invite — don't own!",
    "SPEECH (Aurelia Voss): Meridian routes — closed.",
    "CREATURE (Spark): *steady-hum*"
  ],
  "28": [
    "CAPTION: THE RIFTRIGHT",
    "NARRATION: The architect of the First Rift did not act alone.",
    "SPEECH (Mira Eggwarden): Who were they?",
    "SPEECH (Aurelia Voss): A title first. A name when you've paid more doors.",
    "SPEECH (Mira Eggwarden): This egg is not property. Neither is Cindermink.",
    "CREATURE (Cindermink): *grateful-chuff*"
  ],
  "29": [
    "WHISPER (Merchant Signal): The Keeper has the egg. Proceed to the next gate.",
    "THOUGHT (Cael Vesper): …the price.",
    "CAPTION: NEXT: THE TRAITOR'S GATE",
    "SFX: token-PULSE"
  ],
  "30": [
    "CAPTION: NEXT ISSUE",
    "NARRATION: The Keeper has the egg. Someone opened the next gate from within.",
    "CAPTION: THE TRAITOR'S GATE"
  ],
  "31": [
    "CAPTION: AURELIA VOSS",
    "NARRATION: The Gilded Merchant. Preserves routes others would burn. Morally ambiguous uneasy ally."
  ],
  "32": [
    "CAPTION: LOCKJAW WISP",
    "NARRATION: Merchant companion — Appraiser's Eye · Keyshift · Closed Contract — Control / Utility / Information."
  ],
  "33": [
    "CAPTION: CODEX — GILDED CROSSROADS",
    "NARRATION: Moving bazaar along old Rift routes. Legal trade floor. Portal engine relocates the entire market. Companion trafficking forbidden — but pens exist."
  ],
  "34": [
    "CAPTION: ABILITY — BREAK THE CHAIN",
    "NARRATION: Remove restraints from allied companions and deal Fire damage to controlling devices. Condemn trafficking; rescue is not ownership."
  ],
  "35": [
    "CAPTION: ROUTE OF EVERY DOOR",
    "NARRATION: Tempestria → Gilded Crossroads → Traitor's Gate (teaser)"
  ],
  "36": [
    "CAPTION: EDITOR'S NOTE",
    "NARRATION: Issue #6 distinguishes legal trade from companion trafficking. Living cores are not SKUs. The cliffhanger asks who sells trust from inside the circle."
  ],
  "37": [
    "CAPTION: GILDED CROSSROADS MERCHANT PASS",
    "NARRATION: Central exchange — weapons sheathed. Companion pens — FORBIDDEN. Portal engine — CIRCLE ONLY.",
    "WHISPER: Living cores are not SKUs."
  ],
  "38": [
    "CAPTION: THE MERCHANT'S SECRET",
    "NARRATION: Every door opened. One ally closed the wrong one.",
    "CAPTION: ISSUE #6 · LEGENDS OF THE RIFT"
  ]
};

export const ISSUE_006_COMIC: ComicIssue = {
  slug: "the-merchants-secret",
  issueNumber: 6,
  title: "The Merchant's Secret",
  subtitle: "Chapter Six — Every Door Has a Price",
  synopsis: "Mira Eggwarden, Spark, and the expedition enter the Gilded Crossroads — a moving bazaar powered by old Rift routes. Aurelia Voss formalizes as the Gilded Merchant; Seris Vale weaponizes the stolen royal trade ledger at a trap auction for a dormant Riftborn egg. The team condemns companion trafficking, frees captives with Cindermink's Break the Chain, and saves the egg — but Cael Vesper's hidden merchant debt surfaces in a cliffhanger: The Traitor's Gate.",
  publishedAt: "2026-07-20",
  status: "published",
  tags: ["merchants-secret", "gilded-crossroads", "aurelia-voss", "riftborn", "issue-006", "veiled-meridian", "mira-eggwarden"],
  covers: expandCoverVariants("The Merchant's Secret", "/assets/comics/covers/06-merchants-secret.png"),
  pages: [
  {
    id: "the-merchants-secret-issue-006-p001",
    pageNumber: 1,
    layout: "splash" as ComicPanelLayout,
    role: "front-cover" as ComicPageRole,
    title: "The Merchant's Secret — Cover",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-001.webp",
    artAlt: "The Merchant's Secret — Cover",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p001-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-001.webp",
      
      bubbles: [{ kind: "caption", text: "LEGENDS OF THE RIFT", x: 50, y: 10 }, { kind: "caption", text: "THE MERCHANT'S SECRET", x: 50, y: 82 }, { kind: "caption", text: "ISSUE #6", x: 50, y: 92 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p002",
    pageNumber: 2,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Front Cover",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-002.webp",
    artAlt: "Inside Front Cover",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p002-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-002.webp",
      
      bubbles: [{ kind: "narration", text: "Previously: Tempestria released its wall. Seris stole every door. The market answered.", x: 50, y: 40 }, { kind: "caption", text: "CONTINUE THE FRACTURE DAWN", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p003",
    pageNumber: 3,
    layout: "splash" as ComicPanelLayout,
    role: "credits" as ComicPageRole,
    title: "Credits",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-003.webp",
    artAlt: "Credits",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p003-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-003.webp",
      
      bubbles: [{ kind: "caption", text: "THE MERCHANT'S SECRET", x: 50, y: 14 }, { kind: "narration", text: "Story · Continuity · Lettering · Art Direction — Riftwilds Studio Pipeline. Keeper: Mira Eggwarden.", x: 50, y: 55 }, { kind: "caption", text: "ORIGINAL RIFTWILDS IP", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p004",
    pageNumber: 4,
    layout: "splash" as ComicPanelLayout,
    role: "title" as ComicPageRole,
    title: "Chapter Six — The Merchant's Secret",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-004.webp",
    artAlt: "Chapter Six — The Merchant's Secret",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p004-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-004.webp",
      
      bubbles: [{ kind: "caption", text: "CHAPTER SIX", x: 50, y: 20 }, { kind: "caption", text: "THE MERCHANT'S SECRET", x: 50, y: 35 }, { kind: "narration", text: "Every door has a price. Some prices wear familiar faces.", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p005",
    pageNumber: 5,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Crossroads Spark",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-005.webp",
    artAlt: "Crossroads Spark — The Merchant's Secret page 1",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p005-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-005.webp",
      
      bubbles: [{ kind: "narration", text: "Some markets move. This one moves through doors.", x: 50, y: 10 }, { kind: "caption", text: "GILDED CROSSROADS", x: 50, y: 88 }, { kind: "sfx", text: "portal-HUMMMM", x: 72, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p006",
    pageNumber: 6,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Market Rules",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-006.webp",
    artAlt: "Market Rules — The Merchant's Secret page 2",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p006-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "No weapons drawn. No unregistered spells. No touching sealed merchandise.", speaker: "Cael Vesper", x: 50, y: 28, tail: "down" }, { kind: "speech", text: "And companions?", speaker: "Mira Eggwarden", x: 35, y: 70, tail: "right" }],
    },
    {
      id: "the-merchants-secret-issue-006-p006-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-006.webp",
      
      bubbles: [{ kind: "narration", text: "Living cores are not SKUs — on paper.", x: 50, y: 25 }, { kind: "whisper", text: "Paper and cages disagree.", speaker: "Mira Eggwarden", x: 55, y: 72 }],
    },
    {
      id: "the-merchants-secret-issue-006-p006-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-006.webp",
      
      bubbles: [{ kind: "speech", text: "I know the customs. Trust the route.", speaker: "Cael Vesper", x: 40, y: 30, tail: "down" }, { kind: "thought", text: "Routes are how doors get sold.", speaker: "Mira Eggwarden", x: 60, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p007",
    pageNumber: 7,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Lantern Entry",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-007.webp",
    artAlt: "Lantern Entry — The Merchant's Secret page 3",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p007-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-007.webp",
      
      bubbles: [{ kind: "creature", text: "*pattern-blink*", speaker: "Spirit Moth", x: 40, y: 25, tail: "down" }, { kind: "speech", text: "Follow the moth. It reads merchant codes.", speaker: "Cael Vesper", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p007-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-007.webp",
      
      bubbles: [{ kind: "creature", text: "*scent-alert*", speaker: "Bramblefox", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "Meridian. Already inside.", speaker: "Mira Eggwarden", x: 55, y: 72, tail: "up" }, { kind: "sfx", text: "crate-scrape", x: 70, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p008",
    pageNumber: 8,
    layout: "montage" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Wonder and Danger",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-008.webp",
    artAlt: "Wonder and Danger — The Merchant's Secret page 4",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p008-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "Legal trade glittered like a promise.", x: 50, y: 15 }, { kind: "whisper", text: "Credits for cosmetics — not souls.", speaker: "Shopper", x: 30, y: 55, tail: "right" }],
    },
    {
      id: "the-merchants-secret-issue-006-p008-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-008.webp",
      
      bubbles: [{ kind: "narration", text: "Predators wore the same gold.", x: 50, y: 20 }, { kind: "sfx", text: "muted-chirp", x: 65, y: 60 }],
    },
    {
      id: "the-merchants-secret-issue-006-p008-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-008.webp",
      
      bubbles: [{ kind: "creature", text: "*distress-chirp*", speaker: "Spark", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "Not here. Not yet.", speaker: "Mira Eggwarden", x: 60, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p009",
    pageNumber: 9,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Shelter and Cry",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-009.webp",
    artAlt: "Shelter and Cry — The Merchant's Secret page 5",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p009-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "We return freedom. That is the charter.", speaker: "Shelter Keeper", x: 50, y: 28, tail: "down" }, { kind: "creature", text: "*gentle-bulwark*", speaker: "Mossprig", x: 40, y: 65, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p009-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-009.webp",
      
      bubbles: [{ kind: "speech", text: "This is what trade should look like.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "narration", text: "Rescue is not ownership.", x: 50, y: 75 }],
    },
    {
      id: "the-merchants-secret-issue-006-p009-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-009.webp",
      
      bubbles: [{ kind: "sfx", text: "distant-CRY", x: 70, y: 30 }, { kind: "creature", text: "*archive-lock*", speaker: "Echoquill", x: 35, y: 55, tail: "right" }, { kind: "speech", text: "That wasn't a potion spill.", speaker: "Nira Quill", x: 55, y: 78, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p010",
    pageNumber: 10,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Resonance Less Cooperative",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-010.webp",
    artAlt: "Resonance Less Cooperative — The Merchant's Secret page 6",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p010-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "You brought me a map.", speaker: "Aurelia Voss", x: 35, y: 28, tail: "down" }, { kind: "speech", text: "No. I brought you every door.", speaker: "Seris Vale", x: 65, y: 45, tail: "left" }],
    },
    {
      id: "the-merchants-secret-issue-006-p010-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-010.webp",
      
      bubbles: [{ kind: "speech", text: "Resonance is less cooperative when it chooses its Keeper.", speaker: "Aurelia Voss", x: 50, y: 30, tail: "down" }, { kind: "creature", text: "*appraise-hum*", speaker: "Lockjaw Wisp", x: 65, y: 60, tail: "left" }],
    },
    {
      id: "the-merchants-secret-issue-006-p010-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-010.webp",
      
      bubbles: [{ kind: "whisper", text: "Lanternmaster. You still owe a door.", speaker: "Aurelia Voss", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "…I pay my debts when I understand the price.", speaker: "Cael Vesper", x: 60, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p011",
    pageNumber: 11,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Key for a Buyer",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-011.webp",
    artAlt: "Key for a Buyer — The Merchant's Secret page 7",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p011-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-011.webp",
      
      bubbles: [{ kind: "speech", text: "I will give you the buyer's location. Not the buyer.", speaker: "Aurelia Voss", x: 50, y: 28, tail: "down" }, { kind: "speech", text: "And your price?", speaker: "Mira Eggwarden", x: 35, y: 65, tail: "right" }],
    },
    {
      id: "the-merchants-secret-issue-006-p011-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-011.webp",
      
      bubbles: [{ kind: "speech", text: "One favor. Unspecified. Compact-word.", speaker: "Aurelia Voss", x: 55, y: 35, tail: "down" }, { kind: "whisper", text: "Unspecified favors built this market.", speaker: "Nira Quill", x: 50, y: 75 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p012",
    pageNumber: 12,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Profit vs Preservation",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-012.webp",
    artAlt: "Profit vs Preservation — The Merchant's Secret page 8",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p012-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "You sell routes. Meridian sells cages. Where do you stand?", speaker: "Mira Eggwarden", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p012-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "I preserve what profit would erase. Sometimes preservation looks like profit.", speaker: "Aurelia Voss", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p012-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-012.webp",
      
      bubbles: [{ kind: "speech", text: "Living cores are not SKUs. Not Spark. Not any egg.", speaker: "Mira Eggwarden", x: 45, y: 30, tail: "down" }, { kind: "sfx", text: "auction-DRUM", x: 70, y: 65 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p013",
    pageNumber: 13,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Illegal Cages",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-013.webp",
    artAlt: "Illegal Cages — The Merchant's Secret page 9",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p013-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-013.webp",
      
      bubbles: [{ kind: "creature", text: "*lock-buzz*", speaker: "Thornling", x: 40, y: 28, tail: "down" }, { kind: "sfx", text: "hidden-CLICK", x: 65, y: 55 }],
    },
    {
      id: "the-merchants-secret-issue-006-p013-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-013.webp",
      
      bubbles: [{ kind: "narration", text: "Rescue charters don't use pens.", x: 50, y: 12 }, { kind: "creature", text: "*defiant-hiss*", speaker: "Cindermink", x: 55, y: 60, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p013-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-013.webp",
      
      bubbles: [{ kind: "speech", text: "This is trafficking. Not trade.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "speech", text: "Meridian buyers. I know the marks.", speaker: "Nira Quill", x: 60, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p014",
    pageNumber: 14,
    layout: "two-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "False Walls",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-014.webp",
    artAlt: "False Walls — The Merchant's Secret page 10",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p014-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-014.webp",
      
      bubbles: [{ kind: "creature", text: "*sense-captives*", speaker: "Mossprig", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "How many?", speaker: "Mira Eggwarden", x: 65, y: 70, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p014-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-014.webp",
      
      bubbles: [{ kind: "creature", text: "*phase-reveal*", speaker: "Wisplet", x: 50, y: 35, tail: "down" }, { kind: "narration", text: "Walls lied. The market lied with them.", x: 50, y: 78 }, { kind: "sfx", text: "phase-HUM", x: 70, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p015",
    pageNumber: 15,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Recruitment File",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-015.webp",
    artAlt: "Recruitment File — The Merchant's Secret page 11",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p015-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-015.webp",
      
      bubbles: [{ kind: "creature", text: "*record-trill*", speaker: "Echoquill", x: 40, y: 25, tail: "down" }, { kind: "speech", text: "That's… my recruitment age.", speaker: "Nira Quill", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p015-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-015.webp",
      
      bubbles: [{ kind: "narration", text: "They recruit children the way markets recruit hunger.", x: 50, y: 20 }, { kind: "whisper", text: "I wasn't saved. I was sorted.", speaker: "Nira Quill", x: 50, y: 72 }],
    },
    {
      id: "the-merchants-secret-issue-006-p015-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-015.webp",
      
      bubbles: [{ kind: "speech", text: "You cut their leash at Tempestria. That matters.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "sfx", text: "auction-GONG", x: 70, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p016",
    pageNumber: 16,
    layout: "splash-inset" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Egg Auction Announced",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-016.webp",
    artAlt: "Egg Auction Announced — The Merchant's Secret page 12",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p016-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-016.webp",
      
      bubbles: [{ kind: "caption", text: "LOT ONE — DORMANT RIFBORN EGG", x: 50, y: 12 }, { kind: "speech", text: "Unhatched. Unbonded. Unregistered.", speaker: "Auctioneer", x: 50, y: 35, tail: "down" }, { kind: "creature", text: "*violent-flare!*", speaker: "Spark", x: 35, y: 55, tail: "right" }, { kind: "shout", text: "Spark—!", speaker: "Mira Eggwarden", x: 65, y: 70, tail: "left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p017",
    pageNumber: 17,
    layout: "two-wide" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Underground Archive",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-017.webp",
    artAlt: "Underground Archive — The Merchant's Secret page 13",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p017-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-017.webp",
      
      bubbles: [{ kind: "creature", text: "*keyshift*", speaker: "Lockjaw Wisp", x: 45, y: 28, tail: "down" }, { kind: "speech", text: "Meridian thinks this auction is theirs. It is mine.", speaker: "Aurelia Voss", x: 55, y: 65, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p017-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-017.webp",
      
      bubbles: [{ kind: "narration", text: "Every door had a architect. The name was sealed.", x: 50, y: 15 }, { kind: "sfx", text: "vault-CHAIN", x: 70, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p018",
    pageNumber: 18,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Auction Trap",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-018.webp",
    artAlt: "Auction Trap — The Merchant's Secret page 14",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p018-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "Lot one opens the Resonance line. Bid accordingly.", speaker: "Seris Vale", x: 50, y: 28, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p018-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "The egg is bait.", speaker: "Mira Eggwarden", x: 40, y: 30, tail: "down" }, { kind: "creature", text: "*barrier-flare*", speaker: "Wisplet", x: 65, y: 55, tail: "left" }],
    },
    {
      id: "the-merchants-secret-issue-006-p018-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-018.webp",
      
      bubbles: [{ kind: "speech", text: "Handlers. Not collectors.", speaker: "Nira Quill", x: 50, y: 35, tail: "down" }, { kind: "shout", text: "Seize Subject One if it shows.", speaker: "Seris Vale", x: 65, y: 72, tail: "left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p019",
    pageNumber: 19,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Beyond Control",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-019.webp",
    artAlt: "Beyond Control — The Merchant's Secret page 15",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p019-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "Your network, Merchant. My keys.", speaker: "Seris Vale", x: 50, y: 30, tail: "down" }, { kind: "sfx", text: "ledger-FLIP", x: 70, y: 55 }],
    },
    {
      id: "the-merchants-secret-issue-006-p019-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-019.webp",
      
      bubbles: [{ kind: "speech", text: "Those doors are mine to close.", speaker: "Aurelia Voss", x: 45, y: 30, tail: "down" }, { kind: "speech", text: "Not anymore.", speaker: "Seris Vale", x: 65, y: 65, tail: "left" }],
    },
    {
      id: "the-merchants-secret-issue-006-p019-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-019.webp",
      
      bubbles: [{ kind: "narration", text: "When a network outgrows its merchant, the market breaks.", x: 50, y: 20 }, { kind: "sfx", text: "engine-WHINE", x: 55, y: 70 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p020",
    pageNumber: 20,
    layout: "splash-inset" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Private Auction",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-020.webp",
    artAlt: "Private Auction — The Merchant's Secret page 16",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p020-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-020.webp",
      
      bubbles: [{ kind: "speech", text: "Doors are currency. This egg is a door.", speaker: "Seris Vale", x: 50, y: 25, tail: "down" }, { kind: "caption", text: "PRIVATE CIRCLE — MERIDIAN ONLY", x: 50, y: 88 }, { kind: "sfx", text: "restraint-HUM", x: 72, y: 50 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p021",
    pageNumber: 21,
    layout: "four-grid" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Bidding and Cry",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-021.webp",
    artAlt: "Bidding and Cry — The Merchant's Secret page 17",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p021-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "Bid for the unhatched door!", speaker: "Auctioneer", x: 50, y: 30, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p021-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-021.webp",
      
      bubbles: [{ kind: "creature", text: "*chain-rattle*", speaker: "Cindermink", x: 45, y: 30, tail: "down" }, { kind: "sfx", text: "captive-CRY", x: 65, y: 55 }],
    },
    {
      id: "the-merchants-secret-issue-006-p021-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "They bid on one cage while others scream.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p021-panel-3",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-021.webp",
      
      bubbles: [{ kind: "speech", text: "Then we break both.", speaker: "Nira Quill", x: 55, y: 70, tail: "up" }, { kind: "sfx", text: "sigil-SNAP", x: 70, y: 40 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p022",
    pageNumber: 22,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Spark Revealed",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-022.webp",
    artAlt: "Spark Revealed — The Merchant's Secret page 18",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p022-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-022.webp",
      
      bubbles: [{ kind: "sfx", text: "RESONANCE!", x: 50, y: 14 }, { kind: "shout", text: "Subject One — seize!", speaker: "Seris Vale", x: 70, y: 40, tail: "left" }, { kind: "creature", text: "*protective-roar!*", speaker: "Spark", x: 35, y: 50, tail: "right" }, { kind: "speech", text: "He chooses. You don't.", speaker: "Mira Eggwarden", x: 50, y: 82, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p023",
    pageNumber: 23,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Break the Auction",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-023.webp",
    artAlt: "Break the Auction — The Merchant's Secret page 19",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p023-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-023.webp",
      
      bubbles: [{ kind: "sfx", text: "AUCTION-BREAK", x: 50, y: 12 }, { kind: "creature", text: "*device-snap*", speaker: "Bramblefox", x: 30, y: 45, tail: "right" }, { kind: "creature", text: "*bulwark!*", speaker: "Mossprig", x: 55, y: 55, tail: "down" }, { kind: "shout", text: "Companions first — always!", speaker: "Mira Eggwarden", x: 65, y: 78, tail: "left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p024",
    pageNumber: 24,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Ledger Doors",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-024.webp",
    artAlt: "Ledger Doors — The Merchant's Secret page 20",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p024-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "Every door Tempestria sealed — now mine.", speaker: "Seris Vale", x: 50, y: 28, tail: "down" }, { kind: "sfx", text: "door-MAP", x: 70, y: 55 }],
    },
    {
      id: "the-merchants-secret-issue-006-p024-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "Not all of them.", speaker: "Nira Quill", x: 45, y: 30, tail: "down" }, { kind: "sfx", text: "route-BURN", x: 65, y: 60 }],
    },
    {
      id: "the-merchants-secret-issue-006-p024-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-024.webp",
      
      bubbles: [{ kind: "speech", text: "She closed a door I wanted shut slower.", speaker: "Aurelia Voss", x: 55, y: 35, tail: "down" }, { kind: "speech", text: "Close the cages next.", speaker: "Mira Eggwarden", x: 50, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p025",
    pageNumber: 25,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Break the Chain",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-025.webp",
    artAlt: "Break the Chain — The Merchant's Secret page 21",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p025-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-025.webp",
      
      bubbles: [{ kind: "sfx", text: "BREAK THE CHAIN", x: 50, y: 18 }, { kind: "creature", text: "*ember-cut!*", speaker: "Cindermink", x: 45, y: 45, tail: "down" }],
    },
    {
      id: "the-merchants-secret-issue-006-p025-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-025.webp",
      
      bubbles: [{ kind: "creature", text: "*closed-contract*", speaker: "Lockjaw Wisp", x: 50, y: 30, tail: "down" }, { kind: "speech", text: "Vault sealed. Debts collected.", speaker: "Aurelia Voss", x: 60, y: 70, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p025-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-025.webp",
      
      bubbles: [{ kind: "speech", text: "Freedom is not a receipt.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "creature", text: "*guard-hum*", speaker: "Spark", x: 55, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p026",
    pageNumber: 26,
    layout: "splash-inset" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Bazaar Shifts",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-026.webp",
    artAlt: "Bazaar Shifts — The Merchant's Secret page 22",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p026-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-026.webp",
      
      bubbles: [{ kind: "narration", text: "When the engine breaks schedule, the market breaks geography.", x: 50, y: 10 }, { kind: "sfx", text: "SHIFT-ROOOAR", x: 55, y: 45 }, { kind: "shout", text: "You moved my exit!", speaker: "Seris Vale", x: 70, y: 70, tail: "left" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p027",
    pageNumber: 27,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "Stabilize the Egg",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-027.webp",
    artAlt: "Stabilize the Egg — The Merchant's Secret page 23",
    atmosphere: "rift" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p027-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-027.webp",
      
      bubbles: [{ kind: "sfx", text: "STABILIZE", x: 50, y: 14 }, { kind: "speech", text: "Invite — don't own!", speaker: "Mira Eggwarden", x: 40, y: 50, tail: "right" }, { kind: "speech", text: "Meridian routes — closed.", speaker: "Aurelia Voss", x: 70, y: 40, tail: "left" }, { kind: "creature", text: "*steady-hum*", speaker: "Spark", x: 55, y: 75, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p028",
    pageNumber: 28,
    layout: "three-stack" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Riftwright",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-028.webp",
    artAlt: "The Riftwright — The Merchant's Secret page 24",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p028-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-028.webp",
      
      bubbles: [{ kind: "caption", text: "THE RIFTRIGHT", x: 50, y: 12 }, { kind: "narration", text: "The architect of the First Rift did not act alone.", x: 50, y: 75 }],
    },
    {
      id: "the-merchants-secret-issue-006-p028-panel-1",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "Who were they?", speaker: "Mira Eggwarden", x: 40, y: 30, tail: "down" }, { kind: "speech", text: "A title first. A name when you've paid more doors.", speaker: "Aurelia Voss", x: 60, y: 65, tail: "up" }],
    },
    {
      id: "the-merchants-secret-issue-006-p028-panel-2",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-028.webp",
      
      bubbles: [{ kind: "speech", text: "This egg is not property. Neither is Cindermink.", speaker: "Mira Eggwarden", x: 50, y: 35, tail: "down" }, { kind: "creature", text: "*grateful-chuff*", speaker: "Cindermink", x: 55, y: 72, tail: "up" }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p029",
    pageNumber: 29,
    layout: "splash" as ComicPanelLayout,
    role: "story" as ComicPageRole,
    title: "The Traitor's Gate",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-029.webp",
    artAlt: "The Traitor's Gate — The Merchant's Secret page 25",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p029-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-029.webp",
      
      bubbles: [{ kind: "whisper", text: "The Keeper has the egg. Proceed to the next gate.", speaker: "Merchant Signal", x: 50, y: 30, tail: "down" }, { kind: "thought", text: "…the price.", speaker: "Cael Vesper", x: 35, y: 55, tail: "right" }, { kind: "caption", text: "NEXT: THE TRAITOR'S GATE", x: 50, y: 88 }, { kind: "sfx", text: "token-PULSE", x: 70, y: 65 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p030",
    pageNumber: 30,
    layout: "splash" as ComicPanelLayout,
    role: "teaser" as ComicPageRole,
    title: "Next Issue — The Traitor's Gate",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-030.webp",
    artAlt: "Next Issue — The Traitor's Gate",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p030-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-030.webp",
      
      bubbles: [{ kind: "caption", text: "NEXT ISSUE", x: 50, y: 18 }, { kind: "narration", text: "The Keeper has the egg. Someone opened the next gate from within.", x: 50, y: 50 }, { kind: "caption", text: "THE TRAITOR'S GATE", x: 50, y: 82 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p031",
    pageNumber: 31,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Character Profile — Aurelia Voss",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-031.webp",
    artAlt: "Character Profile — Aurelia Voss",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p031-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-031.webp",
      
      bubbles: [{ kind: "caption", text: "AURELIA VOSS", x: 50, y: 12 }, { kind: "narration", text: "The Gilded Merchant. Preserves routes others would burn. Morally ambiguous uneasy ally.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p032",
    pageNumber: 32,
    layout: "splash" as ComicPanelLayout,
    role: "profile" as ComicPageRole,
    title: "Companion Profile — Lockjaw Wisp",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-032.webp",
    artAlt: "Companion Profile — Lockjaw Wisp",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p032-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-032.webp",
      
      bubbles: [{ kind: "caption", text: "LOCKJAW WISP", x: 50, y: 12 }, { kind: "narration", text: "Merchant companion — Appraiser's Eye · Keyshift · Closed Contract — Control / Utility / Information.", x: 50, y: 80 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p033",
    pageNumber: 33,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Codex — Gilded Crossroads",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-033.webp",
    artAlt: "Codex — Gilded Crossroads",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p033-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-033.webp",
      
      bubbles: [{ kind: "caption", text: "CODEX — GILDED CROSSROADS", x: 50, y: 12 }, { kind: "narration", text: "Moving bazaar along old Rift routes. Legal trade floor. Portal engine relocates the entire market. Companion trafficking forbidden — but pens exist.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p034",
    pageNumber: 34,
    layout: "splash" as ComicPanelLayout,
    role: "lore" as ComicPageRole,
    title: "Ability Spotlight — Break the Chain",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-034.webp",
    artAlt: "Ability Spotlight — Break the Chain",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p034-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-034.webp",
      
      bubbles: [{ kind: "caption", text: "ABILITY — BREAK THE CHAIN", x: 50, y: 14 }, { kind: "narration", text: "Remove restraints from allied companions and deal Fire damage to controlling devices. Condemn trafficking; rescue is not ownership.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p035",
    pageNumber: 35,
    layout: "splash" as ComicPanelLayout,
    role: "map" as ComicPageRole,
    title: "World Map — Tempestria to Crossroads",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-035.webp",
    artAlt: "World Map — Tempestria to Crossroads",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p035-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-035.webp",
      
      bubbles: [{ kind: "caption", text: "ROUTE OF EVERY DOOR", x: 50, y: 10 }, { kind: "narration", text: "Tempestria → Gilded Crossroads → Traitor's Gate (teaser)", x: 50, y: 85 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p036",
    pageNumber: 36,
    layout: "splash" as ComicPanelLayout,
    role: "letters" as ComicPageRole,
    title: "Editor's Note — Doors and Prices",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-036.webp",
    artAlt: "Editor's Note — Doors and Prices",
    atmosphere: "dusk" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p036-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-036.webp",
      
      bubbles: [{ kind: "caption", text: "EDITOR'S NOTE", x: 50, y: 14 }, { kind: "narration", text: "Issue #6 distinguishes legal trade from companion trafficking. Living cores are not SKUs. The cliffhanger asks who sells trust from inside the circle.", x: 50, y: 55 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p037",
    pageNumber: 37,
    layout: "splash" as ComicPanelLayout,
    role: "inside-cover" as ComicPageRole,
    title: "Inside Back Cover",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-037.webp",
    artAlt: "Inside Back Cover",
    atmosphere: "market" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p037-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-037.webp",
      
      bubbles: [{ kind: "caption", text: "GILDED CROSSROADS MERCHANT PASS", x: 50, y: 14 }, { kind: "narration", text: "Central exchange — weapons sheathed. Companion pens — FORBIDDEN. Portal engine — CIRCLE ONLY.", x: 50, y: 50 }, { kind: "whisper", text: "Living cores are not SKUs.", x: 50, y: 78 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  },
  {
    id: "the-merchants-secret-issue-006-p038",
    pageNumber: 38,
    layout: "splash" as ComicPanelLayout,
    role: "back-cover" as ComicPageRole,
    title: "Back Cover — The Traitor's Gate",
    artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-038.webp",
    artAlt: "Back Cover — The Traitor's Gate",
    atmosphere: "night" as ComicPage["atmosphere"],
    panels: [{
      id: "the-merchants-secret-issue-006-p038-panel-0",
      artSrc: "/assets/comics/the-merchants-secret/issue-006/pages/page-038.webp",
      
      bubbles: [{ kind: "caption", text: "THE MERCHANT'S SECRET", x: 50, y: 12 }, { kind: "narration", text: "Every door opened. One ally closed the wrong one.", x: 50, y: 50 }, { kind: "caption", text: "ISSUE #6 · LEGENDS OF THE RIFT", x: 50, y: 88 }],
    }],
    composedPlate: true,
    bakedLettering: true,
  }
  ],
  characters: [
    { name: "Mira Eggwarden", role: "Keeper", blurb: "Enters the Crossroads — refuses companion trafficking." },
    { name: "Spark", role: "Riftborn / Resonance Line", blurb: "Senses the dormant egg; reveals to protect captives." },
    { name: "Aurelia Voss", role: "Gilded Merchant", blurb: "Formalized from Issue #5 Hooded Merchant — uneasy ally." },
    { name: "Cael Vesper", role: "Lanternmaster", blurb: "Knows market customs — traitor cliffhanger." },
    { name: "Seris Vale", role: "Meridian commander", blurb: "Weaponizes the royal trade ledger at auction." },
    { name: "Nira Quill", role: "Uncertain hunter", blurb: "Burns her Meridian path destroying a ledger door." },
    { name: "Lockjaw Wisp", role: "Merchant companion", blurb: "Appraiser's Eye · Keyshift · Closed Contract.", speciesSlug: "lockjaw-wisp" },
    { name: "Cindermink", role: "Rescue companion", blurb: "Cornered Flame · Smoke Slip · Break the Chain.", speciesSlug: "cindermink" },
    { name: "Elara Venn", role: "Vision echo only", blurb: "Not present — Soft Exodus counsel only if invoked." },
  ],
  locations: [
    { name: "Gilded Crossroads", blurb: "Moving bazaar on old Rift routes." },
    { name: "Underground Archive", blurb: "Keys, genealogy, First Rift records." },
    { name: "Private Auction Chamber", blurb: "Trap for a dormant Riftborn egg." },
    { name: "Tempestria", blurb: "Prior issue — recovering off-page." },
  ],
  timelineNote: "After The Storm King — every door leads here.",
  playChapterHref: "/marketplace",
  playChapterLabel: "Visit Marketplace",
  unlockGates: [
    { kind: "prior-issue", slug: "the-storm-king", label: "Complete Issue #5: The Storm King" },
    { kind: "admin-dev", label: "Admin / COMICS_DEV_UNLOCK override" },
  ],
  nextIssueTeaser: {
    slug: "the-traitors-gate",
    hook: "The Keeper has the egg. Proceed to the next gate.",
  },
  readingTimeMinutes: 22,
  factions: [
    { name: "Gilded Merchant Circle", blurb: "Fractured — Aurelia uneasy ally." },
    { name: "Veiled Meridian", blurb: "Egg auction + ledger doors." },
    { name: "Lanternveil Circus", blurb: "Ally compromised by Cael's debt." },
    { name: "Hatchery Compact", blurb: "Living cores are not SKUs." },
  ],
  collectibles: [],
  rewards: [],
  arcId: "fracture-dawn",
  volumeId: "volume-1",
};

export function getIssue006Transcript(pageNumber: number): string[] {
  return ISSUE_006_TRANSCRIPTS[pageNumber] ?? [];
}
