import type { AcademyLesson } from "@/game/academy/types";

/** Advanced Path — mastery tracks (order 100+). */
export const ADVANCED_LESSONS: AcademyLesson[] = [
  {
    id: "adv-pvp",
    slug: "pvp-fundamentals",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 100,
    title: "PvP Fundamentals",
    summary: "Fair duels, consent, and sportsmanship — no wagering.",
    etaMinutes: 5,
    keywords: ["pvp", "duel", "fair", "consent"],
    body: [
      "Player vs player in Riftwilds is skill-focused. Duels and Ranked never require SOL wagers.",
      "Respect consent for social challenges. Leave gracefully; don't harass after losses.",
    ],
    interactive: [
      {
        id: "nav-duels",
        kind: "practice-stub",
        instruction: "Open Duels (practice stub)",
        practiceHref: "/arena/duels",
      },
    ],
    relatedIds: ["adv-ranked", "b15-training"],
  },
  {
    id: "adv-ranked",
    slug: "ranked-ladder",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 101,
    title: "Ranked Ladder",
    summary: "Seasonal ranks, normalization, and disclosure basics.",
    etaMinutes: 5,
    keywords: ["ranked", "ladder", "season", "mmr"],
    body: [
      "Ranked uses seasonal Arena Points and rank bands. Points are earn-only with no monetary value.",
      "Read Ranked disclosures in-app before climbing.",
    ],
    interactive: [
      {
        id: "nav-ranked",
        kind: "menu-navigate",
        instruction: "Open Ranked",
        practiceHref: "/arena/ranked",
      },
    ],
    relatedIds: ["adv-tournaments", "adv-team"],
  },
  {
    id: "adv-guild-wars",
    slug: "guild-wars",
    path: "advanced",
    category: "social",
    difficulty: "advanced",
    order: 102,
    title: "Guild Wars",
    summary: "Coordinate objectives with your guild — competitive social play.",
    etaMinutes: 5,
    keywords: ["guild wars", "guild", "war", "objectives"],
    body: [
      "Guild Wars pit crews on shared objectives. Strategy and teamwork matter more than wallet size.",
      "Participation rewards stay modest; avoid treating wars as investment vehicles.",
    ],
    relatedIds: ["b21-guilds", "adv-tournaments"],
  },
  {
    id: "adv-economy",
    slug: "economy-deep-dive",
    path: "advanced",
    category: "economy",
    difficulty: "advanced",
    order: 103,
    title: "Economy Deep Dive",
    summary: "Faucets, sinks, treasury, and why basics stay SOL-free.",
    etaMinutes: 6,
    keywords: ["economy", "faucet", "sink", "treasury", "credits", "sol"],
    body: [
      "Credits flow from play faucets into sinks (shops, cosmetics, care). Treasury and revenue allocation are public on Economy pages.",
      "Reminder: SOL is never required for basic gameplay. Optional chain features are clearly labeled.",
    ],
    quiz: [
      {
        id: "q-faucet",
        prompt: "What best describes Keeper Credits?",
        choices: [
          { id: "a", label: "A guaranteed investment return", correct: false },
          { id: "b", label: "Soft currency earned by playing", correct: true },
          { id: "c", label: "The same as SOL", correct: false },
        ],
        explainCorrect: "Credits are play-earned soft currency, not a financial instrument.",
      },
    ],
    relatedIds: ["b05-credits-sol", "adv-trading", "cur-economy"],
    rewards: [{ id: "badge-combat-scholar-econ", label: "Ledger Literate", kind: "badge" }],
  },
  {
    id: "adv-trading",
    slug: "trading-and-marketplace",
    path: "advanced",
    category: "economy",
    difficulty: "advanced",
    order: 104,
    title: "Trading & Marketplace",
    summary: "Listings, integrity hooks, and scam avoidance.",
    etaMinutes: 5,
    keywords: ["trade", "marketplace", "listing", "scam"],
    body: [
      "Marketplace demos let you browse listings. Production settlement may use audited escrow — until then, treat values as entertainment.",
      "Never trade off-platform for 'admin recovery.' Use in-app flows only.",
    ],
    interactive: [
      {
        id: "nav-market",
        kind: "menu-navigate",
        instruction: "Open Marketplace",
        practiceHref: "/marketplace",
      },
    ],
    relatedIds: ["adv-economy", "b16-shop"],
  },
  {
    id: "adv-crafting",
    slug: "crafting-optional",
    path: "advanced",
    category: "crafting",
    difficulty: "advanced",
    order: 105,
    title: "Crafting (Optional)",
    summary: "Ember Forge materials loop — optional progression.",
    etaMinutes: 4,
    keywords: ["craft", "forge", "materials", "workshop"],
    body: [
      "Crafting turns gathered materials into gear and goods. It is an optional profession path — you can enjoy Riftwilds without mastering the forge.",
    ],
    relatedIds: ["adv-farming", "adv-professions"],
  },
  {
    id: "adv-farming",
    slug: "farming-basics",
    path: "advanced",
    category: "crafting",
    difficulty: "advanced",
    order: 106,
    title: "Farming",
    summary: "Public farm plots and homestead growing.",
    etaMinutes: 4,
    keywords: ["farm", "plot", "grow", "harvest"],
    body: [
      "Commons public farm plots and Homestead gardens grow care ingredients and materials over time.",
    ],
    relatedIds: ["adv-crafting", "b22-homestead"],
  },
  {
    id: "adv-exploration",
    slug: "exploration-mastery",
    path: "advanced",
    category: "exploration",
    difficulty: "advanced",
    order: 107,
    title: "Exploration Mastery",
    summary: "Fog, hidden areas, resources, and safe travel.",
    etaMinutes: 5,
    keywords: ["explore", "fog", "hidden", "gather", "portal"],
    body: [
      "Reveal fog as you walk. Hidden gardens and chests reward curiosity. Gather nodes refill on timers.",
      "Region unlocks follow story/play — never a paid pass.",
    ],
    interactive: [
      {
        id: "explore-stub",
        kind: "practice-stub",
        instruction: "Enter Live World and open the map (M)",
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b04-map", "adv-bosses"],
  },
  {
    id: "adv-combat",
    slug: "combat-mastery",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 108,
    title: "Combat Mastery",
    summary: "Turns, status, weather hooks, and action economy.",
    etaMinutes: 6,
    keywords: ["combat", "turn", "status", "weather", "actions"],
    body: [
      "Master action selection, status effects, and when to defend or swap. Training is the safe lab; Ranked is the exam.",
    ],
    interactive: [
      {
        id: "combat-practice",
        kind: "practice-stub",
        instruction: "Open Combat Academy practice",
        practiceHref: "/academy?lesson=cur-combat&practice=1",
      },
    ],
    relatedIds: ["cur-combat", "adv-synergies"],
    rewards: [{ id: "badge-combat-scholar", label: "Combat Scholar", kind: "badge" }],
  },
  {
    id: "adv-synergies",
    slug: "affinity-synergies",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 109,
    title: "Synergies",
    summary: "Stack affinities, passives, and team auras.",
    etaMinutes: 5,
    keywords: ["synergy", "passive", "aura", "combo"],
    body: [
      "Synergies reward thoughtful teams — matching affinities and complementary moves — not paywalled power spikes.",
    ],
    relatedIds: ["adv-team", "b18-affinity"],
  },
  {
    id: "adv-team",
    slug: "team-building",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 110,
    title: "Team Building",
    summary: "Roles, coverage, and swap plans.",
    etaMinutes: 5,
    keywords: ["team", "roles", "coverage", "swap"],
    body: [
      "Build for coverage: a wall, a sweeper, and a support beat three of the same niche. Practice swaps in Training.",
    ],
    relatedIds: ["adv-synergies", "adv-ranked"],
  },
  {
    id: "adv-bosses",
    slug: "boss-encounters",
    path: "advanced",
    category: "exploration",
    difficulty: "advanced",
    order: 111,
    title: "Bosses",
    summary: "Read telegraphs, bring resists, don't greed.",
    etaMinutes: 5,
    keywords: ["boss", "raid", "telegraph", "resist"],
    body: [
      "Boss encounters punish greed. Learn patterns, pack recovery items, and rotate injured Riftlings through Recovery.",
    ],
    relatedIds: ["adv-exploration", "b10-recovery"],
  },
  {
    id: "adv-restoration",
    slug: "restoration-ops",
    path: "advanced",
    category: "exploration",
    difficulty: "advanced",
    order: 112,
    title: "Restoration Ops",
    summary: "Coordinate shrine mends and seasonal calls.",
    etaMinutes: 4,
    keywords: ["restoration", "shrine", "seasonal"],
    body: [
      "Advanced restoration tracks multi-step site repairs and seasonal world events. Progress is cooperative play.",
    ],
    relatedIds: ["b23-restoration"],
  },
  {
    id: "adv-professions",
    slug: "professions",
    path: "advanced",
    category: "crafting",
    difficulty: "advanced",
    order: 113,
    title: "Professions",
    summary: "Specialize without locking yourself out of fun.",
    etaMinutes: 4,
    keywords: ["profession", "gather", "craft", "specialize"],
    body: [
      "Professions deepen gathering, crafting, or care services. They are optional mastery — not paywalls.",
    ],
    relatedIds: ["adv-crafting", "adv-farming"],
  },
  {
    id: "adv-dailies",
    slug: "dailies-and-rotations",
    path: "advanced",
    category: "ui",
    difficulty: "advanced",
    order: 114,
    title: "Dailies & Rotations",
    summary: "Efficient daily loops without burnout.",
    etaMinutes: 3,
    keywords: ["daily", "rotation", "quest", "efficiency"],
    body: [
      "Dailies refresh on a schedule. Clear what you enjoy; skip FOMO. Rewards stay modest by design.",
    ],
    relatedIds: ["b13-quests"],
  },
  {
    id: "adv-tournaments",
    slug: "tournaments",
    path: "advanced",
    category: "advanced-combat",
    difficulty: "advanced",
    order: 115,
    title: "Tournaments",
    summary: "Bracket play, spectating, and seasonal cups.",
    etaMinutes: 4,
    keywords: ["tournament", "bracket", "cup", "spectate"],
    body: [
      "Tournaments showcase skill. Spectate from Arena when live. Prizes are cosmetic or points — not investment returns.",
    ],
    interactive: [
      {
        id: "nav-tournaments",
        kind: "menu-navigate",
        instruction: "Open Tournaments",
        practiceHref: "/arena/tournaments",
      },
    ],
    relatedIds: ["adv-ranked", "adv-pvp"],
  },
];
