import type { AcademyLesson } from "@/game/academy/types";

/** Beginner Path lessons 1–30 — hands-on first, short copy. */
export const BEGINNER_LESSONS: AcademyLesson[] = [
  {
    id: "b01-welcome",
    slug: "welcome-to-riftwilds",
    path: "beginner",
    category: "getting-started",
    difficulty: "beginner",
    order: 1,
    title: "Welcome to Riftwilds",
    summary: "Meet the world, your Keeper role, and how the Academy works.",
    etaMinutes: 3,
    keywords: ["welcome", "intro", "keeper", "academy", "riftwilds"],
    body: [
      "You are a Keeper in The Riftwilds — a fractured fantasy world where companions called Riftlings hatch, grow, and adventure beside you.",
      "This Academy is your practice hall. Lessons unlock progress badges and optional one-time rewards. Nothing here requires spending SOL to play the basics.",
      "Use the left rail to browse paths, search topics, or jump back to recent lessons.",
    ],
    tips: ["Bookmark favorites with the star.", "Complete interactives — they stick better than reading alone."],
    shortcuts: ["Esc closes overlays in Live World", "F1 opens Help / Academy from Live World"],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/welcome-commons.png",
        alt: "Riftwild Commons plaza under cyan riftlight",
      },
    ],
    interactive: [
      {
        id: "welcome-checklist",
        kind: "checklist",
        instruction: "Confirm you know the Academy layout",
        checklist: [
          "Left: categories, search, favorites",
          "Center: lesson content + interactives",
          "Right: progress, tips, related lessons",
        ],
      },
    ],
    relatedIds: ["b02-controls", "b05-credits-sol"],
    rewards: [{ id: "badge-first-step", label: "First Step", kind: "badge" }],
  },
  {
    id: "b02-controls",
    slug: "movement-wasd",
    path: "beginner",
    category: "movement",
    difficulty: "beginner",
    order: 2,
    title: "Movement: WASD Gate",
    summary: "Prove you can move — press W, A, S, and D to clear the gate.",
    etaMinutes: 2,
    keywords: ["wasd", "move", "controls", "keyboard", "walk"],
    controlMentions: ["W", "A", "S", "D", "Shift"],
    body: [
      "In Live World, move with W A S D (or arrow keys). Hold Shift to sprint.",
      "Clear the practice gate below, then try the same keys after you Enter the Live World.",
    ],
    tips: ["On mobile, use the on-screen stick when Live World mobile controls are enabled."],
    shortcuts: ["W/A/S/D move", "Shift sprint"],
    interactive: [
      {
        id: "wasd-gate",
        kind: "wasd-gate",
        instruction: "Press W, A, S, and D at least once each",
        requiredKeys: ["w", "a", "s", "d"],
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b03-interact", "b28-keybinds"],
  },
  {
    id: "b03-interact",
    slug: "interact-e-space",
    path: "beginner",
    category: "controls",
    difficulty: "beginner",
    order: 3,
    title: "Interact: E / Space",
    summary: "Talk to NPCs, inspect buildings, and use prompts with E or Space.",
    etaMinutes: 2,
    keywords: ["interact", "e", "space", "npc", "building"],
    controlMentions: ["E", "Space"],
    body: [
      "When a prompt appears (Talk, Inspect, Enter portal), press E or Space.",
      "Interaction menus list options — pick one, or Leave to cancel.",
    ],
    interactive: [
      {
        id: "click-interact-demo",
        kind: "click-target",
        instruction: "Click the glowing prompt plaque to simulate an interact",
        targetId: "demo-prompt",
      },
    ],
    relatedIds: ["b04-map", "b12-npcs"],
  },
  {
    id: "b04-map",
    slug: "world-map-basics",
    path: "beginner",
    category: "world",
    difficulty: "beginner",
    order: 4,
    title: "World Map Basics",
    summary: "Open the map, read waypoints, and understand region travel.",
    etaMinutes: 3,
    keywords: ["map", "m", "waypoint", "region", "travel", "portal"],
    controlMentions: ["M"],
    regionMentions: ["riftwild-commons"],
    body: [
      "Press M in Live World to open the map overlay. Waypoints mark plazas, gates, and points of interest.",
      "Portals and gateway stones move you between regions when unlocked. Travel never requires a paid pet or pass.",
    ],
    interactive: [
      {
        id: "map-waypoint",
        kind: "map-waypoint",
        instruction: "Select the Commons Plaza waypoint on the practice map",
        targetId: "waypoint-plaza",
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b11-commons", "adv-exploration"],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/world-map-hud.png",
        alt: "Stylized Riftwilds world map HUD with cyan waypoints",
      },
    ],
  },
  {
    id: "b05-credits-sol",
    slug: "credits-vs-sol",
    path: "beginner",
    category: "economy",
    difficulty: "beginner",
    order: 5,
    title: "Credits vs SOL",
    summary: "Credits are earned by playing. SOL is never required for basic gameplay.",
    etaMinutes: 4,
    keywords: ["credits", "sol", "economy", "free", "play", "wallet"],
    body: [
      "Keeper Credits are the soft currency you earn from play, care, quests, and events. Use them for everyday cosmetics, care items, and many shop goods.",
      "SOL (or other crypto) may appear for optional marketplace or token features — it is NEVER required to hatch a starter, care for a Riftling, walk Live World, train in Arena, or finish this Academy.",
      "If anyone tells you that you must buy SOL to play the basics, they are wrong. Report scams; trust the in-game economy pages.",
    ],
    tips: [
      "Read /economy/credits for the ledger rules.",
      "Arena Points are earn-only and have no cash value.",
    ],
    quiz: [
      {
        id: "q-sol-required",
        prompt: "Is SOL required for basic gameplay (hatch, care, Live World, training)?",
        choices: [
          { id: "a", label: "Yes — you must buy SOL first", correct: false },
          { id: "b", label: "No — credits and play unlock the basics", correct: true },
          { id: "c", label: "Only on weekends", correct: false },
        ],
        explainCorrect:
          "Correct. SOL is optional for advanced marketplace/token paths. Basics are playable without it.",
      },
    ],
    relatedIds: ["b16-shop", "adv-economy"],
    rewards: [{ id: "badge-economy-aware", label: "Economy Aware", kind: "badge" }],
  },
  {
    id: "b06-hatchery",
    slug: "claim-your-egg",
    path: "beginner",
    category: "riftlings",
    difficulty: "beginner",
    order: 6,
    title: "Claim Your Egg",
    summary: "Visit the Hatchery, claim a starter egg, and start incubation.",
    etaMinutes: 3,
    keywords: ["hatchery", "egg", "claim", "starter", "incubate"],
    body: [
      "Open the Hatchery from Play or the Commons Hatchery building.",
      "Eligible Keepers can claim a starter egg. Incubation runs on a timer — check back to hatch.",
    ],
    interactive: [
      {
        id: "nav-hatchery",
        kind: "menu-navigate",
        instruction: "Open the Hatchery page from the practice link",
        practiceHref: "/hatchery",
      },
    ],
    relatedIds: ["b07-hatch", "b08-first-riftling"],
  },
  {
    id: "b07-hatch",
    slug: "hatching-basics",
    path: "beginner",
    category: "riftlings",
    difficulty: "beginner",
    order: 7,
    title: "Hatching Basics",
    summary: "Finish incubation and welcome your first companion.",
    etaMinutes: 3,
    keywords: ["hatch", "incubate", "riftling", "companion"],
    body: [
      "When the egg timer completes, claim the hatch. Your new Riftling appears in Collection / Profile pets.",
      "Species, affinity, and temperament shape care and combat — the Codex records the details.",
    ],
    relatedIds: ["b08-first-riftling", "b09-care"],
  },
  {
    id: "b08-first-riftling",
    slug: "meet-your-riftling",
    path: "beginner",
    category: "riftlings",
    difficulty: "beginner",
    order: 8,
    title: "Meet Your Riftling",
    summary: "Read species, affinity, temperament, and bond at a glance.",
    etaMinutes: 3,
    keywords: ["riftling", "species", "affinity", "temperament", "bond"],
    body: [
      "Open a pet page to see condition, care score, affinity, and memories.",
      "Affinity hints at combat strengths; temperament affects care pacing and flavor.",
    ],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/riftling-portrait-study.png",
        alt: "Original Riftling companion portrait study",
      },
    ],
    interactive: [
      {
        id: "click-affinity",
        kind: "click-target",
        instruction: "Click the affinity chip on the practice card",
        targetId: "demo-affinity",
      },
    ],
    relatedIds: ["b09-care", "cur-riftling"],
  },
  {
    id: "b09-care",
    slug: "pet-care-loop",
    path: "beginner",
    category: "pet-care",
    difficulty: "beginner",
    order: 9,
    title: "Pet Care Loop",
    summary: "Feed, play, rest — keep care score healthy.",
    etaMinutes: 4,
    keywords: ["care", "feed", "play", "rest", "hunger", "mood"],
    body: [
      "Care actions (feed, play, rest, and more) keep your Riftling healthy. Neglect decays condition over time when care systems are live.",
      "Care score can affect reward eligibility hints — but care is first about companionship, not grinding currency.",
    ],
    interactive: [
      {
        id: "care-checklist",
        kind: "checklist",
        instruction: "Plan a simple daily care loop",
        checklist: ["Feed when hungry", "Play to lift mood", "Rest after training"],
      },
    ],
    relatedIds: ["b10-recovery", "cur-pet-care"],
  },
  {
    id: "b10-recovery",
    slug: "recovery-center",
    path: "beginner",
    category: "pet-care",
    difficulty: "beginner",
    order: 10,
    title: "Recovery Center",
    summary: "Heal and rest companions after hard fights or long treks.",
    etaMinutes: 2,
    keywords: ["recovery", "heal", "rest", "clinic"],
    regionMentions: ["riftwild-commons"],
    body: [
      "The Recovery Center in Commons helps restore worn companions. Use it after Arena drills or exploration.",
    ],
    relatedIds: ["b09-care", "b15-training"],
  },
  {
    id: "b11-commons",
    slug: "riftwild-commons-tour",
    path: "beginner",
    category: "world",
    difficulty: "beginner",
    order: 11,
    title: "Riftwild Commons Tour",
    summary: "Learn the hub districts: Hatchery, Arena, Market, Guild, Academy.",
    etaMinutes: 4,
    keywords: ["commons", "hub", "plaza", "districts", "academy"],
    regionMentions: ["riftwild-commons"],
    body: [
      "Commons is your hub. North holds Hatchery and Arena Gate; south has Market and Guild Hall; east hosts the Rift Archive and Player Academy.",
      "Walk the plaza, talk to Keepers, and use buildings as shortcuts into web features.",
    ],
    interactive: [
      {
        id: "commons-waypoint",
        kind: "map-waypoint",
        instruction: "Mark the Academy on the practice map",
        targetId: "academy",
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b04-map", "b12-npcs"],
  },
  {
    id: "b12-npcs",
    slug: "talking-to-npcs",
    path: "beginner",
    category: "npcs",
    difficulty: "beginner",
    order: 12,
    title: "Talking to NPCs",
    summary: "Greet Keepers, follow dialogue choices, and find services.",
    etaMinutes: 3,
    keywords: ["npc", "dialogue", "talk", "keeper", "solen", "elara"],
    npcMentions: ["archivist-solen", "elara-venn"],
    body: [
      "Approach an NPC until the Talk prompt appears, then press E. Choices can open shops, services, or lore.",
      "Archivist Solen near the Archive can point you back to this Academy.",
    ],
    interactive: [
      {
        id: "npc-click",
        kind: "npc-click",
        instruction: "Click Archivist Solen on the practice stage",
        targetId: "archivist-solen",
      },
    ],
    relatedIds: ["b03-interact", "cur-npc"],
  },
  {
    id: "b13-quests",
    slug: "quest-journal",
    path: "beginner",
    category: "ui",
    difficulty: "beginner",
    order: 13,
    title: "Quest Journal",
    summary: "Track story, daily, and exploration quests on the Quest Board.",
    etaMinutes: 3,
    keywords: ["quest", "journal", "daily", "story", "objectives"],
    body: [
      "Open Quests from the sidebar or Play menu. Accept, track, and complete objectives for keeper XP and care items — not real-money payouts.",
      "The Quest Board links here when you need a refresher tutorial.",
    ],
    interactive: [
      {
        id: "nav-quests",
        kind: "menu-navigate",
        instruction: "Open the Quest Board",
        practiceHref: "/quests",
      },
    ],
    relatedIds: ["adv-dailies", "b01-welcome"],
  },
  {
    id: "b14-inventory",
    slug: "inventory-basics",
    path: "beginner",
    category: "ui",
    difficulty: "beginner",
    order: 14,
    title: "Inventory Basics",
    summary: "Browse items, materials, and cosmetics you own.",
    etaMinutes: 2,
    keywords: ["inventory", "items", "materials", "bag"],
    body: [
      "Inventory lists what you hold. Equip gear from pet loadout screens; consume care items from pet pages when available.",
    ],
    interactive: [
      {
        id: "nav-inventory",
        kind: "menu-navigate",
        instruction: "Open Inventory",
        practiceHref: "/inventory",
      },
    ],
    relatedIds: ["b16-shop", "b17-loadout"],
  },
  {
    id: "b15-training",
    slug: "arena-training",
    path: "beginner",
    category: "combat",
    difficulty: "beginner",
    order: 15,
    title: "Arena Training",
    summary: "Fight practice bouts with no wagering — earn Arena Points.",
    etaMinutes: 4,
    keywords: ["arena", "training", "battle", "points", "practice"],
    body: [
      "Arena Training teaches turn structure safely. Arena Points are seasonal and non-transferable with no cash value.",
      "Never confuse training rewards with real-money gambling — Riftwilds Arena is skill practice.",
    ],
    interactive: [
      {
        id: "nav-training",
        kind: "menu-navigate",
        instruction: "Open Arena Training",
        practiceHref: "/arena/training",
      },
      {
        id: "combat-stub",
        kind: "practice-stub",
        instruction: "Run a Combat Academy practice stub",
        practiceHref: "/academy?lesson=cur-combat&practice=1",
      },
    ],
    relatedIds: ["b17-loadout", "cur-combat", "adv-pvp"],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/combat-training.png",
        alt: "Two original Riftlings sparring in a training yard",
      },
    ],
  },
  {
    id: "b16-shop",
    slug: "shops-and-credits",
    path: "beginner",
    category: "economy",
    difficulty: "beginner",
    order: 16,
    title: "Shops & Credits",
    summary: "Spend earned credits in the Shop — optional SOL paths stay optional.",
    etaMinutes: 3,
    keywords: ["shop", "buy", "credits", "potions", "gear"],
    body: [
      "The Shop sells care goods, materials, and cosmetics. Prefer credits for day-to-day buys.",
      "Marketplace listings may involve optional chain settlement later — never required for basic progress.",
    ],
    interactive: [
      {
        id: "nav-shop",
        kind: "menu-navigate",
        instruction: "Browse the Shop",
        practiceHref: "/shop",
      },
    ],
    quiz: [
      {
        id: "q-shop-currency",
        prompt: "What should you use first for everyday shop purchases?",
        choices: [
          { id: "a", label: "SOL only", correct: false },
          { id: "b", label: "Credits earned by playing", correct: true },
          { id: "c", label: "Arena Points as cash", correct: false },
        ],
        explainCorrect: "Credits are the soft currency for everyday play. Arena Points have no cash value.",
      },
    ],
    relatedIds: ["b05-credits-sol", "adv-trading"],
  },
  {
    id: "b17-loadout",
    slug: "equip-a-loadout",
    path: "beginner",
    category: "combat",
    difficulty: "beginner",
    order: 17,
    title: "Equip a Loadout",
    summary: "Click your Riftling in Live World to open Equipment, or use Arena Loadout.",
    etaMinutes: 4,
    keywords: ["loadout", "weapon", "armor", "equip", "equipment", "riftling", "cosmetic"],
    body: [
      "In Live World, click or tap your active Riftling, choose Equipment, and equip owned gear. Cosmetics show on the companion sprite.",
      "You can also open Arena Loadout or a pet's loadout page for battle-ready named sets. Ranked keeps cosmetics visible with normalized power — SOL is never required for basic cosmetics.",
      "Only items you own can be equipped. Other Keepers' Riftlings are inspect-only.",
    ],
    interactive: [
      {
        id: "nav-live-equipment",
        kind: "menu-navigate",
        instruction: "Enter Live World and open companion Equipment (click your Riftling)",
        practiceHref: "/live-world",
      },
      {
        id: "nav-loadout",
        kind: "menu-navigate",
        instruction: "Open Arena Loadout (battle sets)",
        practiceHref: "/arena/loadout",
      },
      {
        id: "equip-checklist",
        kind: "checklist",
        instruction: "Practice the equip loop",
        checklist: [
          "Click / tap your companion → select highlight",
          "Choose Equipment from the context menu",
          "Equip an owned item and confirm it appears on the world pet",
        ],
      },
    ],
    relatedIds: ["b14-inventory", "b15-training", "b16-shop", "adv-team"],
    tips: [
      "Shop purchases grant inventory immediately — use Equip Now to wear gear right away.",
      "Presets: Default, Adventure, Arena, Homestead, Ceremony.",
    ],
  },
  {
    id: "b18-affinity",
    slug: "affinity-basics",
    path: "beginner",
    category: "combat",
    difficulty: "beginner",
    order: 18,
    title: "Affinity Basics",
    summary: "Ember, Tide, Grove, and more — matchups matter.",
    etaMinutes: 3,
    keywords: ["affinity", "type", "matchup", "ember", "tide"],
    abilityMentions: ["affinity"],
    body: [
      "Each Riftling has an affinity that colors moves and matchups. Favorable affinities hit harder; poor ones struggle.",
      "Check the Arena affinity guide before climbing Ranked.",
    ],
    relatedIds: ["adv-synergies", "cur-combat"],
  },
  {
    id: "b19-profile",
    slug: "keeper-profile",
    path: "beginner",
    category: "ui",
    difficulty: "beginner",
    order: 19,
    title: "Keeper Profile",
    summary: "Display name, pets, achievements, and quick links — including Academy.",
    etaMinutes: 2,
    keywords: ["profile", "achievements", "display name"],
    body: [
      "Your Profile is the hub for pets, loadout snapshots, and achievements. Open Academy anytime from the quick links.",
    ],
    interactive: [
      {
        id: "nav-profile",
        kind: "menu-navigate",
        instruction: "Open Profile",
        practiceHref: "/profile",
      },
    ],
    relatedIds: ["b01-welcome"],
  },
  {
    id: "b20-chat",
    slug: "chat-and-emotes",
    path: "beginner",
    category: "social",
    difficulty: "beginner",
    order: 20,
    title: "Chat & Emotes",
    summary: "Say hello in Live World chat; use T for emotes.",
    etaMinutes: 2,
    keywords: ["chat", "emote", "social", "t"],
    controlMentions: ["Enter", "T"],
    body: [
      "Press Enter to focus chat. Press T for the emote wheel. Be kind — Keepers remember manners.",
    ],
    relatedIds: ["b28-keybinds", "adv-guild-wars"],
  },
  {
    id: "b21-guilds",
    slug: "guilds-intro",
    path: "beginner",
    category: "social",
    difficulty: "beginner",
    order: 21,
    title: "Guilds Intro",
    summary: "Join or browse guilds for social play — wars come later.",
    etaMinutes: 2,
    keywords: ["guild", "social", "party"],
    body: [
      "Guild Hall in Commons and the Guilds page let you find a crew. Advanced Guild Wars lessons cover competitive play.",
    ],
    interactive: [
      {
        id: "nav-guilds",
        kind: "menu-navigate",
        instruction: "Open Guilds",
        practiceHref: "/guilds",
      },
    ],
    relatedIds: ["adv-guild-wars"],
  },
  {
    id: "b22-homestead",
    slug: "homestead-basics",
    path: "beginner",
    category: "world",
    difficulty: "beginner",
    order: 22,
    title: "Homestead Basics",
    summary: "Keeper Row and Homestead — your personal space.",
    etaMinutes: 2,
    keywords: ["homestead", "housing", "keeper row"],
    body: [
      "Homestead is where you personalize a corner of the world. Farming and crafting lessons expand what you can build.",
    ],
    relatedIds: ["adv-farming", "adv-crafting"],
  },
  {
    id: "b23-restoration",
    slug: "world-restoration",
    path: "beginner",
    category: "exploration",
    difficulty: "beginner",
    order: 23,
    title: "World Restoration",
    summary: "Help mend fractured sites across regions.",
    etaMinutes: 3,
    keywords: ["restoration", "shrine", "mend", "world"],
    body: [
      "Restoration content lets Keepers heal damaged sites. Contributions are play-driven — not pay-to-win world control.",
    ],
    interactive: [
      {
        id: "nav-restoration",
        kind: "menu-navigate",
        instruction: "Open World Restoration",
        practiceHref: "/restoration",
      },
    ],
    relatedIds: ["adv-restoration", "adv-exploration"],
  },
  {
    id: "b24-fairness",
    slug: "fairness-and-safety",
    path: "beginner",
    category: "getting-started",
    difficulty: "beginner",
    order: 24,
    title: "Fairness & Safety",
    summary: "No guaranteed profit, no wagering Arena, report scams.",
    etaMinutes: 3,
    keywords: ["fairness", "safety", "scam", "risk", "transparency"],
    body: [
      "Riftwilds is entertainment. Crypto values move; nothing here promises profit.",
      "Read Fairness, Transparency, and Risk pages. Never share seed phrases. Staff will never DM you for wallet keys.",
    ],
    interactive: [
      {
        id: "nav-fairness",
        kind: "menu-navigate",
        instruction: "Open Fairness",
        practiceHref: "/fairness",
      },
    ],
    relatedIds: ["b05-credits-sol"],
  },
  {
    id: "b25-leaderboards",
    slug: "leaderboards",
    path: "beginner",
    category: "ui",
    difficulty: "beginner",
    order: 25,
    title: "Leaderboards",
    summary: "Seasonal ladders for Arena, care, and collection.",
    etaMinutes: 2,
    keywords: ["leaderboard", "rank", "season"],
    body: [
      "Leaderboards celebrate play. Ranks reset by season rules — climbing is optional fun, not a financial product.",
    ],
    relatedIds: ["adv-ranked", "adv-tournaments"],
  },
  {
    id: "b26-collection",
    slug: "collection-codex",
    path: "beginner",
    category: "riftlings",
    difficulty: "beginner",
    order: 26,
    title: "Collection & Codex",
    summary: "Track species you've met and open the Riftling Codex.",
    etaMinutes: 2,
    keywords: ["collection", "codex", "species"],
    body: [
      "Collection shows companions you own. The Codex (via Archive / World) catalogs species lore.",
    ],
    relatedIds: ["b08-first-riftling", "cur-riftling"],
  },
  {
    id: "b27-mobile",
    slug: "mobile-play",
    path: "beginner",
    category: "controls",
    difficulty: "beginner",
    order: 27,
    title: "Mobile Play",
    summary: "Bottom nav + on-screen controls when the flag is on.",
    etaMinutes: 2,
    keywords: ["mobile", "touch", "stick", "responsive"],
    body: [
      "On phones, use the bottom Play / Hatch / Live / Arena / Pack bar. Live World may show a virtual stick when mobile controls are enabled.",
      "The Academy layout stacks panels on small screens — search stays at the top.",
    ],
    relatedIds: ["b02-controls"],
  },
  {
    id: "b28-keybinds",
    slug: "keyboard-shortcuts",
    path: "beginner",
    category: "controls",
    difficulty: "beginner",
    order: 28,
    title: "Keyboard Shortcuts",
    summary: "Master Esc, F1 Help, F2 Settings, M map, T emotes.",
    etaMinutes: 3,
    keywords: ["keybinds", "shortcuts", "f1", "f2", "esc", "help"],
    controlMentions: ["Esc", "F1", "F2", "M", "T", "Enter"],
    body: [
      "F1 opens Help / Academy. F2 opens keybinds settings. Esc closes the topmost panel, then the pause menu.",
      "Customize binds under Settings → Keybinds.",
    ],
    interactive: [
      {
        id: "shortcut-quiz",
        kind: "quiz",
        instruction: "Answer the shortcut quiz below",
      },
    ],
    quiz: [
      {
        id: "q-f1",
        prompt: "Which key opens Help / Academy in Live World?",
        choices: [
          { id: "a", label: "F1", correct: true },
          { id: "b", label: "F5", correct: false },
          { id: "c", label: "P", correct: false },
        ],
        explainCorrect: "F1 is Help. F2 is Settings / keybinds.",
      },
    ],
    relatedIds: ["cur-controls", "b02-controls"],
  },
  {
    id: "b29-practice-run",
    slug: "guided-practice-run",
    path: "beginner",
    category: "getting-started",
    difficulty: "beginner",
    order: 29,
    title: "Guided Practice Run",
    summary: "Checklist: Commons → NPC → Hatchery → Training → Academy graduate prep.",
    etaMinutes: 5,
    keywords: ["practice", "checklist", "graduate", "tour"],
    body: [
      "Put it together: enter Live World, greet an NPC, visit Hatchery or claim status, open Training once, then return here to finish the path.",
    ],
    interactive: [
      {
        id: "practice-checklist",
        kind: "checklist",
        instruction: "Complete each practice beat (stubs count)",
        checklist: [
          "Enter Live World (or open the gate page)",
          "Talk or inspect one NPC / building",
          "Open Hatchery",
          "Open Arena Training",
          "Return to Academy",
        ],
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b30-graduate"],
  },
  {
    id: "b30-graduate",
    slug: "tutorial-graduate",
    path: "beginner",
    category: "getting-started",
    difficulty: "beginner",
    order: 30,
    title: "Tutorial Graduate",
    summary: "Finish the Beginner Path and claim your graduate badge.",
    etaMinutes: 2,
    keywords: ["graduate", "complete", "badge", "finish"],
    body: [
      "Mark this lesson complete after finishing the earlier beginner lessons. You unlock the Tutorial Graduate achievement and a small one-time badge reward.",
      "Advanced Path lessons are optional mastery tracks — take them when you're ready.",
    ],
    interactive: [
      {
        id: "graduate-confirm",
        kind: "checklist",
        instruction: "Confirm you're ready to graduate",
        checklist: [
          "I know credits ≠ SOL requirement",
          "I can move and interact in Live World",
          "I know where Hatchery, Quests, and Arena live",
        ],
      },
    ],
    rewards: [
      { id: "badge-tutorial-graduate", label: "Tutorial Graduate", kind: "badge" },
      { id: "title-academy-novice", label: "Academy Novice", kind: "title" },
      {
        id: "credits-graduate-token",
        label: "Graduate Token Credits",
        kind: "token-credits",
        amount: 25,
      },
    ],
    relatedIds: ["adv-pvp", "cur-combat", "adv-economy"],
  },
];
