import type { AcademyLesson } from "@/game/academy/types";

/** Focused curricula (order 200+). */
export const CURRICULUM_LESSONS: AcademyLesson[] = [
  {
    id: "cur-riftling",
    slug: "riftling-academy",
    path: "curriculum",
    category: "riftlings",
    difficulty: "beginner",
    order: 200,
    title: "Riftling Academy",
    summary: "Species, affinity, temperament, bond, and memories.",
    etaMinutes: 6,
    keywords: ["riftling", "species", "bond", "memory", "codex"],
    body: [
      "Riftlings are original companions of The Riftwilds — not borrowed IP. Learn to read a pet sheet: condition, care score, affinity, temperament, and memory log.",
      "Bond grows with consistent care and shared adventures. Memories record milestones like first meal or first win.",
    ],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/riftling-portrait-study.png",
        alt: "Riftling study illustration",
      },
    ],
    interactive: [
      {
        id: "riftling-checklist",
        kind: "checklist",
        instruction: "Identify the fields on a pet sheet",
        checklist: ["Affinity", "Temperament", "Care score", "Memories"],
      },
    ],
    relatedIds: ["b08-first-riftling", "cur-pet-care"],
  },
  {
    id: "cur-pet-care",
    slug: "pet-care-academy",
    path: "curriculum",
    category: "pet-care",
    difficulty: "beginner",
    order: 201,
    title: "Pet Care Academy",
    summary: "Hunger, mood, rest, and recovery loops in depth.",
    etaMinutes: 6,
    keywords: ["care", "feed", "mood", "decay", "recovery"],
    body: [
      "Care systems decay over real time when enabled. Feed before hunger bites, play when mood dips, rest after Arena.",
      "Recovery Center helps after tough content. Care eligibility hints are guidance — companionship comes first.",
    ],
    interactive: [
      {
        id: "care-practice",
        kind: "practice-stub",
        instruction: "Open a pet page (demo if needed)",
        practiceHref: "/pets/demo-riftling",
      },
    ],
    relatedIds: ["b09-care", "b10-recovery"],
  },
  {
    id: "cur-combat",
    slug: "combat-academy",
    path: "curriculum",
    category: "combat",
    difficulty: "beginner",
    order: 202,
    title: "Combat Academy",
    summary: "Interactive practice stubs for turns, affinity, and loadouts.",
    etaMinutes: 8,
    keywords: ["combat", "practice", "training", "turn", "stub"],
    body: [
      "Combat Academy mixes short drills with links into Arena Training. Practice stubs below simulate decision gates when Live World combat isn't driving this page.",
    ],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/combat-training.png",
        alt: "Combat training illustration",
      },
    ],
    interactive: [
      {
        id: "pick-action",
        kind: "click-target",
        instruction: "Choose Strike on the practice action bar",
        targetId: "demo-strike",
      },
      {
        id: "pick-defend",
        kind: "click-target",
        instruction: "Choose Guard when the foe telegraphs a heavy",
        targetId: "demo-guard",
      },
      {
        id: "open-training",
        kind: "practice-stub",
        instruction: "Launch a real Training bout",
        practiceHref: "/arena/training",
      },
    ],
    quiz: [
      {
        id: "q-wager",
        prompt: "Does Arena Training involve real-money wagering?",
        choices: [
          { id: "a", label: "Yes", correct: false },
          { id: "b", label: "No", correct: true },
        ],
        explainCorrect: "Arena is skill practice. Points have no cash value.",
      },
    ],
    relatedIds: ["b15-training", "adv-combat"],
    rewards: [{ id: "badge-combat-drill", label: "Drill Complete", kind: "badge" }],
  },
  {
    id: "cur-economy",
    slug: "economy-academy",
    path: "curriculum",
    category: "economy",
    difficulty: "beginner",
    order: 203,
    title: "Economy Academy",
    summary: "Credits first, optional SOL second — every time.",
    etaMinutes: 6,
    keywords: ["economy", "credits", "sol", "shop", "treasury"],
    body: [
      "Earn credits by playing. Spend them on care and cosmetics. Explore Treasury and Transparency when you want the public numbers.",
      "Critical rule: SOL is never required for basic gameplay.",
    ],
    quiz: [
      {
        id: "q-basic-sol",
        prompt: "To walk Live World and care for a starter, you must…",
        choices: [
          { id: "a", label: "Buy SOL first", correct: false },
          { id: "b", label: "Just play — credits and free paths cover basics", correct: true },
        ],
        explainCorrect: "Basics are playable without SOL.",
      },
    ],
    relatedIds: ["b05-credits-sol", "adv-economy"],
  },
  {
    id: "cur-world-map",
    slug: "world-map-academy",
    path: "curriculum",
    category: "world",
    difficulty: "beginner",
    order: 204,
    title: "World Map Academy",
    summary: "Regions, portals, gateways, and waypoints.",
    etaMinutes: 5,
    keywords: ["map", "portal", "gateway", "region", "waypoint"],
    regionMentions: ["riftwild-commons", "ember-crater", "moonwater-coast", "elderwood-forest"],
    body: [
      "The map shows regions and travel options. Portals and gateway stones are the primary movers. Fast travel unlocks with play progress.",
    ],
    media: [
      {
        type: "illustration",
        src: "/assets/academy/world-map-hud.png",
        alt: "World map HUD illustration",
      },
    ],
    interactive: [
      {
        id: "waypoint-drill",
        kind: "map-waypoint",
        instruction: "Select Ember Crater on the practice map",
        targetId: "ember-crater",
        practiceHref: "/live-world",
      },
    ],
    relatedIds: ["b04-map", "adv-exploration"],
  },
  {
    id: "cur-npc",
    slug: "npc-academy",
    path: "curriculum",
    category: "npcs",
    difficulty: "beginner",
    order: 205,
    title: "NPC Academy",
    summary: "Services, shops, quests, and reading dialogue trees.",
    etaMinutes: 4,
    keywords: ["npc", "shop", "service", "dialogue", "quest"],
    npcMentions: ["elara-venn", "archivist-solen", "tessa-windmere", "bram-ironroot"],
    body: [
      "NPCs offer talk, shops, and services. Look for occupation cues — smiths forge, archivists catalog, merchants trade.",
    ],
    interactive: [
      {
        id: "npc-solen",
        kind: "npc-click",
        instruction: "Select Archivist Solen",
        targetId: "archivist-solen",
      },
    ],
    relatedIds: ["b12-npcs"],
  },
  {
    id: "cur-ui",
    slug: "ui-academy",
    path: "curriculum",
    category: "ui",
    difficulty: "beginner",
    order: 206,
    title: "UI Academy",
    summary: "Header, sidebar, HUD chips, and where Help lives.",
    etaMinutes: 4,
    keywords: ["ui", "hud", "sidebar", "header", "help"],
    body: [
      "Desktop: Site Header groups + Game Sidebar. Mobile: bottom nav. Live World adds HUD chips, minimap, and chat.",
      "Help / Academy is always one click away from nav, Profile, Quests, Esc menu, or F1.",
    ],
    relatedIds: ["b19-profile", "b28-keybinds"],
  },
  {
    id: "cur-controls",
    slug: "keyboard-academy",
    path: "curriculum",
    category: "controls",
    difficulty: "beginner",
    order: 207,
    title: "Keyboard Shortcut Academy",
    summary: "Full control sheet with practice gates.",
    etaMinutes: 5,
    keywords: ["keyboard", "shortcuts", "keybinds", "accessibility"],
    controlMentions: ["W", "A", "S", "D", "Shift", "E", "Space", "M", "T", "Enter", "Esc", "F1", "F2"],
    body: [
      "Memorize the core sheet, then customize under Settings → Keybinds. Accessibility: all critical actions also have clickable UI.",
    ],
    interactive: [
      {
        id: "wasd-again",
        kind: "wasd-gate",
        instruction: "Refresh the WASD gate",
        requiredKeys: ["w", "a", "s", "d"],
      },
    ],
    relatedIds: ["b02-controls", "b28-keybinds"],
  },
];
