/**
 * Modular earning paths for Rift Exchange.
 * status: live = wired to existing systems; partial = UI + hooks; scaffold/coming = honest stubs.
 */

import type { EarningMethod } from "@/lib/exchange/types";

const weekEnd = () =>
  new Date(Date.now() + 4 * 86400_000 + 8 * 3600_000).toISOString();

const dayEnd = () => new Date(Date.now() + 20 * 3600_000).toISOString();

export const EARNING_METHODS: EarningMethod[] = [
  {
    id: "tournaments",
    title: "Skill tournaments",
    summary:
      "Compete in free / Credits / Gold brackets. Optional SOL prize pools stay flagged off until audited.",
    rewardRangeLabel: "Credits · cosmetics · optional SOL pool (when live)",
    currencyHint: "MIXED",
    difficulty: "hard",
    popularity: 78,
    status: "partial",
    requirements: ["Constructed deck ready", "Fair-play account in good standing"],
    href: "/tcg/battle",
    endsAt: weekEnd(),
    progressPercent: 35,
    category: "competition",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "marketplace_sales",
    title: "Player Marketplace sales",
    summary:
      "List eligible cosmetics, collectibles, and alt-art — never base competitive power. Fees fund community buckets.",
    rewardRangeLabel: "Seller proceeds after fees (Credits-first; SOL optional)",
    currencyHint: "MIXED",
    difficulty: "moderate",
    popularity: 82,
    status: "live",
    requirements: ["Eligible cosmetic/collectible ownership", "Listing rules pass"],
    href: "/marketplace",
    endsAt: null,
    progressPercent: null,
    category: "trade",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "player_shops",
    title: "Player shops",
    summary: "Curate a named stall with featured cosmetics and ratings stubs.",
    rewardRangeLabel: "Sale proceeds when buyers settle (demo)",
    currencyHint: "CREDITS",
    difficulty: "moderate",
    popularity: 54,
    status: "partial",
    requirements: ["Shop profile stub", "At least one eligible listing"],
    href: "/marketplace/shops",
    endsAt: null,
    progressPercent: 20,
    category: "trade",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "creator_program",
    title: "Creator program",
    summary:
      "Publish cosmetic packs, lore drops, and event kits. Tips and cuts are entertainment — not investment.",
    rewardRangeLabel: "Creator cut on verified purchases (scaffold %)",
    currencyHint: "MIXED",
    difficulty: "moderate",
    popularity: 61,
    status: "partial",
    requirements: ["Creator guidelines accepted", "Cosmetic-only catalog"],
    href: "/creators",
    endsAt: null,
    progressPercent: null,
    category: "creation",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "commissions",
    title: "Player commissions",
    summary: "Request custom cosmetic / lore commissions between keepers — escrow scaffold later.",
    rewardRangeLabel: "Negotiated Credits (escrow coming)",
    currencyHint: "CREDITS",
    difficulty: "moderate",
    popularity: 28,
    status: "scaffold",
    requirements: ["Both parties confirm brief", "No competitive-power items"],
    href: "/marketplace/commissions",
    endsAt: null,
    progressPercent: null,
    category: "creation",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "rentals",
    title: "Cosmetic rentals",
    summary: "Time-boxed sleeve / board / showcase rentals — never rented competitive cards.",
    rewardRangeLabel: "Rental fee after platform cut (scaffold)",
    currencyHint: "CREDITS",
    difficulty: "easy",
    popularity: 22,
    status: "scaffold",
    requirements: ["Eligible cosmetic ownership", "Duration ≤ policy max"],
    href: "/marketplace/rentals",
    endsAt: null,
    progressPercent: null,
    category: "trade",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "bounties",
    title: "Community bounties",
    summary: "Complete published bounty briefs (art, QA, lore) for Credits / cosmetic drops.",
    rewardRangeLabel: "50–2,500 Credits · cosmetics (band)",
    currencyHint: "CREDITS",
    difficulty: "moderate",
    popularity: 40,
    status: "scaffold",
    requirements: ["Open bounty claim", "Deliverable review"],
    href: "/exchange#bounties",
    endsAt: weekEnd(),
    progressPercent: 0,
    category: "community",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "streamer",
    title: "Streamer / content drops",
    summary: "Eligible creators may receive promotional cosmetic / Credits drops for verified streams.",
    rewardRangeLabel: "Promo Credits · cosmetic codes (scaffold)",
    currencyHint: "CREDITS",
    difficulty: "moderate",
    popularity: 45,
    status: "scaffold",
    requirements: ["Creator flag", "Activity verification stub"],
    href: "/creators",
    endsAt: null,
    progressPercent: null,
    category: "creation",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "guild",
    title: "Guild vendors & goals",
    summary: "Guild stalls and restoration goals — soft rewards now; SOL pools later if funded.",
    rewardRangeLabel: "Guild Credits · cosmetics (scaffold SOL)",
    currencyHint: "MIXED",
    difficulty: "moderate",
    popularity: 58,
    status: "scaffold",
    requirements: ["Guild membership", "Contribution score"],
    href: "/marketplace/guild",
    endsAt: weekEnd(),
    progressPercent: 12,
    category: "community",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "world_events",
    title: "World events & festivals",
    summary: "Seasonal Live World / festival participation with soft rewards and occasional funded prizes.",
    rewardRangeLabel: "Credits · cosmetics · funded prizes when announced",
    currencyHint: "MIXED",
    difficulty: "easy",
    popularity: 70,
    status: "partial",
    requirements: ["Event region access", "Participation actions"],
    href: "/live-world",
    endsAt: dayEnd(),
    progressPercent: 48,
    category: "community",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "community_voting",
    title: "Community voting grants",
    summary: "Propose or vote on treasury-funded community grants — stub ballots only today.",
    rewardRangeLabel: "Grant payouts if proposal funded (stub)",
    currencyHint: "SOL_OPTIONAL",
    difficulty: "easy",
    popularity: 33,
    status: "scaffold",
    requirements: ["Account age stub", "One proposal / vote window"],
    href: "/treasury",
    endsAt: null,
    progressPercent: null,
    category: "community",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "museum_tips",
    title: "Museum tips & exhibits",
    summary:
      "Showcase sealed Codex lines; optional tips and list-from-exhibit cosmetics for the marketplace.",
    rewardRangeLabel: "Optional tip Credits · listing proceeds",
    currencyHint: "CREDITS",
    difficulty: "easy",
    popularity: 36,
    status: "partial",
    requirements: ["Museum exhibit / sealed line", "Cosmetic-only listings"],
    href: "/tcg/museum",
    endsAt: null,
    progressPercent: null,
    category: "showcase",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "weekly_challenges",
    title: "Weekly challenges",
    summary: "Soft weekly goals for Credits and cosmetics — skill/fun first, never grind-for-SOL.",
    rewardRangeLabel: "100–800 Credits · cosmetic chance",
    currencyHint: "CREDITS",
    difficulty: "easy",
    popularity: 74,
    status: "partial",
    requirements: ["Login streak optional", "Challenge objectives"],
    href: "/quests",
    endsAt: weekEnd(),
    progressPercent: 55,
    category: "competition",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "esports",
    title: "Esports circuits",
    summary: "Spectator-friendly brackets and sponsored cups — betting never enabled.",
    rewardRangeLabel: "Sponsored prize bands when announced",
    currencyHint: "SOL_POOL",
    difficulty: "expert",
    popularity: 30,
    status: "coming",
    requirements: ["Circuit invite / open qualifier", "Anti-collusion checks"],
    href: "/exchange#esports",
    endsAt: null,
    progressPercent: null,
    category: "competition",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "sponsorship",
    title: "Event sponsorship",
    summary: "Guilds / creators may sponsor cosmetic showcases — brand tips, not pay-to-win.",
    rewardRangeLabel: "Sponsor cut stubs (not live)",
    currencyHint: "MIXED",
    difficulty: "hard",
    popularity: 18,
    status: "scaffold",
    requirements: ["Sponsor agreement stub", "Cosmetic-only activations"],
    href: "/creators",
    endsAt: null,
    progressPercent: null,
    category: "ops",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "referral",
    title: "Referrals (activity-gated)",
    summary:
      "Both referrer and invitee must meet activity gates. Anti-multi-account required before any live SOL.",
    rewardRangeLabel: "Cosmetic / Credits only until anti-abuse live",
    currencyHint: "CREDITS",
    difficulty: "easy",
    popularity: 50,
    status: "scaffold",
    requirements: ["Invitee completes onboarding + battles", "Device / IP risk checks stub"],
    href: "/rewards",
    endsAt: null,
    progressPercent: null,
    category: "community",
    walletRequired: false,
    competitivePower: false,
  },
  {
    id: "achievement_promo",
    title: "Achievement promo drops",
    summary:
      "Rare promotional SOL / Credits drops for milestone achievements — never grind loops, never guaranteed.",
    rewardRangeLabel: "Occasional promo band (admin-funded)",
    currencyHint: "SOL_OPTIONAL",
    difficulty: "hard",
    popularity: 25,
    status: "scaffold",
    requirements: ["Specific achievement unlocked", "Promo window open"],
    href: "/rewards",
    endsAt: null,
    progressPercent: null,
    category: "showcase",
    walletRequired: true,
    competitivePower: false,
  },
  {
    id: "reward_vault",
    title: "Community Reward Vault",
    summary:
      "Epoch shares from verified marketplace fees and deposits — wallet optional to view; claims flagged off by default.",
    rewardRangeLabel: "Epoch claimable when funded (not from token buys)",
    currencyHint: "SOL_OPTIONAL",
    difficulty: "easy",
    popularity: 66,
    status: "partial",
    requirements: ["Eligible pet / keeper status", "Claims flag + verified deposits"],
    href: "/rewards",
    endsAt: null,
    progressPercent: null,
    category: "ops",
    walletRequired: false,
    competitivePower: false,
  },
];

export function listEarningMethods(opts?: {
  status?: EarningMethod["status"] | "any";
  category?: EarningMethod["category"] | "any";
}): EarningMethod[] {
  return EARNING_METHODS.filter((m) => {
    if (opts?.status && opts.status !== "any" && m.status !== opts.status) return false;
    if (opts?.category && opts.category !== "any" && m.category !== opts.category) return false;
    return true;
  });
}

export function getEarningMethod(id: string): EarningMethod | undefined {
  return EARNING_METHODS.find((m) => m.id === id);
}
