/** Versioned Arena realtime protocol (Phase 2+). Phase 1 uses REST. */

export const ARENA_PROTOCOL_VERSION = 1;

export const ClientToServer = {
  JOIN_BATTLE: "JOIN_BATTLE",
  LEAVE_BATTLE: "LEAVE_BATTLE",
  READY: "READY",
  SELECT_ACTION: "SELECT_ACTION",
  CANCEL_SELECTION: "CANCEL_SELECTION",
  SURRENDER: "SURRENDER",
  REQUEST_STATE: "REQUEST_STATE",
  SEND_EMOTE: "SEND_EMOTE",
  PING: "PING",
} as const;

export const ServerToClient = {
  BATTLE_SNAPSHOT: "BATTLE_SNAPSHOT",
  PLAYER_READY: "PLAYER_READY",
  ROUND_STARTED: "ROUND_STARTED",
  ACTION_LOCKED: "ACTION_LOCKED",
  ACTIONS_REVEALED: "ACTIONS_REVEALED",
  ACTION_RESOLVED: "ACTION_RESOLVED",
  PET_STATE_CHANGED: "PET_STATE_CHANGED",
  STATUS_APPLIED: "STATUS_APPLIED",
  STATUS_REMOVED: "STATUS_REMOVED",
  ROUND_ENDED: "ROUND_ENDED",
  BATTLE_ENDED: "BATTLE_ENDED",
  PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
  PLAYER_RECONNECTED: "PLAYER_RECONNECTED",
  COMMAND_REJECTED: "COMMAND_REJECTED",
  PONG: "PONG",
} as const;
